codevise/pageflow

- pageflow.gemspec
0.4.2 causes an error: Sprockets::FileNotFound: couldn't find file
'jquery-fileupload/vendor/load-image'
> Fix jquery-fileupload-rails version to 0.4.1

- app/assets/javascripts/pageflow/editor/views/files_explorer_view.js
The recently added `pageflow` prefix was missing.
> Fix Translation Key in FilesExplorerView

- app/helpers/pageflow/entries_helper.rb
- app/helpers/pageflow/render_json_helper.rb
- app/views/pageflow/entries/show.html.erb
- spec/helpers/pageflow/entries_helper_spec.rb
The UTF8 characters \u2028 and u2029 are treated as whitespace in
javascript blocks and may therefore not appear in string literals of
JSON fragments that are embedded into javascript.
Prevent illegal syntax error in seed data script tag of entries.
See also #191.
> Escape illegal UTF8 Characters in Entry JSON Seed

- app/assets/javascripts/pageflow/editor/base.js
- app/controllers/pageflow/editor/entries_controller.rb
- app/helpers/pageflow/files_helper.rb
- app/views/pageflow/editor/entries/seed.json.erb
- app/views/pageflow/entries/edit.html.erb
- config/routes.rb
- spec/controllers/pageflow/editor/entries_controller_spec.rb
* Prevents displaying obsolete seed data from cached page when
returning to the editor via browser back.
* Prevents illegal syntax error (#191) when json seed contains
unescaped UTF8 whitespace characters.
> Fetch editor seed data in separate JSON request.

- app/assets/javascripts/pageflow/editor/models/edit_lock_container.js
- app/assets/javascripts/pageflow/editor/views/locked_view.js
When authentication for the edit lock aquire request fails, redirect
to login page. Prevent clients from indefinitely polling from an
expired session.
> Stop Edit Lock Polling when Unauthenticated

- app/views/pageflow/entries/show.html.erb
Otherwise page specific share headers are not rendered.
> Include Share Target in Head Cache Key

- lib/pageflow/configuration.rb
- lib/pageflow/plugin.rb
- spec/pageflow/configuration_spec.rb
Allow Pageflow extensions to group multiple configuration changes in a
single method. This allows extensions authors to change the way their
plugin integrates with Pageflow without changing the Pageflow
initializer of the host application.
> Add Plugin API to Configuration

- pageflow.gemspec
`sass-rails 5.0` no longer allows mixing sprockets `require` and scss
`@import`. Still `jquery-ui-rails` uses `require` which causes some
stylesheets not to be loaded.
> Restrict sass-rails Gem Version to ~> 4.0

- pageflow.gemspec
Use pessimistic version constraint
* on minor versions for gems >= 1.0
* on patch level version for 0.x gems
> Narrow down Gem Versions in pageflow.gemspec

- .travis.yml
Triggered by "sudo: false". Enables caching of bundled gems.
> Use Container Based Travis Infrastructure

- spec/support/config/i18n.rb
Some specs might change I18n.locale. Some JavaScript specs though rely
on the fact that the locale in the test process is the same as in the
server used for the headless tests.
> Reset Locale to Default Locale Before Each Spec

- app/controllers/pageflow/revisions_controller.rb
- app/models/pageflow/widget.rb
- app/views/pageflow/entries/_entry.html.erb
- app/views/pageflow/entries/partials.html.erb
- app/views/pageflow/entries/show.html.erb
- doc/creating_widget_types.md
- lib/pageflow/widget_type.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/controllers/pageflow/revisions_controller_spec.rb
- spec/models/pageflow/widget_spec.rb
- spec/support/helpers/test_widget_type.rb
Add `enabled_in_preview?` method in widget type.
> Allow Excluding Widgets from Being Rendered in Preview

- admins/pageflow/entry.rb
- app/views/components/pageflow/admin/tabs_view.rb
- lib/pageflow/ability_mixin.rb
- lib/pageflow/admin/tabs.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/pageflow/admin/tabs_spec.rb
- spec/support/helpers/view_component_example_group.rb
- spec/views/components/pageflow/admin/tabs_view_spec.rb
Add option to `tabs_view` component that uses ActiveAdmin authorization
adapter to determine which tabs are visible for a user.
> Allow Authorizing Admin Tabs

- app/views/pageflow/entries/show.json.jbuilder
While files are processed, the editor polls for changes to progress and state fields. For large pageflows the time needed to render this info for all files can get long. Cache fragments for individual files to speed things up.
> Fragment Caching for Editor File Polling

- app/models/concerns/pageflow/hosted_file.rb
- app/models/pageflow/image_file.rb
- app/models/pageflow/video_file.rb
- config/initializers/paperclip.rb
- lib/pageflow/configuration.rb
- pageflow.gemspec
* Paperclip 3.5 did not clean up tempfiles correctly when processing
thumbnails
* Disable all content type checks for now to prevent regressions.
> Use Paperclip 4.2

- Gemfile
Seems to override version given in gemspec. Causing it to use
arbitrary teaspoon versions when running tests.
> Also mention teaspoon version in Gemfile

- app/assets/javascripts/pageflow/ui.js
Some plugins expect `pageflow.Object` to be defined after requiring
`pageflow/ui`.
> Require pageflow/object.js from pageflow/ui.js

- app/helpers/pageflow/entries_helper.rb
- spec/helpers/pageflow/entries_helper_spec.rb
* Do not render a leading comma if no default file rights are defined
for the account.
* Include rights of all registered file types.
> Improve Entry File Rights Helper

- config/initializers/paperclip.rb
Inside the development buckets assets are stored in developer specific
directories to prevent id clashes. By default the host name of the
development machine is used. This variable allows overriding the
directory name.
> Allow Overriding Attachments Scope Name

- app/controllers/pageflow/entries_controller.rb
- spec/controllers/pageflow/entries_controller_spec.rb
CDNs cannot handle basic auth protected origin.
> Only Protect HTML Format with Password

- pageflow.gemspec
Paperclip 4.3 introduces some backward incompatible changes. See
thoughtbot/paperclip#1904.
> Fix Paperclip Version to 4.2 until 4.3 Issues are Resolved

- app/assets/javascripts/pageflow/browser.js
- spec/javascripts/support/fake_browser_features.js
Make sure feature detection finishes synchronously. Otherwise
components depending on features cannot be tested before detection is
finished.
> Disable Bandwidth Feature Detection in Test Environment

- app/assets/javascripts/pageflow/ui/views/inputs/text_input_view.js
Sometimes the change event is not fired even though the view has been
edited.
> Save TextInputView on Close

- app/assets/javascripts/pageflow/ui/views/configuration_editor_tab_view.js
Allow passing options when using predefined configuration editor tab
groups.
> Options for Configuration Editor Tab Groups

- app/assets/javascripts/pageflow/preload.js
- app/helpers/pageflow/background_image_helper.rb
- app/views/layouts/pageflow/application.html.erb
- app/views/pageflow/entries/show.css.erb
- spec/helpers/pageflow/background_image_helper_spec.rb
* Trigger preloading of all matched images not only first
* Use css class on same element not parent, to workaround cases were
chrome does not notice that a parent class changed and fails to
load images.
> Impove Image Preloading

- app/assets/javascripts/pageflow/page_types/video.js
The state before playback starts should be equal to when playback
paused.
> Set lock-showing Class Initially

- app/assets/javascripts/pageflow/page_types/video.js
Allow to display faded video controls when focus enters.
> Focussed CSS Class For Video Player Controls

- vendor/assets/javascripts/audio5.min.js
* Events sometimes fire late
* If loop option was set, the audio restarted even though it was
paused.
> Do not Rely on Events to Set Audio Player Playing State

- app/assets/javascripts/pageflow/settings.js
Do not fail if Safari throws error when accessing
`window.localStorage`.
> Improve Local Storage Detection

- pageflow.gemspec
This fixes a problem where the host application's test fail when
FactoryGirl is used there.
> add spec/fixtures path to gem files list

- pageflow.gemspec
* The glob given so far did not match any files.
* The `test_files` attribute it self is no longer present in the gemspec docs and does not serve any special purpose in our case.
> Remove test_files Attribute from Gemspec

- pageflow.gemspec
Change `files` attribute in gemspec to include the readme and the changelog file.
> Include Readme and Changelog in Gemspec

- admins/pageflow/entry.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/entry_duplicate.rb
- config/locales/new/duplicate_entry.yml
- spec/controllers/admin/entries_controller_spec.rb
- spec/features/account_manager/duplicating_an_entry_spec.rb
- spec/features/admin/duplicating_an_entry_spec.rb
- spec/models/pageflow/entry_duplicate_spec.rb
- spec/models/pageflow/entry_spec.rb
- spec/support/dominos/admin/entry_page.rb
Let admin and account manager user create copies of existing
entries. Copy draft and memberships to new entry.
This feature can used to create a collection of template entries.
> Duplicating Entries

- app/controllers/pageflow/entries_controller.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/controllers/pageflow/revisions_controller_spec.rb
- spec/support/matchers/have_meta_tag.rb
fixes #373
The find was not scoped before causing pages from the draft to be used in the social media tags when a page share target was passed.
> Find Share Target Page in Published Revision

- app/helpers/pageflow/entries_helper.rb
- spec/helpers/pageflow/entries_helper_spec.rb
Generated entry css should be invalidated in the CDN when the version changes. Otherwise outdated CSS might be served.
> Include Pageflow Version in Entry CSS Url

- app/assets/javascripts/pageflow/widgets/navigation_mobile.js
iScroll prevents default on touch events causing links in the credits text and copyright links to be no-op. While there needs to be a more general solution to this problem, stopping propagation on those links
at least makes them clickable for now.
> Fix Copyright Links in Mobile Navigation

- app/assets/javascripts/pageflow/editor/views/edit_widget_view.js
Do not fail if the entry has a a widget with current widget type null
and no available widget types. Simply hide the select.
> Make EditWidgetView handle widgets with no available widget types

- app/assets/javascripts/pageflow/editor/models/mixins/stage_provider.js
Calling `slice` in an Underscore chain on an undefined value works in some browsers, but fails in others. Some tests rely on `UploadedFile` models with an undefined `stages` array. Then the `stageProvider` failed while trying to process stages.
> Fix bug related to Underscore.js

- lib/generators/pageflow/theme/theme_generator.rb
fixes #384 
In commit a0ad811 the generator was refactored, the contents of the main
stylesheet were moved into variables.css.scss. This change fixes the
generator so that the generated theme name is replaced again.
> fix theme name replacement in generator

- app/controllers/concerns/pageflow/public_https_mode.rb
- app/controllers/pageflow/application_controller.rb
- app/controllers/pageflow/entries_controller.rb
- app/controllers/pageflow/files_controller.rb
- lib/generators/pageflow/initializer/templates/pageflow.rb
- lib/pageflow/configuration.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/controllers/pageflow/files_controller_spec.rb
Pageflow has always been serving assets over a CDN without https
endpoint. The prevent_ssl filter made sure to redirect to a non-https
method when assets are involved. This change makes that setting
configurable. You can now ignore, enforce or prevent https.
The default is to prevent https, like how Pageflow < 1.0 behaved.
However in new initializers the generated value is :ignore. This should
make the setting compatible with most applications out of the box.
fixes codevise/pageflow#388
> make https mode configurable

- app/assets/stylesheets/pageflow/entries.css.scss
Before the i18n changes it used to only have a background image on
mobile platform. But since texts are localized, the text also became
visible on desktop browsers.
> Ensure hidden text indicator is only visible on mobile

- app/assets/javascripts/pageflow/editor/views/publish_entry_view.js
One still has to select the publication mode, but if automatic
depublication is chosen, the date now has a default.
> Prefill depublication date field to one year from now

- app/assets/javascripts/pageflow/editor/api/page_type.js
- app/assets/javascripts/pageflow/ui.js
- app/assets/javascripts/pageflow/ui/utils/i18n_utils.js
- app/assets/javascripts/pageflow/ui/views/configuration_editor_tab_view.js
- app/assets/javascripts/pageflow/ui/views/configuration_editor_view.js
- app/assets/javascripts/pageflow/ui/views/inputs/select_input_view.js
- app/assets/javascripts/pageflow/ui/views/mixins/input_view.js
- app/views/pageflow/page_types/_page_type.json.jbuilder
- spec/javascripts/pageflow/ui/utils/i18n_utils_spec.js
- spec/javascripts/pageflow/ui/views/inputs/select_input_view_spec.js
- spec/javascripts/pageflow/ui/views/mixins/input_view_spec.js
- spec/javascripts/support/use_fake_translations.js
Before, translations for page attribute labels and inline help texts were looked up in the `activerecord.attributes` and `pageflow.ui.inline_help` scopes. Translations for select box entries
where looked up in `activerecord.values`.  This caused three problems:
* No two page types could use different texts for the same attribute.
* Active record scopes reveal too much implementation details. Should
be `pageflow...` scope.
* Translations for an attribute were scattered accross different
parent scopes.
Introduce new scopes for common and page type specific attribute translations:
pageflow.common_page_attributes.<attribute>.label
pageflow.common_page_attributes.<attribute>.inline_help
pageflow.common_page_attributes.<attribute>.inline_help_disabled …
> Page Attribute Translation Key Prefixes

- app/assets/javascripts/pageflow/editor/models/theming.js
- app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js
- app/views/pageflow/editor/themings/_theming.json.jbuilder
- config/initializers/features.rb
- config/locales/new/emphasize_pages_in_navigation.yml
- config/locales/new/scroll_indicator_modes.yml
- lib/pageflow/theme.rb
- lib/pageflow/themes.rb
Both do not make sense as features since they need to be supported by the theme to work. If the theme supports them though, there is really no reason not to enable them.
> Emphasized Pages and Scoll Indicator Modes Theme Options

- app/assets/javascripts/pageflow/editor/initializers/boot.js
- app/assets/javascripts/pageflow/editor/views/scrolling_view.js
The scrollbar's position is now being remembered in the chapters overview. Issue #378 solved.
> Implement remembering of scroll position in chapter overview

- app/assets/javascripts/pageflow/editor/templates/files_explorer.jst.ejs
- app/assets/javascripts/pageflow/editor/templates/loading.jst.ejs
- app/assets/javascripts/pageflow/editor/templates/other_entries_blank_slate.jst.ejs
- app/assets/javascripts/pageflow/editor/views/loading_view.js
- app/assets/javascripts/pageflow/editor/views/other_entries_collection_view.js
- app/assets/javascripts/pageflow/editor/views/other_entry_item_view.js
- app/assets/stylesheets/pageflow/animations.css.scss
- app/assets/stylesheets/pageflow/animations/loading.css.scss
- app/assets/stylesheets/pageflow/editor/base.css.scss
- app/assets/stylesheets/pageflow/editor/files_explorer.css.scss
- app/assets/stylesheets/pageflow/editor/loading.css.scss
Editor's file reuse panel/dialog displays a loading animation during template retrieval instead of a text message. Solves #379.
> Implement loading spinner for file reuse panel

- app/helpers/pageflow/pages_helper.rb
- spec/helpers/pageflow/pages_helper_spec.rb
Styles were used the wrong way around causing blurry thumbnails to be
displayed.
> Use large link thumbnail if hero argument is true

- app/models/pageflow/entry_duplicate.rb
- spec/models/pageflow/entry_duplicate_spec.rb
Ensure the same features are enabled on the copied entry. Otherwise there may be errors when opening the editor and page types are missing.
> Copy feature flags to duplicated entry

- app/models/pageflow/entry.rb
- db/migrate/20151022080518_add_first_published_at_to_entries.rb
- spec/models/pageflow/entry_spec.rb
Allows to easily sort entries by publication date without having them move to the top on re-publication.
> Record when an entry has first been published 

- spec/features/admin/enabled_a_feature_for_an_account_spec.rb
- spec/spec_helper.rb
- spec/support/helpers/pageflow_global_config_api_helper.rb
This new test helper allows to test controllers that use the `Pageflow.config_for` method. This is necessary since manually made changes to `Pageflow.config` as part of test setup are not visible in these config objects.
> Allow adding Pageflow configure blocks in tests

- .rubocop_hound.yml
- admins/pageflow/accounts.rb
- admins/pageflow/entry.rb
- app/views/admin/accounts/_form.html.erb
- lib/pageflow/admin/form_input.rb
- lib/pageflow/admin/form_inputs.rb
- lib/pageflow/configuration.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/pageflow/admin/form_inputs_spec.rb
- spec/support/pageflow/dummy/rails_template.rb
- spec/support/pageflow/dummy/templates/add_custom_fields.rb
Via the `Pageflow.config.admin_form_inputs.register` method it is now possible to add further inputs to entry, account and theming forms. This provides a cleaner extension point than overriding from partials or admin methods.
> Add configuration API to add inputs to admin forms 

- app/assets/stylesheets/pageflow/editor/base.css.scss
Some page types rely on the fact that the background of the Pageflow
is black, which is true in the published version. Since the editor's
preview background was white, especially pages without configured
background image used to flash on page change.
> Make editor background color black

- app/assets/javascripts/pageflow/editor/views/editor_view.js
Previously we were looking at `event.target` to determine if `href` is empty. But if a `div` inside a link was clicked, the `div` is the target. We have to use `currentTarget` to inspect the link.
> Correctly detect links to prevent default for in editor

- app/assets/javascripts/pageflow/slideshow/page_widget.js
* Reset `preloaded` flag to allow calling `preload` page type hook again
* If the page is currently active, call preload the page immediately
> Ensure pages are preloaded in editor after type change

- app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
Ensure the update mechanism does not replace arbitrary elements matching the selectors somewhere deep in the document.
> Widget preview update improvement

- .rubocop.yml
- app/assets/javascripts/pageflow/editor/base.js
- app/assets/javascripts/pageflow/editor/initializers/stylesheet_reloading.js
- app/assets/javascripts/pageflow/editor/models/entry.js
- app/assets/javascripts/pageflow/editor/utils/reload_stylesheet.js
- app/helpers/pageflow/entries_helper.rb
This allows to use image css class in the editor instead of urls in inline styles. The editor display does therefore better match the final result.
> Reload dynamically generated entry stylesheet

- app/assets/javascripts/pageflow/slideshow/hidden_text_indicator_widget.js
Used to be coupled to css class that would also hide all content of
the page.
> Add css class to prevent display of hidden text indicator

- app/assets/javascripts/pageflow/slideshow/page_widget.js
If manual start is enabled, the activated hook of the first page is
not supposed to be triggered if another page has already been
navigated to via the url fragment.
The page widget listens for its `deactivate` event to cancel delayed
page type hooks. The event name was wrong though, causing the page
hook to fire anyway.
> Prevent incorrectly called page type hook on manual start

- README.md
The wildcard in the original command led to a "*" in the resulting name (see #314). Use `rename` command instead.
> Fix migration rename command in Readme

- app/views/pageflow/entries/edit.html.erb
Ensure translations from the selected locale are used for the scroll indicators inside the editor.
> Use entry locale for scroll indicators in editor

- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/views/pageflow/config/_editor_seeds.json.jbuilder
- lib/pageflow/configuration.rb
- lib/pageflow/engine.rb
- pageflow.gemspec
- spec/helpers/pageflow/config_helper_spec.rb
- spec/pageflow/configuration_spec.rb
Translations for public pages are now supplied via the `pageflow-public-i18n` gem. Allow selecting one of the supported locales inside the editor.
> Add config option for available public locales

- lib/pageflow/configuration.rb
- spec/pageflow/configuration_spec.rb
`I18n.available_locales` now also includes locales only supported for
entries.
> Explicitly set available locales in config

- app/views/pageflow/entries/navigation/_bar_top.html.erb
Wring keys were used for sub share navigation
> Use correct key in navigation share box

- app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
Prevent server endpoint for widget rendering to be hit too often when multiple changes occur inside the editor.
> Debounce widget update in editor

- app/assets/javascripts/pageflow/page_transitions.js
- app/assets/javascripts/pageflow/slideshow.js
- app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
- app/assets/stylesheets/pageflow/page_transitions.css.scss
- app/assets/stylesheets/pageflow/page_transitions/scroll_over_from_left.scss
- app/assets/stylesheets/pageflow/page_transitions/scroll_over_from_right.scss
- config/locales/new/scroll_over.de.yml
- config/locales/new/scroll_over.en.yml
The "scroll over" transitions look as if the new page was moved in
from the side. Returning reveals the unmoved original page.
> Use special page transitions for storyline change

- doc/understanding_plugins_and_features.md
This is explicitly checked:
https://github.com/codevise/pageflow/blob/127e61bb2b371ed0c799bd3abb26de77602a31b5/lib/pageflow/features.rb#L30
passing a symbol here will not work.
> features must be registered with a String

- app/assets/javascripts/pageflow/base.js
- app/assets/javascripts/pageflow/native_scrolling.js
- app/assets/javascripts/pageflow/ready.js
- app/assets/javascripts/pageflow/slideshow.js
When embedding Pageflow in an iframe, the wheel should not scroll the
outer page.
Prevent scroll bounce only on slideshow to enable touch scrolling in
the editor sidebar.
> Improve native scrolling prevention

- app/assets/javascripts/pageflow/ui/views/inputs/text_area_input_view.js
TextAreaInputView introduces two new options, disableRichtext & disableLinks. Both are false by default.
> Implement options for disabling rich text and links in TextAreaInputView

- app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js
Links within the overview description cause misalignment of the preview boxes. Thus it is reasonable to disallow setting links there. Note: This bugfix requires PR #404.
> Disallow links in overview description

- app/assets/javascripts/pageflow/editor/views/editor_view.js
* Disable hot keys to open/close the sidebar (Ctrl + cursor keys) which conflicted with text movement commands.
* Disable open/close animation which caused text areas to be rendered blank after reopening the sidebar.
> Optimize sidebar for text box compatibility

- app/assets/javascripts/pageflow/browser/hashchange_support.js
- app/assets/javascripts/pageflow/history.js
Setting the `location.hash` on page change caused the browser
navigation bar to appear on landscape Mobile Safari. Therefore
`hashchange support` was disabled for such devices, causing deep
linking to break.
When introducing the push state adapter this choice was not
re-evaluated, keeping history deactivated. Manipulating history via the
push state API does not appear to trigger navigation bar display
though. Therefore the iOS 8 special case can be removed.
> Use history PushStateAdapter on iOS 8 and above

- app/controllers/pageflow/entries_controller.rb
- spec/controllers/pageflow/entries_controller_spec.rb
To enable CDN access, generated css of password protected entries is
accessible without password. The check used `format.html?`, which
returned `false`, though, when the Accept header was set to "*/*"
causing the HTML format also to be publicly accessible.
Explicitly check for `format.css?` now.
> Prevent accessing password protected entries

- app/models/pageflow/account.rb
- spec/models/pageflow/account_spec.rb
themings and folders must not be orphaned, because they will break the UI in some ways.
I don't know if you like this spec style, I can do it differently, but this is what I usually do.
> destroy dependent account objects

- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/helpers/pageflow/social_share_helper.rb
- lib/pageflow/engine.rb
- pageflow.gemspec
- spec/helpers/pageflow/social_share_helper_spec.rb
* Turn \&nbsp; into spaces
* Decode other entities to utf8 character
* Prevent rich text and links in description
> Remove HTML entities from social share description

- lib/pageflow/engine.rb
This is much faster then with the json gem. The gem was a dependency all along, but since it was not required is was never picked up by MultiJson.
> Ensure MultiJson uses yajl json adapter.

- app/assets/stylesheets/pageflow/ui/forms.css.scss
- app/assets/stylesheets/pageflow/ui/tabs_view.css.scss
* Increase padding to prevent labels from overlapping help text
* Use pointer events to display inline help only if the cursor is above the help icon
* Improve display of multi line labels
> Improve inline help in forms

- app/views/pageflow/file_types/_thumbnails.css.erb
- spec/helpers/pageflow/file_thumbnails_helper_spec.rb
Allow prefixing a thumbnail css class with `lazy_` to only load images when either the `load_all_images` class is set on body (for non js) or `load_image` is set on the element itself.
> Add image CSS classes to lazy load thumbnails

- CONTRIBUTING.md
- spec/support/pageflow/dummy/rails_template.rb
- spec/support/pageflow/dummy/templates/database.yml
Host is specified according to `CONTRIBUTING.md`. Port is specified
accordingly.
> Optionally specify a host for the dummy instance

- app/assets/javascripts/pageflow/widgets/navigation.js
- app/assets/javascripts/pageflow/widgets/overview.js
Overview hides content on show. Navigation used to re-display the
content on page change, but now failed to do so since the css classes
used in the overview widget changed.
Remove this coupling by making the overview register event listeners
for next page change and re-displaying content itself.
> Decouple overview and navigation widgets

- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/controllers/pageflow/entries_controller.rb
- app/helpers/pageflow/entries_helper.rb
- app/helpers/pageflow/meta_tags_helper.rb
- app/models/pageflow/draft_entry.rb
- app/models/pageflow/published_entry.rb
- app/views/layouts/pageflow/_meta_tags.html.erb
- app/views/layouts/pageflow/application.html.erb
- app/views/pageflow/editor/entries/_entry.json.jbuilder
- app/views/pageflow/entries/show.html.erb
- app/views/pageflow/meta_tags/_entry.html.erb
- app/views/pageflow/social_share/_entry_meta_tags.html.erb
- config/locales/de.yml
- config/locales/new/dynamic_meta_de.yml
- config/locales/new/dynamic_meta_en.yml
- db/migrate/20160216130336_add_meta_fields_to_revision.rb
- lib/generators/pageflow/initializer/templates/pageflow.rb
- lib/pageflow/configuration.rb
- spec/helpers/pageflow/entries_helper_spec.rb
- spec/helpers/pageflow/meta_tags_helper_spec.rb
- spec/models/pageflow/published_entry_spec.rb
* allow meta author, keywords and publisher to be set per entry
* allow meta author, keywords and publisher defaults to be configured
Also moves rendering of the meta tags into a helper, where we
encapsulate the logic of rendering the values or falling back to the
configured defaults.
This is a breaking change for folks who have overriden the
app/views/layouts/pageflow/_meta_tags.html.erb partial!
Fixes codevise/pageflow#499
> Make the html meta tags more configurable

- app/assets/javascripts/pageflow/editor/collections/chapter_pages_collection.js
- app/assets/javascripts/pageflow/editor/collections/storyline_chapters_collection.js
- app/assets/javascripts/pageflow/editor/models/storyline_ordering.js
- app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
- app/assets/javascripts/pageflow/editor/views/storyline_picker_view.js
- app/models/pageflow/revision.rb
- spec/controllers/pageflow/storylines_controller_spec.rb
- spec/models/pageflow/revision_spec.rb
* Update foreign keys when moving chapters and pages 
* Prevent exception in StorylineOrdering when moving pages
* Update foreign keys when moving chapters and page
* Update storyline picker more often
> Storyline Editor Fixes

- app/controllers/pageflow/editor/files_controller.rb
- spec/controllers/pageflow/editor/files_controller_spec.rb
Do not require edit lock for retrying or updating rights. We used to
require an edit lock for the entry the file had originally been
uploaded in.
> Prevent edit lock warning when editing reused file

- app/assets/javascripts/pageflow/browser/css_animations.js
- app/assets/stylesheets/pageflow/delayed_text_fade_in.css.scss
IE 9 does not know css animations. Feature detect and only apply the
fade in styles if animtions are supported. Otherwise text is never
displayed.
> Ensure delayed text is displayed id no CSS animation support

- app/assets/javascripts/pageflow/editor/views/edit_storyline_view.js
- app/assets/javascripts/pageflow/slideshow.js
- app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
- config/locales/new/storylines.en.yml
- config/locales/new/storylines.yml
Save a page transition per storyline which is used when:
* Entering the storyline from a page of the parent page's storyline
* Returning to a page of the parent's page storyline. In this case the
animation is played reversed.
> Parent page transition

- app/assets/stylesheets/pageflow/themes/default/page.css.scss
Replace hard coded values in default page theme with variables that can be overridden in custom themes.
This is a first step towards #470, which will introduce a more flexible way of overriding typography rules via maps which are only available in SASS 3.4.
> Introduce SCSS variables for page typography

- admins/pageflow/accounts.rb
- app/controllers/pageflow/editor/widgets_controller.rb
- app/helpers/pageflow/admin/widgets_helper.rb
- app/helpers/pageflow/widgets_helper.rb
- app/models/pageflow/draft_entry.rb
- app/models/pageflow/published_entry.rb
- app/models/pageflow/theming.rb
- app/models/pageflow/widget.rb
- app/views/admin/accounts/_form.html.erb
- app/views/pageflow/admin/widgets/_fields.html.erb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/controllers/pageflow/revisions_controller_spec.rb
- spec/helpers/pageflow/admin/widgets_helper_spec.rb
- spec/helpers/pageflow/widgets_helper_spec.rb
- spec/models/pageflow/widget_spec.rb
So far resolving widgets for a subject did not take into consideration
whether a widget type is scoped to a feature. Therefore default widget
types registered inside a feature were always displayed.
Ensure that resolving widgets always looks up widget types in the
account or entry specific configuration.
fixes #474
> Allow registering default widget types in features

- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/mobile_platform.js
- app/assets/javascripts/pageflow/browser/video.js
- app/assets/javascripts/pageflow/video_player.js
- app/assets/javascripts/pageflow/video_player/filter_sources.js
Video tag loop attribute is broken for hls videos in Safari 9. Filter sources to ensure mp4 is used.
> Ensure background videos loop on desktop safari 9

- app/assets/javascripts/pageflow/base.js
- app/helpers/pageflow/common_entry_seed_helper.rb
- app/helpers/pageflow/public_i18n_helper.rb
- app/views/pageflow/entries/show.html.erb
- app/views/pageflow/public_i18n/_javascript_tag.html.erb
- spec/helpers/pageflow/common_entry_seed_helper_spec.rb
- spec/helpers/pageflow/pubic_i18n_helper_spec.rb
This change allows javascript access to translations from the
`pageflow.public` namespace in the published entry.
* Include entry locale in common seed
* Render public translations of entry locale in published entry
> Provide public translations for js

- app/assets/javascripts/pageflow/editor/api.js
- app/assets/javascripts/pageflow/editor/models/storyline.js
- app/assets/javascripts/pageflow/editor/models/storyline_transitive_child_pages.js
- app/assets/javascripts/pageflow/editor/views/edit_storyline_view.js
- app/assets/javascripts/pageflow/editor/views/inputs/page_link_input_view.js
- app/assets/javascripts/pageflow/editor/views/page_item_view.js
- app/assets/javascripts/pageflow/editor/views/page_selection_view.js
- app/assets/javascripts/pageflow/editor/views/storyline_outline_view.js
- app/assets/javascripts/pageflow/editor/views/storyline_picker_view.js
- app/assets/stylesheets/pageflow/editor/outline.css.scss
- spec/javascripts/models/storyline_transitive_child_pages_spec.js
* Allow filtering allowed pages in selectPage call 
* Do not allow pages of child storylines or the storyline itself to be selected as parent page.
> Prevent creation of loops in the storyline hierarchy 

- admins/pageflow/user.rb
- app/helpers/pageflow/admin/users_helper.rb
- app/views/admin/users/me.html.erb
- app/views/pageflow/admin/users/_cannot_delete.html.erb
- app/views/pageflow/admin/users/_may_delete.html.erb
- lib/pageflow/ability_mixin.rb
- lib/pageflow/configuration.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/features/editor/deleting_account_spec.rb
- spec/helpers/pageflow/admin/users_helper_spec.rb
- spec/models/pageflow/user_spec.rb
In some cases it might make sense to prevent the last user of an account from loosing his ability to sign in. This configuration option leaves the details of this policy to the host application.
> Add config option to forbid deleting user account

- app/assets/stylesheets/pageflow/editor/base.css.scss
- app/assets/stylesheets/pageflow/jquery_ui.css.scss
- pageflow.gemspec
* Update `sass-rails` to major version 5 which support `sass` 3.4.
* Require `sass` at least 3.4 for maps support
* Fix `jquery-ui-rails` version and explicitly require internal files. The gem uses sprockets requires inside which are now ignored by Scss imports.
* Ensure `jquery-ui-rails` is imported before `pageflow/ui` to ensure correct css precedence.
> Update Sass to 3.4

- app/assets/javascripts/pageflow/slideshow/page_widget.js
Set `is_near_top` or `is_near_bottom` CSS classes on the page element when the scroller is near a boundary.
> Add page css classes for scroller boundary position

- app/assets/javascripts/pageflow/page_types/video.js
While historically this might have been required for iOS, it causes
crashes of Chrome on Android now. Keep for iOS to prevent making
things worse there.
> Do not set video src on video page activate

- app/assets/javascripts/pageflow/widgets/share_menu.js
In the presence of FastClick binding both touchend and click to toggle
the share menu, double fires and makes it impossible to open the menu.
> Increase FastClick compatibility of share menu

- app/assets/javascripts/pageflow/widgets/navigation.js
Menu box used to close whenever focus left top level share buttons.
> Fix keyboard access to sub share menu

- app/assets/javascripts/pageflow/editor/models/theming.js
- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/assets/javascripts/pageflow/widgets/navigation.js
- app/assets/stylesheets/pageflow/themes/default/navigation.css.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/dimensions.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/separator_lines.scss
- app/controllers/pageflow/entries_controller.rb
- app/helpers/pageflow/navigation_bar_helper.rb
- app/models/pageflow/draft_entry.rb
- app/models/pageflow/overview_button.rb
- app/models/pageflow/published_entry.rb
- app/views/pageflow/editor/entries/_entry.json.jbuilder
- app/views/pageflow/editor/themings/_theming.json.jbuilder
- app/views/pageflow/entries/_navigation.html.erb
- app/views/pageflow/entries/navigation/_bar_top.html.erb
- app/views/pageflow/entries/navigation/_overview_button.html.erb
- config/locales/new/optional_overview_button.de.yml
- config/locales/new/optional_overview_button.en.yml
- db/migrate/20160225075853_add_overview_button_enabled_to_revisions.rb
- lib/pageflow/theme.rb
- spec/factories/revisions.rb
- spec/helpers/pageflow/navigation_bar_helper_spec.rb
- spec/models/pageflow/overview_button_spec.rb
For some entries with multiple storylines or very short entries, the
overview in its current form does not make sense. Add an option to
hide the overview button in navigation bars.
Whether the option is available at all, can be controlled via a theme
option `no_overview_button`. This replaces the SCSS based hiding of
the overview button.
> Add option to hide overview button

- app/assets/stylesheets/pageflow/mixins/pageflow.css.scss
- app/assets/stylesheets/pageflow/slideshow.css.scss
- app/assets/stylesheets/pageflow/themes/default/base.css.scss
- app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
- app/assets/stylesheets/pageflow/themes/default/navigation.css.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/widget_margin.scss
- app/assets/stylesheets/pageflow/themes/default/slideshow.scss
- doc/creating_widget_types.md
fixes #413 
Allow widgets to request a safe area along the page margin.
> Introduce widget margins

- pageflow.gemspec
Prevent usage of sprockets 3 for now which causes precompile errors.
> Narrow sprockets-rails version

- app/assets/javascripts/pageflow/editor/views/editor_view.js
Moving the cursor inside a text field should not move the
scroller. Since iScroll binds event listener on body we, need to stop
propagation.
> Prevent scrolling preview while forus in sidebar

- app/assets/stylesheets/pageflow/navigation_mobile.css.scss
Align with normal navigation layout.
> Move share button in mobile navigation to bottom

- app/assets/javascripts/pageflow/slideshow/atmo.js
- config/locales/new/disable_atmo.de.yml
As long as there are still auto play bugs, WDR does not want to have
it play at all.
> Disable atmo on mobile platform

- .sassdocrc
- .travis.yml
- Gemfile
- README.md
Use the `pageflow-theme-doc-publisher` gem to generate SassDoc for the
default theme and push it to GitHub pages.
> Generate theme documentation

- app/assets/stylesheets/pageflow/themes/default/README.md
- doc/creating_themes.md
- lib/generators/pageflow/theme/templates/themes/%name%.scss.tt
- lib/generators/pageflow/theme/templates/themes/%name%/variables.scss.tt
- lib/generators/pageflow/theme/theme_generator.rb
Instead of copying the default theme, the generator now scaffolds a theme which adapts the default theme via SCSS variables.
> Theme generator for configurable default theme

- .gitignore
.ruby-version can be used to test various ruby versions
/coverage needs not to be committed either
> ignore a few more files

- admins/pageflow/entry.rb
- app/assets/stylesheets/pageflow/admin.css.scss
- app/assets/stylesheets/pageflow/admin/entries.css.scss
- app/assets/stylesheets/pageflow/admin/entries/index_table.scss
- app/assets/stylesheets/pageflow/admin/filters.scss
- app/assets/stylesheets/pageflow/admin/icon_button.scss
- app/assets/stylesheets/pageflow/admin/icon_link.scss
- app/assets/stylesheets/pageflow/admin/publication_state_indicator.scss
- app/assets/stylesheets/pageflow/admin/tooltip_bubble.scss
- app/helpers/pageflow/admin/entries_helper.rb
- app/models/concerns/pageflow/entry_publication_states.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/revision.rb
- app/views/admin/entries/_attributes_table.html.arb
- app/views/admin/entries/_links.html.arb
- app/views/components/pageflow/admin/entry_publication_state_indicator.rb
- app/views/components/pageflow/admin/icon_link_to.rb
- config/locales/new/admin_entry_filters.de.yml
- config/locales/new/admin_entry_filters.en.yml
- config/locales/new/admin_entry_table.de.yml
- config/locales/new/admin_entry_table.en.yml
- config/locales/new/entry_edited_at.de.yml
- config/locales/new/entry_edited_at.en.yml
- db/migrate/20160310080213_add_edited_at_to_entries.rb
- db/migrate/20160425192648_add_index_for_revision_publication_timestamps.rb
- spec/models/concerns/pageflow/entry_publication_states_spec.rb
- spec/models/pageflow/revision_spec.rb
* 	Keep separate edited_at timestamp for entries
* Display publication state
* Add published since column
* Use icons instead of buttons in table
* Use same icons on buttons on show page
* Add entry table filters
> Improve admin entry index

- lib/generators/pageflow/active_admin_initializer/active_admin_initializer_generator.rb
- lib/generators/pageflow/initializer/templates/pageflow.rb
- lib/pageflow.rb
- spec/pageflow_spec.rb
* Move `load_path` manipulation to Active Admin initializer
* Introduce static method to hide load path construction details
> Encapsulate Active Admin load path setup

- admins/pageflow/accounts.rb
- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/models/pageflow/entry.rb
- app/models/pageflow/theming.rb
- app/views/admin/accounts/_form.html.erb
- app/views/admin/accounts/_theming_details.html.arb
- app/views/pageflow/config/_editor_seeds.json.jbuilder
- config/locales/new/default-meta-on-theming.de.yml
- config/locales/new/default-meta-on-theming.en.yml
- db/migrate/20160617123557_add_meta_fields_to_theming.rb
- spec/features/admin/editing_an_account_spec.rb
- spec/models/pageflow/entry_spec.rb
- spec/models/pageflow/theming_spec.rb
- spec/support/dominos/admin/account_form.rb
- spec/support/dominos/admin/account_page.rb
This pull request adds default fields for author, publisher and keywords to Theming (Account).
> Improve meta fields

- README.md
- lib/generators/pageflow/install/install_generator.rb
- lib/generators/pageflow/procfile/procfile_generator.rb
- lib/generators/pageflow/procfile/templates/Procfile
- spec/generators/pageflow/procfile/procfile_generator_spec.rb
> Generate procfile

- app/assets/javascripts/pageflow/editor/views/edit_meta_data_view.js
- app/assets/javascripts/pageflow/widgets/share_menu.js
- app/controllers/pageflow/entries_controller.rb
- app/helpers/pageflow/entries_helper.rb
- app/helpers/pageflow/social_share_helper.rb
- app/helpers/pageflow/social_share_links_helper.rb
- app/models/pageflow/draft_entry.rb
- app/models/pageflow/published_entry.rb
- app/views/pageflow/editor/entries/_entry.json.jbuilder
- app/views/pageflow/entries/share_menu/_facebook_link.html.erb
- app/views/pageflow/entries/share_menu/_google_link.html.erb
- app/views/pageflow/entries/share_menu/_twitter_link.html.erb
- app/views/pageflow/social_share/_entry_meta_tags.html.erb
- app/views/pageflow/social_share/_image_tags.html.erb
- app/views/pageflow/social_share/_page_meta_tags.html.erb
- config/locales/new/share_url.de.yml
- config/locales/new/share_url.en.yml
- db/migrate/20160715105408_add_share_url_to_revisions.rb
- spec/helpers/pageflow/entries_helper_spec.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
- spec/helpers/pageflow/social_share_links_helper_spec.rb
This is useful for:
* embedded entries that are actually viewed via a different domain
* entries that are part of a larger project whose landing page is
supposed to be shared instead of the individual entry.
This change allows to set a custom share url via the social sharing
tab inside the editor. If it is set, the Twitter/Facebook/Google links
directly pass this url, instead of offering to either share the whole
entry or the current page.
> Allow specifying custom share url

- app/assets/javascripts/pageflow/slideshow/scroller_widget.js
- app/assets/javascripts/pageflow/widgets/header.js
* 	Improve scroller widget boundary events
Ensure boundary events trigger when the position is reset. This
ensures that header logos can be faded out correctly when scrolling
back to a page with position bottom.		
* 	Improve setting of near_bottom class in header
When scrolling back to a page the class may not be set since we are at
the bottom of the page. Rely completely on the scroller events of the
current page.
> Improve boundary events

- .travis.yml
- Gemfile
- README.md
- lib/pageflow/engine.rb
- pageflow.gemspec
- spec/support/pageflow/dummy/rails_template.rb
- spec/support/pageflow/rails_version.rb
Make Pageflow work with Rails 4.2. I'm considering dropping support for 4.0 and 4.1 since they are no longer maintained now that Rails 5 is out. This would allow us to rely on `ActiveJob`, which would be nice.
> Update to Rails 4.2

- app/models/pageflow/account.rb
- spec/models/pageflow/account_spec.rb
Instead, ActiveRecord::DeleteRestrictionError will be raised. Entries
without accounts leave the system in an unstable state, so it must be
prevented.
Fixes #562
> prevent account with entries being deleted

- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/ios_platform.js
Trident is the Microsoft rendering engine. Edge no longer reports as
Trident.
> Add browser agent based detection for IE up to 11

- app/assets/javascripts/pageflow/highlighted_page.js
- app/assets/javascripts/pageflow/widgets/page_navigation_list.js
- spec/javascripts/pageflow/highlighted_page_spec.js
Add option to `pageNavigationList` which is passed to
`HighlightedPage` to allow overriding the navigation bar mode. This
can be used in navigation bars which always only display the main
storyline.
> Allow overriding logic to determine highlightes page

- app/assets/stylesheets/pageflow/themes/default/indicators.scss
- app/assets/stylesheets/pageflow/themes/default/indicators/widget_margins.scss
On mobile the scroll indicator is aligned on the rigth. Apply widget
margin to prevent it being hidden behind navigation bars which are
also visible on mobile.
> Apply widget margin to mobile scroll indicator

- .travis.yml
Prevent Coveralls from submitting duplicate comments.
> Use parallel Coverall builds

- README.md
- pageflow.gemspec
`cancan` is no longer maintained.
> Switch to cancancan from cancan

- app/views/pageflow/admin/widgets/_fields.html.erb
- pageflow.gemspec
Fixes most of the remaining deprecation warnings.
> Update ActiveAdmin to 1.0.pre4

- app/assets/stylesheets/pageflow/admin/entries.scss
- app/views/components/pageflow/admin/embedded_index_table.rb
- spec/views/components/pageflow/admin/embedded_index_table_spec.rb
* Ensure newest revision is at the top, by preventing embedded index
table from reordering if table is not sortable
* Highlight published revision
> Improve revisions table on entry admin page

- README.md
Ruby 1.9 still works, but is no longer recommended. No compatibility
issues with any Ruby 2 version are known at this point.
> Update ruby version requirement in README

- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/facebook.js
- app/assets/javascripts/pageflow/widgets/loading_spinner.js
- app/assets/stylesheets/pageflow/base.scss
On iOS Facebook displays a toolbar at the bottom of the screen hiding
parts of the play controls. Detect Facebook browser via user agent and
apply fixed position to wrapper.
> Ensure facebook app does not crop viewport

- app/views/layouts/pageflow/application.html.erb
content_tag with a nested yield does not work completely, because the
end of the tag is swallowed unless you use `capture` inside the block.
This change replaces the content_tag helper with the regular HTML tag.
Now the </body></html> appears in the page.
> Remove cargo-culted @body_class

- app/assets/stylesheets/pageflow/base.scss
The same problem with a custom app toolbar hiding parts of the
Pageflow now also happens in other apps (i.e. Twitter). Since the fix
does not seem to change the behavior in other iOS browsers, apply it
universally.
> Extend Facebook in-app browser fix to iOS platform

- app/assets/stylesheets/pageflow/base.scss
The same problem with a custom app toolbar hiding parts of the
Pageflow now also happens in other apps (i.e. Twitter). Since the fix
does not seem to change the behavior in other iOS browsers, apply it
universally.
Backport of #637
> Extend Facebook in-app-browser fix to ios platform

- admins/pageflow/entry.rb
- spec/controllers/admin/entries_controller_spec.rb
- Only users with account manager or admin permissions will see the
account filter
- The account filter will only display accounts within the scope of the
respective user
> Have account filter respect permissions

- app/assets/javascripts/pageflow/slideshow/hidden_text_indicator_widget.js
So far the css classes `hide_content_with_text` and
`no_hidden_text_indicator` had to be present on the page's `section`
element. Allowing them also on the `.content_and_background` wrapper
element makes things much easer to control for page types since that
element is rendered by them.
> Allow setting hide text related css classes on wrapper

- config/initializers/zencoder.rb
- lib/pageflow/zencoder_video_output_definition.rb
- spec/pageflow/zencoder_video_output_definition_spec.rb
- spec/support/matchers/have_output.rb
Additionally, test for all generated outputs, depending on flags
skip_hls and skip_smil.
fixes #536
> Add option to skip smil output

- app/assets/javascripts/pageflow/slideshow/lazy_page_widget.js
The page widget sets an index property during initialization. This is
used by analytics adapters to create page names of the form
"<index>-<page_title>". While creating the lazy loading page widget
wrapper, this property must have been forgotten. Ensure it is also set
on the wrapper widget.
> Fix page widget index for analytics adapters

- app/assets/javascripts/pageflow/editor/api.js
- app/assets/javascripts/pageflow/editor/api/file_type.js
- app/assets/javascripts/pageflow/editor/api/file_types.js
- app/assets/javascripts/pageflow/editor/collections/files_collection.js
- app/assets/javascripts/pageflow/editor/collections/subset_collection.js
- app/assets/javascripts/pageflow/editor/controllers/sidebar_controller.js
- app/assets/javascripts/pageflow/editor/initializers/routing.js
- app/assets/javascripts/pageflow/editor/routers/sidebar_router.js
- app/assets/javascripts/pageflow/editor/templates/files_blank_slate.jst.ejs
- app/assets/javascripts/pageflow/editor/templates/filtered_files.jst.ejs
- app/assets/javascripts/pageflow/editor/views/file_item_view.js
- app/assets/javascripts/pageflow/editor/views/files_view.js
- app/assets/javascripts/pageflow/editor/views/filtered_files_view.js
- app/assets/javascripts/pageflow/editor/views/inputs/file_input_view.js
- app/assets/stylesheets/pageflow/editor/base.scss
- app/assets/stylesheets/pageflow/editor/filtered_files.scss
- config/locales/new/file_filters.de.yml
- spec/javascripts/api_spec.js
- spec/javascripts/collections/files_collection_spec.js
* Let file types define named filter functions that can be applied to
the list of files.
* Extend `selectFile` API function to accept options object which
contains file selection handler name and filter name.
* Extract `FilteredFilesView` from `FilesView` which applies the
specified filter to the list and displays a banner with a link to
display the complete list again.
* Add options `FileInputView` to specify a filter name for file
selection.
* Allow displaying a custom text when no files match the active filter.
> File filters

- app/assets/javascripts/pageflow/widgets/navigation_mobile.js
Scroller in mobile should not prevent default. Preventing default on
`touchstart` causes `click` events not to be fired which made it
impossible to expand sharing menu items.
Since native scrolling is prevented for the mobile navigation anyway,
the option can be disabled.
> Fix sharing menu in mobile navigation

- app/assets/javascripts/pageflow/widgets/navigation_mobile.js
Scroller in mobile should not prevent default. Preventing default on
`touchstart` causes `click` events not to be fired which made it
impossible to expand sharing menu items.
Since native scrolling is prevented for the mobile navigation anyway,
the option can be disabled.
Backport of #661
> Backport: Fix sharing menu in mobile navigation

- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/video.js
Already Safari 9 failed to loop hls videos. While Safari 10 on Sierra
appears to be fixed, Safari 10 on El Capitan still has the
problem. Since there is no obvious way to detect El Capitan/Sierra,
apply the fix to both browser versions.
> Fix video loop on Safari 10 on El Capitan.

- app/assets/javascripts/pageflow/widgets/navigation.js
- app/assets/javascripts/pageflow/widgets/overview.js
- app/assets/stylesheets/pageflow/navigation_bar.scss
- app/assets/stylesheets/pageflow/overview.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/dimensions.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/icons/icon_font.scss
- app/assets/stylesheets/pageflow/themes/default/navigation/icons/sprite.scss
- app/assets/stylesheets/pageflow/themes/default/overview/icons/icon_font.scss
- app/assets/stylesheets/pageflow/themes/default/overview/icons/sprite.scss
- app/assets/stylesheets/pageflow/themes/legacy/navigation.scss
- app/views/pageflow/entries/navigation/_bar_bottom.html.erb
- app/views/pageflow/entries/navigation/_bar_top.html.erb
- app/views/pageflow/entries/overview/_entry.html.erb
Styles meant for the main scroll indicator applied to the scroll
indicators inside the navigation and overview widgets.
Prefix classes with widget name to prevent collision.
> Fix css class collision in widget scroll indicators

- app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
Allow to reuse the watermark logo inside the header widget. The logo
fades in as soon as the header is active.
> Add logo theme option to fade in with header

- app/assets/javascripts/pageflow/ui/utils/i18n_utils.js
- spec/javascripts/pageflow/ui/utils/i18n_utils_spec.js
- add html option to findTranslation, which will expand searches to also
look for keys with _html suffix
- HTML-escape translations whose keys do not end in _html
> Improve HTML translation support in I18nUtils

- app/assets/javascripts/pageflow/slideshow/atmo.js
This way, sites have the option to force this value after the Pageflow
javascript-code is done initialising.
See #554 for previous discussion.
> move disabled into the initializer

- app/assets/javascripts/pageflow/editor/initializers/setup_collections.js
- app/assets/javascripts/pageflow/ready.js
Create a uniform end point for libraries to subscribe to, which need
to load data either from the JSON seed or the Backbone collections.
> Trigger event when seed data is available

- spec/models/pageflow/edit_lock_spec.rb
FactoryGirl no longer allows models created by `build_stubbed` to
access database methods, which some of `EditLock`'s methods do. Use
`create` strategy instead if a database id is required for the test.
> Use create instead of build_stubbed in EditLock tests

- app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
If the loading spinner has a drop shadow of its own, the glow does not
make sense.
> Add theme option to hide glow behind loading spinner logo

- .travis.yml
`has_scope 0.7`, which is now allowed by newer versions of `inherited_resources`, requires Ruby 2.1.7.
> Update Travis Ruby version to 2.1.7

- app/mailers/pageflow/user_mailer.rb
- spec/mailers/pageflow/user_mailer_spec.rb
Starting with version 2.4.1 `resque_mailer` symbolizes keys in
parameters passed to mailer methods. Symbolize keys to work with both
versions.
See also zapnap/resque_mailer#100
> Handle symbolized keys in mailer options

- app/assets/javascripts/pageflow/editor/models/mixins/retryable.js
Former parameter caused a get request, which lead to a 404.
> Use correct Backbone sync parameter to trigger retry

- app/helpers/pageflow/common_entry_seed_helper.rb
- app/helpers/pageflow/entry_json_seed_helper.rb
- app/models/concerns/pageflow/hosted_file.rb
- app/models/pageflow/audio_file_url_templates.rb
- app/models/pageflow/image_file.rb
- app/models/pageflow/image_file_url_templates.rb
- app/models/pageflow/original_hosted_file_url_templates.rb
- app/models/pageflow/url_template.rb
- app/models/pageflow/video_file_url_templates.rb
- app/views/pageflow/editor/files/_file.json.jbuilder
- app/views/pageflow/entry_json_seed/_entry.json.jbuilder
- app/views/pageflow/files/_file.json.jbuilder
- app/views/pageflow/video_files/_video_file.json.jbuilder
- lib/pageflow/built_in_file_type.rb
- lib/pageflow/file_type.rb
- lib/pageflow/page_types.rb
- spec/helpers/pageflow/common_entry_seed_helper_spec.rb
- spec/helpers/pageflow/entry_json_seed_helper_spec.rb
- spec/helpers/pageflow/files_helper_spec.rb
- spec/models/concerns/pageflow/hosted_file_spec.rb
- spec/models/pageflow/audio_file_url_templates_spec.rb
- spec/models/pageflow/image_file_spec.rb
- spec/models/pageflow/image_file_url_templates_spec.rb
- spec/models/pageflow/original_hosted_file_url_templates_spec.rb
- spec/models/pageflow/video_file_url_templates_spec.rb
- spec/support/helpers/json_helper.rb
* Include file model type names in common seed
* Include file url templates in common seed 
* Generate seed data for files
> Reorganize file seed data

- app/assets/stylesheets/pageflow/page_types/video/content_hiding.scss
Otherwise shadow and text hide the text tracks.
> Hide audio page content when text tracks are displayed

- .rubocop.yml
- app/assets/javascripts/pageflow/editor/models/page.js
- app/helpers/pageflow/common_entry_seed_helper.rb
- app/models/pageflow/thumbnail_file_resolver.rb
- app/views/pageflow/page_types/_page_type.json.jbuilder
- lib/pageflow/page_type.rb
- spec/helpers/pageflow/common_entry_seed_helper_spec.rb
- spec/helpers/pageflow/page_types_helper_spec.rb
- spec/javascripts/models/page_spec.js
- spec/models/pageflow/thumbnail_file_resolver_spec.rb
Allow restricting when a thumbnail candidate may be used by giving an
attribute and a desired value. This makes it possible, for example, to
use different thumbnail candidates based on a `background_type`
configuration attribute.
> Introduce conditional thumbnail candidates

- config/initializers/zencoder.rb
Also fall back to `s3_host_alias` when `hls_host_alias` or
`hls_origin_host_alias` is `nil`, not only when the key is not
present.
Otherwise, when reading the option from an environment variable, we
have to make sure not to set the key if the value is not present.
> Improve hls options fallback

- app/assets/javascripts/pageflow/editor/models/entry.js
Filter out attribute when setting files collection in non-merge mode.
> Do not overwrite file rights when polling

- app/assets/stylesheets/pageflow/themes/default/player_controls/vjs_mapping.scss
- node_package/src/components/PageBackground.jsx
- node_package/src/components/__spec__/PageBackground-spec.jsx
- node_package/src/interactivePageBackground/components/Page.jsx
- node_package/src/media/components/Page.jsx
Allow displaying the slim control's shadow along the bottom for pages
with player controls. The old solution causes the shadow to be applied
twice on audio pages with background video.
> Add css class to page background with controls

- config/locales/new/alt.de.yml
- config/locales/new/alt.en.yml
- config/locales/new/background_types.de.yml
- config/locales/new/confirm_upload.de.yml
* Mention screen readers
* Say that file rights are displayed in the copyright section
> Improve inline help for rights and alt text field

- app/assets/stylesheets/pageflow/themes/default/mixins/indicator_typography.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/slim/control_bar.scss
Allow overriding for phone, desktop or in general.
> Allow overriding typography of slim control bar text

- app/assets/javascripts/pageflow/editor/views/file_item_view.js
Allow file selection handler to return `false` to prevent redirection
back to referer. This can be used if the made selection was invalid or
if navigation was already triggered by the `call` method.
> Let file selection handler abort navigation

- node_package/src/media/components/createFilePlayer/handlePlayerState.js
- node_package/src/media/components/createFilePlayer/index.jsx
Prevent getting stuck in prebuffering state when it has been triggered
before a file has been assigned.
> Continue prebuffer on media tag init

- app/assets/javascripts/pageflow/browser/autoplay_support.js
- app/assets/javascripts/pageflow/browser/facebook.js
- app/assets/javascripts/pageflow/browser/ios_platform.js
- app/assets/javascripts/pageflow/browser/video.js
- app/assets/javascripts/pageflow/media_player/volume_fading.js
- node_package/src/media/components/PageBackgroundVideo.jsx
- node_package/src/media/components/__spec__/PageBackgroundVideo-spec.jsx
* Autoplay
* Native video player
Add iphone platform and native video player features
Show video poster if mute autoplay is not supported
There is no easy way to feature detect autoplay. Since eventually all
devices will support it and a custom mobile poster can always be
specified, we can drop the special case.
> Add feature detection for mobile video features

- spec/models/pageflow/edit_lock_spec.rb
- spec/models/pageflow/user_spec.rb
RSpec < 3.6 used to rely on `record.persisted?` in `be_new_record`
matcher. Now it used `record.new_record?` which is false for destroyed
records. Use correct `be_destroyed` matcher which simply delegates to
`record.destroyed?`.
> Use correct matcher to expect destroyed record

- app/assets/javascripts/pageflow/ui/views/inputs/select_input_view.js
- spec/javascripts/pageflow/ui/views/inputs/select_input_view_spec.js
The change in #725 made sure that the first option is always displayed
as a default value in a select box without blank item. This broke the
`ensureValueDefined' option: A value would only be defined if the
select box did not have selected item.
Instead explicitly check that if the model has a value defined for the
property. If not, calling `save` is enough now since the first item
has already been selected.
> Fix ensureValueDefined option of SelectInputView

- CHANGELOG.md
- config/initializers/paperclip.rb
In addition to the existing Expires header _for now_. I am actually proposing we get rid of the Expires header completely. I'll write this in a comment on the pull request.
Expires is HTTP/1.0 (!)
Cache-Control is HTTP/1.1 and supersedes Expires.
Cache-Control offers everything from Expires and a lot more.
In our case, it's important to mark the files public, so that they will
be cached by proxies. Also give them the same high expiry time (1 year), because they
have timestamps in the URL, which invalidates the cache.
> add Cache-Control header for S3 uploads

- node_package/spec/support/index.js
- node_package/spec/support/mockContext.js
- node_package/spec/support/stubI18n.js
- node_package/src/__spec__/i18n-spec.js
- node_package/src/components/CloseButton.jsx
- node_package/src/components/__spec__/CloseButton-spec.jsx
Use the `t` function which is given via `connect`, rather than
accessing the global `I18n` object which uses the   default locale.
> Use entry locale in CloseButton translations

- app/assets/javascripts/pageflow/editor/models/page.js
On choosing a page link, properly update title when it should be an
empty string. Without this, e.g. in ReferenceInputView, `title` will
not update in certain situations, because page#title() returns
`'undefined'` due to `''` falsiness in Javascript.
To reproduce:
```
this.configuration.get('title') === ''
this.configuration.get('additional_title') === undefined
```
> Fix page title hysteresis

- app/models/pageflow/roles.rb
- spec/models/pageflow/roles_spec.rb
Normally when a user that is member of entry is also member of the
entry's account. Still this can be false when an entry has been moved
between accounts.
Prevent exception on entry admin page when trying to find the highest
role of a user.
> Change Roles.high to not expect account membership

- app/views/components/pageflow/admin/user_accounts_tab.rb
- app/views/components/pageflow/admin/user_entries_tab.rb
- lib/pageflow/view_component.rb
- spec/support/config/devise.rb
- spec/support/helpers/view_component_example_group.rb
- spec/views/components/pageflow/admin/user_accounts_tab_spec.rb
- spec/views/components/pageflow/admin/user_entries_tab_spec.rb
When eager loading memberships entities, we need to ensure (using
`references`) that ActiveRecord always does a join instead of separate
query. Otherwise the conidition inside the `account`/`entry`
associations references a missing column.
Before the table only worked when sorting by entity name since the
order requires a join.
Also make sure to actually use the preloaded association to prevent
N+1 queries.
> Fix exception when sorting user accounts table by role

- app/assets/stylesheets/pageflow/themes/default/player_controls/widget_margins.scss
widgets don't _have_ to provide it.
it will raise an error in the default player otherwise.
continuation of #771
> mark %pageflow_widget_margin_right optional

- CHANGELOG.md
- config/initializers/widget_types.rb
- lib/generators/pageflow/initializer/templates/pageflow.rb
- spec/generators/pageflow/initializer/initializer_generator_spec.rb
This exposes the player controls, making them configurable from the host
application. It's possible to do this already, directly in the pageflow
initializer:
```
config.widget_types.register(Pageflow::BuiltInWidgetType.slim_player_controls,
default: true)
```
The classic controls would still be available, though. To allow removing
them altogether, I see different options:
- The simplest thing would be to move the registration calls for the
widget types [1] to the host application initializer. This would be a
breaking change, but maybe even more aligned with the way things work
for built in page types already.
> move player controls to host pageflow initialization

- CHANGELOG.md
- lib/generators/pageflow/initializer/templates/pageflow.rb
- lib/pageflow.rb
- lib/pageflow/built_in_widget_types_plugin.rb
- spec/generators/pageflow/initializer/initializer_generator_spec.rb
In #774, widget type registrations have been moved to the host application, to
allow disabling built in widget types.
Extracting the register calls into a plugin has a couple of
advantages:
* Should there ever be a need to add a built-in widget type, host
applications which follow the default setup need not be modified.
* More in line with the way built in page types are registered.
* Same flexibility: If you do not wish to use the default set of built
in widget types, simply replace the plugin with a bunch of custom
register calls.
> Move register calls for built-in widget types to plugin

- app/helpers/pageflow/themes_helper.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/published_entry.rb
- app/models/pageflow/revision.rb
- app/models/pageflow/theming.rb
- app/views/admin/accounts/_form.html.erb
- app/views/pageflow/config/_editor_seeds.json.jbuilder
- db/migrate/20170315130000_add_theme_name_to_revisions.rb
- lib/pageflow/configuration.rb
- lib/pageflow/seeds.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/features/account_manager/editing_an_account_spec.rb
- spec/helpers/pageflow/entry_json_seed_helper_spec.rb
- spec/helpers/pageflow/themes_helper_spec.rb
- spec/models/concerns/pageflow/feature_target_spec.rb
- spec/models/pageflow/home_button_spec.rb
- spec/models/pageflow/overview_button_spec.rb
- spec/models/pageflow/revision_spec.rb
- spec/models/pageflow/theming_spec.rb
Integrate themes with feature flags
> Themes as features

- app/assets/stylesheets/pageflow/themes/default/logo/alignment.scss
- app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
- app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
In phone layout, the logo remains on left side to prevent conflict
with mobile navigation button.
> Add theme option to right align logo in desktop layout

- app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
Provide a separate variable for the logo on the first page, to allow
e.g. having a transparent logo on all but the first page.
> Allow specifying opacity of image variant logo

- app/assets/stylesheets/pageflow/themes/default/page/line_lengths.scss
When split layout is enabled, we not only need to shorten the title
but all page content. Otherwise page content can overlap with the
embed if a theme increases `$page-content-max-width` or
`$page-content-width`.
> Ensure all content is contained in left columns

- app/assets/javascripts/pageflow/audio_context.js
- app/assets/javascripts/pageflow/audio_player.js
- app/assets/javascripts/pageflow/audio_player/get_media_element_method.js
- app/assets/javascripts/pageflow/base.js
- app/assets/javascripts/pageflow/media_player/volume_fading.js
- app/assets/javascripts/pageflow/media_player/volume_fading/interval.js
- app/assets/javascripts/pageflow/media_player/volume_fading/noop.js
- app/assets/javascripts/pageflow/media_player/volume_fading/web_audio.js
- app/assets/javascripts/pageflow/video_player.js
- app/assets/javascripts/pageflow/video_player/get_media_element_method.js
- vendor/assets/javascripts/audio5.min.js
Setting `volume` in an interval has performance issues and can lead to
popping/sizzling noises on Firefox.
* Add `getMediaElement` method to media players to allow accessing the
underlying media element. This required use the players as audio
source.
* Add a Pageflow API to create a shared `AudioContext`. There can only
be a limited number of contexts in one page (i.e. 6 in Chrome, at
the time of writing). So allow reusing it for all Pageflow features.
* If an `AudioContext` can be created, connect a gain node and use its
methods to perform volume fading.
* On Chrome and Firefox, the `crossorigin` attribute needs to be set
to `anonymous`, to allow `AudioContext` usage for cross origin audio
files. Since `audio5js` is already patched, make adding the
attribute the new default.
> Use Web Audio API for volume fading if available

- app/models/pageflow/entry_publication.rb
- spec/models/pageflow/entry_publication_spec.rb
Allow plugins to register custom functionality to be performed when an
entry has been published.
> Call hook on entry publication

- app/models/concerns/pageflow/feature_target.rb
- app/models/concerns/pageflow/output_source.rb
- app/models/concerns/pageflow/serialized_configuration.rb
super is a bit counter-intuitive since the method might not exist on the superclass, but we're just relying on the message being picked up anyway. By reading the attribute the intent is made more clear.
We are not using `read_attribute` but the brackets, because the latter raises an exception when the attribute cannot be found. The rails style guide recommends so. https://github.com/bbatsov/rails-style-guide#read-attribute
> read the attribute instead of super

- app/helpers/pageflow/social_share_helper.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
Fallback to page thumbnails if configured share image no longer
exists.
> Prevent 404 when share image has been deleted

- spec/support/Rakefile
- spec/support/pageflow-support.gemspec
- spec/support/pageflow/dummy/app.rb
- spec/support/pageflow/dummy/rails_template.rb
* Prevent install generators from failing when generating dummy app in
plugin engine by requiring Pageflow from dummy app. In a real app
Pageflow would be required by Bundler since it would be listed in
the app's Gemfile. This need not be the case in plugin engines.
* Include pageflow version in dummy app directory name to ensure
regeneration when running specs with other Pageflow version.
* Ensure `pageflow-support` gem version matches `pageflow` gem
version.
* Restrict `mysql` dependency version.
* Allow using bundler gem tasks for `pageflow-support`.
> Improve pageflow-support gem

- doc/using_the_nginx_upload_module.md
Ensure files are cleaned up when upload fails due to edit lock
conflict.
> Improve nginx-upload-module example config

- node_package/src/components/index.js
Allow plugins to use the library which comes packaged with the
Pageflow gem.
> Export `Measure` from `react-measure`

- node_package/src/components/BackgroundImage.jsx
- node_package/src/utils/index.js
- node_package/src/utils/preloadBackgroundImage.js
Setting the `load_image` css class to make sure the `background-image`
rule applies does not trigger image loading (e.g. in Chrome). Detect
image url via computed styles to account for media queries and ensure
image is loaded via `new Image()`.
Originally similar functionality was part of most page types'
`preload` hooks, but has not been ported to React based page types so
far.
> Preload page background images

- app/models/pageflow/account_member_query.rb
- app/models/pageflow/account_role_query.rb
- app/models/pageflow/application_query.rb
- app/models/pageflow/entry_role_query.rb
- app/policies/pageflow/account_policy.rb
- spec/models/pageflow/account_member_query_spec.rb
- spec/models/pageflow/account_role_query_spec.rb
- Introduce AccountRoleQuery
- Introduce AccountMemberQuery
- Make AccountMemberQuery and EntryRoleQuery depend on ApplicationQuery
> Extend query interface

- app/assets/javascripts/pageflow/history.js
- app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
When looking at an entry each visited page used to be recorded as an
individual history entry. This can make it quite hard to leave a
Pageflow when coming from some external site since you have to trace
your whole path through the entry backwards.
Now instead, we only record history entries when changing pages via
links or buttons and ignore page changes that are caused by back/next
scroll navigation.
This allows to use the back button to return from a sub storyline or
go back to a page with internal links. The overall behavior should
resemble interaction with a normal website much more closely.
> Do not record history when changing pages via scrolling

- app/assets/javascripts/pageflow/history.js
- app/assets/javascripts/pageflow/slideshow.js
Previously when opening a URL with a page id fragment, the entry's
first page would shortly be visible followed by an instant transition
to the target page.
This is especially problematic for analytics purposes as the short
visit to the first page is counted as a normal page impression.
This changes ensures the page given by the id in the url fragment is
visited right away.
> Use page from URL hash es landing page

- admins/pageflow/membership.rb
- app/views/admin/memberships/_form.html.erb
- app/views/admin/memberships/_role_hint.html.arb
- app/views/components/pageflow/admin/add_membership_button_if_needed.rb
- app/views/components/pageflow/admin/members_tab.rb
- app/views/components/pageflow/admin/user_accounts_tab.rb
- app/views/components/pageflow/admin/user_entries_tab.rb
- app/views/components/pageflow/admin/users_tab.rb
- remove redundant `permitted_params`
- change form: entry/account for query params which are visible in URLs, 'Pageflow::Entry'/'Pageflow::Account' elsewhere to minimize confusion
> Fix memberships

- admins/pageflow/user.rb
- app/models/pageflow/invitation_form.rb
- app/models/pageflow/invited_user.rb
- app/views/admin/users/_form.html.erb
- app/views/admin/users/invitation.html.erb
- config/locales/new/invitation_form.de.yml
- config/locales/new/invitation_form.en.yml
- spec/controllers/admin/users_controller_spec.rb
- spec/features/account_manager/inviting_a_user_spec.rb
- spec/features/registered_user/editing_profile_spec.rb
- spec/support/dominos/admin/invitation_form.rb
There a are two bugs in Pageflow 12.0.0 that allow signed in users to escalate their privileges.
* With a manually crafted request, any signed in user can set the `admin` flag on their own user account.
* With a manually crafted request, a user with account manager role in at least one account, can add users to arbitrary accounts. This can be used to gain account manager privileges in any account.
Affected versions: 12.0.0 (including all release candidates)
Unaffected version: 0.11.x and older
Versions fixes: 12.0.1
> Prevent escalation of privileges

- admins/pageflow/accounts.rb
- admins/pageflow/user.rb
- app/policies/pageflow/entry_policy.rb
- app/policies/pageflow/user_policy.rb
- lib/pageflow/ability_mixin.rb
- lib/pageflow/active_admin_can_can_fix.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/features/account_manager/listing_users_spec.rb
- spec/features/admin/sees_all_users_spec.rb
- spec/pageflow/active_admin_can_can_fix_spec.rb
- spec/policies/pageflow/entry_policy_spec.rb
- spec/policies/pageflow/user_policy_spec.rb
CanCan does not evaluate `can` blocks when classes are passed as
subject. Switch to passing symbols in these cases to prevent new and
index pages from being accessible for users without permissions.
> Ensure new entry button is hidden for editors

- admins/pageflow/accounts.rb
- admins/pageflow/entry.rb
- admins/pageflow/user.rb
- app/policies/pageflow/account_policy.rb
- app/policies/pageflow/application_policy.rb
- app/policies/pageflow/entry_policy.rb
- app/policies/pageflow/user_policy.rb
- config/initializers/admin_resource_tabs.rb
- lib/pageflow/ability_mixin.rb
- lib/pageflow/configuration.rb
- lib/pageflow/configuration/permissions.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/policies/pageflow/account_policy_spec.rb
- spec/policies/pageflow/entry_policy_spec.rb
- spec/policies/pageflow/user_policy_spec.rb
Allow taking permissions from account managers to
* manage features
* set entry theming
* see admin flags on user admin page
> Add config options to restrict account manager permissions

- admins/pageflow/user.rb
- app/views/admin/users/me.html.erb
- spec/controllers/admin/users_controller_spec.rb
- spec/models/pageflow/user_spec.rb
Prevent displaying unsafed data in utility navigation when validation
failed.
> Use copy of current_user in profile form

- app/models/pageflow/revision.rb
- app/models/pageflow/theming.rb
leaves invalid rows in the database otherwise.
> destroy widgets when parent subject is destroyed

- .rubocop.yml
- app/models/pageflow/video_file.rb
- app/models/pageflow/zencoder_attachment.rb
- lib/pageflow/zencoder_video_output_definition.rb
- spec/factories/entries.rb
- spec/factories/video_files.rb
- spec/models/pageflow/video_file_spec.rb
- spec/models/pageflow/zencoder_attachment_spec.rb
- spec/pageflow/zencoder_video_output_definition_spec.rb
- spec/spec_helper.rb
- spec/support/matchers/have_output.rb
- spec/support/matchers/url_matchers.rb
CDN urls might change or be generated dynamically. Prevent having to
regenerate all playlists then.
> Use relative URLs inside dash and hls playlists

- app/assets/javascripts/pageflow/editor/initializers/setup_file_types.js
Safari gives an empty string as `type` for vtt file uploads. Test for
file extension instead. We already do this for `srt` files anyway.
> Fix file type detection for vtt uploads on Safari

- app/views/components/pageflow/admin/revisions_tab.rb
Changes nothing about actual permissions; they were not allowed to use
these anyway
> Hide Restore link and Snapshot button for entry previewers

- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/textTracks.js
When text tracks load asynchronously, we need to make sure to update
the mode once they have been added. In some cases text tracks
activated by default were not displayed during the initial run.
> Activate text track after it has been added

- app/jobs/pageflow/prune_auto_snapshots_job.rb
- app/models/pageflow/auto_snapshot_pruning.rb
- app/models/pageflow/chapter.rb
- app/models/pageflow/revision.rb
- app/models/pageflow/storyline.rb
- lib/tasks/pageflow_tasks.rake
- spec/jobs/pageflow/prune_auto_snapshots_job_spec.rb
- spec/models/pageflow/auto_snapshot_pruning_spec.rb
Prevent database from growing too much.
> Add Rake task and Resque job to delete old auto snapshots

- app/assets/javascripts/pageflow/media_player/volume_fading.js
`pagefow-vr` player does not support accessing the media element
directly.
> Use Web Audio volume fading only if player has getMediaElement

- node_package/src/media/selectors.js
Fails in server side rendering.
> Prevent calling localeCompare of null.

- README.md
- doc/versioning_policy.md
Adjust install instructions to depend on specific minor versions and
mention manual update steps.
> Add documentation for versioning policy

- db/migrate/20170222124848_update_video_file_output_presences.rb
If hls files are generated from smil files, the output will be [marked as present automatically][1]. If Zencoder generated hls playlists were used, they need to be marked as present in this migration. We can simply add the item to the list by default since the externally generated items are [merged as a hash][2] preventing duplicates in the resulting list.
[1]: https://github.com/codevise/pageflow/blob/c54d3fce638f8ed40f4ec0d6a9c0e8f1be5d7bc3/app/models/pageflow/video_file.rb#L143
[2]: https://github.com/codevise/pageflow/blob/c54d3fce638f8ed40f4ec0d6a9c0e8f1be5d7bc3/app/models/concerns/pageflow/output_source.rb#L44
> Include hls in output presences of legacy files

- CHANGELOG.md
- README.md
- lib/generators/pageflow/routes/routes_generator.rb
- spec/generators/pageflow/routes/routes_generator_spec.rb
This will mount Resque::Web in the routes at /background_jobs.
Fixes #856
> add Resque::Server to install generator

- .travis.yml
- Rakefile
- spec/support/pageflow/dummy/app.rb
On some internal projects this approach reduced the timout related
Poltergeist errors since assets are no longer precompiled in the
request cycle the first time any asset is used.
> Precompile assets in Travis run

- app/assets/javascripts/pageflow/media_player.js
- app/assets/javascripts/pageflow/media_player/catch_play_promise.js
- app/assets/javascripts/pageflow/video_player/use_slim_controls_during_phone_playback.js
- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/index.jsx
VideoJS 6 initialized the HTML5 tech asynchronously. Interaction with the
API is only possible after the `ready` callback has been invoked.
When updating video related attributes in the editor, attempts to interact
with the player shortly after its recreation lead to exceptions which
prevented changes to be saved to the server.
Fixes #874
> Handle async tech loading in VideoJS 6

- app/models/pageflow/url_template.rb
- spec/models/pageflow/url_template_spec.rb
Prevent `:id_partition` placeholder from being inserted multiple
times.
> Make url template generation more robust

- app/views/components/pageflow/admin/users_tab.rb
Do not load account N times via `membership.entity`. We already know
that it's the account we are currently viewing.
> Fix N+1 query in account admin users tab

- node_package/src/components/PlayerControls/TimeDisplay.jsx
- node_package/src/components/PlayerControls/__spec__/TimeDisplay-spec.jsx
- node_package/src/media/__spec__/createReducer-spec.js
- node_package/src/media/actions.js
- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/watchPlayer.js
- node_package/src/media/createReducer.js
HLS on Android reports NaN initially. Update on timeupdate and prevent
display of broken time stamps.
> Improve handling of NaN duration

- app/helpers/pageflow/video_files_helper.rb
The `VideoFilesHelper` is still used to render video tags in linkmap
pages. Without the crossorigin attribute, volume fading via Web Audio
Api is not permitted.
> Add crossorigin attribute to video tag rendered by helper

- app/helpers/pageflow/public_i18n_helper.rb
- spec/helpers/pageflow/public_i18n_helper_spec.rb
Only use default locale if key is missing.
> Fix order of public i18n fallback

- app/models/pageflow/entry.rb
- app/models/pageflow/revision.rb
- db/migrate/20170912165050_reset_copied_snapshot_type.rb
- spec/factories/revisions.rb
- spec/models/pageflow/entry_spec.rb
- spec/models/pageflow/revision_spec.rb
Reset the snapshot type attribute when copying a snapshot revision to
make it the new draft.
Migrate database to reset snapshot type of drafts that were restored
from snapshot or publications that were copied from such drafts.
> Reset snapshot type when restoring revision

- app/assets/javascripts/pageflow/base.js
- app/assets/javascripts/pageflow/vendor.js
- app/views/layouts/pageflow/application.html.erb
- lib/pageflow/engine.rb
- spec/javascripts/spec_helper.js
These will be compiled separately. Since they change less often,
the idea is that these assets will remain in cache for longer.
Continuation of #860 where Travis refused to play nice.
> Split vendored code from our own

- app/models/pageflow/account.rb
- app/models/pageflow/application_record.rb
- app/models/pageflow/audio_file.rb
- app/models/pageflow/chapter.rb
- app/models/pageflow/edit_lock.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/file_usage.rb
- app/models/pageflow/folder.rb
- app/models/pageflow/image_file.rb
- app/models/pageflow/membership.rb
- app/models/pageflow/page.rb
- app/models/pageflow/revision.rb
- app/models/pageflow/storyline.rb
- app/models/pageflow/text_track_file.rb
- app/models/pageflow/theming.rb
- app/models/pageflow/video_file.rb
- app/models/pageflow/widget.rb
All models inherit from it instead of `ActiveRecord::Base`.
This is the default in Rails too and it provides a standard approach to
put things applicable to all models.
> Introduce ApplicationRecord

- .travis.yml
Calling `bundle exec` from a ruby script after Bundler has been set up
fails for vendored Bundler version that comes with Rubygems 2.7.
https://github.com/rubygems/rubygems/issues/2055
`rake pageflow:dummy` invokes `bundle exec rails new`. Calling `rake`
via `bundle exec` can be used as a temporary workaround.
> Fix dummy app generation on Travis for Rubygems 2.7

- app/mailers/pageflow/user_mailer.rb
Stating with [1] a `HashWithIndifferentAccess` is passed which does
not support the `symbolize_keys!` method which we used before to
ensure compatbility with `resque_mailer` 2.4.1.
[1] https://github.com/zapnap/resque_mailer/pull/102
> Work around breaking change in resque_mailer 2.4.3

- app/views/admin/accounts/_form.html.erb
- app/views/admin/accounts/_theming_defaults_inline_help.html.erb
- app/views/admin/accounts/_widgets_inline_help.html.erb
- config/locales/new/theming_defaults.de.yml
- config/locales/new/theming_defaults.en.yml
Themes can now be configured per entry. The theme name stored in
`Theming` only acts as a default.
> Move theme name drop down into defaults sections

- app/assets/javascripts/pageflow/editor/collections/pages_collection.js
- app/assets/javascripts/pageflow/editor/collections/subset_collection.js
- spec/javascripts/collections/subset_collection_spec.js
fixes #890
The editor preview displays a subset collection of persisted
pages. Ensure subset collections sort when parent collection is
sorted.
> Ensure page order in editor preview stays up to date

- admins/pageflow/accounts.rb
- admins/pageflow/entry.rb
- admins/pageflow/user.rb
- app/models/concerns/pageflow/serialization_blacklist.rb
- app/models/pageflow/account.rb
- app/models/pageflow/entry.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/models/concerns/pageflow/serialization_blacklist_spec.rb
- spec/models/pageflow/account_spec.rb
- spec/models/pageflow/entry_spec.rb
* Define CSV columns to work around unsafe defaults.
* Remove entry password_digest and feature_configuration attributes
from JSON/XML serializations.
> Remove sensitive data from Active Admin downloads

- .travis.yml
The fix introduced in #893 is no longer needed with RubyGems 2.7.3.
> Remove RubyGems 2.7.0 dummy app generation fix

- doc/adding_editor_help_entries.md
- doc/creating_a_pageflow_plugin_rails_engine.md
- doc/creating_page_types.md
- doc/creating_page_types/custom_redux_modules.md
- doc/creating_page_types/displaying_background_images_or_videos.md
- doc/creating_page_types/editor_integration.md
- doc/creating_page_types/using_separate_scroller_and_foreground.md
- doc/creating_widget_types.md
- doc/creating_widget_types/editor_integration.md
- doc/creating_widget_types/enabling_widgets_by_default.md
- doc/creating_widget_types/theme_integration.md
- doc/creating_widget_types/widget_margins.md
- doc/creating_widget_types/with_erb_templates.md
- doc/creating_widget_types/with_react_components.md
- doc/index.md
- doc/using_redux_selectors.md
* Describe the recommended React based approach to create page types
* Describe both the ERB and React based approach to create widget
types
* Give an overview of the Redux related concepts in Pageflow
* Incorporate steps to create Rails engine written by @tilsammans 
This still needs a bit of proof reading, but I guess it's an okay starting point.
> Update page type and widget type creation guides

- doc/adding_app_news.md
- doc/index.md
- doc/using_krant_to_display_broadcast_messages_and_news.md
- lib/pageflow.rb
- lib/pageflow/configuration.rb
- lib/pageflow/news_item_api.rb
- spec/pageflow/news_item_api_spec.rb
Provide api for plugins to register news items to be added to the
configured news collection.
See https://github.com/codevise/krant
> Allow integrating with Krant app news

- app/views/admin/accounts/_account_details.html.arb
- app/views/admin/accounts/_theming_details.html.arb
- app/views/admin/entries/_attributes_table.html.arb
- app/views/components/pageflow/admin/extensible_attributes_table.rb
- config/initializers/admin_attributes_table_rows.rb
- doc/extending_admin_resources.md
- doc/index.md
- lib/pageflow/admin/attributes_table_rows.rb
- lib/pageflow/configuration.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/factories/accounts.rb
- spec/factories/entries.rb
- spec/views/components/pageflow/admin/extensible_attributes_table_spec.rb
Let plugins add rows to the attributes tables that are displayed on
the admin resource pages.
> Allow registering admin attributes table rows

- app/assets/javascripts/pageflow/slideshow/hide_text_on_swipe.js
- app/assets/javascripts/pageflow/slideshow/page_widget.js
- app/assets/javascripts/pageflow/slideshow/swipe_gesture.js
Reaching inside the page's DOM from the page widget to attach event
listeners does not work when React re-renders the page. Use event
delegation on the page's element which never changes during the page
life cycle.
> Fix "hide text" swipe gesture for React page types

- app/assets/javascripts/pageflow/slideshow.js
- app/assets/javascripts/pageflow/slideshow/page_split_layout.js
Previously logic was duplicated in pageflow-chart and
pageflow-embedded-video, but needed to get more complicated to handle
the following cases:
* Hidden title: When the title has been hidden we need to measure the
page content.
* Temporarily hidden text: When the user clicks the "hide text"
button, the content text moves out to the left. We need to account
for this changed position when measuring the space left and right of
the content.
> Add page split layout utility methods

- .rubocop.yml
- admins/pageflow/user.rb
- app/policies/pageflow/user_policy.rb
- lib/pageflow/ability_mixin.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/features/account_manager/deleting_a_user_spec.rb
- spec/features/account_manager/suspending_a_user_spec.rb
- spec/policies/pageflow/user_policy_spec.rb
Account managers need a way to revoke member access. When multi
account users are disabled, the sole account membership cannot be
deleted. In this case, it makes sense to allow account managers to
suspend or even destroy users since they cannot be members of any
other account anyway.
Moreover, this PR adds missing authorization logic for the admin
controller actions used to suspend users or resend invitation mails.
> Extend user management permissions in single account mode

- app/assets/stylesheets/pageflow/page.scss
- app/assets/stylesheets/pageflow/themes/default/logo.scss
- app/assets/stylesheets/pageflow/themes/default/page.scss
- app/assets/stylesheets/pageflow/themes/default/page/line_lengths.scss
- app/assets/stylesheets/pageflow/themes/default/page/paddings.scss
Mainly motivated by the need to customize the padding top on all pages
to make room for larger logos that are displayed on all pages.
Remove rules for `.content_and_background > .page_header`
selector. Before the React rewrite, video and audio page placed the
page header above the page background in statically rendered HTML and
had JS move the DOM element into the scroller. This alternative DOM
order allowed displaying the media tag below the page header in the
non-js case. Still, statically rendered media tags have long been
removed since they trigger preloading in a lot of browsers. Instead
only a link to a separate video page is present in the non-js
case. The alternative DOM order is no longer needed.
There were also special non-js styles for the video and audio page
removing page …
> Move page padding from legacy styles to theme

- app/assets/javascripts/pageflow/editor/initializers/setup_collections.js
- spec/helpers/pageflow/entries_helper_spec.rb
- spec/helpers/pageflow/themings_helper_spec.rb
* Remove unneeded TODO from Backbone initializer. Code has worked like
this for a long time. No intention to change it.
* Move url helpers include in spec to before block to align with other
helper specs.
> Remove TODO comments

- app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
The opacity value of the watermark logo variant can now be determined by the variable: 
`$logo-watermark-variant-opacity`
Default value is still 0.3
> Variable for watermark logo opacity

- admins/pageflow/entry.rb
- spec/controllers/admin/entries_controller_spec.rb
The name we want to filter by comes from the account model.
> Fix filtering in searchable theming select in entry form

- node_package/src/pages/__spec__/createPageType-spec.jsx
Calling jQuery's `append` method started to cause an error of the
form
'undefined' is not a function (evaluating 'elem.getAttribute( "type" )')
in a jQuery function called `disableScript` which tries to change the
`type` attribute of script tags while parsing HTML. I could not
reproduce the error locally. Also it is not clear to me why there
should be `script` elements inside the newly created div element.
As a workaround we can use DOM API instead of jQuery to setup the
fixture page element.
> Fix jQuery error in node_package specs on Travis

- app/helpers/pageflow/overview_helper.rb
- app/views/pageflow/entries/overview/_page.html.erb
- spec/helpers/pageflow/overview_helper_spec.rb
Prevent displaying a blank overlay for page items.
> Fallback to page title in overview page description

- app/assets/javascripts/pageflow/editor/views/page_preview_view.js
- app/assets/javascripts/pageflow/links.js
- app/assets/javascripts/pageflow/slideshow/page_widget.js
* Ensure page perma id links do not open new tab
* Make page perma id links work in editor by preventing default and
using slideshow navigation
* Move existing link target fix to page widget
> Improve content links to pages of entry

- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/autoplay_support.js
- node_package/src/media/components/PageBackgroundVideo.jsx
- node_package/src/media/components/__spec__/PageBackgroundVideo-spec.jsx
Same restrictions apply as on mobile devices.
> Mute background videos to fix autoplay on Safari 11

- app/assets/stylesheets/pageflow/themes/default/page.scss
The `margin-bottom` value had the same variable as the `margin-top` value. Now it uses the correct variable for the corresponding value how can specified themes.
> fixed wrong variable for page-header-title

- app/assets/stylesheets/pageflow/page_transitions/fade.scss
- app/assets/stylesheets/pageflow/page_transitions/fade_to_black.scss
- app/assets/stylesheets/pageflow/slideshow.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/slim/container.scss
Ensure `content` and `backgroundArea` only have transitions applied
when they are actually being animated. Otherwise they might be visible
when we want to move them out of the view quickly.
For page transitions CSS this means only applying `transition` when
- the `active` class is present (for animating a page into view)
- an `animate-out-*` class is present (for animating a page out of
view when it no longer has the `active` class.
`animate-in-*` classes are applied before the `active` class and are
used to move the page out of the viewport before the animation
begins. This needs to happen immediately.
For historic reasons, a redundant transition declaration was applied
in `slideshow.scss` that had to be removed. The different page
transitions need to handle this themselves.
Also the …
> Fix page transition effects in Chrome 66 and above

- lib/pageflow/engine.rb
- pageflow.gemspec
- spec/factories/accounts.rb
- spec/factories/audio_files.rb
- spec/factories/chapters.rb
- spec/factories/edit_locks.rb
- spec/factories/entries.rb
- spec/factories/feature_targets.rb
- spec/factories/file_usages.rb
- spec/factories/folders.rb
- spec/factories/hosted_files.rb
- spec/factories/image_files.rb
- spec/factories/invited_user.rb
- spec/factories/memberships.rb
- spec/factories/pages.rb
- spec/factories/revisions.rb
- spec/factories/storylines.rb
- spec/factories/text_track_files.rb
- spec/factories/themings.rb
- spec/factories/users.rb
- spec/factories/video_files.rb
- spec/factories/widgets.rb
- spec/support/config/factory_girl.rb
- spec/support/pageflow/dom/admin/page.rb
The gem has been renamed. Since plugin specs reuse factories this is a breaking change since it basically forces plugins to upgrade to FactoryBot as well.
> Replace FactoryGirl with FactoryBot

- app/models/pageflow/null_user.rb
- app/models/pageflow/revision.rb
Implement `to_ary` to make it behave like `nil` when being passed to
`Array.wrap`.
> Fix handling of null object in presence validation

- CHANGELOG.md
- README.md
- pageflow.gemspec
- spec/support/pageflow-support.gemspec
The 0.4 series contains versions that are not compatible with Rails
5.2.
> Use ar_after_transaction 0.5

- lib/generators/pageflow/resque/templates/resque.rb
- spec/support/pageflow/support.rb
This ensures presence of the `Resque` constant during generation
of the dummy app when using `pageflow-support`.
> Require resque in initializer

- config/initializers/zencoder.rb
- lib/pageflow.rb
- lib/pageflow/engine.rb
- lib/pageflow/zencoder_api.rb
Remove `require` calls for files that can be auto loaded during
initialization and will be eager loaded in engine.
Do not use `require_dependency` to load files that have
already been required in gemspec or `lib/pageflow.rb`.
> Prevent redefining constants by loading files multiple times

- app/assets/stylesheets/pageflow/page_types/video.scss
- app/assets/stylesheets/pageflow/page_types/video/mobile_poster.scss
- node_package/src/media/components/Page.jsx
Before the poster was only displayed if the `native_video_player`
feature was present. This is only the case on iPhone.
Now we show the poster on all phone platforms, but hide it while
videos are playing if the `native_video_player` feature is not
present. Otherwise the video being played inline would not be visible.
REDMINE-15810
> Ensure mobile video poster is displayed on Android

- app/assets/stylesheets/pageflow/themes/default/page.scss
- app/assets/stylesheets/pageflow/themes/default/page/hyphenate.scss
In portrait phone layout, the most problems with long words in headers
come up. Allow browser to break words.
> Hyphenate narrow headers by default

- app/assets/stylesheets/pageflow/admin.scss
- app/assets/stylesheets/pageflow/admin/active_admin_patches.scss
Extract Active Admin SCSS patches from admin.scss
Ensure patches are imported before Bourbon. We use the `dark-button`
mixin, which in turn uses `linear-gradient`. which is redefined by
Bourbon to do something unrelated.
> Fix background color of form buttons in admin action items

- app/assets/javascripts/pageflow/slideshow/adjacent_preparer.js
- spec/javascripts/pageflow/slideshow/adjacent_preparer_spec.js
Requests can queue up when preparing too many video pages at once.
REDMINE-15823
> Limit number of prepared pages

- app/controllers/pageflow/admin/initial_passwords_controller.rb
- app/views/pageflow/admin/initial_passwords/edit.html.erb
- app/views/pageflow/user_mailer/invitation.html.erb
- app/views/pageflow/user_mailer/invitation.text.erb
- config/locales/new/initial_password.de.yml
- config/locales/new/initial_password.en.yml
- config/routes.rb
When a user clicks the link in an invitation mail, we used to send
them to the edit password page. The wording of that page is tailored
to the case when users actually want to recover their password - not
for setting a password while accepting an invitation.
In particular the view contained a "Sign in" link which lead to the
normal sign in page. Invited users sometimes clicked the link instead
of saving the password.
Subclass `Devise::PasswordsController` to use a customized view. Adapt
the wording. Remove the "Sign in" link.
REDMINE-15682
> Improve initial password workflow for invitations

- spec/support/pageflow-support.gemspec
- spec/support/pageflow/support.rb
Ensure Factory Bot is loaded before Pageflow engine to make Pageflow
append its factory definitions path.
> Add factory_bot dependency to pageflow-support

- .rubocop.yml
- doc/creating_file_types.md
- spec/pageflow/built_in_file_type_spec.rb
- spec/support/helpers/pageflow_global_config_api_helper.rb
- spec/support/pageflow/global_config_api_test_helper.rb
- spec/support/pageflow/lint.rb
- spec/support/pageflow/test_page_type.rb
Provide specs that can be used by plugins to ensure that file type
json partials render correctly.
Extract global config api helper and test file/page types into
`pageflow-support`.
> Add shared example to pageflow-support to lint file types

- .rubocop.yml
- app/controllers/pageflow/editor/files_controller.rb
- app/models/concerns/pageflow/hosted_file.rb
- app/models/concerns/pageflow/uploaded_file.rb
- lib/pageflow/file_type.rb
- spec/controllers/pageflow/editor/files_controller_spec.rb
- spec/factories/hosted_files.rb
- spec/pageflow/file_type_spec.rb
- spec/support/helpers/test_file_type.rb
- spec/support/helpers/test_hosted_file.rb
- spec/support/pageflow/dummy/templates/create_test_hosted_file.rb
Also, file types can now define custom attributes. Custom attributes
serve a different purpose than configuration attributes: Their values
do not change after a file is created. Thus, we can persist them
directly on the file as opposed to on file usages, since constant
attributes need no versioning.
REDMINE-15957
> Custom params for file types

- .rubocop.yml
- app/assets/javascripts/pageflow/editor/views/embedded/background_image_embedded_view.js
- app/helpers/pageflow/background_image_helper.rb
- app/helpers/pageflow/file_background_images_helper.rb
- app/helpers/pageflow/pages_helper.rb
- app/models/pageflow/image_file_css_background_image_urls.rb
- app/models/pageflow/video_file_css_background_image_urls.rb
- app/views/pageflow/entries/show.css.erb
- app/views/pageflow/file_background_images/_rule.css.erb
- lib/pageflow/built_in_file_type.rb
- lib/pageflow/file_type.rb
- lib/pageflow/file_types.rb
- spec/helpers/pageflow/background_image_helper_spec.rb
- spec/helpers/pageflow/file_background_images_helper_spec.rb
- spec/pageflow/file_types_spec.rb
- spec/support/pageflow/lint.rb
So far the generated entry stylesheet only included rules to apply
background images based on image and video files.
Extend the file type API to allow providing background image urls for
generated rules. To ensure uniqueness, CSS class names are built from
file type name and an infix provided by the file type. Add private API
to let built in file types choose their own prefix to stay backward
compatible.
REDMINE-15957
> File type background image rules for generated css

- app/assets/javascripts/pageflow/editor/models/mixins/transient_references.js
- spec/javascripts/models/mixins/transient_references_spec.js
* Dispatch event when referenced record becomes ready.
* Prevent updating the foreign key before the referenced record can be
looked up by id in its collection. This prevents edge cases where
the updated foreign key is used by an event handler which tries to
look up the referenced file for further processing.
REDMINE-15957
> Improve transient references

- app/assets/javascripts/pageflow/editor/models/file_stage.js
- app/assets/javascripts/pageflow/editor/models/mixins/stage_provider.js
- app/assets/javascripts/pageflow/editor/views/file_stage_item_view.js
- app/assets/javascripts/pageflow/editor/views/inputs/file_processing_state_display_view.js
- app/assets/javascripts/pageflow/ui/views/mixins/input_view.js
- app/assets/stylesheets/pageflow/editor/file_stages.scss
- app/assets/stylesheets/pageflow/editor/inputs.scss
- app/assets/stylesheets/pageflow/editor/inputs/file_processing_state_display.scss
- app/assets/stylesheets/pageflow/ui/forms.scss
- spec/javascripts/models/file_stage_spec.js
- spec/javascripts/models/mixins/stage_provider_spec.js
- spec/javascripts/pageflow/ui/views/mixins/input_view_spec.js
- spec/javascripts/support/dominos/base.js
- spec/javascripts/support/dominos/editor/file_stage_item_view.js
- spec/javascripts/support/factories.js
- spec/javascripts/views/inputs/file_processing_state_display_spec.js
A view that can be used to display the processing progress of non top
level files inside of configuration editors.
* Adapt CSS of `FileStageItemView` so that the view can be used
outside of `FileIteView` via a `stand_alone` CSS class.
* Rewrite `inputView` visibility handling to use a CSS class to hide
the element. This allows views to set additional CSS classes that
can also hide the element without the inline style overriding
visibility.
* Create subset collection of unfinished stages in `stageProvider`.
* Add new `FileProcessingStateDisplayView` which displays
`FileStageItemViews` for all unfinished stages and hides itself if
there are non left.
* Allow file type specific localized file stage description
REDMINE-15957
> Add view to display unfinished file stages

- app/assets/javascripts/pageflow/editor/collections/files_collection.js
- app/assets/javascripts/pageflow/editor/models/entry.js
- app/assets/javascripts/pageflow/editor/models/preview_entry_data.js
- app/assets/javascripts/pageflow/editor/models/uploaded_file.js
- app/assets/javascripts/pageflow/entry_data.js
- app/assets/javascripts/pageflow/seed_entry_data.js
- config/routes.rb
- spec/javascripts/collections/files_collection_spec.js
- spec/javascripts/models/entry_spec.js
- spec/javascripts/models/preview_entry_data_spec.js
- spec/javascripts/pageflow/seed_entry_data_spec.js
* Add `findOrCreateBy` to files collection.
* Allow looking up files collection by file type object not just
collection name.
* Add `getFile` method to `EntryData` to allow accessing file
attributes in editor/published entry js consistently.
REDMINE-15957
> Improve files JS API

- app/controllers/pageflow/editor/files_controller.rb
- app/models/concerns/pageflow/hosted_file.rb
- app/models/pageflow/draft_entry.rb
- app/models/pageflow/image_file.rb
- spec/controllers/pageflow/editor/files_controller_spec.rb
- spec/models/concerns/pageflow/hosted_file_spec.rb
- spec/models/pageflow/draft_entry_spec.rb
- spec/models/pageflow/image_file_spec.rb
Prevent creating files without attachment. Make `FilesController`
respond with `:unprocessable_entity`.
Before creating a file without attachment lead to an exception of the
form
> no implicit conversion of nil into String
when trying to get the file's basename for entry seed data.
REDMINE-15616
> Validate attachment presence for image and hosted files

- .scss-lint.yml
- app/assets/javascripts/pageflow/editor/api/page_type.js
- app/assets/javascripts/pageflow/editor/initializers/boot.js
- app/assets/javascripts/pageflow/editor/templates/emulation_mode_button.jst.ejs
- app/assets/javascripts/pageflow/editor/templates/entry_preview.jst.ejs
- app/assets/javascripts/pageflow/editor/views/emulation_mode_button_view.js
- app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
- app/assets/javascripts/pageflow/editor/views/sidebar_footer_view.js
- app/assets/javascripts/pageflow/slideshow.js
- app/assets/javascripts/pageflow/slideshow/scroll_indicator_widget.js
- app/assets/stylesheets/pageflow/editor/base.scss
- app/assets/stylesheets/pageflow/editor/emulation_mode_button.scss
- app/assets/stylesheets/pageflow/editor/entry_preview.scss
- app/assets/stylesheets/pageflow/editor/help.scss
- app/assets/stylesheets/pageflow/editor/sidebar_footer.scss
- app/assets/stylesheets/pageflow/entries.scss
- app/views/pageflow/entries/edit.html.erb
- config/initializers/features.rb
- config/locales/new/phone_emulation.de.yml
- config/locales/new/phone_emulation.en.yml
* Let page types declare phone emulation support
* Resize entry preview to phone layout
* Prevent slidehshow navigation to other page since it might not
support phone emulation
* Display message when slideshow navigation is prevented
* Add emulation mode menu to bottom of editor sidebar
REDMINE-15957
> Add phone emulation mode to editor

- app/helpers/pageflow/render_json_helper.rb
- spec/helpers/pageflow/entry_json_seed_helper_spec.rb
Escape closing tags to prevent closing script tags from causing syntax
errors.
REDMINE-15615
> Make JSON seed safe to embed in HTML

- .travis.yml
- pageflow.gemspec
Update Capybara and Webmock for Ruby compatibility fixes.
> Add Ruby 2.5.3 to Travis file

- node_package/src/media/sagas/index.js
Otherwise, when using slim player controls, it is not displayed again
on pause or when the video ends.
REDMINE-15847
> Hide scroll indicator during video also on iOS

- app/assets/stylesheets/pageflow/admin/tabs_view.scss
- app/views/components/pageflow/admin/tabs_view.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/support/dominos/admin/account_page.rb
- spec/views/components/pageflow/admin/tabs_view_spec.rb
Active Admin tries to apply jQuery UI tabs widgets to elements
matching `.tabs`. Use fully qualified class instead to prevent this.
REDMINE-15764
> Prevent class name collision in admin tabs view

- app/assets/javascripts/pageflow/base.js
`pageflow.navigationDirection` needs to be defined, before
`pageflow.pageTransitions` can be initialized.
> Init page transitions after navigation direction

- Gemfile
- spec/support/config/capybara.rb
Install `capybara-chromedriver-logger`.
> Make js specs fail on js errors

- app/models/pageflow/widget.rb
- app/views/pageflow/entries/_entry.html.erb
- app/views/pageflow/entries/show.html.erb
- lib/pageflow/react/widget_type.rb
- lib/pageflow/widget_type.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/models/pageflow/widget_spec.rb
- spec/support/helpers/test_widget_type.rb
Allow inserting widgets before entry. This is a prerequisite to
introduce widget types for different loading spinners.
REDMINE-15907
> Introduce widget insert points

- node_package/src/__spec__/backgroundMedia-spec.js
- node_package/src/backgroundMedia/index.js
- node_package/src/boot.js
Pass `backgroundMedia` as part of options in boot instead.
> Decouple node package specs from pageflow.backgroundMedia

- app/assets/javascripts/pageflow/slideshow.js
Just go to normal landing page, instead of changing the hash to
`undefined` and failing to load.
REDMINE-15001
> Ignore invalid page perma id hash

- app/assets/javascripts/pageflow/slideshow/adjacent_pages.js
`AdjacentPage#nextPage` already returns a page widget
instance. `AdjacentPage#of` treated it like a jQuery object.
REDMINE-16050
> Fix adjacent page lookup for page preloading

- app/controllers/concerns/pageflow/public_https_mode.rb
- app/controllers/pageflow/entries_controller.rb
- lib/pageflow/configuration.rb
- lib/pageflow/primary_domain_entry_redirect.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/pageflow/primary_domain_entry_redirect_spec.rb
Add `public_entry_redirect` configuration attribute, to determine
a redirect location based on an entry.
Provide `PrimaryDomainEntryRedirect` implementation that redirect to
entry url using account cname.
REDMINE-16070, REDMINE-15193, REDMINE-15984
> Add config option to always redirect to cname of entry

- node_package/package.json
- node_package/src/index.js
In Safari 12, creating an array via a literal and calling
`Array#reverse` on it causes arrays created from an identical literal
to be reversed as well from that point on. An internal shared
representation of the array literal gets mutated.
https://stackoverflow.com/questions/52390368/array-state-will-be-cached-in-ios-12-safari-is-it-a-bug-or-feature/52392901#52392901
This polyfill detects the bug and overrides `Array#reverse` with a
fixed implementation.
The bug caused video text tracks to switch positions from bottom to
top on each update.
REDMINE-16049
> Use polyfill to fix Array#reverse in Safari 12

- app/assets/stylesheets/pageflow/themes/default/overview/icons/icon_font.scss
Add unused parameters to overview icon font mixin to prevent error
caused by unknown parameters.
REDMINE-15986
> Ensure share-icon-color key can be used in $widget-icon-font-options

- app/assets/javascripts/pageflow/admin/accounts.js
ActiveAdmin sets the current action as class on the body.
Since the checkbox toggle script is only supposed to be run on the form (i.e. new and edit)
and not on the show view, the selector needs to be narrowed down to these actions.
REDMINE-16109
> Run checkbox toggle script for accounts only on new and edit

- app/models/pageflow/widget.rb
- spec/models/pageflow/widget_spec.rb
Do not filter widgets by insert point if not `insert_point` option is
passed to `resolve`.
This ensures all widgets show up in the `EditWidgetsView` regardless
of their insert point.
REDMINE-15907
> Show widgets of all insert points in editor

- app/jobs/pageflow/upload_file_to_s3_job.rb
- app/models/concerns/pageflow/hosted_file.rb
- spec/factories/hosted_files.rb
- spec/jobs/pageflow/upload_file_to_s3_job_spec.rb
Future versions of Pageflow will use direct upload to transfer files
to S3. Files will need to be re-downloaded for processing.
The only known (to the author) Pageflow plugin that uses this option
is `pageflow-panorama` < 1.0. `pageflow-panorama` 1.0 switches to
re-downloading in
https://github.com/codevise/pageflow-panorama/commit/23c5e6e7a931002f55c62dbfd25b20d82c155f15
REDMINE-16119
> Remove HostedFile#keep_on_filesystem_after_upload_to_s3

- app/assets/javascripts/pageflow/media_player/volume_binding.js
- app/assets/javascripts/pageflow/widgets/multimedia_alert.js
- node_package/src/media/actions.js
- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/handlePlayerState.js
- node_package/src/media/components/createFilePlayer/index.jsx
- node_package/src/media/components/createFilePlayer/watchPlayer.js
- node_package/src/media/createReducer.js
- node_package/src/media/sagas/__spec__/fadeInWhenPageWillActivate-spec.js
- node_package/src/media/sagas/fadeInWhenPageWillActivate.js
- node_package/src/media/sagas/muteBackgroundMediaOnPlayFailed.js
- node_package/src/pages/actions.js
Ensure volume is turned down until delayed start has finished
(e.g. the multimedia alert has been closed).
We cannot use mute since, if unmuted autoplay is disabled, there is no way
to know whether unmuting the video will pause it. Hence we change the
volume factor to set volume to 0. That way the unmute button will be shown
if autoplay fails.
Add a `backgroundMedia.unmute` call to the multmedia alert, to ensure
clicking the "Let's go" button unmutes background media.
To prevent timing issues:
- Ensure `PREBUFFERED` is never dispatched immediately after
`PREBUFFER` to be able to wait in sagas.
- Wait for videojs to be ready, but use sync variant of `ready` by
passing `true` as second argument. Otherwise `shouldPlay` can
already be reset a `pause` event, before we handle the prop change …
> Play background video silently until page did activate

- app/assets/javascripts/pageflow/media_player/volume_binding.js
- app/assets/javascripts/pageflow/widgets/multimedia_alert.js
- node_package/src/media/actions.js
- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/handlePlayerState.js
- node_package/src/media/components/createFilePlayer/index.jsx
- node_package/src/media/components/createFilePlayer/watchPlayer.js
- node_package/src/media/createReducer.js
- node_package/src/media/sagas/__spec__/fadeInWhenPageWillActivate-spec.js
- node_package/src/media/sagas/fadeInWhenPageWillActivate.js
- node_package/src/media/sagas/muteBackgroundMediaOnPlayFailed.js
- node_package/src/pages/actions.js
Backport of #1078
Ensure volume is turned down until delayed start has finished
(e.g. the multimedia alert has been closed).
We cannot use mute since, if unmuted autoplay is disabled, there is no
way to know whether unmuting the video will pause it. Hence we change
the volume factor to set volume to 0. That way the unmute button will
be shown if autoplay fails.
Add a `backgroundMedia.unmute` call to the multmedia alert, to ensure
clicking the "Let's go" button unmutes background media.
To prevent timing issues:
- Ensure `PREBUFFERED` is never dispatched immediately after
`PREBUFFER` to be able to wait in sagas.
- Wait for videojs to be ready, but use sync variant of `ready` by
passing `true` as second argument. Otherwise `shouldPlay` can
already be reset a `pause` event, before we handle …
> Play background video silently until page did activate (12.x Backport)

- app/models/concerns/pageflow/hosted_file.rb
- doc/creating_file_types.md
Providing a method for use in migrations is a bad idea since changing
it retroactively changes old migrations. It can thus never be changed.
Change docs to suggest just adding the columns explictly.
REDMINE-16119
> Remove deprecated HostedFile.columns method

- spec/support/config/capybara.rb
Whenever changes a made inside the editor, a debounced request is made
to update the server rendered widgets.
Some of the js based editor specs trigger this request even after the
test itself has finished. The request fails since the database has
already been cleaned.
Do not make the spec fail if this happens.
> Do not fail capybara spec on failing widget refresh

- doc/creating_file_types.md
We still need to include `attachment_on_filesystem` columns. Also
`parent_file` columns were missing.
Was missing in #1085.
REDMINE-16119
> Fix example migration in file type guide

- app/assets/javascripts/pageflow/base.js
- app/assets/javascripts/pageflow/delayed_start.js
- app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
- app/assets/javascripts/pageflow/manual_start.js
- app/assets/javascripts/pageflow/ready.js
- app/assets/javascripts/pageflow/slideshow/page_widget.js
- app/assets/javascripts/pageflow/slideshow/scroll_indicator_widget.js
- spec/javascripts/pageflow/delayed_start_spec.js
Manual start is only one way to delay the first page. Provide API to
wait for additional promises before triggering delayed page type
hooks.
REDMINE-16148, REDMINE-15907
> Extract DelayedStart from pageflow.manualStart

- node_package/src/media/__spec__/createReducer-spec.js
- node_package/src/media/components/__spec__/createFilePlayer-spec.jsx
- node_package/src/media/components/createFilePlayer/handlePlayerState.js
- node_package/src/media/createReducer.js
When the media player is paused by an external event (i.e. a different
player library that has direct access to the media element), we want
to make sure that the `PAUSED` action does not lead to another call of
`pause` on the media element.
We can distinguish this from the case where `PAUSE` caused
`shouldPlay` to become `false` by checking whether `isPlaying` is
already false and skip calling `pause` on the media player.
By mistake, `isPlaying` was also set to `false` on
`FADE_OUT_AND_PAUSE` before. This needs to be removed since otherwise
now the `pause` would be skipped
REDMINE-16148, REDMINE-14305
> Improve handling of externally controlled player

- app/assets/javascripts/pageflow/slideshow.js
Prevent creating an invalid CSS selector when looking up a page based
on the perma id passed in the fragment of a deep link.
REDMINE-16276
> Parse page perma id from URL fragment

- app/assets/javascripts/pageflow/browser/video.js
- app/assets/javascripts/pageflow/video_player/filter_sources.js
Safari also supports MSE and therefore picks dash in our current
setup. Still dash performs slightly worse in Safari, i.e. displaying a
black frame at the end when looping a video.
We could change the order of sources to make hls come first. Since
this might have negative effects in other browsers and we already need
to filter sources to handle bugs in Safari < 11, we instead remove the
dash source dynamically.
REDMINE-16318
> Ensure hls videos are used in Safari

- app/assets/javascripts/pageflow/browser/video.js
- app/assets/javascripts/pageflow/video_player/filter_sources.js
Backport of #1096 
Safari also supports MSE and therefore picks dash in our current
setup. Still dash performs slightly worse in Safari, i.e. displaying a
black frame at the end when looping a video.
We could change the order of sources to make hls come first. Since
this might have negative effects in other browsers and we already need
to filter sources to handle bugs in Safari < 11, we instead remove the
dash source dynamically.
REDMINE-16318
> Ensure hls videos are used in Safari (12.x Backport)

- app/assets/javascripts/pageflow/jquery_utils.js
- app/views/pageflow/entries/mobile_navigation/_page.html.erb
- app/views/pageflow/entries/navigation/_page.html.erb
- app/views/pageflow/entries/overview/_page.html.erb
* Pass urls through `asset_path` to ensure digests are included in
placeholder paths.
* Only set `src` attribute if empty to prevent reloading images on 404
or when cache is disabled via dev tools.
REDMINE-16290
> Improve lazy loading thumbnails

- app/assets/javascripts/pageflow/jquery_utils.js
- app/views/pageflow/entries/mobile_navigation/_page.html.erb
- app/views/pageflow/entries/navigation/_page.html.erb
- app/views/pageflow/entries/overview/_page.html.erb
* Pass urls through `asset_path` to ensure digests are included in
placeholder paths.
* Only set `src` attribute if empty to prevent reloading images on 404
or when cache is disabled via dev tools.
REDMINE-16290
> Improve lazy loading thumbnails (12.x Backport)

- app/assets/javascripts/pageflow/widgets.js
Previously, dismissing the cookie notice removed the div but did not resize the banner image,
which left an empty div at the bottom of the page.
Explicitly calling the resize hook in `pageflow.widgets.use` takes care of resizing the banner image
back to the full available height.
REDMINE-16186
> Trigger resize hooks on cookie notice dismiss

- admins/pageflow/accounts.rb
- admins/pageflow/entry.rb
- app/models/pageflow/theming.rb
- app/views/admin/accounts/_form.html.erb
- app/views/admin/accounts/_theming_details.html.arb
- config/locales/new/create_new_entry_in_editors_locale.de.yml
- config/locales/new/create_new_entry_in_editors_locale.en.yml
- db/migrate/20190109085744_add_default_locale_to_themings.rb
- spec/controllers/admin/entries_controller_spec.rb
Customers who have set their language to english have reported that the default language for new stories is still German. This behavior was perceived as a bug.
This PR introduces a new column `default_locale` on account/theming level where a default language for new stories can be specified (defaults to German), which is then used for new stories.
For new accounts the `default_locale` will initially get set to the locale the user specified during signup.
REDMINE-16323
> Set locale to editors locale for new entries

- admins/pageflow/accounts.rb
- app/models/pageflow/theming.rb
- app/views/admin/accounts/_form.html.erb
- app/views/admin/accounts/_theming_details.html.arb
- config/locales/new/create-new-entries-with-default-locale.de.yml
- config/locales/new/create-new-entries-with-default-locale.en.yml
- db/migrate/20190109085744_add_default_locale_to_themings.rb
- spec/controllers/admin/entries_controller_spec.rb
Backport of #1100 
Customers who have set their language to english have reported that
the default language for new stories is still German.
This behavior was perceived as a bug.
This PR introduces a new column default_locale on account/theming level
where a default language for new stories can be specified (defaults to German),
which is then used for new stories.
For new accounts the default_locale will initially get set to the locale the user
specified during signup.
REDMINE-16323
> Create new entries with default locale (12.x Backport)

- config/locales/new/phone_horizontal_slideshow_mode_feature.de.yml
- config/locales/new/phone_horizontal_slideshow_mode_feature.en.yml
- lib/pageflow/built_in_widget_types_plugin.rb
Provide a way to disable the editor option if it is not wanted.
REDMINE-15907
**Manual Update Step**
The horizontal swipe navigation on phone is now guarded by a feature
flag. If you there are entries using this functionality, make sure to
add the following line to your Pageflow initializer:
config.features.enable_by_default('phone_horizontal_slideshow_mode')
> Scope phone horizontal swipe with feature flag

- app/helpers/pageflow/entries_helper.rb
- spec/helpers/pageflow/entries_helper_spec.rb
`Configuration#public_entry_request_scope` and
`Configuration#public_entry_redirect` can be used to restrict which
entries are accessible under which hostname. This also applies to
entry stylesheet requests. Therefore, when an asset host is
configured, we need to make sure that entry stylesheet requests are
not blocked.
`stylesheet_link_tag` always uses the asset host when a relative URL
is passed. We could pass an absolute URL using the hostname of the
current request, but that might cause problems with caching.
Enforce always using a relative URL by generating the link tag
manually.
REDMINE-16292
> Do not use asset host in entry stylesheet link tags

- app/helpers/pageflow/entries_helper.rb
- spec/helpers/pageflow/entries_helper_spec.rb
Backport of #1107
`Configuration#public_entry_request_scope` and
`Configuration#public_entry_redirect` can be used to restrict which
entries are accessible under which hostname. This also applies to
entry stylesheet requests. Therefore, when an asset host is
configured, we need to make sure that entry stylesheet requests are
not blocked.
`stylesheet_link_tag` always uses the asset host when a relative URL
is passed. We could pass an absolute URL using the hostname of the
current request, but that might cause problems with caching.
Enforce always using a relative URL by generating the link tag
manually.
REDMINE-16292
> Do not use asset_host in entry stylesheet link tags (12.x Backport)

- app/assets/stylesheets/pageflow/themes/default/page.scss
Backport of #1108
Let theme apply styles to tagline and subtitle in phone layout. This
used to only work for the title.
REDMINE-16357
> Add theme vars for phone typography of tagline and subtitle (12.x Backport)

- app/assets/stylesheets/pageflow/themes/default/page.scss
Let theme apply styles to tagline and subtitle in phone layout. This
used to only work for the title.
REDMINE-16357
> Add theme vars for phone typography of tagline and subtitle

- app/assets/javascripts/pageflow/widgets/navigation.js
- app/assets/javascripts/pageflow/widgets/page_navigation_list.js
- app/views/pageflow/entries/_navigation.html.erb
- app/views/pageflow/entries/navigation/_page.html.erb
Prevent loading navigation bar thumbnails of pages in hidden
storylines.
Ensure images are lazy loaded once pages become visible. In
particular, this means images are loaded after the loading indicator
disappeared. Lately we've been moving towards displaying loading
states in less important cases in favor of speeding up observed
loading time.
REDMINE-16467
> Lazy load navigation bar thumbnails

- spec/support/config/capybara.rb
Saving the order of storylines is debounced (see
`app/assets/javascripts/pageflow/editor/initializers/setup_collections.js`)
and is therefore sometimes triggered even after the database cleaner
has removed the corresponding entities. This leads to a 401 error that
makes the tests fails.
> Ignore storyline order error in js specs

- config/locales/new/missing_active_admin_filters.de.yml
These are missing from the `de` locale in Active Admin 1.3.x and have
only been added in 1.4.0. Since Pageflow already duplicates a good
amount of the Active Admin locales, adding these does not really make
things worse.
REDMINE-16490
> Add missing Active Admin translations for filters

- app/models/pageflow/revision.rb
- spec/factories/revisions.rb
- spec/features/account_previewer/filtering_entries_by_attributes_spec.rb
- spec/models/pageflow/revision_spec.rb
- spec/support/dominos/admin/filter_form.rb
Trying to filter entries by publication date in the entry admin index
list caused an error of the form:
Column 'published_at' in on clause is ambiguous
The combination of the `includes(:published_revision)` in
`scoped_collection` and the `:published_revision_published_at` filter
caused the revisions table to be joined twice, making the unqualified
column `published_at` in the query of the `Revision.published` scope
ambiguous.
Since there is no documented way to obtain the current table alias,
the `published` query has been rewritten to use hash syntax instead of
an SQL fragment.
The comparison of `published_until` can be replaced with a date
range. Since `published_at` is only ever set to the current time, its
value can never be in the future. Checking for its presence is
therefore …
> Ensure entries can be filtered by publication date

- node_package/src/builtInPageTypes/audio.jsx
- node_package/src/media/components/PageFilePlayer.jsx
- node_package/src/media/components/createFilePlayer/index.jsx
Prevent displaying text tracks behind the waveform player controls.
REDMINE-16524
> Display text tracks at the top if waveform is present

- app/views/components/pageflow/admin/embedded_index_table.rb
- spec/views/components/pageflow/admin/embedded_index_table_spec.rb
Minor adjustment to embedded_index_table for activeadmin-1.3.1-compatibility.
REDMINE-15693
REDMINE-16536
> Fix scope filter translation for embedded_index_table

- vendor/assets/javascripts/audio5.min.js
Support for loop option was accidentally removed in #1018.
REDMINE-16543
> Re-apply loop patch for Audio5js

- app/assets/javascripts/pageflow/ready.js
The editor initializes the slideshow independently of the
`pageflow.ready` promise. This can cause the first `pagepreloaded`
event to be dispatched even before feature detection has finished.
In these cases `pageflow.ready` stayed pending and features depending
on `pageflow.ready` (e.g. lazy loading of thumbnails in the built in
navigation bar) did not work correctly.
Start listening for a `pagepreload` event on the document element
right away and track whether the event occurred with a promise.
REDMINE-16546
> Prevent missing first pagepreloaded event in pageflow.ready

- app/assets/javascripts/pageflow/browser.js
- app/assets/javascripts/pageflow/browser/agent.js
- app/assets/javascripts/pageflow/browser/volume_control_support.js
- app/assets/javascripts/pageflow/media_player/volume_fading.js
- spec/javascripts/pageflow/browser/agent_spec.js
When using Webaudio API there are cracking noises when playing
audio. Revert to legacy interval based volume fading for desktop
Safari.
Allow overriding browser feature flags via query string.
REDMINE-15776
> Fix cracking noises in audios on Safari

- app/assets/stylesheets/pageflow/editor/wysihtml5.scss
* Do not cover part of text area, instead show below text area and
move subsequent inputs down.
* Hide no-op cancel button for existing links
REDMINE-14892
> Improve text area link dialog

- app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/general.js
Some people rely on long titles as a workaround for missing formatting
options.
REDMINE-16574
> Increase max length for page tagline, title and subtitles

- app/helpers/pageflow/page_types_helper.rb
- app/views/pageflow/page_types/_page_type.json.jbuilder
- app/views/pageflow/react/page.html.erb
- doc/creating_page_types.md
- lib/pageflow/built_in_page_type.rb
- lib/pageflow/built_in_page_types_plugin.rb
- spec/pageflow/built_in_page_type_spec.rb
- spec/support/pageflow-support.gemspec
- spec/support/pageflow/lint.rb
- spec/support/pageflow/lint/file_type.rb
- spec/support/pageflow/lint/page_type.rb
- spec/support/pageflow/render_page_test_helper.rb
Backport of #1133
This can be used by plugin engines to
* check that rendering page template does not raise errors
* check that rendering json seed does not raise errors
* check that all required translations are defined
Make `pageflow-support` depend on `factory_bot_rails` instead of
`factory_bot` to make sure factories are loaded automatically.
REDMINE-16511
> Add shared specs to pageflow-support to lint page types (13.x backbort)

- app/helpers/pageflow/page_types_helper.rb
- app/views/pageflow/page_types/_page_type.json.jbuilder
- app/views/pageflow/react/page.html.erb
- doc/creating_page_types.md
- lib/pageflow/built_in_page_type.rb
- lib/pageflow/built_in_page_types_plugin.rb
- spec/pageflow/built_in_page_type_spec.rb
- spec/support/pageflow-support.gemspec
- spec/support/pageflow/lint.rb
- spec/support/pageflow/lint/file_type.rb
- spec/support/pageflow/lint/page_type.rb
- spec/support/pageflow/render_page_test_helper.rb
This can be used by plugin engines to
* check that rendering page template does not raise errors
* check that rendering json seed does not raise errors
* check that all required translations are defined
Make `pageflow-support` depend on `factory_bot_rails` instead of
`factory_bot` to make sure factories are loaded automatically.
REDMINE-16580
> Add shared specs to pageflow-support to lint page types

- app/assets/javascripts/pageflow/editor/models/hosted_file.js
- app/assets/javascripts/pageflow/editor/models/image_file.js
- app/assets/javascripts/pageflow/editor/models/uploaded_file.js
- app/models/concerns/pageflow/hosted_file.rb
- app/models/concerns/pageflow/uploaded_file.rb
- app/views/pageflow/editor/files/_file.json.jbuilder
- db/migrate/20190306161431_copy_file_attributes_of_failed_uploads.rb
- spec/javascripts/models/mixins/stage_provider_spec.js
- spec/javascripts/models/uploaded_file_spec.js
- Copy filesystem attributes for legacy files in state uploading_failed to s3-related attributes
- mirror new uploading_failed backend state to frontend representation
- remove destroy-call when uploads fail to keep the records persisted in the failed state
REDMINE-16119
> Migrate files whose upload failed

- pageflow.gemspec
- spec/support/config/capybara.rb
- spec/teaspoon_env.rb
Old setup lead errors of the form
This version of ChromeDriver only supports Chrome version 74
> Update chromedriver-helper to fix Travis build

- app/assets/javascripts/pageflow/editor/collections/files_collection.js
- app/assets/javascripts/pageflow/editor/sync.js
- app/controllers/pageflow/editor/files_controller.rb
- spec/controllers/pageflow/editor/files_controller_spec.rb
To allow for conditional publishing of files without attachment.
Needed for linkmap page color map files to start processing.
REDMINE-16119
> Allow passing custom query params for collection.create

- app/assets/javascripts/pageflow/page_types/mixins/default_page_content.js
- app/assets/javascripts/pageflow/slideshow.js
- app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
- app/assets/stylesheets/pageflow/overview.scss
- app/assets/stylesheets/pageflow/themes/default/overview/colors.scss
- app/assets/stylesheets/pageflow/themes/default/overview/typography.scss
- app/helpers/pageflow/entries_helper.rb
- app/models/pageflow/revision.rb
- app/views/pageflow/chapters/_chapter.html.erb
- app/views/pageflow/entries/_entry.html.erb
- app/views/pageflow/entries/_multimedia_alert.html.erb
- app/views/pageflow/entries/overview/_entry.html.erb
- app/views/pageflow/pages/_page.html.erb
* Move top links out of page sections
* Add chapters to document outline
* Clean up header structure by removing non-essential headers from
widgets.
REDMINE-16511
> Improve header structure

- app/assets/javascripts/pageflow/ready.js
Ensure `pageflow.visited` is present when `pageflow.ready` is
resolved. Since we also resolve `pageflow.ready` in the editor now,
this lead to errors when navigation widgets tried to used
`pageflow.visited`.
> Setup visited pages before resolving ready

- app/helpers/pageflow/page_background_asset_helper.rb
- spec/helpers/pageflow/page_background_asset_helper_spec.rb
- spec/support/pageflow/render_page_test_helper.rb
REDMINE-16580
Ensure page types can use helpers like `page_background_asset` which
depend on `@entry` being assigned.
> Assign @entry attribute in render_page test helper

- spec/support/pageflow/lint/page_type.rb
The linkmap page is an example of a page that does not have a content
wrapper.
REDMINE-16580
> Do not require content_wrapper in page type lint specs

- app/assets/javascripts/pageflow/editor/models/page.js
- app/assets/javascripts/pageflow/editor/views/page_preview_view.js
- app/assets/stylesheets/pageflow/print_view.scss
- app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
- app/assets/stylesheets/pageflow/themes/default/page/header.scss
- app/assets/stylesheets/pageflow/themes/default/page/paddings.scss
- app/helpers/pageflow/pages_helper.rb
- app/models/pageflow/chapter.rb
- app/models/pageflow/revision.rb
- spec/controllers/pageflow/entries_controller_spec.rb
- spec/helpers/pageflow/pages_helper_spec.rb
- spec/models/pageflow/revision_spec.rb
Using `:first-child` no longer works since pages are now wrapped in
chapter sections in published entries.
Make theme more robust by setting a `first_page` css class instead.
REDMINE-16708
> Fix first page selectors in themes

- spec/helpers/pageflow/entry_json_seed_helper_spec.rb
Jbuilder now escapes script tags automatically.
> Fix spec for jbuilder 2.9

- app/assets/stylesheets/pageflow/base.scss
Safari sets background color of fullscreen elements to white via user
agent styles. This can be seen on before/after pages when switching to
fullscreen mode.
REDMINE-16802
> Reset background color in fullscreen Safari

- app/assets/javascripts/pageflow/ui/templates/inputs/text_area_input.jst.ejs
- app/assets/javascripts/pageflow/ui/views/inputs/text_area_input_view.js
- app/assets/stylesheets/pageflow/editor/wysihtml5.scss
Do not depend on link dialog and link button to be siblings in the
DOM. Instead of using an adjacent CSS selector, explicitly set a CSS
class when the dialog is shown.
REDMINE-16728
> Ensure remove link button is show in text editor

- app/assets/javascripts/pageflow/ui/templates/inputs/text_area_input.jst.ejs
- app/assets/javascripts/pageflow/ui/views/inputs/text_area_input_view.js
- app/assets/stylesheets/pageflow/editor/wysihtml5.scss
Backport of #1160
Do not depend on link dialog and link button to be siblings in the
DOM. Instead of using an adjacent CSS selector, explicitly set a CSS
class when the dialog is shown.
REDMINE-16728
> Ensure remove link button is show in text editor (14.1 Backport)

- Gemfile
Ensure `Gemfile` entry (which is required to make Active Admin
stylesheets work) uses the same version constraint as
gemspec. Otherwise `Gemfile` wins allowing incompatible gem versions.
> Fix sassc-rails development dependency

- .travis.yml
Default bundler cannot handle Ruby version requirements correctly and
just fails if a gem requires a newer version. For example, `capybara`
requires Ruby 2.4 starting with version 3.16. Current version of
bundler handles this correctly and only installs 3.15.1 for Ruby 2.3.
> Update bundler in Travis build

- .jshintrc
- app/assets/javascripts/pageflow/editor/views/edit_page_view.js
- app/assets/javascripts/pageflow/slideshow/scroller_widget.js
- app/assets/javascripts/pageflow/ui/templates/tabs_view.jst.ejs
- app/assets/javascripts/pageflow/ui/views/configuration_editor_view.js
- app/assets/javascripts/pageflow/ui/views/tabs_view.js
- app/assets/javascripts/pageflow/widgets/navigation.js
- app/assets/javascripts/pageflow/widgets/navigation_mobile.js
- app/assets/javascripts/pageflow/widgets/overview.js
- app/assets/javascripts/pageflow/widgets/scroll_button.js
- app/assets/stylesheets/pageflow/ui/tabs_view.scss
- vendor/assets/javascripts/iscroll.js
Now that plugins can add additional tabs to page configuration editors, tabs will overflow more often. Add scroller and always bring current tab into view port.
Declare `IScroll` as global in JSHint config, instead of using `global` comments.
REDMINE-16823
> Make TabsView tabs scrollable

- app/assets/javascripts/pageflow/editor/api.js
- app/assets/javascripts/pageflow/editor/api/common_page_configuration_tabs.js
- doc/adding_common_page_configuration_tabs.md
- doc/index.md
- spec/javascripts/views/edit_page_view_spec.js
Let plugins add tabs to the configuration editors of all pages. This
can be used to store settings for cross page type functionality in the
page configuration.
REDMINE-16823
> Add plugin API to add common page config tabs

- app/assets/javascripts/pageflow/slideshow/page_widget.js
The used CSS selector no longer applies for React based pages since an
additional wrapper div has been added around the scroller.
For internal link and text pages the selector never matched.
REDMINE-16835
> Fix hide text on swipe

- app/assets/javascripts/pageflow/editor/models/storyline.js
When using the "Add storyline button" above the entry outline in the
editor a duplicate storyline is created on the server. Since it's not
known in the client side, it is not included in `/order` updated. This
means `position` stays `nil` and moves the storyline to the top of the
list, making it the main storyline. After reloading the editor, the
next storyline order update fixes the problem.
This happens because `StorylineScaffold` triggers a
`scaffold:storyline` event before the storyline is persisted. The
sitemap plugin listens for this event and updates the configuration to
ensure `lane` and `row` are set. This causes the storyline to auto
save. Since Scaffold uses `Backbone.sync` directly, a second create
request is dispatched and only a single storyline model is added in
the client, …
> Prevent creating storyline twice

- node_package/package-lock.json
- node_package/package.json
- node_package/src/media/components/VideoFilePlayer/Positioner/index.jsx
- node_package/src/media/components/createFilePlayer/MediaTag.jsx
- node_package/src/media/components/createFilePlayer/__spec__/MediaTag-spec.jsx
- Update `react-measure` to version that uses patched
`get-node-dimensions` which does not clone nodes. Nodes were cloned
in some cases when trying to measure hidden elements, leading to
additional network connections in Firefox 67.
- A detached DOM element is used to build the HTML for
`MediaTag`. Setting `preload` to `auto` in the detached element,
triggers a separate request in Firefox 67 which afterwards keeps a
network connection open.
Set `preload` to `none` and perform text replacement in the string
which is passed to `dangerouslySetInnerHTML`.
REDMINE-16834
> Prevent duplicate network requests for video preload

- spec/support/config/capybara.rb
As described in [1]:
With the release of Chrome 75 (and ChromeDriver 75) we started seeing
this error:
```
Capybara::Chromedriver::Logger::TestHooks.after_example! NoMethodError: private method `log' called for #<Selenium::WebDriver::Remote::W3C::Bridge:0x00007fad79f94218>
```
ChromeDriver 75 now runs in W3C standard compliant mode by default
[2]. Which ultimately means that
`driver.browser.manage.logs.get(:browser)` is not a compliant way to
get access to the logs.
[1] https://github.com/dbalatero/capybara-chromedriver-logger/issues/11
[2] http://chromedriver.chromium.org/downloads
> Fix Capybara tests in Chrome 75

- app/assets/stylesheets/pageflow/navigation_bar.scss
Trying to hide the texts of thumbnail links in the default navigation
bar, links in the credit box got hidden as well by accident.
REDMINE-16923
> Prevent hiding links in credits menu

- app/assets/javascripts/pageflow/editor/models/page.js
- app/assets/javascripts/pageflow/editor/views/configuration_editors/audio.js
- app/assets/javascripts/pageflow/editor/views/configuration_editors/background_image.js
- app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/general.js
- app/assets/javascripts/pageflow/editor/views/configuration_editors/video.js
- app/assets/javascripts/pageflow/ui/views/inputs/select_input_view.js
- app/assets/stylesheets/pageflow/themes/default/page/line_lengths.scss
- app/assets/stylesheets/pageflow/themes/default/page/shadow.scss
- config/locales/new/text_position_center.de.yml
- config/locales/new/text_position_center.en.yml
- node_package/src/builtInPageTypes/audio.jsx
- node_package/src/builtInPageTypes/plain.jsx
- node_package/src/builtInPageTypes/video.jsx
Page types can now opt in to a new text position variant called
"center" by passing the `supportsTextPositionCenter` option to the
`general` configuration editor inputs group and setting the
`supports_text_position_center` class on their wrapper element.
Text stays left aligned but is moved to the center of the page. The
shadow turns into a transparent single-color overlay.
So far only the built in page types support this.
Adapt select input view to display the default option if the current
value is not among the options. This ensures that the drop down
displays "Left" even if "Center" has been selected before changing the
page type.
REDMINE-16909
> Add text position center option

- app/assets/stylesheets/pageflow/themes/default/anchors.scss
Allow displaying an external link icon for content text links that
open in a new tab.
REDMINE-16909
> Add theme option for alternative content link icon

- app/assets/stylesheets/pageflow/themes/default/page/anchors.scss
Prevent rendering a space between a link and a following comma etc.
REDMINE-16909
> Remove margin right of links in page text

- app/helpers/pageflow/entry_json_seed_helper.rb
- app/views/pageflow/audio_files/_audio_file.json.jbuilder
- app/views/pageflow/image_files/_image_file.json.jbuilder
- app/views/pageflow/structured_data/_entry.json.jbuilder
- app/views/pageflow/video_files/_video_file.json.jbuilder
- spec/helpers/pageflow/structured_data_helper_spec.rb
- include url
- include articleSection "longform"
- include thumbnailUrl if thumbnail file is present
- format all dates as UTC,
- render keywords, authors and publishers separated by commas as individual items
REDMINE-16909
> Structured data changes

- app/helpers/pageflow/social_share_helper.rb
- app/jobs/pageflow/poll_zencoder_job.rb
Previously, when using protocol relative URLs for paperclip and
zencoder attachments, HTTP was used as default protocol in social
share meta tag image URLs and when downloading thumbnails and posters
generated by Zencoder.
Also HTTPS URLs were actively rewritten to HTTP due to some cargo
culted workaround for a problem where Facebook had problems with HTTPS
urls.
In both cases a redirect to HTTPS served by the CDN caused problems:
* Facebook does not appear to follow redirects and instead complains
about invalid content type.
* `open-uri` which is used by Paperclip to perform the image download
also does not follow redirects. Video Files stay in `encoding` state
forever since `PollZencoderJob` assumes thumbnails are not there
yet.
It should be safe to assume that the CDN supports HTTPS if …
> Support CDN that redirects to HTTPS

- app/models/concerns/pageflow/hosted_file.rb
- app/state_machines/pageflow/encoded_file_state_machine.rb
- app/state_machines/pageflow/processed_file_state_machine.rb
- spec/factories/audio_files.rb
- spec/factories/image_files.rb
- spec/factories/video_files.rb
- spec/models/concerns/pageflow/hosted_file_spec.rb
- spec/state_machines/pageflow/encoded_file_state_machine_examples.rb
- spec/state_machines/pageflow/processed_file_state_machine_spec.rb
Provide a generic way to find out if the state machine of a file is in
a failed state. This can be used to prevent waiting forever when
waiting for a file to get ready.
REDMINE-16880
> Add failed? method to file models

- app/helpers/pageflow/social_share_links_helper.rb
Current URL only redirects to user's home page. It seems Twitter
currently offers a Web Intent API for our use case. See [1].
REDMINE-16999
[1] https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent.html
> Update Twitter share URL

- app/helpers/pageflow/social_share_links_helper.rb
Backport of #1202
Current URL only redirects to user's home page. It seems Twitter
currently offers a Web Intent API for our use case. See [1].
REDMINE-16999
[1] https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent.html
> Update Twitter share URL (14.x backport)

- .travis.yml
- CHANGELOG.md
- db/migrate/20140418225525_setup_schema.rb
- spec/support/pageflow/dummy/templates/database.yml
Emoji are popular, and pageflow gem currently defines a charset as default that doesn't support them. This PR removes that default and also nudges a few testing/CI aspects toward utf8mb4
REDMINE-17010
> Remove default charset utf8mb3

- db/migrate/20190820152900_drop_accounts_themes.rb
Since d4073c17, Theme is a Ruby object instead of an ActiveRecord
model. This table is unused since then and can thus be dropped.
REDMINE-17005
> Drop pageflow_accounts_themes table

- app/assets/javascripts/pageflow/ui/views/tabs_view.js
It seems that on mobile devices, iScroll's preventDefault setting
prevents tab click and touch events from having an effect, rendering
tabs unreachable. Changing iScroll's setting fixes this.
REDMINE-17050
> Make tabs in mobile editor touchable

- pageflow.gemspec
Sprockets 4 does not support procs in config.assets.precompile which
we currently depend on in pageflow/engine.rb.
REDMINE-17098
> Require Sprockets < 4

- pageflow.gemspec
In #1217 it was added as development dependency by accident.
REDMINE-17098
> Restrict sprockets as runtime depenency

- spec/support/pageflow/lint.rb
- spec/support/pageflow/lint/file_type.rb
To integration test import/export further file types need to be
registered and prerequisite files need to be included in the export.
REDMINE-16810
> Allow specifying prerequisites in file type lint specs

- spec/support/pageflow-support.gemspec
- spec/support/pageflow/support.rb
Normally the host application needs to either depend on either
`sassc-rails` or `sass-rails`. Ensure gem is present in plugin test
suites.
> Add sassc-rails as development dependency

- app/models/concerns/pageflow/reusable_file.rb
- lib/pageflow/revision_component.rb
- spec/models/concerns/pageflow/reusable_file_spec.rb
- spec/pageflow/revision_component_spec.rb
Ensure caching of generated CSS is busted when:
* A usage is edited
* A file becomes ready
REDMINE-16809
> Touch revision on file or usage change

- lib/pageflow/engine.rb
- lib/pageflow/revision_component.rb
- pageflow.gemspec
- spec/pageflow/revision_component_spec.rb
- spec/support/helpers/test_revision_component.rb
Use advisory lock to ensure only a single thread/passenger process
calculates the next perma_id at a time. Otherwise the same maximum
perma_id can be used to set the perma_ids of two concurrently created
components.
REDMINE-16809
> Prevent perma_id clashes for concurrently created revision components

- app/models/pageflow/draft_entry.rb
- lib/pageflow/revision_component.rb
- spec/models/pageflow/draft_entry_spec.rb
- spec/pageflow/revision_component_spec.rb
- spec/support/config/database_cleaner.rb
- spec/support/helpers/test_revision_component.rb
Wrapping `RevisionComponent#save` in an advisory lock, does not
suffice for cases where the revision component is created through an
association, i.e
revision.file_usages.create!(...)
In this case `CollectionAssociation#_create_record` [1] already starts
the transaction before the lock is required. Since the transaction is
then committed only after the advisory lock is already released, the
following race condition can occur:
Thread 1:                       Thread 2:
|                               |
BEGIN                           |
GET LOCK                        |
SELECT MAX perma_id             |
INSERT revision component       |
RELEASE LOCK                    |
|                               BEGIN
|                               GET LOCK
|                               SELECT MAX …
> Prevent further cases of perma id clashes

- lib/pageflow/entry_export_import/zip_archive.rb
- spec/pageflow/entry_export_import/zip_archive_spec.rb
* Support UTF-8 characters in archive entry file names
* Use zip64 to support achrives that are larger than 4GB.
REDMINE-16810
> Tweak import/export zip options

- pageflow.gemspec
Sprockets 4 does not support procs in config.assets.precompile which
we currently depend on in pageflow/engine.rb.
REDMINE-17098
> Require Sprockets < 4 (14.x Backport)

- app/models/pageflow/revision.rb
- spec/models/pageflow/revision_spec.rb
Returning the locale as symbol causes errors in
Pageflow analytics interpolator
REDMINE-17194
> Change revision#locale to always return string

- app/models/pageflow/revision.rb
- spec/models/pageflow/revision_spec.rb
Backport of #1239
Returning the locale as symbol causes errors in
Pageflow analytics interpolator
> Change revision#locale to always return string (15.0 Backport)

- app/helpers/pageflow/social_share_helper.rb
- app/views/pageflow/social_share/_image_tags.html.erb
- spec/factories/image_files.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
REDMINE-16972
It's a temporary solution to display images in facebook post preview and also handle the exception caused for panorama pages.
In future we will think of way to create a preview of panorama page also.
> Fb image share panorama page

- app/models/pageflow/draft_entry.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/published_entry.rb
- db/migrate/20191113124400_add_type_name_to_entries.rb
- doc/creating_entry_types.md
- doc/index.md
- lib/pageflow/configuration.rb
- lib/pageflow/entry_type.rb
- lib/pageflow/entry_types.rb
- spec/models/pageflow/entry_spec.rb
- spec/pageflow/entry_types_spec.rb
- spec/support/helpers/test_entry_type.rb
Allow registering entry types in the Pageflow configuration. Add a
`type_name` attribute to `Entry` which can be used to look up the
corresponding `EntryType` object.
REDMINE-17208, REDMINE-17213
> Add entry type concept

- pageflow.gemspec
- spec/support/config/capybara.rb
- spec/support/config/web_mock.rb
According to [1], chromedriver-helper is unmaintained. Its former
maintainer encourages using webdrivers [2].
As part of this change, we allow connections to update drivers in the
WebMock config. See [3] for details about this.
[1] https://github.com/flavorjones/chromedriver-helper#notice-this-gem-is-out-of-support-as-of-2019-03-31
[2] https://github.com/titusfortner/webdrivers
[3] https://github.com/titusfortner/webdrivers/issues/109
REDMINE-17242
> Replace chromedriver-helper by webdrivers

- CHANGELOG.md
- doc/creating_file_types.md
- doc/understanding_entry_export_and_import.md
- lib/pageflow/file_type.rb
- lib/pageflow/file_types.rb
- lib/pageflow/page_types.rb
- spec/pageflow/configuration_spec.rb
- spec/pageflow/file_type_spec.rb
- spec/pageflow/file_types_spec.rb
- spec/pageflow/page_types_spec.rb
- spec/support/helpers/test_file_type.rb
Previously, FileType objects could be initialized using a model reference. This is now deprecated and will be removed in a future version. Please use a string that contains the model name instead
REDMINE-17243
> Defer creating filetypes

- .travis.yml
Provide faster test feedback by executing the different RSpec/Jest
test suites in multiple jobs.
Travis limits the number of parallel jobs for open source projects to
five. We therefore only run the main test suite against multiple Ruby
versions and group all Jest suites into a single job.
Remove `sudo` options, which `travis lint` claims has no effect
anymore.
> Split Travis run into multiple jobs

- bin/build-edge
- doc/contributing/node_package_development.md
- entry_types/scrolled/package/package.json
- packages/pageflow/config/webpack.js
- rollup.config.js
* Update `bin/build-edge` script to include all build outputs
* Turn pageflow into peer dependency of scrolled package
* Provide Webpack config fragment in pageflow package
* Improve handling of svg files in Rollup build
REDMINE-17274
> Improve support for Webpack setup in host appplication

- config/routes.rb
- doc/creating_entry_types.md
- entry_types/scrolled/app/controllers/pageflow_scrolled/editor/sections_controller.rb
- entry_types/scrolled/config/routes.rb
- entry_types/scrolled/lib/pageflow_scrolled.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/sections_controller_spec.rb
- lib/pageflow/editor_controller.rb
- lib/pageflow/entry_type.rb
- lib/pageflow/entry_types.rb
- pageflow.gemspec
- spec/pageflow/editor_controller_spec.rb
- spec/pageflow/entry_types_spec.rb
- spec/requests/pageflow/editor/custom_routes_spec.rb
- spec/spec_helper.rb
- spec/support/helpers/edit_lock_test_helpers.rb
- spec/support/pageflow/edit_lock_test_helper.rb
- spec/support/pageflow/editor_controller_test_helper.rb
Add `editor_app` option to `EntryType` to allow adding entry type
specific routes below `/editor/entries/:id/<entry_type_name>/`. This
can be used for entry type specific editor REST controllers.
Allow including `Pageflow::EditorController` in entry type specific
editor controllers to handle common concerns like authentication and
authorization.
Provide a controller test helper that creates and signs a user, gives
them edit permission and acquires an edit lock.
Add example editor controller to scrolled engine.
REDMINE-17265
> Let entry types define editor controllers

- Gemfile
- entry_types/scrolled/lib/pageflow_scrolled/engine.rb
Soon as Webpacker is required, it starts complaining if the host
application does not have files like `config/webpacker.yaml`. Since,
for now, Webpacker is only required when using the scrolled entry
type, we let Bundler require it by adding an entry to the `Gemfile`.
This makes sure it is required at the right moment to define its Rails
helpers etc.
We leave the `gemspec` entry to make sure host application use a
compatible version if they decide to use Webpacker.
Remove version string from `sassc-rails` Gemfile entry to remove
warning about duplicate entries.
> Do not force host application to install Webpacker

- app/controllers/pageflow/editor/entries_controller.rb
- app/views/layouts/pageflow/editor.html.erb
- app/views/pageflow/editor/entries/show.html.erb
- entry_types/paged/app/views/pageflow_paged/editor/entries/_head.html.erb
- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
Before published entries and the editor used the same layout. This will let us work with a simplified layout for the editor, move the previous application layout to the entry type engine.
REDMINE-17269
> Decouple editor layout

- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
Follow up for #1284. As long as we still load the paged js in the
editor, this global has to be set.
REDMINE-17269
> Set PAGEFLOW_EDITOR global in scrolled editor

- doc/contributing/node_package_development.md
When linking a local pageflow gem from a host application (for the
first time?), we need to run `yarn install` in the host application to
pick up the linked packages in a way that doesn't let the app crash.
Also, this replaces two 'or' by 'and', because 'or' confused me as to
which order would be valid.
REDMINE-17257
> Add needed command to node package development docs

- entry_types/scrolled/package/src/frontend/TextBlock.js
Turned from React fragments into HTML strings during migration from
`example.js` to DB seeds.
REDMINE-17260
> Render raw html in text block content items

- spec/factories/published_entries.rb
Set `type_name` of `published_entry` factory to `paged`. Previous
`nil` value caused error when trying to construct entry type specic
config.
REDMINE-17257
> Fix scrolled entry json seed spec

- entry_types/scrolled/package/spec/entryState/structure-spec.js
- entry_types/scrolled/package/src/entryState/structure.js
- entry_types/scrolled/package/src/frontend/Chapter.js
In #1298, the `Chapter` component was extracted from the `Entry`
component. Before, the `Entry`, while iterating sections, used the
index of that iteration to tell each Section whether it's the current
section and pass references to its adjacent sections.
This logic was moved into `Chapter`. The index of a section inside a
chapter cannot be used, though, to track the active scene of the
entry. Moreover, only references to adjacent sections inside that
chapter were passed.
Restore and move this logic into the `useEntryStructure` hook.
REDMINE-17300
> Fix section index and references to adjacent chapters

- Gemfile
- app/assets/stylesheets/pageflow/admin/embedded_index_table.scss
- lib/generators/pageflow/active_admin_initializer/active_admin_initializer_generator.rb
- lib/generators/pageflow/assets/assets_generator.rb
- pageflow.gemspec
- spec/generators/pageflow/active_admin_initializer/active_admin_initializer_spec.rb
- spec/generators/pageflow/assets/assets_generator_spec.rb
- spec/support/pageflow-support.gemspec
REDMINE-17241
- All coffee scripts are removed and should not be added again. if it is required then coffee-rails gem should be included.
- Active admin load_paths are added using the setter `+=` instead of `unshift` method as a workaround to activeadmin initialisation order [issue](https://github.com/activeadmin/activeadmin/issues/5995)
> Updated active admin to 2.5.0

- entry_types/paged/app/controllers/concerns/pageflow_paged/without_controller_namespace_partial_path_prefix.rb
- entry_types/paged/app/controllers/pageflow_paged/entries_controller.rb
- entry_types/paged/spec/controllers/pageflow_paged/entries_controller_spec.rb
- entry_types/paged/spec/support/helpers/stub_template_controller_test_helper.rb
Plugins like `pageflow-external-links` depend on having `render site`
where site is a `Pageflow::ExternalLinks::Site` render
`pageflow/external_links/sites/_site.html.erb`. By default Rails looks
for `pageflow_paged/pageflow/external_links/sites/_site.html.erb` when
rendering in the context of
`PageflowPaged::EntriesController`. Temporarily set
`prefix_partial_path_with_controller_namespace` [1] to `false` in an
`around_action` to disable this behavior.
[1] https://edgeguides.rubyonrails.org/configuring.html#configuring-action-view
REDMINE-17319
> Do not prefix partial paths with pageflow_paged

- app/views/components/pageflow/admin/add_membership_button.rb
- app/views/pageflow/admin/entries/_cannot_add_user.html.erb
- app/views/pageflow/admin/users/_cannot_add.html.erb
- config/locales/new/entry_membership.de.yml
- config/locales/new/entry_membership.en.yml
- spec/support/helpers/stub_template_in_helper_specs.rb
- spec/views/components/pageflow/admin/add_membership_button_spec.rb
* add user button is not shown if there are no users in the account
* current user is not considered in the list of users to be added
* If there are no users in the account, quota is checked and
message is displayed if exhausted, otherwise invite users message is displayed
REDMINE-16606
> Entry add member changes

- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
Set devtools global in development mode. This allows inspecting React
elements with the Chome devtools extension also inside the iframe
preview of scrolled entries,
REDMINE-17431
> Enable React devtools in editor iframe

- entry_types/scrolled/package/spec/collections-spec.js
- entry_types/scrolled/package/spec/entryState/legalInfo-spec.js
- entry_types/scrolled/package/spec/entryState/metadata-spec.js
- entry_types/scrolled/package/spec/support/normalizeSeed.js
- entry_types/scrolled/package/src/collections.js
- entry_types/scrolled/package/src/editor/views/SectionItemView.js
- entry_types/scrolled/package/src/editor/views/SectionItemView.module.css
- entry_types/scrolled/package/src/entryState/watchCollections.js
- entry_types/scrolled/package/src/frontend/SectionThumbnail.js
- entry_types/scrolled/package/src/frontend/SectionThumbnail.module.css
- entry_types/scrolled/spec/spec_helper.rb
- packages/pageflow/src/testHelpers/factories.js
* Downgrade to `chromedriver` 79 to workaround bug that causes timeout when switching between iframes.
* Fix React warnings about state updates on unmounted components and missing keys.
REDMINE-17430
> Make pageflow-scrolled Capybara specs less flaky

- entry_types/scrolled/package/.storybook/preview-head.html
- entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.module.css
Hide the progress bar in storybook to prevent noisy change
Percy alerts for inline videos.
> Prevent Percy from reporting different video loading progress

- entry_types/scrolled/config/locales/new/de.yml
- entry_types/scrolled/config/locales/new/en.yml
- entry_types/scrolled/package/src/frontend/navigation/AppHeader.js
- entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
- entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js
- entry_types/scrolled/package/src/frontend/navigation/ChapterLink.module.css
- entry_types/scrolled/package/src/frontend/navigation/ChapterLinkTooltip.js
- entry_types/scrolled/package/src/frontend/navigation/LegalInfoMenu.js
- entry_types/scrolled/package/src/frontend/navigation/LegalInfoMenu.module.css
- entry_types/scrolled/package/src/frontend/navigation/LegalInfoTooltip.js
- entry_types/scrolled/package/src/frontend/navigation/LegalInfoTooltip.module.css
- entry_types/scrolled/package/src/frontend/navigation/SharingMenu.js
- entry_types/scrolled/package/src/frontend/navigation/SharingMenu.module.css
- entry_types/scrolled/package/src/frontend/navigation/SharingTooltip.module.css
Add summary to mobile navigation.
Restructure nav icons to account for empty set of share providers.
Translate hard-coded chapter tooltip title.
Only show chapters with title and summary in navigation.
REDMINE-17425
> Improve navigation

- entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
use chart urls without protocol in iframe src,
so that correct protocol gets selected based on the parent
> DataWrapper Chart URL Fix

- app/models/pageflow/draft_entry.rb
- app/models/pageflow/published_entry.rb
The manual_start, emphasize_chapter_beginning and emphasize_chapter_beginning
attributes have been migrated to the revisions configuration.
Access via DraftEntry or PublishedEntry now delegates to the revisions configuration.
There is a modified getter for configuration in revision which accesses
legacy column values on read.
REDMINE-17498
> Read migrated attributes from configuration

- app/models/pageflow/draft_entry.rb
- app/models/pageflow/published_entry.rb
Backport of #1366
The `manual_start`, `emphasize_chapter_beginning` and `emphasize_chapter_beginning`
attributes have been migrated to the revisions configuration.
Access via DraftEntry or PublishedEntry now delegates to the revisions configuration.
There is a modified getter for configuration in revision which accesses
legacy column values on read.
REDMINE-17498
> Read migrated attributes from configuration (15.1 Backport)

- packages/pageflow/src/editor/views/EditPageView.js
While replacing references to the global `pageflow.editor` with api
objects passed in via view options, it was overlooked that in the
event handler `this.options` does not refer to the options of the
`EditPageView`, but instead of the `ExtendedSelectInputView`.
Using an arrow function corrects the context of the callback.
REDMINE-17480
> Fix help link in editor page type drop down

- pageflow.gemspec
These outputs have recently be added to the package and were
forgotten in the gemspec.
REDMINE-17382
> Include scrolled content element js files in gem

- pageflow.gemspec
Backport of #1373 
These outputs have recently be added to the package and were
forgotten in the gemspec.
REDMINE-17382
> Include scrolled content element js files in gem (15.2 Backport)

- app/assets/javascripts/pageflow/admin/accounts.js
"Enable home button by default" check box needs to be disabled when
selected theme does not support home button. Theme select id changed
while extracting entry templates. Update selector.
REDMINE-17545
> Fix disabling home button input in account form based on theme

- app/assets/javascripts/pageflow/admin/accounts.js
Backport of #1375 
"Enable home button by default" check box needs to be disabled when
selected theme does not support home button. Theme select id changed
while extracting entry templates. Update selector.
REDMINE-17545
> Fix disabling home button input in account form based on theme (15.2 Backport)

- entry_types/scrolled/spec/spec_helper.rb
Travis now uses Chrome 81, which no longer can be used with
Chromedrvier 79.
REDMINE-17430
> No longer pin chrome driver in scrolled Capybara specs

- entry_types/scrolled/package/spec/support/stories.js
- entry_types/scrolled/package/src/frontend/__stories__/transitions-stories.js
Make cross browser testing easier. Since CSS of a section depends on
entering and exiting transition, add one story for each combination of
enter/exit transitions.
Exclude from Percy build since visual diff is not meaningful.
REDMINE-17369
> Add stories for section transitions

- .github/workflows/docs.yml
- .travis.yml
The storybook generated via GitHub actions (#1392) is missing the seed data
file. Publish as part of Percy storybook job instead.
Use `$TRAVIS_BRANCH` as `$PAGEFLOW_PAPERCLIP_S3_ROOT` to make sure
storybook builds for version tags use their own set of files on
S3. Pull requests still use files based on the most recent `master`
build.
Run Percy job and publishing for all upstream branches and tags (not
just `master`) to keep a history of published storybooks.
We cannot use Travis gh-pages deploy strategy since it removes all
previously published files on deploy. We want to keep old versions,
though.
REDMINE-17369
> Publish pageflow-scrolled storybook via Travis

- .travis.yml
- entry_types/scrolled/doc/creating_content_elements.md
- entry_types/scrolled/lib/pageflow_scrolled/seeds.rb
- entry_types/scrolled/lib/tasks/pageflow_scrolled_tasks.rake
- entry_types/scrolled/package/src/contentElements/inlineAudio/stories.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/stories.js
- entry_types/scrolled/package/src/frontend/Audio.js
- entry_types/scrolled/package/src/frontend/Video.js
- entry_types/scrolled/spec/pageflow_scrolled/seeds_spec.rb
> Use files in CI/storybook seed

- entry_types/scrolled/package/spec/frontend/ContentElement-spec.js
- entry_types/scrolled/package/src/frontend/ContentElement.js
- entry_types/scrolled/package/src/frontend/ContentElement.module.css
- entry_types/scrolled/package/src/frontend/api/ContentElementTypeRegistry.js
Prevent the whole preview from not rendering just because one content
element has an unknown type.
> Render placeholder for content element of missing type

- entry_types/scrolled/package/src/frontend/Section.js
Creating a new object each time prevents memoizing content element
components.
REDMINE-17336
> Memoize section properties

- package.json
- yarn.lock
`babel-plugin-transform-runtime` does not extract all helpers by
default, since it assumes an old version of `@babel/runtime` is
used. In our case, this causes `_objectSpread` helpers to be inserted
for each file using the spread operator. Fixed in [1].
[1] https://github.com/facebook/create-react-app/pull/7726
> Update Babel preset to fix duplicate helpers in build output

- entry_types/scrolled/app/controllers/pageflow_scrolled/editor/chapters_controller.rb
- entry_types/scrolled/app/controllers/pageflow_scrolled/editor/content_elements_controller.rb
- entry_types/scrolled/app/controllers/pageflow_scrolled/editor/sections_controller.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/chapters_controller_spec.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/content_elements_controller_spec.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/sections_controller_spec.rb
Otherwise Backbone passes the response to `set` again, causing an
unneeded entry state update and rerender.
REDMINE-17336
> Make scrolled API respond with no content for PUT/DELETE

- entry_types/scrolled/package/documentation.yml
Remove from docs since those cannot be used outside of
`pageflow/frontend` and might change in the future.
REDMINE-17376
> Make useEntryStructure/useSectionStructure hooks private

- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css
[REDMINE#17372](https://redmine.codevise.de/issues/17372)
(1/6)
> Removed max-width for label of before/after content element, which was causing the long labels to break in to different lines. Removed all the variables containing label width dependent on the slider position
> Removed label dependency for before/after

- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css
[REDMINE#17372](https://redmine.codevise.de/issues/17372)
(4/6)
> Since custom properties are not supported in IE11, removed them and replaced them with static values.
> Remove css custom properties

- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/InlineBeforeAfter.module.css
[REDMINE#17372](https://redmine.codevise.de/issues/17372)
(3/6)
> Give minimum `min-height` to the `inline_before_after_root` element so if there are no images the element can be easily selected which before was difficult.
> Give height to element in case of no images

- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css
[REDMINE#17372](https://redmine.codevise.de/issues/17372)
(2/6)
> Increased the fade out transition time of before/after labels so there must be a delay in fade-out on mousedown/touchstart.
Since it was an inline property coming from `react-compare-image`, so override the value by using `!important`.
> Delay label fadeout on mousedown/touchstart

- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
REDMINE-17372
(5/6)
> If no image is present, there will be a placeholder image as a background of single color. As discussed with Tim, took simple color svgs and converted them into Data URIs.
If an image is missing then this placeholder image will be shown.
> This was not in the list, but Tim suggested to move this piece of code to a useEffect function so it doesn't trigger on every render and just once for the first time.
So` initial-rect-width` will be set the first time only.
> Added placeholder images for before/after

- entry_types/scrolled/package/.storybook/preview-head.html
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
Prevent flaky snapshots when chart does not load fast enough.
REDMINE-17388
> Hide Datawrapper chart in Percy snapshot

- entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js
- entry_types/scrolled/package/src/contentElements/videoEmbed/frontend.js
* Ensure element can be selected in editor.
* Use `isPrepared` state to lazy load player.
REDMINE-17386
> Improve video embed content element

- entry_types/scrolled/package/spec/frontend/EditableText-spec.js
- entry_types/scrolled/package/src/frontend/EditableText.js
Simple way to span short sections with no other content than the
backdrop image.
REDMINE-17704
> Ensure empty paragraphs have height

- entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
- entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.module.css
Prevent inline images from becoming taller than the viewport.
REDMINE-17708
> Display pillar boxes for full width inline images

- entry_types/scrolled/package/spec/editor/views/EditSectionTransitionView-spec.js
- entry_types/scrolled/package/src/editor/views/EditSectionTransitionEffectView.js
- entry_types/scrolled/package/src/editor/views/EditSectionTransitionEffectView.module.css
- entry_types/scrolled/package/src/editor/views/EditSectionTransitionView.js
- package/src/testHelpers/dominos/ui/index.js
- package/src/testHelpers/dominos/ui/inputs/RadioButtonGroupInput.js
- package/src/testHelpers/dominos/ui/inputs/TransitionsInput.js
REDMINE-17641
[PR-1455](https://github.com/codevise/pageflow/pull/1455)
- Created a thumbnail input preview for the section transitions.
- For the new section transition input view, changed the dropdown to radio button to add animations and select only one at a time. Hide the buttons.
- Created a new radio button template, added in the input view.
- Gave some basic stylings.
- Changed the selectInputView to thumbnailInputView in EditSectionTransitionView.
Update:
- Make thumbnail input preview specific to Pageflow Scrolled.
- Deleted the previously created files.
- Shifted the sass to css module.
> Preview thumbnails for section transitions

- package/src/frontend/VideoPlayer/filterSources.js
Safari complains about removing a non-existent child.
REDMINE-17646
> Add existence check for dash source

- entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.module.css
- entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/InlineBeforeAfter.module.css
- entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.module.css
- entry_types/scrolled/package/src/frontend/ContentElement.js
- entry_types/scrolled/package/src/frontend/ContentElementMargin.js
- entry_types/scrolled/package/src/frontend/ContentElementMargin.module.css
- entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.module.css
Add top/bottom margin to all content elements - except for position
full to ensure the section backdrop does not become visible
above/below full width elements in single element sections.
REDMINE-17672
> Use consistent margins around content elements

- entry_types/scrolled/package/src/contentElements/heading/Heading.js
- entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
- entry_types/scrolled/package/src/frontend/InlineCaption.module.css
- entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
- entry_types/scrolled/package/src/frontend/index.js
Instead of setting text-shadow default for all content inside
a gradient box, export withShadow class and use it only on
headlines inside gradient boxes for now.
This makes the CSS class available for all content elements
which desire a text shadow when placed inside a gradient box,
but removes the necessity to explicitly overwrite the text-shadow
if not.
REDMINE-17686
> Change default of text-shadow for gradient box

- entry_types/scrolled/package/spec/frontend/inlineEditing/useCachedValue-spec.js
- entry_types/scrolled/package/src/frontend/inlineEditing/useCachedValue.js
Before `useCachedValue` created a new debounced function whenever
`onDebouncedChange` changed. The previous debounced function was not
cancelled causing old values to be reported to `onDebouncedChange`.
In the case of `EditableText`, these old values then were saved to the
entry state. In the triggered rerender, `useCachedValue` then regarded
these old values as outside updates and called `onReset`. Slate then
got confused with those frequent updates and caused an exception when
trying to update the DOM selection.
> Debounce saving editable text also when rerendered

- entry_types/scrolled/package/spec/support/rendering.js
- entry_types/scrolled/package/spec/support/stories.js
- entry_types/scrolled/package/src/frontend/RootProviders.js
- entry_types/scrolled/package/src/frontend/SectionThumbnail.js
- entry_types/scrolled/package/src/frontend/__stories__/MediaPlayer-stories.js
- entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
- entry_types/scrolled/package/src/frontend/__stories__/transitions-stories.js
- entry_types/scrolled/package/src/frontend/i18n.js
- entry_types/scrolled/package/src/frontend/index.js
- entry_types/scrolled/package/src/frontend/inlineEditing/__stories__/EditableText-stories.js
The main motivation for this change is to allow `useI18n` outside of
an `EntryStateProvider` by giving the `LocaleContext` `en` as default
value. This lets us use translations in low level components without
having to resort to tools like `renderInEntry`.
As a nice side effect, this change prevents having all components with
translations subscribe to the entry state context. Below a
`React.memo`, components with `useI18n` will now only rerender when
the locale changes.
REDMINE-17673, REDMINE-173763
> Provide locale via separate context

- entry_types/scrolled/package/spec/frontend/focusOutline-spec.js
- entry_types/scrolled/package/src/frontend/RootProviders.js
- entry_types/scrolled/package/src/frontend/focusOutline.js
- entry_types/scrolled/package/src/frontend/focusOutline.module.css
Prevent showing focus outline after clicking player control buttons.
REDMINE-17736
> Only show focus outline after keyboard input

- entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
When controls (e.g. the player button) are clicked they receive the
focus. This causes the controls to never fade, even though the focus
outline is hidden (since it is only visible after keyboard
interaction). Only prevent controls from becoming inactive because the
focus is inside when focus rect is visible.
REDMINE-17751
> Hide focused controls if focus outline hidden

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/applyPlayerState.js
- entry_types/scrolled/package/src/frontend/__stories__/MediaPlayer-stories.js
- entry_types/scrolled/package/src/frontend/__stories__/browserBugs-stories.js
Observed on both Chrome 79 and 83 on Ubuntu. Playing an inline audio,
scrolling away, returning and playing again causes the browser tab to
crash with a `SIGSEGV` error.
Error can be reproduced for audio elements that are connected to an
audio context.
* Play audio so the current time in the player state progresses.
* Unallocated the player causing the blank audio file of zero duration
to be assigned.
* Allocated the player again with the previous file aga. Video.js
updates the source only after a delay. So when we restore the
current time in `applyPlayerState` the zero duration audio file is
actually still loaded.
* Next time the player is played, the tab is likely to crash.
The added `browserBug` story repeats these steps until the error
happens.
Setting `currentTime` only after …
> Fix segfault on media playback in Chrome

- doc/creating_entry_types.md
- entry_types/scrolled/package/src/editor/config.js
- entry_types/scrolled/package/src/editor/views/BrowserNotSupportedView.js
- entry_types/scrolled/package/src/editor/views/BrowserNotSupportedView.module.css
- package/spec/editor/api-spec.js
- package/src/editor/api/index.js
- package/src/editor/base.js
REDMINE-17565
> - [X] A function that is called in startEditor to check whether the current browser is supported added
> - [X] A view that is rendered instead of the editor if the function returns false.
- Created a new view, which will be rendered if the browser is not supported.
- Provide a function in `entry_type/scrolled/package/src/editor` to detect the type of browser and a view to display.
- Extended the `pageflow/editor` api to include a callback function which will get the result from scroll and either then start the app or display the view.
> Extend editor api to detect browser

- entry_types/scrolled/package/src/frontend/PlayerControls/ProgressIndicators.js
There appear to be race conditions where `progress` events are
dispatched when the duration of media player has not been updated
yet.
REDMINE-17761
> Prevent progress bar with more than 100%

- entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
Use top margins only. Since margins can not collapse accross open
ended cards, bottom margins cause gaps to appear.
REDMINE-17759
> Prevent gaps in cards

- entry_types/scrolled/package/src/editor/config.js
- package/spec/frontend/browser/agent_spec.js
- package/src/frontend/browser/Agent.js
REDMINE-17565
We want to restrict entry to editor on certain devices and browsers.
> Extend the Agent API to cover four most used desktop browsers.
> Extend the agent-specs to cover all the newly added cases.
> Extend the existing user agent detection code for desktop browsers

- entry_types/scrolled/package/spec/support/stories.js
Prevent big images from loading to slowly and thus not showing up in
snapshots causing false positives on Percy.
REDMINE-17741
> Use empty inline images in appearance stories

- spec/support/pageflow/dummy/rails_template.rb
Pass `abort_on_failure` option to explictly ignore failing `rake
db:drop` command when no databases exist. Failures used to be ignored.
REDMINE-17780
> Fix dummy app generation with Thor 1.0

- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/LinkInput.js
`onSubmit` function was called twice: Once for enter key, once for
blur. Make enter key blur input, to only call function once.
REDMINE-17782
> Do not create two nested links when closing link box with Enter

- entry_types/scrolled/spec/spec_helper.rb
- spec/support/pageflow/dummy/rails_template.rb
Backport of #1522 
Pass `abort_on_failure` option to explictly ignore failing `rake
db:drop` command when no databases exist. Failures used to be ignored.
REDMINE-17780
> Fix dummy app generation with Thor 1.0 (15.2 Backport)

- config/initializers/help_entries.rb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/new/help.de.yml
- config/locales/new/help.en.yml
- entry_types/paged/config/initializers/features.rb
- entry_types/paged/config/initializers/help_entries.rb
- entry_types/paged/config/locales/new/help.de.yml
- entry_types/paged/config/locales/new/help.en.yml
- entry_types/scrolled/config/initializers/help_entries.rb
- entry_types/scrolled/config/locales/new/de.yml
- entry_types/scrolled/config/locales/new/en.yml
* Split title and options into multiple entries to make "general" and
"social" reusable.
* Extract paged specific help entries into paged engine.
* Add outline for scrolled help entries.
REDMINE-17295, REDMINE-17296, REDMINE-17294
> Separate scrolled and paged help entries

- package/src/editor/models/EntryMetadata.js
`EntryMetadata` model does not have an id, but it still represents a
saved record that needs to be synced to entry state. Otherwise credits
and sharing options do not get updated.
REDMINE-17781
> Sync entry metadata model into entry state

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/__stories__/mediaPlayerAutoplay-stories.js
* Add prop to `MediaPlayer` to allow appending suffix to source
urls. This is used to reuse the one seed media file as multiple
sources that are handled independently by the browser.
* Add a story that creates multiple players and tries to autoplay them
one by one.
REDMINE-17770
> Add story to test media autoplay

- entry_types/scrolled/package/spec/frontend/MediaPlayer/textTracks-spec.js
- entry_types/scrolled/package/src/frontend/Backdrop.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/textTracks.js
Backdrop videos are supposed to be atmo not content. Due to covering
object fit, text tracks might be clipped off anyway.
REDMINE-17791
> Disable text tracks in backdrop videos

- entry_types/scrolled/package/spec/frontend/EditableInlineText-spec.js
- entry_types/scrolled/package/spec/frontend/inlineEditing/EditableInlineText-spec.js
- entry_types/scrolled/package/src/contentElements/heading/Heading.js
- entry_types/scrolled/package/src/frontend/EditableInlineText.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText.js
Move default value logic to `EditableInlineText` component. Prevent
generating invalid default children when default value is undefined.
REDMINE-17798
> Fix heading default value logic

- package/src/frontend/browser/Agent.js
REDMINE-17737
After IOS 13 update, iPad reports the same user string
as Safari on Dekstop MacOS
It adds further support of detecting multi touch devices
At the time of this writing there are no other devices
with multi-touch support other than IOS/iPadOS
Also, adds a check for IE devices to be detected as
IOS devices
> Add logic to detect IOS 13 Safari on iPad

- entry_types/scrolled/package/spec/frontend/MotifArea-spec.js
- entry_types/scrolled/package/src/frontend/MotifArea.js
Trying to compute the position of the motif area element, when image
width and height have not yet been determined leads to `NaN`
values. Since `NaN != NaN`, the `onUpdate` callback is then called on
every render leading to an infinite loop.
This causes freezes the editor soon as an uploading or unprocessed
image is selected as backdrop of a section.
REDMINE-17839
> Do not compute motif area if image is not yet ready

- doc/contributing/node_package_development.md
- entry_types/scrolled/package/package.json
- yarn.lock
Since only one copy of React is allowed to be loaded at a time, soon
as other Paegflow plugin packages that define content elements are
added to a host application, we need to make sure that all Pageflow
packages share a React version.
`pageflow-scrolled` can therefore no longer declare `react` as a
normal dependency, but instead needs to rely on the host application
to install a shared copy of React.
When running `yarn install` in the root of the `pageflow` repository,
React packages will still be installed into the root `node_modules`
directory since they are transitive dependencies of other packages
`pageflow-scrolled` depends on.
This has the positive side effect that - for example when running Jest -
React can still be imported. On the other hand, when linking the
`pagefow-scrolled` …
> Turn react and react-dom into peer dependencies of pageflow-scrolled

- package/src/ui/templates/inputs/textAreaInput.jst
- package/src/ui/views/inputs/TextAreaInputView.js
The default used to be "http://".
REDMINE-17842
> Default to empty link url in text area input view

- entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.js
- entry_types/scrolled/package/src/frontend/inlineEditing/Toolbar.js
- entry_types/scrolled/package/src/frontend/inlineEditing/Toolbar.module.css
Prevent toolbar from hiding "insert before" button.
REDMINE-17845
> Collapse inline selection toolbar for small viewports

- entry_types/scrolled/package/spec/contentElements/dataWrapperChart/useIframeHeight-spec.js
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/useIframeHeight.js
* Store height in state to trigger React update when message
arrives. Otherwise the chart is only resized next time the component
is rendered.
* Ensure event handler is removed correctly. Previously it was added
to `window` and removed from `document`. Change test to assert that
messages are no longer processed instead of mocking the (wrong)
implementation detail.
* Wrap `postMessage` calls in `act` calls to correctly trigger React
updates in specs. Since post message events are handled
asynchronously, we need to call `tick` inside `act` to make sure
React is still awaiting state updates while the message is being
processed. This relies on the fact that JSDOM implements
`postMessage` by scheduling the event handler for immediate
execution when the message is sent. `tick` therefore yields …
> Fix responsive Datawrapper chart height hook

- entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/entry_json_seed_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
REDMINE-17778
Social sharing meta tags and meta tags
are rendered by paged in entry head. Same
can be used for scrolled
It adds the same helpers used for paged in scrolled
entry head
It also changes the lang attribute and reflect the entry
locale as in paged
> Add meta tags in scrolled

- config/initializers/entry_types.rb
- lib/generators/pageflow/initializer/templates/pageflow.rb
Registering entry types in a host app initializer allows disabling an
entry type in the host application. Before this was only possible via
feature flags, which could always be changed by system admins.
REDMINE-17852
> Move entry type registration to host app

- admins/pageflow/entry_templates.rb
- app/models/pageflow/entry_template.rb
- app/views/admin/entry_templates/_form.html.erb
- config/locales/new/edit_entry_templates.de.yml
- config/locales/new/edit_entry_templates.en.yml
* Use conventional keys for validation error messages. Before, the
error message translation lived below `attributes.models` which is
reserved for model name translations. Localeapp complains about
namespaces which contain pluralization keys (i.e. `one`) as well as
other keys (i.e. the error message) and skips importing the former.
* Use Formtastic helper to actually render the error message in the
form. Before, submitting the `new` form just re-rendered the form
without any indication of an error, when an entry template of the
same type had been created in the meantime. The Formtastic helper
always prefixes the error message with the attribute name. We
therefore have to go a bit out of our way to formulate the error
message accordingly.
* Include a hint in the error message about what …
> Improve error messages when entry template creation fails

- package/spec/frontend/media_player/volume_binding_spec.js
- package/src/frontend/mediaPlayer/volumeBinding.js
On a waveform audio page that has a atmo that is configured to pause
during page media playback, atmo resumes when seeking in the playing
waveform audio.
Wavesurfer pauses the media element while seeking. This causes the
atmo to be resumed and immediately faded out again. With the new async
promises, the following order of execution can be observed:
```
* Wavesurfer pauses before seek
* Atmo plays
| * Wavesurfer plays after seed
| * Atmo fades out (since it has not yet faded in yet this completes
| | immediately)
| * Atmo pauses
* Atmo fades in
```
Now two problems come into play:
* Audio5.js ignores the pause call [2] since it has not yet handled
the `play` event and thinks that the player is still paused.
* The fade in happens even though the player has been paused in the
meantime.
This …
> Abort playAndFadeIn if paused while waiting for play promise

- entry_types/scrolled/package/src/frontend/transitions/revealFadeOut.module.css
- entry_types/scrolled/package/src/frontend/transitions/revealFadeOutBg.module.css
Reveal/fade out sections need to make their backdrop longer to apply
the clipping effect only at the top. Using height 200% works is the
same as 200vh as long as the section does not have a lot of
content. For longer sections this causes the backdrop to extend beyond
the next section. Change height to account for longer sections.
REDMINE-17838
> Prevent empty space below entry

- entry_types/scrolled/package/src/frontend/PlayerControls/MenuBarButton.module.css
- rollup.config.js
CSS modules rules can not reliably override rules from composed rules
[1]. Use more specific selector to ensure menu button can override
padding of unstyled button.
PostCSS Rollup plugin generates duplicate rules when importing another
rule in multiple places [2]. Enable minification to remove those
duplicates in extracted CSS.
REDMINE-17871
[1] see https://github.com/css-modules/css-modules/issues/195
[2] https://github.com/egoist/rollup-plugin-postcss/issues/26
> Deal with duplicated rules in extracted CSS

- entry_types/scrolled/package/src/frontend/PlayerControls/WaveformPlayerControls/Wavesurfer.js
When adding a caption to a waveform audio content element, the
`Waveform` and the `MediaPlayer` components get unmounted and
recreated wrapped in a `Figure` component. Removing the `MediaPlayer`
dispatches the `discardMediaElementId` action, but this only gets
processed for the next render. When the `Waveform` component is
mounted wrapped in the `Figure` component, the stored media element id
has not yet changed, still the `MediaPlayer` component is not yet
mounted again. Trying to look up the media element fails.
If we ignore the missing media element. The `Waveform` will get
unmounted again once the `discardMediaElementId` action has been
processed. Once the new `Audio` component has been mounted it
dispatches a `saveMediaElementId` action which in turn causes a new
`Waveform` component …
> Do not fail if media element for waveform cannot be found

- entry_types/scrolled/package/src/frontend/Entry.module.css
- entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
Prevent scrolling when clicking the first chapter link after loading
the document. Before, the first chapter began right below the
navigation bar. Now the navigation bar no longer has a height. We have
added a padding to the first chapter to prevent content or the section
selection rect from being hidden behind the navigation bar.
REDMINE-17874
> Let first chapter begin at the very top

- app/assets/stylesheets/pageflow/editor/base.scss
- entry_types/scrolled/config/locales/new/de.yml
- entry_types/scrolled/config/locales/new/en.yml
- entry_types/scrolled/package/src/editor/views/BlankEntryView.js
* Blank slate styles in `pageflow/editor` use Source Sans Pro. So far
that was only defined in `pageflow/application.scss`. Also import it
`pageflow/editor.scss` to make it available for Pageflow
Scrolled. For Paged the duplicate definition should not hurt.
* Since the blank slate page disappears as soon as the first section
has been added, it does not make sense to include steps with
instructions about adding and editing content elements. Keep a third
item since there maybe is a chance that the user reads ahead one
item and since a two item list looks weird.
REDMINE-17841
> Improve scrolled editor blank slate

- package/src/editor/base.js
`browser.detectFeatures` now returns a native `Promise` object. This
is not recognized as a promise by our version of `jQuery.when`. This
causes the editor to start before feature detection finished when
loading the seed data completes too fast. Code trying to access
browser featues then fails with a "Feature detection has not finished
yet" error.
`Promise.all` works for any "thenable" - in paricular jQuery promises
[1].
REDMINE-17882
[1] https://stackoverflow.com/questions/25061336/ecmascript-promise-all-method-works-with-jquery-deferred-why
> Wait for feature detection before booting editor

- app/models/pageflow/account_role_query.rb
- app/models/pageflow/managed_user_query.rb
- app/policies/pageflow/folder_policy.rb
- app/policies/pageflow/membership_policy.rb
- app/policies/pageflow/theming_policy.rb
- app/policies/pageflow/user_policy.rb
Double quotes will work with mysql, but will break postgresql.
This fixes an error message after logging in with a non-admin user, while using a postgresql db.
> String literals in SQL should only be enclosed by single quotes

- entry_types/scrolled/package/src/editor/vendor/jquery.imgareaselect.js
- entry_types/scrolled/package/src/editor/views/EditMotifAreaDialogView.module.css
Once background position depends on motif area, it will be important
to assign identical motif areas to backdrop images of adjacent
sections when using section transitions to build scroll animations.
Making the selection rect snap to a grid makes it more likely to
select exactly the same motif area when drawing roughly the same
rectangle.
Grid size is calculated such that the longer side of the image is
always divided into 20 cells. For the other dimension, cell size is
increased just enough to ensure the length of the shorter side of the
image is a multiple of the cell size.
Hide overflow of preview thumbnail to prevent rounding errors from
making mask element extend beyond image by a pixel.
REDMINE-17967
> Make motif area selection snap to grid

- entry_types/scrolled/app/helpers/pageflow_scrolled/react_server_side_rendering_helper.rb
Having to restart the Rails server to synchronize server- and
client-side JS introduces an additional error source in many dev scenarios that
otherwise don't have anything to do with the SSR/CSR distinction.
To avoid this, we only memoize the renderer in environments that
aren't development.
REDMINE-18013
> Remove renderer memoization in development

- package/src/ui/views/inputs/ColorInputView.js
Minicolors can not handle when settings are updated with a shorter
array of swatches than initially passed (see
https://github.com/claviska/jquery-minicolors/issues/287).
Minicolors converts the swatch strings to object and stores the
converted settings. When settings are updated, the new settings and
the old are deeply merged. If the new settings contain less swatch
colors, merging in the old settings adds a bunch of items to the
swatches array that have already been converted to objects. When
Minicolor proceeds to process the settings then, it cannot handle the
already converted items in the swatches array.
Minicolors stores its settings via `jQuery#data`. So before updating
the settings, we now remove the `swatches` property from the stored
settings. This way the settings object …
> Work around Minicolors problem with updating swatches

- entry_types/scrolled/package/src/contentElements/textBlock/editor.js
When deleting a content element that sits between two text blocks that
have not yet been edited, `merge` needs to handle configurations that
do not contain `value` properties.
REDMINE-17968
> Fix error when merging empty text blocks

- entry_types/scrolled/package/spec/frontend/AudioPlayer-spec.js
- entry_types/scrolled/package/spec/frontend/Image-spec.js
- entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
- entry_types/scrolled/package/src/frontend/AudioPlayer/index.js
- entry_types/scrolled/package/src/frontend/Image.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/VideoPlayer/index.js
- package/spec/frontend/media/media_spec.js
- package/src/frontend/media/MediaPool.js
REDMINE-17864
It renders alt texts if provided or empty
text for all background and inline images,
videos, and audios
beforeAfter images already had a mechanism
to render alt texts
We already get the files in video, and audio player.
It sends the value to MediaPool where it adds the attribute
to the player
> Renders alt text for media

- entry_types/scrolled/package/src/frontend/Atmo.js
- entry_types/scrolled/package/src/frontend/useAtmo.js
- package/spec/frontend/media/PlayerSourceIDMap_spec.js
- package/src/frontend/media/PlayerSourceIDMap.js
Before, changing to a section without atmo only paused the atmo multi
player without changing its current file id. When a media content
element in a section without atmo was then set to turn down atmo
during playback, pausing the media element resumed the atmo that had
been playing for a previous section.
To work around this issue, we always fade the multiplayer on section
change - even to an undefined audio file perma id if non is given. We
change the `PlayerSourceIDMap` to return a `Null` player if no sources
can be found for the passed id. When moving back and forth between a
section with atmo and an adjacent section without atmo, this will now
cause players for the same audio file to be requested whenever we
enter the section with atmo. To prevent creating multiple players in
this …
> Prevent resuming atmo of other section

- .github/workflows/tests.yml
- bin/rspec-with-retry
- entry_types/scrolled/bin/rspec-with-retry-on-timeout
Make overall test run less flaky. Since those specs run in a separate
job, they are quite fast to retry.
REDMINE-18078
> Retry js specs of pageflow engine

- .github/workflows/tests.yml
- bin/rspec-with-retry
- entry_types/scrolled/bin/rspec-with-retry-on-timeout
- entry_types/scrolled/spec/pageflow_scrolled/seeds_spec.rb
- spec/controllers/pageflow/editor/file_import_controller_spec.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
- spec/models/pageflow/text_track_file_spec.rb
- spec/state_machines/pageflow/image_and_text_track_processing_state_machine_spec.rb
- spec/state_machines/pageflow/media_encoding_state_machine_examples.rb
- spec/support/pageflow/support/config/paperclip.rb
Speed up tests by only processing attachments of factory created files
if the test actually uses the files. Also process attachments in JS
specs since the browser might request processed files for display.
> Stub Paperclip by default in specs 

- entry_types/scrolled/config/locales/new/de.yml
- entry_types/scrolled/config/locales/new/en.yml
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.module.css
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
* Never show scroll bars on iframe. Before, scroll bars sometimes
flashed during resizing.
* Add padding to prevent displaying charts too close to the viewport
edge.
* Make background color configurable. Use background color of default
Datawrapper as default to give padding the same color as chart
itself. This allows choosing a good color for charts with
transparent backgrounds.
* Make iframe title configurable to improve accessibility.
REDMINE-18082
> Improve Datawrapper chart display

- entry_types/scrolled/package/spec/editor/controllers/PreviewMessageController-spec.js
- entry_types/scrolled/package/spec/editor/views/EntryPreviewView-spec.js
- entry_types/scrolled/package/spec/frontend/features/scrollPointMessages-spec.js
- entry_types/scrolled/package/spec/support/pageObjects.js
- entry_types/scrolled/package/src/editor/controllers/PreviewMessageController.js
- entry_types/scrolled/package/src/editor/views/EntryPreviewView.js
- entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementDecorator.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EntryDecorator.js
- entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.js
- entry_types/scrolled/package/src/frontend/inlineEditing/scrollPoints.js
If a content element is selected, make sure that it is still visibile
in the viewport after toggling the emulation mode. If no content
element is selected, keep the first content element with positive y
coordinate in the viewport.
REDMINE-17964
> Preserve scroll position when toggling phone preview

- entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
- entry_types/scrolled/package/src/frontend/VideoPlayerControls.js
Recent change caused audio controls to be hidden when not hovering.
REDMINE-17746
> Never hide audio controls

- entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
Was indented to keep navigation open while tooltips are
showing. Caused navigation to remain open when scrolling after
clicking unmute button.
> Do not keep navigation open when focus is within

- entry_types/scrolled/package/src/frontend/MediaInteractionTracking.js
Prevent timeout set by `MediaInteractionTracking` from firing after
the component has been unmounted.
> Prevent state update on unmounted component

- entry_types/scrolled/package/src/frontend/useBoundingClientRect.js
- entry_types/scrolled/package/src/frontend/useMotifAreaState.js
Ensure content/motif area intersection is measured again after padding
has been applied to the content. Othwerwise the backdrop shadow is
visible initially, even if the motif area has zero intersection with
content.
REDMINE-18022
> Do not show scroll position based backdrop shadow initially

- entry_types/scrolled/package/spec/frontend/MotifArea-spec.js
- entry_types/scrolled/package/spec/frontend/useBackgroundFile-spec.js
- entry_types/scrolled/package/src/frontend/useBackgroundFile.js
When an image file is used as both desktop and mobile image and a
motif area is selected for the desktop variant, the mobile variant
will start using the default motif area stored in the file
configuration.
We accept the breaking change since there are no important old entries
yet.
REDMINE-18038
> Do not fall back to file default motif area

- entry_types/scrolled/package/src/frontend/Entry.module.css
- entry_types/scrolled/package/src/frontend/Foreground.js
- entry_types/scrolled/package/src/frontend/Foreground.module.css
- entry_types/scrolled/package/src/frontend/Section.js
Apply padding to foreground of first section to prevent pushing the
backdrop below the navigation bar. If the first section uses a fixed
backdrop, it should also be fixed when first scrolling the page.
REDMINE-18071
> Do not move backdrop when navigation is scrolled out of view

- yarn.lock
Prevent `pageflow-scrolled` from including different version of
`core-js` in bundle then the one included for the `pageflow` main
package.
REDMINE-18156
> Deduplicate core-js in yarn.lock

- package/spec/frontend/media/MediaPool_spec.js
- package/src/frontend/media/MediaPool.js
- package/src/frontend/media/blankSources.js
Use VideoJS `src` method to reset sources to blank sources instead of
setting sources of the media element directly. This ensures the DASH
media player is disposed correctly, preventing it from trying to
access the source buffer after it has already been removed.
We need to pass object with `src`/`type` instead of string to make
sure VideoJS recognizes the data url as supported source.
REDMINE-17807
> Fix "SourceBuffer removed from parent media source" error

- app/assets/stylesheets/pageflow/editor/drop_down_button.scss
- app/assets/stylesheets/pageflow/editor/select_button.scss
- app/assets/stylesheets/pageflow/entries.scss
- app/assets/stylesheets/pageflow/navigation_mobile.scss
- app/assets/stylesheets/pageflow/themes/default/anchors.scss
- app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
- app/assets/stylesheets/pageflow/themes/default/page/anchors.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/classic/info_box.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/shared/menu_bar.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/slim/control_bar.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/slim/info_box.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/slim/quality_menu.scss
- app/assets/stylesheets/pageflow/themes/default/player_controls/waveform/wave.scss
- app/assets/stylesheets/pageflow/ui/forms.scss
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.module.css
- entry_types/scrolled/package/src/frontend/PlayerControls/MenuBarButton.module.css
- entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.module.css
- entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
- entry_types/scrolled/package/src/frontend/thirdPartyConsent/OptOutInfo.module.css
So far `pointer-events: all` was used to re-enable pointer events for
an element inside a `pointer-events: none` parent. The correct way to
reset pointer events is to use `auto`, though. `all` is reserved for
SVG and causes SVG elements to receive pointer events even if
`visibility` is `hidden`. This caused share icons in the hidden
tooltip to be clickable.
Replace all occurences across all CSS files.
REDMINE-18174
[1] https://developer.mozilla.org/de/docs/Web/CSS/pointer-events
> Invisible share links should not be clickable

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/spec/frontend/PlayerContainer-spec.js
- entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/updateObjectPosition.js
- package/spec/frontend/media/media_spec.js
- package/src/frontend/media/MediaPool.js
Crop positions of background files can change when the viewport
resizes. So far player object position could only be updated by
disposing the player and requesting a new one. On mobile resize events
also sometimes happen due to browser chrome being hidden while
scrolling. Replacing the player is too heavy weight in these
cases. Change `MediaPlayer` to update object position of player in
place instead.
REDMINE-18166
> Do not request new player when object position changes

- entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
For unknown reasons, if `touch-action: none` is set on the navigation
bar, tapping somewhere inside the navigation bar, causes weird
rendering glitches when scrolling the page from then on. Especially
when scrolling the page via a flick gesture, once the scroll animation
stops, the page is sometims briefly rendered as if the viewport height
had changed: a white rect appears at the bottom of the page and
covering background images are briefly moved to an incorrect position.
The same effect is visible if scrolling is blocked by preventing
default on `touchmove` instead of applying `touch-action: none`. To
still prevent the mobile navigation from scrolling the page, we force
it to have scroll overflow and use `overscroll-behavior`.
REDMINE-18162
> Fix scroll flickering on Android Chrome

- entry_types/scrolled/package/src/frontend/useMediaMuted.js
Run `useOnUnmuteMedia` in stack triggered by user interaction to ensure audio
playback is permitted. `useEffect` runs deferred.
REDMINE-18173
> Play unmute sound on iOS

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/updatePlayerState.js
When scrolling away from a media element that is playing without sound
while the audio context has not yet been resumed (i.e. auto play is
still forbidden by the browser), the controls switch to paused state,
but the element keeps playing. This can be observed in Chrome before
the first user interaction with the document.
The problem is caused by the fact that `AudioContext#resume` returns a
promise that stays pending when auto play is forbidden.
[`tryResumeIfSuspended`](https://github.com/codevise/pageflow/blob/62b7c1a8304c97d8fef9d5cdcfdeb143ed6159e1/package/src/frontend/mediaPlayer/volumeFading/webAudio.js#L23) in the `volumeFading/webAudio` module
therefore also stays pending. This causes `fadeVolume` to not
resolve. [`fadeOutAndPause`](https://github.com/codevise/pageflow/blob/62b7c1a …
> Ensure muted inline media pauses on deactivation

- entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
Setting `innerHTML` of the `PlayerContainer` to an empty string
apparently also removes all children from the player div that is
stored in the media pool. Removing the child explicitly instead.
REDMINE-18118
> Don't remove media tag when unallocating player in IE 11

- app/assets/stylesheets/pageflow/loading_spinner.scss
- entry_types/paged/app/views/layouts/pageflow_paged/_loading_spinner_inline_script.html.erb
- entry_types/paged/app/views/layouts/pageflow_paged/application.html.erb
- entry_types/paged/app/views/pageflow_paged/editor/entries/_head.html.erb
Before the paged entry type was extracted, the editor used the same
layout as the published entries. Once the paged entries used their own
layout [1], the editor got a separate layout [2] and everything
related to Paged was removed [3]. We missed that the loading spinner
inline script was also needed inside the editor to ensure the preview
could be displayed. Add it back to the paged head editor partial.
We also could have added the rule to an editor stylesheet, but that
would have meant introducing a third place where loading spinner
display is controlled. This way editor and published entry work the
same way.
REDMINE-17738
[1] https://github.com/codevise/pageflow/commit/b0762674c999140021dc725f4445d21b3e72a417#diff-d6c740536eb9bfa6732ef7dfa73df647cae865b6d4a0f7d48ea309ded4c745aa
[2] …
> Fix classic loading spinner preview in editor

- entry_types/scrolled/package/src/editor/models/Chapter.js
- package/spec/editor/collections/ForeignKeySubsetCollection-spec.js
- package/src/editor/collections/ForeignKeySubsetCollection.js
Ensure content elements are removed from `entry.contentElements` Backbone
collection when a chapter is deleted. Before, deleting a chapter already
removed sections and removing a section already removed content elements,
but removal did not cascade across multiple levels.
When new content elements were created afterwards, those received the same
perma ids as the left over content elements causing duplicates to show up
in the preview.
REDMINE-18272
> Cascade model removal through ForeignKeySubsetCollection

- entry_types/scrolled/app/views/pageflow_scrolled/entries/_global_notices.html.erb
- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
- entry_types/scrolled/config/locales/new/global_notices.de.yml
- entry_types/scrolled/config/locales/new/global_notices.en.yml
- entry_types/scrolled/package/src/frontend/globalNotices.module.css
- entry_types/scrolled/package/src/frontend/index.js
IE 11 currently renders the entry, but does not scale backdrop assets
correctly (due to missing `object-fit` support) and renders section
transition incorrectly (due to missing `position sticky` support).
REDMINE-18283
> Display notices for unsupported browser or non-js

- entry_types/scrolled/lib/generators/pageflow_scrolled/install/install_generator.rb
- entry_types/scrolled/package/config/webpack.js
- entry_types/scrolled/package/package.json
- entry_types/scrolled/package/src/frontend/dash.js
- package/spec/frontend/media/MediaPool_spec.js
- package/src/frontend/media/createMediaPlayer.js
- yarn.lock
Replace `videojs-contrib-dash` with `@videojs/https-streaming` which
comes with Video.js by default now. Make `video.js` import resolve to
core variant to allow lazy loading `http-streaming` package only when
HLS is not supported.
Disable Babel compilation of `node_modules` to prevent error of the
form "_typeof is not defined" in Video.js HTTP streaming service
worker that is registered when DASH sources are used.
No longer precompiling `node_modules` means that some ES6 syntax
included in some of the packages will end up in the
bundle. `therubyracer` gem then causes "Use of const in strict mode"
error during SSR. Upgrading the host application to use `mini_racer`
instead fixes the problem.
REDMINE-18311
> Upgrade Scrolled to Video.js 7

- admins/pageflow/user.rb
- app/views/pageflow/admin/initial_passwords/edit.html.erb
- pageflow.gemspec
`trackable` module is no longer enabled by default. Remove columns
from CSV report to stay compatible with new default.
Replace deprecated error messages helper.
REDMINE-18256
> Upgrade to Devise 4.7

- lib/pageflow/user_mixin.rb
- spec/models/pageflow/user_spec.rb
Prevent storing invalid locales which will then cause an exception
when `I18n.locale` is set for user.
REDMINE-18256
> Validate user locale

- entry_types/scrolled/package/src/frontend/polyfills.js
Passing the document `root`, which fixes positive root margin handling
in iframes for Chrome, causes `IntersectionObserver` not to trigger
callback at all in Safari. Without `root` option, Safari still ignores
positive root margins in iframes. Delete the built-in to ensure the
polyfill is loaded instead.
REDMINE-18070
> Fix lazy loading in editor for Safari

- entry_types/scrolled/package/src/contentElements/heading/editor.js
- entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js
Previously used hash function only supported limited range of
characters as input.
REDMINE-18456
> Allow non latin characters in video embed caption

- entry_types/scrolled/config/locales/new/image_rights.de.yml
- entry_types/scrolled/config/locales/new/image_rights.en.yml
- entry_types/scrolled/package/spec/entryState/legalInfo-spec.js
- entry_types/scrolled/package/src/entryState/legalInfo.js
- entry_types/scrolled/package/src/frontend/navigation/LegalInfoMenu.js
- entry_types/scrolled/package/src/frontend/polyfills.js
* Do not display duplicate entries if multiple images have the same
rights strings.
* Only fall back to default rightsif there is an image with an empty
rights string.
* Extract german "Bildrechte" string to translation.
REDMINE-18444
> Improve file rights

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/spec/support/fakeMedia.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
- package/spec/frontend/media/MediaPool_spec.js
- package/src/frontend/media/MediaPool.js
Do not try to remove a media element from the DOM that has already
been allocated by another player. Instead, detach and unwatch player
in `onRelease` callback that can be also invoked by the pool when it
decides to unallocate a player early.
REDMINE-18426
> Handle player unallocated by empty pool

- entry_types/scrolled/package/spec/editor/models/SectionConfiguration-spec.js
- entry_types/scrolled/package/src/editor/models/SectionConfiguration.js
Setting section configuration attributes like `backdropType` or
`backdropImage` also updates the `backdrop` attribute which is read in
frontend code. So far these updates each triggered a save request,
which could lead to race conditions when different Passenger processes
handled these requests concurrently since the first request still
contained an old value for the `backdrop` attribute.
Perform both updates in a single `set` call. It would probably be
better to not store `backdrop` at all and compute it in the structure
hooks. For now, we went with the smaller change, though.
REDMINE-18462
> Do not trigger multiple save requests for backdrop updates

- entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.module.css
Since background color is set to black, we also need to set the text
color to prevent displaying black text on back backgrounds in sections
with black text color.
REDMINE-18528
> Fix embed video opt in text color in inverted section

- entry_types/scrolled/package/src/frontend/MediaPlayer/videojsBase.module.css
VideoJS inserts an iframe which becomes visible due to user agent
styles.
REDMINE-18552
> Hide frame around inline video on iOS 12

- pageflow.gemspec
Had not been noticed before when using gem from an edge branch.
REDMINE-18696
> Include scrolled package shared config in gem

- package/spec/ui/views/ConfigurationEditorView-spec.js
- package/src/ui/views/ConfigurationEditorView.js
Shorthand to let all views/inputs on a tab use a common model.
REDMINE-18761
> Allow passing model to configuration editor tab

- package/src/vendor/backbone.babysitter.js
- package/src/vendor/backbone.js
- package/src/vendor/backbone.marionette.js
- package/src/vendor/cocktail.js
- package/src/vendor/i18n.js
- package/src/vendor/iscroll.js
- package/src/vendor/jquery-ui/index.js
Let external packages re-use the vendored legacy JS libraries without
needing to enable Babel for the node module. Use
`require`/`module.exports` instead.
REDMINE-18761
> Do not use import/export keywords in vendored deps

- .github/workflows/storybook.yml
- entry_types/scrolled/package/.storybook/main.js
Safe navigation operator `?.` in `Consent/index.js` caused storybook
build to fail.
REDMINE-18920
> Transpile pageflow package in scrolled storybook

- entry_types/scrolled/config/locales/new/header_size.de.yml
- entry_types/scrolled/config/locales/new/header_size.en.yml
- entry_types/scrolled/package/src/contentElements/heading/Heading.js
- entry_types/scrolled/package/src/contentElements/heading/editor.js
- entry_types/scrolled/package/src/contentElements/heading/stories.js
- entry_types/scrolled/package/src/frontend/Text.js
- entry_types/scrolled/package/src/frontend/Text.module.css
So far headings in the first section were large, others
small. Introduce medium text size and allow overriding default.
REDMINE-19007
> Make heading text size configurable

- entry_types/scrolled/package/spec/frontend/features/thirdPartyConsent-spec.js
- entry_types/scrolled/package/src/contentElements/dataWrapperChart/frontend.js
- entry_types/scrolled/package/src/contentElements/videoEmbed/frontend.js
- entry_types/scrolled/package/src/frontend/thirdPartyConsent/registerVendors.js
Prevent showing consent UI if entry does not use analytics, only
embeds.
REDMINE-18993
> Use lazy opt-in consent paradigm for scrolled embeds

- entry_types/scrolled/package/spec/contentElements/externalLinkList/frontend/ExternalLink-spec.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
Add default protocol to ensure URLs without a protocol are not
interpreted as relative paths.
REDMINE-18997
> Prevent interpreting external links as relative

- entry_types/scrolled/package/src/editor/views/EditSectionTransitionEffectView.module.css
Pseudo elements are only allowed for elements that can have
children. Chrome supports this against spec.
REDMINE-18891
> Render fade transition check box in Firefox

- entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
- package/spec/ui/views/inputs/UrlInputView-spec.js
- package/src/ui/views/inputs/UrlInputView.js
Do not expect protocols in host strings. This prevents having to
include both http and https versions of a supported host if
`permitHttps` is set to true. Ignore protocols in host names for
backwards compatibility.
REDMINE-19000
> Improve supported host handling in url input

- entry_types/scrolled/config/locales/new/video_embed_poster.de.yml
- entry_types/scrolled/config/locales/new/video_embed_poster.en.yml
- entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js
- entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
Facebook videos do not support displaying automatic posters. Allow
setting one manually.
REDMINE-19167
> Allow defining custom poster for video embeds

- app/helpers/pageflow/page_types_helper.rb
- app/helpers/pageflow/themes_helper.rb
Turn page_types into array since JBuilder
2.11.3 (https://github.com/rails/jbuilder/pull/501) requires
collection to respond to `empty?`, which `Enumerable` does not
provide. See also https://github.com/rails/jbuilder/issues/514
REDMINE-19357
> Fix compatibility with JBuilder 2.11.3

- app/models/pageflow/entry_role_query.rb
- spec/models/pageflow/entry_role_query_spec.rb
Performance issues were particularly noticeable when listing entries
for file reuse.
Use inner join for account memberships instead of left joining both
entry and account memberships. This uses the fact that every user with
an entry membership also has an account membership.
REDMINE-18999
> Prevent full table scan in EntryRoleQuery::Scope

- app/helpers/pageflow/embed_code_helper.rb
`scrolling` attribute is deprecated. Paged entries do not need it
since they hide scroll bars via `overflow: hidden`. For Scrolled
entries it needs to be removed to enable native scrolling.
REDMINE-19063
> Remove scrolling attribute from embed iframe snippet

- entry_types/scrolled/package/src/editor/views/EditSectionTransitionEffectView.js
Now that the default transition is `fadeBg`, when creating a new
section next to a non-full-height section, we want to prevent
displaying the "fade" option as selected. Instead, we want to
highlight the first enabled option "scroll", which acts as a fallback
in this case.
REDMINE-19303
> Do not display disabled transition option as active

- entry_types/scrolled/package/src/frontend/MediaPlayer.module.css
MediaPlayer styles to make player use full height in content element
also applied to text track display elements managed by Video.js.
REDMINE-19196
> Display subtitles at the bottom of the media element

- entry_types/scrolled/package/src/contentElements/iframeEmbed/IframeEmbed.js
- entry_types/scrolled/package/src/contentElements/iframeEmbed/IframeEmbed.module.css
Transformation is not accounted for when computing overflow. So even
if the element does not overflow visually, there are still horizontal
scroll bars. Hide (invisible) overflow of element.
REDMINE-19406
> Prevent scaled iframe element from causing horizontal overflow

- entry_types/paged/packages/pageflow-paged-react/src/loadingSpinner/components/MediaLoadingSpinner.jsx
When the image is blurred we use the medium variant to speed up
loading. If the image is not blurred the quality difference is
noticeable.
REDMINE-19419
> Use large image variant for non-blurred media loading spinner

- entry_types/scrolled/package/.storybook/main.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/ChapterLink.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/Scroller.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/stories.js
- entry_types/scrolled/package/values/breakpoints.module.css
- pageflow.gemspec
Provide reusable breakpoints in
`pageflow-scrolled/values/breakpoints.module.css` that align with the
breakpoints that can be used in theme properties and typography
settings. Use these breakpoints in default navigation widget.
REDMINE-19429
> Align navigation breakpoints with theme breakpoints

- entry_types/scrolled/package/package.json
- yarn.lock
Add react packages Scrolled's devDependencies to
* Fix missing peer dependency warnings
* Ensure packages are installed in development (not just as a side
effect of installing storybook)
* Make used version explicit
REDMINE-19525
> Upgrade React minor version used in development

- entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_theme.json.jbuilder
- entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
`<use xlink:href>` in SVG elements only works with same origin.
REDMINE-19535
> Always use relative paths for custom icons

- entry_types/scrolled/package/spec/entryState/getFileUrlTemplateHost-spec.js
- entry_types/scrolled/package/spec/frontend/dash-spec.js
- entry_types/scrolled/package/src/entryState/getFileUrlTemplateHost.js
- entry_types/scrolled/package/src/entryState/index.js
- entry_types/scrolled/package/src/frontend/dash.js
- entry_types/scrolled/package/src/frontend/index.js
- package/spec/frontend/browser/agent_spec.js
- package/src/frontend/browser/Agent.js
- package/src/frontend/browser/video.js
- package/src/testHelpers/fakeBrowserAgent.js
- package/src/testHelpers/index.js
Android does not play HLS videos for such host names. Since our DASH
source comes first, we can fall back to DASH in this case.
REDMINE-19543
> Load DASH on Android if hls-playlist host contains an underscore

- entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
- entry_types/scrolled/package/src/frontend/Text.module.css
So far, the text block content element specified the margin of its
heading via a rule of the form `.text h2`, which has higher
specificity than the typography rules generated from theme options.
Move margin to `heading-xs` text size rule, which is only used by the
text block content element at the moment and has lower specificity.
REDMINE-19573
> Allow overriding text block heading margins in typography rules

- entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css
Do not apply inline content max width below wide viewport. This
prevents awkward intermediate states on tablets.
REDMINE-19482
> Apply consist max-width to wide elements

- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
`100vh` represents largest viewport [1], which causes menu to exceed
viewport height when browser navigation bar is shown.
[1] https://dev.to/frehner/css-vh-dvh-lvh-svh-and-vw-units-27k4
> Ensure last item of mobile menu is visible on Android

- entry_types/scrolled/package/src/widgets/defaultNavigation/ToggleMuteButton.module.css
`fill: currentColor` is set on the button. Safari evaluates
`currentColor` on the element itself. We thus need to also override
color there.
> Fix unmute icon color in Safari

- app/helpers/pageflow/file_background_images_helper.rb
- app/models/pageflow/entry_at_revision.rb
- app/models/pageflow/image_file_css_background_image_urls.rb
- config/locales/new/highdef_background_images.de.yml
- config/locales/new/highdef_background_images.en.yml
- entry_types/paged/config/initializers/features.rb
- lib/pageflow/file_type.rb
- spec/helpers/pageflow/file_background_images_helper_spec.rb
- spec/support/pageflow/lint/file_type.rb
When using text in images the current compression settings for the
`large` variant lead to sub-optimal results. The higher resolution
images happen to use higher values for the quality parameter.
REDMINE-19692
> Add feature flag to use ultra image variant for paged backgrounds

- app/models/pageflow/video_file.rb
- app/models/pageflow/video_file_url_templates.rb
- config/initializers/paperclip.rb
- entry_types/paged/packages/pageflow-paged-react/src/files/__spec__/selectors-spec.js
- entry_types/paged/packages/pageflow-paged-react/src/files/expandUrls.js
- entry_types/scrolled/package/spec/entryState/useFile-spec.js
- entry_types/scrolled/package/src/entryState/extendFile.js
- spec/models/pageflow/video_file_url_templates_spec.rb
- spec/models/pageflow/zencoder_attachment_spec.rb
Make HLS-SMIL file name configurable and introduce
`:pageflow_hls_qualities` interpolation, which can be used to generate
HLS urls of the form
.../,low,medium,high,fullhd,.mp4.csmil/master.m3u8
The listed qualities correspond to present outputs.
REDMINE-19686
> Support csmil HLS playlists

- app/controllers/pageflow/edit_locks_controller.rb
- spec/controllers/pageflow/edit_locks_controller_spec.rb
For pathologically large entries this copying everything can take so
long that opening the editor no longer works. Add feature flag to at
least restore editor access.
REDMINE-19747
> Allow disabling taking snapshots when acquiring an editor lock

- admins/pageflow/entry.rb
- app/assets/javascripts/pageflow/admin/entries.js
- app/helpers/pageflow/admin/entries_helper.rb
- app/views/admin/entries/_form.html.erb
- app/views/admin/entries/_not_allowed_to_see_entry_types.json.jbuilder
- app/views/admin/entries/entry_type_name_input.html.erb
- app/views/admin/entries/entry_types.json.jbuilder
- app/views/pageflow/admin/entries/_entry_type_name_input.html.erb
- lib/pageflow/configuration.rb
- spec/controllers/admin/entries_controller_spec.rb
- spec/helpers/pageflow/admin/entries_helper_spec.rb
- spec/support/helpers/stub_template_controller_test_helper.rb
* Hide account select when unneeded
* Allow dynamically setting default entry type
* Allow overriding entry type input partial in host application 
REDMINE-19745, REDMINE-19489
> Improve entry new form

- app/assets/stylesheets/pageflow/editor/confirm_encoding.scss
- app/state_machines/pageflow/media_encoding_state_machine.rb
- app/views/pageflow/editor/encoding_confirmations/check.json.jbuilder
- lib/pageflow/configuration.rb
- package/src/editor/controllers/SidebarController.js
- package/src/editor/templates/confirmEncoding.jst
- package/src/editor/views/ConfirmEncodingView.js
- spec/controllers/pageflow/editor/encoding_confirmations_controller_spec.rb
- spec/pageflow/configuration_spec.rb
- spec/state_machines/pageflow/media_encoding_state_machine_examples.rb
- spec/support/helpers/zencoder_api_double.rb
Let host application decide on a per-file basis whether encoding needs
to be confirmed by the user.
REDMINE-19483
> Allow skipping encoding confirmation

- entry_types/scrolled/package/src/testHelpers/rendering.js
Exporting the test helpers from the package in #1818, caused the
storybook to raise an error of the form "Could not auto-detect a React
renderer" during rendering. The Percy related actions failed silently.
> Fix storybook

- app/models/pageflow/customized_theme.rb
- app/models/pageflow/entry_at_revision.rb
- app/models/pageflow/revision.rb
- spec/pageflow/theme_customizations_spec.rb
So far, we passed a `PublishedEntry` when actually computing theme
options for a published entry, but only passed an `Entry` when
previewing a theme customization. We now always pass an `Entry`.
To allow having the transformation depend on the actual theme, we
change the signature of the lambda to also take a theme option. This
is safer than always passing a `PublishedEntry` since calling
`PublishedEntry.theme` in the transform leads to a stack overflow.
REDMINE-17625
> Pass consistent arguments when transforming theme options

- entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
We need to find a good alternative to the fixed space before headings
in the first section. Since some entries rely on the space, though, we
cannot simply remove it.
At least when the cards are used, we know that we do not want to add a
padding to the card. So we start by fixing this case as a special
case.
REDMINE-19912
> Remove space before heading in cards appearance

- app/assets/stylesheets/pageflow/page.scss
Addition of `pointer-events: none` dates back to very early commit that claims to improve non-js functionality of video page. Since lazy loading has been added since then, video pages do not work without js anyway.
Enabling pointer events makes content accessible without otherwise altering behavior of the pages in any noticeable way.
REDMINE-19986
> Ensure scroller content is accessible via OS X Spoken Content

- entry_types/scrolled/package/src/frontend/EditableText.js
- entry_types/scrolled/package/src/frontend/EditableText.module.css
Slate sets `white-space: pre-wrap` as an inline style. Outside the editor, we need to set it ourselves to ensure line breaks take effect.
REDMINE-19967
> Ensure soft breaks are visible outside editor

- entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
In #1867 we ensured that the `lang` attribute on the `html` tag is set based on the entry's locale in the editor. By switching the locale for the whole seed template, we also made inline editing help texts and prompts use the entry locale. Only set `lang` attribute based on entry locale instead.
REDMINE-19967
> Ensure inline editing help texts/prompts use user locale

- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
Otherwise importing images from editor js results in paths that are missing the `/packs` prefix.
REDMINE-19985
> Also set Webpack public path for editor JS.

- entry_types/scrolled/package/spec/frontend/VhFix-spec.js
- entry_types/scrolled/package/src/frontend/Content.js
- entry_types/scrolled/package/src/frontend/Fullscreen.module.css
- entry_types/scrolled/package/src/frontend/VhFix.js
Prevent backdrop from staying to small once in-app browsers (e.g. Twitter browser) hides its toolbars on scroll.
REDMINE-20011
> Ensure backdrop covers viewport in iOS in-app browers

- .github/workflows/storybook.yml
- .github/workflows/tests.yml
`actions/setup-ruby` started raising error:
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6 not found
> Migrate to supported setup-ruby action

- entry_types/scrolled/package/src/contentElements/heading/Heading.js
- entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
- entry_types/scrolled/package/src/contentElements/heading/editor.js
The automatic padding for headings in first sections keeps confusing users. Still, we cannot simply remove it without risking breaking existing entries. We therefore add a new default config which turns it off for new headings. Since we expect to add some sort of margin settings for all content element types at some point, we try to name the property in a way that we can continue to use once we introduce this concept.
REDMINE-20084
> Disable top padding for new headings

- app/assets/stylesheets/pageflow/themes/default/page.scss
assets:precompile returned an error:
** Execute assets:precompile
rake aborted!
Sass::SyntaxError: Invalid CSS after "...or page content": expected selector or at-rule, was "$page-content-f..." /usr/local/bundle/gems/pageflow-15.7.1/app/assets/stylesheets/pageflow/themes/default/page.scss:15 /usr/local/bundle/gems/pageflow-15.7.1/app/assets/stylesheets/pageflow/themes/default/base.scss:22 /usr/local/bundle/gems/pageflow-15.7.1/app/assets/stylesheets/pageflow/themes/default.scss:1 /usr/local/bundle/gems/sass-3.7.4/lib/sass/scss/parser.rb:1308:in `expected'
After investigation i found that a missing semicolon caused the issue.
> Missing semicolon in themes/default/page.scss

- package/spec/frontend/Consent_spec.js
- package/src/frontend/Consent/index.js
Using this paradigm causes vendors to be accepted unless the opt-out cookie is present.
REDMINE-19544
> Display opt-out vendors as accepted by default on privacy page

- .github/workflows/reusable-workflow-rspec.yml
Can be used in plugin repositories to limit duplication.
REDMINE-20103
> Add reusable GitHub workflow to run RSpec tests

- entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
* Also apply to desktop layout.
* Rename to align naming with other progress bar related properties.
* Reference correct name in theme docs.
REDMINE-20108
> Improve theme property for default navigation progress bar height

- entry_types/scrolled/package/src/frontend/Widget.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
Pass props whether navigation is expanded or mobile menu is open. Can
be used to build custom footers.
REDMINE-20108
> Add widget slot to default navigation

- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
Hover effect barely takes effect on touch devices. Use separator lines
to be consistent with desktop chapter list.
REDMINE-20108
> Simplify borders in default navigation mobile chapter menu

- app/models/pageflow/theming.rb
- spec/models/pageflow/widget_spec.rb
Was meant to ensure that polymorphic associations keep working. This
only works for `belongs_to` associations, though, not for
`has_many`. Moreover, `Widget` references `EntryTemplate` anyway - not
`Theming`/`Site`. Plugins that use `Theming` will need to be migrated.
REDMINE-20103, REDMINE-20090
> Remove Theming alias for Site

- app/views/admin/accounts/_form.html.erb
- config/locales/new/multiple_sites.de.yml
- config/locales/new/multiple_sites.en.yml
Extracted fields have moved again to site admin. The original move is
long enough ago now to no longer warrant the hint.
REDMINE-20103, REDMINE-20090
> Remove entry template from account form

- vendor/assets/javascripts/iscroll.js
Both Edge 107 and Chrome 109 on Microsoft Surface Laptio 1 with
Windows 10 Pro did not react to touch events. This is caused by
iScrolls detecting touch as disabled on these platforms (via
`'ontouchstart' in window`) even though touch events are fired when
the user interacts with the touch screen.
On Android and iOS (where touch already is detected correctly) iScroll
registers both mouse and touch event handlers and tracks which kind of
event initiated the scroll to ignore the others. We therefore remove
touch feature detection altogether and always register touch event
handlers.
On platforms that really do not have touch events, those events should
then just never fire.
REDMINE-20117
> Fix scrolling classic page content on Windows 10 with touch screen

- app/models/pageflow/image_file.rb
- spec/models/pageflow/image_file_spec.rb
Especially for small images with extreme aspect ratios, this can lead to images which exceed limits and cause errors of the form:
convert-im6.q16: width or height exceeds limit
For example, a 1000x10 image scaled to cover 1024x1024 a rect leads to an image that is 102400 pixels wide.
Instead only scale panorama images if their dimensions exceed the size of the box that we want to cover in both dimensions.
To be able to use image dimensions to define style geometry, we need to detect width and height before post processing starts.
REDMINE-20147
> Do not scale images up when creating panorama styles

- package/src/frontend/media/MediaPool.js
Mobile browsers only allow playing videos and audios with sound, when the play call is triggered directly via a user
interaction (e.g. handling a click event). Same goes for unmuting an already playing muted video or audio element.
Once a video or audio element has been unmuted like that, we can pause and resume also outside of a user interaction (e.g. based on a firing intersection observer). Media elements stay "blessed" like this, even when we change the source.
To allow autoplaying videos and audios with sound on mobile browsers, we keep a pool of media elements that we unmute once the user clicks the unmute button. We then reuse ("allocate") those players whenever we want to play video or audio.
At least on iOS 15.4.1 and 16.3 setting `unmute` to `false` only has this blessing effect …
> Improve blessing media elements for iOS

- lib/pageflow/seeds.rb
- spec/pageflow/seeds_spec.rb
Default behavior changes to adding empty string text to every page of a seeded paged entry. This makes it a bit more straightforward to spot where text should go.
Every page will contain the same text after seeding.
REDMINE-20135
> Allow seeding text to paged entries

- entry_types/scrolled/config/locales/new/counter.de.yml
- entry_types/scrolled/config/locales/new/counter.en.yml
- entry_types/scrolled/config/locales/new/quote.de.yml
- entry_types/scrolled/config/locales/new/quote.en.yml
- entry_types/scrolled/doc/creating_content_element_types.md
- entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
- entry_types/scrolled/doc/creating_themes/custom_typography.md
- entry_types/scrolled/package/documentation.yml
- entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
- entry_types/scrolled/package/spec/editor/views/inputs/ColorSelectInputView-spec.js
- entry_types/scrolled/package/spec/editor/views/inputs/ListboxInputView-spec.js
- entry_types/scrolled/package/spec/frontend/paletteColor-spec.js
- entry_types/scrolled/package/src/contentElements/counter/Counter.js
- entry_types/scrolled/package/src/contentElements/counter/Counter.module.css
- entry_types/scrolled/package/src/contentElements/counter/editor.js
- entry_types/scrolled/package/src/contentElements/counter/stories.js
- entry_types/scrolled/package/src/contentElements/quote/Quote.js
- entry_types/scrolled/package/src/contentElements/quote/editor.js
- entry_types/scrolled/package/src/contentElements/quote/stories.js
- entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
- entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
- entry_types/scrolled/package/src/editor/views/inputs/ColorSelectInputView.js
- entry_types/scrolled/package/src/editor/views/inputs/ColorSelectInputView.module.css
- entry_types/scrolled/package/src/editor/views/inputs/ListboxInputView.js
- entry_types/scrolled/package/src/frontend/index.js
- entry_types/scrolled/package/src/frontend/paletteColor.js
Let themes define color properties of the form `palette_color_*` which can be used by content elements in color settings to let users pick a color from a predefined palette.
Quotes and counters are the first elements to support palette colors.
REDMINE-20218
> Introduce palettes

- entry_types/scrolled/package/src/frontend/Section.module.css
- entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
- entry_types/scrolled/package/values/colors.module.css
Can be used to apply `-webkit-text-stroke` based on the current text color when `color` (and thus `currentColor`) has been set to `transparent`.
REDMINE-20162
> Make content text color available in custom property

- entry_types/scrolled/config/locales/new/counter.de.yml
- entry_types/scrolled/config/locales/new/counter.en.yml
- entry_types/scrolled/package/src/contentElements/counter/Counter.js
- entry_types/scrolled/package/src/contentElements/counter/editor.js
- entry_types/scrolled/package/src/frontend/Text.module.css
Ensure 9-digit numbers with a unit still fit mobile viewport and
left/right aligned inline column without wrapping.
REDMINE-20171
> Add even smaller counter text size

- entry_types/scrolled/package/spec/frontend/useDelayedBoolean-spec.js
- entry_types/scrolled/package/spec/frontend/useSectionLifecycle-spec.js
- entry_types/scrolled/package/src/frontend/Section.js
- entry_types/scrolled/package/src/frontend/useDelayedBoolean.js
- entry_types/scrolled/package/src/frontend/useScrollPositionLifecycle.js
We want to start background videos in fade sections only once the section becomes active to prevent missing the beginning.
Invoke `onVisible` only once the section is active for fade section. Invoke `onInvisible` with a short delay once the section is no longer active to prevent pausing background videos while the fade transition is still in progress.
REDMINE-20230
> Improve onVisible/onInvisible callbacks

- entry_types/scrolled/package/spec/frontend/useSectionLifecycle-spec.js
- entry_types/scrolled/package/src/frontend/Section.js
- entry_types/scrolled/package/src/frontend/useScrollPositionLifecycle.js
The previous attempt to fix the issue in #1947 did not take into account that sections that enter with a fade transition can still exit with a different transition. So using the `isActive` probe to determine `isVisible` does not work. Instead we adapt the `isVisible` intersection observer to apply a root margin. We then need to ensure that `onVisible` and `onActivate` are never called out of order even if the intersection observers fire in different orders.
This is important since we mute and play videos in `onVisible` and unmute in `onActivate`. Videos might otherwise stay muted if we get the execution order wrong.
REDMINE-20230
> Improve onVisible/onInvisible callbacks for fade sections

- app/models/pageflow/entries_feed.rb
- app/views/pageflow/feeds/index.atom.builder
- spec/controllers/pageflow/feeds_controller_spec.rb
Use custom_feed_url as self and canonical_entry_url_prefix as alternate. This accommodates setups where feeds are served from a location that proxies to the site.
REDMINE-20013
> Use custom site urls in feed

- doc/setting_up_external_services.md
aws s3 now needs json instead of xml CORS config. I think this sould be correct?
> Make CORS config json

- entry_types/scrolled/package/spec/contentElements/quote/isBlank-spec.js
- entry_types/scrolled/package/src/contentElements/quote/Quote.js
- entry_types/scrolled/package/src/contentElements/quote/isBlank.js
Once some text had been entered and removed, hiding the line already worked. Also detect initial empty array as blank.
REDMINE-20294
> Hide empty attribution line of quote element

- entry_types/scrolled/package/spec/collections-spec.js
- entry_types/scrolled/package/spec/entryState/legalInfo-spec.js
- entry_types/scrolled/package/src/collections.js
- entry_types/scrolled/package/src/entryState/EntryStateProvider.js
- entry_types/scrolled/package/src/entryState/legalInfo.js
Previously only rights of image files where displayed. To do this, we need to extract rights information from all files collections. Add a new `useMultipleEntryStateCollectionItems` hook based on a new `createMultipleItemsSelector`, which can be used to extract multiple collections at once and only re-render when an item of one of the collection changes.
REDMINE-20295
> Display rights of all files in credits box

- app/models/pageflow/widget.rb
- lib/pageflow/widget_types.rb
- spec/controllers/pageflow/editor/widgets_controller_spec.rb
- spec/models/pageflow/widget_spec.rb
When a widget type is defined within a feature, revisions and entry templates still may contain widgets of that type once the feature has been disabled.
So far, we assigned a null widget type in that case, which rendered the empty string. In published scrolled entries, these widgets then got filtered out when compiling seed data since they did not match the special `:react` insert point [1]. In the editor, these widgets were still included in collections, which led to JS errors when trying to look up the editor or frontend JS counter part of a widget. Here we fail loudly, when a widget type is not defined to make integration errors between JS and Ruby easy to spot.
While we still want to support widgets with null widget types for placeholders, we can skip widgets that do not have a …
> Filter out widgets of unknown widget types

- app/models/pageflow/widget.rb
- spec/models/pageflow/widget_spec.rb
In #1961 we started filtering out widgets with unknown type name. We do not want to filter out widgets with empty type name, though. Otherwise there is no way to turn off a default widget.
REDMINE-20207
> Allow turning default widgets off

- entry_types/scrolled/package/spec/frontend/Layout-spec.js
- entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
- entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css
Since one uses custom margin and one doesn't, they cannot be in one box. Multiple sticky boxes inside a single group do not interact correctly, we create a new group.
REDMINE-20325
> Prevent sticky gallery and sticky image from overlapping

- entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
Ensure consistent display in editor and published entry. Slate detects RTL text and sets a dir attribute on text nodes. Outside of the editor text was still always LTR.
This is just a first step, with many more layout issues in right-to-left mode remaining.
REDMINE-20378
> Set text direction attribute for scrolled entries

- entry_types/scrolled/package/spec/support/__spec__/stories-spec.js
- entry_types/scrolled/package/spec/support/stories.js
- entry_types/scrolled/package/src/contentElements/counter/stories.js
- entry_types/scrolled/package/src/contentElements/quote/stories.js
- entry_types/scrolled/package/src/contentElements/textBlock/stories.js
So far theme properties in stories were set directly as keys below `themeOptions.properties`. In real themes, a scope like `root` or `defaultNavigation` needs to be inserted as an intermediate level.
To allow testing these scopes in stories, we now generate a full style tag with scope rules instead of only setting the properties as inline styles on a wrapper div.
REDMINE-20411
> Support scopes in storybook theme properties

- entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
- entry_types/scrolled/package/src/contentElements/heading/Heading.js
- entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
- entry_types/scrolled/package/src/contentElements/heading/stories.js
- entry_types/scrolled/package/src/contentElements/textBlock/stories.js
- entry_types/scrolled/package/src/frontend/EditableText.js
- entry_types/scrolled/package/src/frontend/EditableText.module.css
Introduce `headings` scope to be able to restrict the existing `darkContentTextColor` and `lightContentTextColor`.
REDMINE-20411
> Allow changing light and dark text color of headings

- entry_types/scrolled/lib/tasks/pageflow_scrolled/storybook.rake
- entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
Ensure content probe element has correct width. Caused two column layout to move content down even if motif fits nexts to cotnent.
This went unnoticed since storybook used v2 frontend. Switch storybook back to v1 frontend since this what is still used in production.
REDMINE-20384
> Fix two column motif area content measuring

- entry_types/scrolled/package/src/frontend/utils.module.css
We already adapted the clip-path before to prevent line artifacts from showing up between sections. Now there appear to be cases where the fallback `clip` property causes this problem as well. Since it was only meant to support IE 11, which we no longer support anyway, the fallback can be removed.
REDMINE-20413
> Remove legacy clip for revealed sections

- package/spec/ui/views/inputs/ColorInputView-spec.js
- package/src/ui/views/inputs/ColorInputView.js
When pausing after typing the first three digits of a color code (e.g., #abc), minicolors already updates the value with a normalized representation (e.g., #aabbcc). Before, the `change` handler updated the model, which in turn triggered the `load` method, causing the value of the input to be updated. This prevented the user from finishing typing the full color code.
REDMINE-20413
> Prevent normalizing color input too early

- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
When scaling items, the background sometimes becomes visible at the borders of the image due to rendering rounding errors. Apply content surface color only to details below image.
REDMINE-20413
> Prevent white lines around external link image

- entry_types/scrolled/package/src/frontend/__stories__/floatingAndSelfClearing-stories.js
- entry_types/scrolled/package/src/frontend/layouts/Center.module.css
When an element is inlined, but follows smaller side-by-side floated elements that are not yet inlined, we need to make sure that the inlined element is cleared to save it from getting smashed between the two floated elements.
REDMINE-20384
> Clear inlined float

- entry_types/scrolled/package/spec/frontend/EditableText-spec.js
- entry_types/scrolled/package/src/contentElements/textBlock/stories.js
- entry_types/scrolled/package/src/frontend/EditableText.js
Prevent collapsing single space leafs between formatted words. Prevent empty text blocks from collapsing.
REDMINE-20413
fixes #1967
> Make text block spacing more consistent between editor and published entry

- app/controllers/pageflow/entries_controller.rb
- lib/pageflow/configuration.rb
- spec/requests/pageflow/entries_show_request_spec.rb
- spec/support/pageflow/global_config_api_test_helper.rb
Allow including a `Cache-Control` header in the response for published
entries. Skip for password protected entries to prevent leaking
protected content into public caches.
REDMINE-20428
> Add public_entry_cache_control_header config option 

- .github/workflows/tests.yml
- Gemfile
- entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
- entry_types/scrolled/lib/generators/pageflow_scrolled/install/install_generator.rb
- entry_types/scrolled/lib/pageflow_scrolled/additional_seed_data.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/chapters_controller_spec.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/content_elements_controller_spec.rb
- entry_types/scrolled/spec/controllers/pageflow_scrolled/editor/sections_controller_spec.rb
- entry_types/scrolled/spec/spec_helper.rb
- entry_types/scrolled/spec/support/config/webpacker.rb
- package/config/webpack5.js
- pageflow.gemspec
- spec/support/pageflow/dummy/app.rb
- spec/support/pageflow/dummy/rails_template.rb
> Fix scrolled specs for Rails 6

- .github/workflows/tests.yml
- doc/creating_entry_types.md
- entry_types/paged/spec/controllers/pageflow_paged/editor/entries_controller_spec.rb
- entry_types/paged/spec/controllers/pageflow_paged/entries_controller_spec.rb
> Fix paged specs for Rails 6

- entry_types/scrolled/package/spec/editor/models/Chapter-spec.js
- entry_types/scrolled/package/spec/editor/models/Section-spec.js
- entry_types/scrolled/package/src/editor/models/Chapter.js
- entry_types/scrolled/package/src/editor/models/Section.js
- entry_types/scrolled/package/src/editor/views/SectionItemView.js
- package/spec/editor/collections/ForeignKeySubsetCollection-spec.js
- package/src/editor/collections/ForeignKeySubsetCollection.js
> Improve transition display in outline

- entry_types/scrolled/package/src/frontend/focusOutline.module.css
Recently changed to prevent display in editor UI. Caused rule to disable focus rect after non-keyboard input to have to low specificity.
> Fix hiding focus outline

- .github/workflows/reusable-workflow-rspec.yml
Set `PAGEFLOW_DEPENDENCIES` environment variable to `experimental` to signal that Pageflow should be installed from edge branch. This will let us experiment with different upgraded dependencies without needing to change plugin code.
REDMINE-19438
> Run plugin specs in reusable workflow against Rails 6.1

- config/initializers/paperclip.rb
- entry_types/paged/lib/pageflow_paged/engine.rb
- entry_types/scrolled/lib/pageflow_scrolled/engine.rb
- lib/pageflow/engine.rb
- lib/pageflow/global_config_api.rb
- spec/pageflow/global_config_api_spec.rb
- spec/pageflow/news_item_api_spec.rb
- spec/support/pageflow-support.gemspec
- spec/support/pageflow/dummy/app.rb
- spec/support/pageflow/dummy/rails_template.rb
> Fix Zeitwerk compatibility

- entry_types/scrolled/package/src/contentElements/quote/Quote.js
- entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
- entry_types/scrolled/package/src/contentElements/quote/editor.js
- entry_types/scrolled/package/src/contentElements/quote/stories.js
So far quote design was only controlled via theme options. We now allow using quotes with different designs side by side via theme defined content element variants.
REDMINE-20380
> Let themes use quote variant with centered quote mark

- app/models/concerns/pageflow/reusable_file.rb
- app/models/pageflow/membership.rb
> Fix Active Record errors deprecation warning

- Gemfile
- entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
- entry_types/scrolled/lib/generators/pageflow_scrolled/install/install_generator.rb
- entry_types/scrolled/spec/support/config/webpacker.rb
- pageflow.gemspec
We plan to eventually drop support for Webpacker. But until the Rails 6 migration is finished, we aim to support both.
Decouple from experimental Rails version environment variable and detect Shakapacker global instead.
Enhance install generator to create required PostCSS config. which is no longer generated by Shalapacker's install generator.
REDMINE-19438
> Support both Webpacker and Shakapacker

- entry_types/scrolled/app/helpers/pageflow_scrolled/react_server_side_rendering_helper.rb
> Fix SSR webpack-dev-server client code removal for Webpack 5

- entry_types/scrolled/config/locales/new/portrait_inline_video.de.yml
- entry_types/scrolled/config/locales/new/portrait_inline_video.en.yml
- entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
- entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
We support portrait alternatives for inline images and backdrop
videos/images. Extend feature to inline videos.
REDMINE-20470
> Allow setting portrait version for inline videos

- README.md
- lib/generators/pageflow/resque/templates/resque.rake
- lib/generators/pageflow/resque/templates/resque.rb
- lib/generators/pageflow/routes/routes_generator.rb
- pageflow.gemspec
- spec/generators/pageflow/routes/routes_generator_spec.rb
- spec/support/pageflow-support.gemspec
> Update resque-scheduler for Ruby 3 support

- .github/workflows/tests.yml
- Gemfile
- app/controllers/pageflow/entries_controller.rb
- app/helpers/pageflow/revision_file_helper.rb
- app/helpers/pageflow/social_share_helper.rb
- app/models/concerns/pageflow/uploadable_file.rb
- entry_types/paged/spec/support/config/database_cleaner.rb
- entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
- entry_types/scrolled/lib/pageflow_scrolled/web_app_manifest.rb
- entry_types/scrolled/spec/support/config/database_cleaner.rb
- pageflow.gemspec
- spec/helpers/pageflow/revision_file_helper_spec.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
- spec/support/config/database_cleaner.rb
- spec/support/helpers/stub_template_in_helper_specs.rb
- spec/support/pageflow-support.gemspec
- spec/support/pageflow/dummy/app.rb
- spec/support/pageflow/dummy/config/pageflow.rb
- spec/support/pageflow/dummy/rails_template.rb
> Rails 7.1 support

- lib/pageflow/paperclip_processors/webp.rb
- spec/pageflow/paperclip_processors/webp_spec.rb
vips raises `smartcrop: bad extract area` error when image is smaller than cropped size and only sclaing down is allowed. In fact, we want to scale the image up, when using a cropping geometry.
REDMINE-20473
> Relax size option when cropping in webp processor

- app/models/pageflow/entry.rb
- spec/models/pageflow/entry_spec.rb
- spec/models/pageflow/revision_spec.rb
This enables an edge-case where the account of an example entry is changed transiently before creating a theme customization preview. Make sure feature flags of the account are taken into account correctly.
Generally, this should be an improvement since draft and published revisions no longer need to look up there entries in a separate query.
REDMINE-20474
> Set inverse of draft and published_revision associations on entry

- entry_types/scrolled/package/src/frontend/FullscreenViewer/index.module.css
Since the fullscreen root element lies outside of the main content element, the normal font rule does not apply.
> Use theme entry font for captions of fullscreen image galleries

- spec/support/pageflow/dummy/config/pageflow.rb
The storybook GitHub action sets the `S3_*` environment variables to use example files from an S3 bucket. Leave Paperclip config untouched if these variables have been set.
> Do not force local Paperclip storage in storybook seeds

- entry_types/scrolled/lib/generators/pageflow_scrolled/install/install_generator.rb
- entry_types/scrolled/package/config/webpack.js
- entry_types/scrolled/package/widgets-server.js
Implicitly define packs via pageflow-scrolled/config. Allow importing all widget for SSR.
* Remove `defaultNavigation.js` and `consentBar.js` from `app/javascript/packs/pageflow-scrolled/widgets`
* Import `pageflow-scrolled/widgets-server` instead of `pageflow-scrolled/widgets/defaultNavigation` and `pageflow-scrolled/widgets/consentBar` in `app/javascript/packs/pageflow-scrolled-server.js`
REDMINE-20093
> Decouple host application from scrolled widget packs

- app/models/pageflow/account.rb
- app/models/pageflow/entry.rb
- app/models/pageflow/revision.rb
- app/models/pageflow/site.rb
- lib/pageflow/user_mixin.rb
Active Admin 3.2 [1] calls `ransackable_associations` without passing an auth object.
[1] https://github.com/activeadmin/activeadmin/pull/8164
> Do not require auth object for ransackable_* methods

- app/helpers/pageflow/page_types_helper.rb
- spec/helpers/pageflow/page_types_helper_spec.rb
Rails 7 no longer allows to set instance variables via render locals [1]. Since `RevisionFileHelper#find_file_in_entry` depends on a `@entry` instance variable being set, we need to set in on the view object ourselves.
REDMINE-20487
[1] https://github.com/rails/rails/pull/41464
> Set entry instance variable when rendering page type templates

- entry_types/paged/app/controllers/pageflow_paged/entries_controller.rb
- entry_types/paged/spec/controllers/pageflow_paged/entries_controller_spec.rb
Do not raise exception when page parameter refers to unknown page.
> Fall back to entry when share page is missing

- entry_types/scrolled/package/spec/frontend/features/backdropAnimationEffects-spec.js
- entry_types/scrolled/package/src/frontend/v1/Backdrop/Effects.js
- spec/support/pageflow/dummy/rails_template.rb
> Prevent gap in background with parallax effect

- entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
- entry_types/scrolled/package/src/contentElements/quote/stories.js
First line might start further on the right. We cannot just position the hanging opening quote relative to the bounding box of the quote.
> Fix hanging quote position in center-ragged layout

- entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/watchPlayer.js
- package/src/frontend/media/MediaPool.js
> Improve media events

- package/spec/frontend/media/MediaPool_spec.js
- package/src/frontend/VideoPlayer/mediaEvents.js
- package/src/frontend/media/MediaPool.js
When a player is unallocated, we reset src to a blank media file via a placeholder data url and pause the player. The player still triggers timeupdate and pause events that we want to turn into media events. We do not want to report the data url as file name, since analytics integrations rely on stable file names. We thus store the previous src and use that wehn reporting the remaining events.
REDMINE-20591
> Store previous src for media event file names

- entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
- entry_types/scrolled/lib/pageflow_scrolled/additional_packs.rb
- entry_types/scrolled/spec/helpers/pageflow_scrolled/packs_helper_spec.rb
Core editor styles are inserted as inline style tags via `rollup-plugin-postcss` which relies on `style-inject`.
For additional editor packs in the host application, this mechanism does not work with Shakapacker's default setup. We thus add an option to also add links to additional stylesheet packs.
REDMINE-20374
> Allow registering additional editor packs with stylesheets

- entry_types/scrolled/package/src/contentElements/imageGallery/useIntersectionObserver.js
Safari (tested with 17.3) also triggers the observer callback for children whose `intersectionRatio` is below the threshold. This only happens inside the editor iframe. In the preview or published entries, the behavior matches Chrome and Firefox.
We need to double check `intersectionRatio` ourselves to prevent invoking the `onVisibleIndexChange` callback for all of the children, which leads to a broken image gallery.
REDMINE-20635
> Fix image gallery scrolling in editor on Safari

- entry_types/scrolled/package/src/frontend/Section.js
- entry_types/scrolled/package/src/widgets/textInlineFileRights/TextInlineFileRights.js
- entry_types/scrolled/package/src/widgets/textInlineFileRights/TextInlineFileRights.module.css
* Hide type prefixes if there is only a single item
* Add copyright sign
* Add background to section rights for better readability
`BackgroundColorProvider` needs to be pulled up to make `useDarkBackground` usable in inline rights widgets.
REDMINE-20689
> Improve text inline file rights

- entry_types/scrolled/config/locales/new/nav-palette-color.de.yml
- entry_types/scrolled/config/locales/new/nav-palette-color.en.yml
- entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
- entry_types/scrolled/package/spec/widgets/defaultNavigation/Defaultnavigation-spec.js
- entry_types/scrolled/package/src/editor/config.js
- entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
- package/spec/editor/views/EditWidgetView-spec.js
- package/src/editor/controllers/SidebarController.js
- package/src/editor/views/EditWidgetView.js
> Accent color palettes for default navigation

- admins/pageflow/sites.rb
- app/models/pageflow/account.rb
- app/models/pageflow/site.rb
- spec/controllers/admin/accounts_controller_spec.rb
- spec/controllers/admin/sites_controller_spec.rb
- spec/models/pageflow/account_spec.rb
This causes the permalink field to be displayed when creating or renaming entries.
REDMINE-19973
> Create default permalink directory for new sites

- app/models/pageflow/draft_entry.rb
- app/models/pageflow/entry_translation_group.rb
- app/models/pageflow/published_entry.rb
- entry_types/scrolled/app/helpers/pageflow_scrolled/entry_json_seed_helper.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry_translations.json.jbuilder
- entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
- spec/factories/published_entries.rb
- spec/models/pageflow/draft_entry_spec.rb
- spec/models/pageflow/published_entry_spec.rb
Also list translations that have been published with noindex. Keep filtering those out in hreflang meta tags, but let users switch between translations even if a translation is excluded from search engine indexes.
For entries that have been published with password protection, also list password protected translations. We still want to filter out password protected translations in publicly visible entries to allow temporarily publishing a translation (e.g., for proof reading) without having it show up in already published content. Still, if all entries of a translation group are supposed to be published with password protection, we still want to let users take advantage of the translations menu feature.
REDMINE-20740
> Make filtering of entry translations menu less restrictive

- app/helpers/pageflow/social_share_helper.rb
- app/models/pageflow/image_file.rb
- spec/helpers/pageflow/social_share_helper_spec.rb
- spec/models/pageflow/image_file_spec.rb
webp support among social appears to still be patchy.
REDMINE-20770
> Always use jpg for social share images

- app/helpers/pageflow/widgets_helper.rb
- entry_types/scrolled/package/spec/entryState/widgets-spec.js
- entry_types/scrolled/package/src/entryState/watchCollections.js
- package/spec/editor/api/WidgetTypes-spec.js
- package/spec/editor/collections/widgetsCollection-spec.js
- package/src/editor/api/WidgetType.js
- package/src/editor/collections/WidgetsCollection.js
- package/src/testHelpers/factories.js
- spec/helpers/pageflow/widgets_helper_spec.rb
Align with seed of published entries. Otherwise this causes problems when a template based widgets uses a role that is also used by Pageflow Scrolled since there is then no component to render it.
REDMINE-20765
> Do not sync non-react widgets to scrolled state in editor

- app/helpers/pageflow/entries_helper.rb
- entry_types/scrolled/package/spec/widgets/defaultNavigation/LegalInfoLink-spec.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/LegalInfoLink.js
- spec/helpers/pageflow/entries_helper_spec.rb
This is an ugly workaround to allow triggering a global function that displays a consent layer. This wants to be an official JS API instead someday. But since Pageflow itself currently does not have a concept of external consent, today is not that day.
REDMINE-20765
> Allow opening external privacy settings via privacy link

- entry_types/scrolled/package/src/widgets/defaultNavigation/Scroller.module.css
On some machines setting `scrollLeft` does not work on containers with no pointer-events. Switching overflow to scroll works around the problem. Use CSS to prevent scroll bars showing up.
REDMINE-20780
> Fix chapter scroller issue on Chrome 126 on OS X

- entry_types/scrolled/package/spec/frontend/features/backdropAnimationEffects-spec.js
- entry_types/scrolled/package/spec/frontend/v1/Backdrop/Effects-spec.js
- entry_types/scrolled/package/spec/support/matchMediaStub.js
- entry_types/scrolled/package/src/frontend/SectionViewTimelineProvider.js
- entry_types/scrolled/package/src/frontend/prefersReducedMotion.js
- entry_types/scrolled/package/src/frontend/v1/Backdrop/Effects.js
Disable scroll parallax and autozoom if the userhas enabled a setting on their device to minimize the amount of non-essential motion.
> Honor user's reduced motion preference for backdrop animations

- entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry.json.jbuilder
- entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
So far, we passed the template object which happened to respond to `params` just like `request`.
> Pass real request object to additional seed callable

- app/helpers/pageflow/entries_helper.rb
Workaround for cases where we want to have a privacy link and a separate link to trigger a consent layer. This allowsto abuse the copyright link as a way to open the consent layer.
REDMINE-20765
> Allow using javascript scheme for all credit box links

- entry_types/scrolled/package/spec/frontend/features/backdropAnimationEffects-spec.js
- entry_types/scrolled/package/spec/frontend/v1/Backdrop/Effects-spec.js
- entry_types/scrolled/package/src/frontend/Backdrop.module.css
- entry_types/scrolled/package/src/frontend/v1/Backdrop/Effects.js
- entry_types/scrolled/package/src/frontend/v1/Backdrop/Effects.module.css
When applying the auto-zoom effect, Chrome sometimes stopped painting the backdrop, showing the dark default backdrop instead. Using a CSS keyframe animation instead of calling `animate` appears to avoid the problem.
REDMINE-20789
> Workaround Chrome auto zoom animation bug

- entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
- entry_types/scrolled/doc/creating_themes/custom_icons.md
- entry_types/scrolled/package/spec/frontend/ThemeIcon-spec.js
- entry_types/scrolled/package/src/frontend/ThemeIcon.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcons.module.css
- entry_types/scrolled/package/src/widgets/defaultNavigation/Logo.js
* Allow controlling width of buttons and icon size. Center icons in buttons.
* Allow controlling inline padding of navigation bar.
* Allow replacing mobile menu button with custom theme icon.
REDMINE-20674
> Add theme properties for default navigation bar buttons

- entry_types/scrolled/config/locales/new/hotspots.de.yml
- entry_types/scrolled/config/locales/new/hotspots.en.yml
- entry_types/scrolled/package/spec/contentElements/hotspots/Hotspots-spec.js
- entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
- entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
- entry_types/scrolled/package/src/contentElements/hotspots/editor/SidebarEditAreaView.js
- entry_types/scrolled/package/src/contentElements/hotspots/editor/index.js
- entry_types/scrolled/package/src/contentElements/hotspots/getTooltipReferencePosition.js
- entry_types/scrolled/package/src/frontend/Text.module.css
- package/spec/ui/views/inputs/SelectInputView-spec.js
- package/src/ui/views/inputs/SelectInputView.js
- package/src/ui/views/inputs/SliderInputView.js
> Further improvements for hotspots element

- app/assets/stylesheets/pageflow/editor/base.scss
- app/assets/stylesheets/pageflow/editor/drop_down_button.scss
- app/assets/stylesheets/pageflow/editor/list.scss
- app/assets/stylesheets/pageflow/editor/outline.scss
- app/assets/stylesheets/pageflow/editor/sortable.scss
- app/assets/stylesheets/pageflow/mixins/buttons.scss
- app/assets/stylesheets/pageflow/ui/properties.scss
- entry_types/scrolled/config/locales/new/reorder_chapters.de.yml
- entry_types/scrolled/config/locales/new/reorder_chapters.en.yml
- entry_types/scrolled/package/src/editor/views/ChapterItemView.module.css
- entry_types/scrolled/package/src/editor/views/EntryOutlineView.js
- entry_types/scrolled/package/src/editor/views/EntryOutlineView.module.css
- entry_types/scrolled/package/src/editor/views/SectionItemView.js
- entry_types/scrolled/package/src/editor/views/SectionItemView.module.css
- entry_types/scrolled/package/src/editor/views/outline.module.css
- package/package.json
- package/src/editor/views/DropDownButtonView.js
- package/src/ui/views/SortableCollectionView.js
- yarn.lock
> Reorder chapters mode

- package/src/ui/views/SortableCollectionView.js
Properly tear down sortables. On second visit of the outline, the old sortables were still intervening and causing chaotic behavior.
REDMINE-20837
> Fix flickering when sorting sections after returning to the outline

- entry_types/scrolled/package/src/editor/views/ChapterItemView.js
- package/src/ui/views/SortableCollectionView.js
Safari apparently gets confused with the scaled section thumbnail and incorrectly uses a much larger rectangle when generating the drag image of a dragged section item. The image then also includes text of other chapters and section items of the outline and parts of the sidebar footer.
Use fallback instead of native draggable for sections in Safari.
Related: https://github.com/SortableJS/Sortable/issues/291
REDMINE-20837
> Fix drag image of dragged section in Safari

- entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_theme.json.jbuilder
- entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
This enabled toggling between different icon sets using theme option overrides.
REDMINE-20841
> Make custom icon directory name configurable via theme options

- entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
- entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
- entry_types/scrolled/spec/helpers/pageflow_scrolled/themes_helper_spec.rb
> Support referencing theme assets from shared theme directory

- entry_types/scrolled/package/package.json
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText/index.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText/shortcuts.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/shortcuts.js
- yarn.lock
While it would be nice to fully support undo/redo for all editor actions, inline editable text looks like a good place to start. For text blocks we reset the undo history when the value is altered from the outside (e.g., when splitting or merging text blocks by moving elements).
> Add undo/redo to inline editable texts

- spec/support/dominos/editor/publish_entry_panel.rb
Apparently the date picker overlay now opens to the top, hiding the header that we were trying to click to blur the input. Hit tab key instead to blur.
> Fix publishing entry feature spec

- entry_types/scrolled/package/spec/editor/models/Cutoff-spec.js
- entry_types/scrolled/package/src/editor/models/Cutoff.js
When no cutoff section has been set, new sections, which do not have a perma id yet, were recognized as matching the cutoff section perma id.
REDMINE-20674
> Do not show cutoff mode indicator on newly created sections

- entry_types/scrolled/package/spec/widgets/defaultNavigation/Defaultnavigation-spec.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/Logo.js
Can be used to construct custom navigation bar widgets based on default navigation that are not limited to only showing theme logos.
REDMINE-20856
> Allow overriding navigation bar logo settings via prop

- entry_types/scrolled/package/src/frontend/Content.module.css
When the last section does not use full height, depending on its transition settings, its backdrop can still have full viewport height. This can cause the document to expand vertically resulting in empty space below the footer.
REDMINE-20872
> Prevent last section from extending beyond footer

- entry_types/scrolled/config/locales/new/align_justified.de.yml
- entry_types/scrolled/config/locales/new/align_justified.en.yml
- entry_types/scrolled/package/spec/frontend/EditableText-spec.js
- entry_types/scrolled/package/spec/frontend/inlineEditing/EditableText/blocks-spec.js
- entry_types/scrolled/package/src/contentElements/textBlock/editor.js
- entry_types/scrolled/package/src/contentElements/textBlock/stories.js
- entry_types/scrolled/package/src/frontend/EditableText.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/blocks.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
Per paragraph setting like color/typography variant.
REDMINE-20877
> Support justified text align inside text blocks

- app/assets/stylesheets/pageflow/ui/forms.scss
- entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
Also hide separator if last child of configuration editor tab.
> Hide caption variants select if only one item

- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarEditLinkView.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/below.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/right.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
Render divs instead of links and skip hover specific styles if URL is empty. This is a first step towards turning the element into a more generic image/text composition.
REDMINE-20852
> Allow using external links as static teaser list

- entry_types/scrolled/config/locales/de.yml
- entry_types/scrolled/config/locales/en.yml
- entry_types/scrolled/config/locales/new/ext-link-options.de.yml
- entry_types/scrolled/config/locales/new/ext-link-options.en.yml
- entry_types/scrolled/config/locales/new/teaser_inline_editing.de.yml
- entry_types/scrolled/config/locales/new/teaser_inline_editing.en.yml
- entry_types/scrolled/package/spec/contentElements/externalLinkList/editor/models/ExternalLinkCollection-spec.js
- entry_types/scrolled/package/spec/contentElements/externalLinkList/frontend/ExternalLink-spec.js
- entry_types/scrolled/package/spec/contentElements/externalLinkList/frontend/ExternalLinkList-spec.js
- entry_types/scrolled/package/spec/frontend/inlineEditing/EditableLink-spec.js
- entry_types/scrolled/package/spec/support/stories.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarEditLinkView.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarListView.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/models/ExternalLinkCollection.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/models/ExternalLinkModel.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/below.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
- entry_types/scrolled/package/src/frontend/Text.js
- entry_types/scrolled/package/src/frontend/Text.module.css
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableLink.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableLink.module.css
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/HoveringToolbar.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.module.css
- entry_types/scrolled/package/src/testHelpers/renderInContentElement.js
> Turn external links element into teasers element

- app/models/pageflow/entry_at_revision.rb
- lib/pageflow/theme_customizations.rb
- spec/pageflow/theme_customizations_spec.rb
Make it possible to rewrite overrides based on revision configuration (i.e. appearance settings). To keep the interface consistent, we need to construct a preliminary PublishedEntry to pass when previewing a theme customization.
REDMINE-20892
> Pass PublishedEntry when transforming theme customization overrides

- package/spec/editor/views/EditMetaDataView-spec.js
- package/src/editor/api/index.js
- package/src/editor/views/EditMetaDataView.js
So far there was only a way for entry types to add inputs. Now we can also add inputs from additional editor packs to add theme specific options.
REDMINE-20892
> Add editor API to add additional appearance inputs

- entry_types/scrolled/package/spec/support/__spec__/stories-spec.js
- entry_types/scrolled/package/spec/support/stories.js
- entry_types/scrolled/package/src/frontend/Section.js
- entry_types/scrolled/package/src/frontend/Section.module.css
- entry_types/scrolled/package/src/frontend/__stories__/lightDarkContentScopes-stories.js
- entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
While we already have separate theme properties for dark and light content text color etc. these scopes allow setting other theme properties like accent colors differently for dark and light content.
REDMINE-20892
> Add scopes for light and dark content

- entry_types/scrolled/package/spec/editor/controllers/PreviewMessageController-spec.js
- entry_types/scrolled/package/src/editor/controllers/PreviewMessageController.js
Unmounting the component can cause useEffect to run that triggers a transient state update. Ignore update messages for elements that are not present in Backbone collection.
> Prevent error when deleting content element with transient state

- entry_types/scrolled/config/locales/de.yml
- entry_types/scrolled/config/locales/en.yml
- entry_types/scrolled/config/locales/new/hide_chapter.de.yml
- entry_types/scrolled/config/locales/new/hide_chapter.en.yml
- entry_types/scrolled/package/spec/editor/views/ChapterItemView-spec.js
- entry_types/scrolled/package/spec/entryState/structure-spec.js
- entry_types/scrolled/package/spec/widgets/defaultNavigation/Defaultnavigation-spec.js
- entry_types/scrolled/package/src/editor/views/ChapterItemView.js
- entry_types/scrolled/package/src/editor/views/ChapterItemView.module.css
- entry_types/scrolled/package/src/editor/views/EditChapterView.js
- entry_types/scrolled/package/src/entryState/structure.js
- entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
* Fix inline help text in edit chapter view that claimed chapters where hidden if title or description are blank.
* Show title of hidden chapters in brackets in outline.
* Hide blank title of sole-chapter to prevent entries with only one chapter from looking incomplete.
* Filter out hidden chapters from entry state in default navigation.
REDMINE-20961
> Allow hiding chapters in navigation

- entry_types/scrolled/package/src/frontend/ContentElementScrollSpace.module.css
If the element itself, e.g. a list of teasers, is already taller than the viewport, the stand-alone effect does not make sense. Prevent the spacer height from restricting the height of the element, causing it to overflow over the following elements.
> Prevent tall stand-alone elements from breaking layout

- entry_types/scrolled/package/spec/frontend/EditableText-spec.js
- entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
- entry_types/scrolled/package/src/contentElements/textBlock/stories.js
- entry_types/scrolled/package/src/frontend/EditableText.js
- entry_types/scrolled/package/src/frontend/EditableText.module.css
Do not move list icon inside the item since the list does not use centered text align. Otherwise the second line of a wrapping item is aligned with the list icon
> Fix indentation of justified lists in center ragged sections

- entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
- entry_types/scrolled/package/src/frontend/EditableText.module.css
`root` class is not applied by inline editing component.
> Fix display of justified lists in center ragged lists in editor

- app/helpers/pageflow/entries_helper.rb
- app/helpers/pageflow/feeds_helper.rb
- app/helpers/pageflow/hreflang_links_helper.rb
- app/helpers/pageflow/sites_helper.rb
- app/models/pageflow/home_button.rb
- app/models/pageflow/site.rb
- app/models/pageflow/sitemaps.rb
- entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry_translations.json.jbuilder
- lib/pageflow/configuration.rb
- spec/helpers/pageflow/entries_helper_spec.rb
- spec/helpers/pageflow/sites_helper_spec.rb
- spec/models/pageflow/site_spec.rb
Split off `site_url_options` and pass entry instead of site to `public_entry_url_options` if both config options are defined. Allow defining `public_entry_url_options` in feature flag.
REDMINE-20969
> Allow entry specific public_entry_url_options

- entry_types/scrolled/config/locales/new/image_gallery_peeks.de.yml
- entry_types/scrolled/config/locales/new/image_gallery_peeks.en.yml
- entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.js
- entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.module.css
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/ItemsListView.js
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/SidebarController.js
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/SidebarEditItemView.js
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/SidebarRouter.js
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/index.js
- entry_types/scrolled/package/src/contentElements/imageGallery/editor/models/ItemsCollection.js
- entry_types/scrolled/package/src/contentElements/imageGallery/stories.js
- entry_types/scrolled/package/src/frontend/PaginationIndicator.js
- entry_types/scrolled/package/src/frontend/PaginationIndicator.module.css
- entry_types/scrolled/package/src/frontend/index.js
> Pagination and portrait images for image galleries

- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/frontend/Text.js
- entry_types/scrolled/package/src/frontend/Text.module.css
> Add scale categories for teaser title and tagline

- entry_types/scrolled/config/locales/new/ext-link-options.de.yml
- entry_types/scrolled/config/locales/new/ext-link-options.en.yml
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
- entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
- entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
- entry_types/scrolled/package/src/frontend/LinkButton.js
- entry_types/scrolled/package/src/frontend/LinkButton.module.css
- entry_types/scrolled/package/src/frontend/index.js
- Introduced a new configuration option `displayButtons` for the teaser list, allowing users to toggle the visibility of buttons for opening links.
- Extract LinkButton component from hotspots tooltip
- Add theme properties to allow styling link buttons in light and dark content
REDMINE-20984
> Add display buttons option for external links

- entry_types/scrolled/config/locales/new/ext-link-options.de.yml
- entry_types/scrolled/config/locales/new/ext-link-options.en.yml
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
- entry_types/scrolled/package/src/frontend/LinkButton.module.css
> Allow changing text alignment in teaser links

- entry_types/scrolled/package/src/contentElements/heading/stories.js
- entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
- entry_types/scrolled/package/src/frontend/EditableInlineText.js
- entry_types/scrolled/package/src/frontend/EditableInlineText.module.css
- entry_types/scrolled/package/src/frontend/Text.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText/index.js
- entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText/index.module.css
> Support inline text effects in via custom theme properties

- entry_types/scrolled/config/locales/new/ext-link-options.de.yml
- entry_types/scrolled/config/locales/new/ext-link-options.en.yml
- entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
- entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/below.module.css
- entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
- entry_types/scrolled/package/src/frontend/InlineFileRights.js
- entry_types/scrolled/package/src/frontend/LinkButton.module.css
- entry_types/scrolled/package/src/frontend/Text.module.css
- entry_types/scrolled/package/src/widgets/iconInlineFileRights/IconInlineFileRights.js
- entry_types/scrolled/package/src/widgets/iconInlineFileRights/IconInlineFileRights.module.css
> Fine tune teaser test positions

- entry_types/scrolled/config/locales/new/backdrop_size.de.yml
- entry_types/scrolled/config/locales/new/backdrop_size.en.yml
- entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
- entry_types/scrolled/package/src/editor/views/EditSectionView.js
- entry_types/scrolled/package/src/frontend/Backdrop.module.css
- entry_types/scrolled/package/src/frontend/Section.js
- entry_types/scrolled/package/src/frontend/__stories__/backdropSize-stories.js
- entry_types/scrolled/package/src/frontend/transitions/scrollInScrollOut.module.css
- entry_types/scrolled/package/src/frontend/v1/Backdrop/index.js
Prevent cropping important parts of the image when the section does not cover the whole viewport.
This is a first step which does not yet cover all edge cases. Mainly works for sections with scroll-in/scroll-out transitions.
REDMINE-21031
> Allow scaling backdrop to cover section instead of viewport

- entry_types/scrolled/package/src/frontend/FitViewport.module.css
In some contexts in can be ok to display elements that do not fit the viewport.
REDMINE-21083
> Let themes opt out of fit viewport logic

- doc/creating_file_types.md
- entry_types/scrolled/config/locales/new/vr_image_projection.de.yml
- entry_types/scrolled/config/locales/new/vr_image_projection.en.yml
- package/spec/editor/views/EditFileView-spec.js
- package/spec/editor/views/FilteredFilesView-spec.js
- package/spec/editor/views/UploadableFilesView-spec.js
- package/src/editor/views/EditFileView.js
- package/src/editor/views/FilteredFilesView.js
- package/src/editor/views/UploadableFilesView.js
Allow scoping translations for configuration editor inputs, filters and table columns to entry type.
So far Pageflow Scrolled implicitly relied on translations from the `pageflow-vr` gem for its `vrImage` element. `pageflow-vr` only works with Pageflow Paged, though. This chagne allows to break the unintended dependency.
fixes #2100
> Support entry type specific editor translations for file types

- package/spec/ui/views/inputs/CheckBoxInputView-spec.js
- package/src/ui/views/inputs/CheckBoxInputView.js
When `displayCheckedIfDisabled` was true, the checkbox remained checked.
> Reset checkbox with undefined value when disabled binding changes

- app/views/pageflow/editor/config/_seeds.json.jbuilder
- spec/support/helpers/test_file_importer.rb
Make it easier for file importer plugins to reference images from their repository.
> Pass file importer logos through asset pipeline

- pageflow.gemspec
> Include missing JS file from scrolled package in gem

- entry_types/scrolled/package/spec/frontend/paletteColor-spec.js
- entry_types/scrolled/package/src/frontend/paletteColor.js
Custom properties set to empty strings in React component inline styles (e.g., `style={{'--something': ''}}`) are ignored in client side rendering, but result in properties with empty values in SSR. When a palette color option has been reset to the automatic value this can cause unwanted overrides of properties (e.g., invisible hotspot indicators). Make empty string result in undefined property value.
> Ignore empty palette color

- entry_types/scrolled/package/spec/frontend/MediaPlayer/textTracks-spec.js
- entry_types/scrolled/package/spec/frontend/PlayerContainer-spec.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/textTracks.js
- entry_types/scrolled/package/src/frontend/MediaPlayer/usePlayerTextTracks.js
When playing HLS video, iOS injects a captions text track with blank properties and sets it to showing. This overrides the default text track controlled by Pageflow. More aggressively update the showing text track when on play or when text tracks change.
REDMINE-19924
> Fix default text tracks on iOS

- entry_types/scrolled/package/spec/frontend/features/changeURLFragment-spec.js
- entry_types/scrolled/package/src/frontend/Content.js
- entry_types/scrolled/package/src/frontend/useChapterSlugUpdater.js
Do not already update the URL fragment based on the current section before the browser had time to scroll to the chapter/section referenced in the URL fragment.
This also keeps deep link fragments around and only updates the slug after the next chapter change.
> Prevent URL fragment update from breaking deep linking

- entry_types/scrolled/config/locales/de.yml
- entry_types/scrolled/config/locales/en.yml
- entry_types/scrolled/package/spec/frontend/Counter-spec.js
- entry_types/scrolled/package/src/contentElements/counter/Counter.js
- entry_types/scrolled/package/src/contentElements/counter/editor.js
Allow controlling whether entrance/counting animations begin when the element first becomes visible or when it reaches the center of the viewport. Defaults to center (onActivate) for backwards compatibility.
> Configure when counter animation should start

- entry_types/scrolled/config/locales/de.yml
- entry_types/scrolled/config/locales/en.yml
- entry_types/scrolled/package/spec/contentElements/inlineVideo/handlers-spec.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
- entry_types/scrolled/package/src/contentElements/inlineVideo/handlers.js
If the entry is not yet unmuted, it can make sense to offer a play button to let the user intentionally play the video with sound. If sound has already been enabled, it can still make sense to auto-player subsequent videos in the story.
> Allow autoplaying inline videos only if entry is unmuted
