app/assets/stylesheets/pageflow/subshare.css.scss
app/views/pageflow/entries/_mobile_navigation.html.erb
app/views/pageflow/entries/navigation/_bar_top.html.erb

* Update Facebook URL
* Style mobile sub share menu

Improve Social Sharing

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/editor/base.js
app/assets/javascripts/pageflow/editor/views/edit_page_view.js
app/assets/javascripts/pageflow/ui.js
app/assets/javascripts/pageflow/ui/views/inputs/extended_select_input_view.js
app/assets/javascripts/pageflow/ui/views/inputs/select_input_view.js
app/assets/stylesheets/pageflow/jquery_ui.css.scss
app/assets/stylesheets/pageflow/ui.css.scss
app/assets/stylesheets/pageflow/ui/input/extended_select_input.css.scss
app/views/pageflow/page_types/_page_type.json.jbuilder
config/locales/new/page_type_select.yml
pageflow.gemspec
vendor/assets/javascripts/jquery.ui.all.js

Show page types in categories and with descriptions.

New Page Type Select

---

app/assets/javascripts/pageflow/ui/renderer.js

If template is a function simply use it as a template.

Accept Functions in Marionette Renderer

---

pageflow.gemspec

fixes #190
2.x should also be compatible.

Loosen JBuilder Dependency

---

pageflow.gemspec

Ensure aws-sdk Gem Verion 1.x is used

---

.travis.yml
spec/support/config/database_cleaner.rb

* Start Xvfb in `before_install` travis hook
* Use `Capybara.reset_sessions!` before database cleaner

Impove Execution of JS Specs

---

app/assets/javascripts/pageflow/audio_player.js
app/assets/javascripts/pageflow/audio_player/media_events.js
app/assets/javascripts/pageflow/page_types/audio.js
app/assets/javascripts/pageflow/page_types/video.js
app/assets/javascripts/pageflow/video_player.js
app/assets/javascripts/pageflow/video_player/media_events.js

Allow accessing information about current page in media events.

Pass Page Widget in Media Event Context Option

---

README.md

Cannot use ruby 2.2.x

---

README.md

* Mention ImageMagick dependency
* Include `rails new` call
* Create database before invoking generator
* Add troubleshooting hints

Update Installation Instructions in README.md

---

app/assets/stylesheets/pageflow/page_types/audio.css.scss

so text wont disappear behind additional infobox

fixes audio page phone margin

---

app/helpers/pageflow/social_share_helper.rb
app/views/pageflow/social_share/_entry_meta_tags.html.erb
app/views/pageflow/social_share/_page_meta_tags.html.erb
spec/factories/image_files.rb
spec/helpers/pageflow/social_share_helper_spec.rb

* Add fallbacks for page and entry share description texts
* Don't provide alternative images for open graph if share image is picked

Improve Social Share Features

---

app/assets/javascripts/pageflow/settings.js

In web views `window.localStorage` might be undefined. Pageflow should
load anyway.

Check for Local Storage in Settings

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/object.js
app/assets/javascripts/pageflow/ui.js
app/assets/javascripts/pageflow/ui/object.js

We also need a Backbone-like base object for non-editor features.

Promote pageflow.Object to application.js

---

spec/features/editor/editing_entry_outline_spec.rb
spec/support/dominos/editor/entry_outline.rb

Wait for Editor Outline to Appear in Feature Spec

---

app/assets/javascripts/pageflow/editor/initializers/setup_collections.js
app/assets/javascripts/pageflow/editor/models/entry.js
app/assets/javascripts/pageflow/editor/templates/publish_entry.jst.ejs
app/assets/javascripts/pageflow/editor/views/publish_entry_view.js
app/assets/stylesheets/pageflow/admin/entries.css.scss
app/assets/stylesheets/pageflow/editor/publish_entry.css.scss
app/controllers/pageflow/editor/entry_publications_controller.rb
app/controllers/pageflow/entries_controller.rb
app/models/pageflow/draft_entry.rb
app/models/pageflow/entry.rb
app/models/pageflow/published_entry.rb
app/views/components/pageflow/admin/revisions_tab.rb
app/views/pageflow/editor/accounts/_account.json.jbuilder
app/views/pageflow/editor/entries/_entry.json.jbuilder
app/views/pageflow/editor/entries/seed.json.erb
app/views/pageflow/editor/entry_publications/check.json.jbuilder
config/locales/de.yml
config/locales/en.yml
config/locales/new/password_protection.yml
db/migrate/20150603091823_add_password_attributes_to_revisions.rb
pageflow.gemspec
spec/controllers/pageflow/editor/entry_publications_controller_spec.rb
spec/controllers/pageflow/entries_controller_spec.rb
spec/factories/entries.rb
spec/features/editor/publishing_an_entry_spec.rb
spec/models/pageflow/entry_spec.rb
spec/support/dominos/admin/entry_revision.rb
spec/support/dominos/editor/publish_entry_panel.rb
spec/support/matchers/be_published_with_password.rb
spec/support/matchers/be_published_without_password.rb

Allow to protect published entries with basic auth. Enhance publication view in editor to configure password protection.

Password protection

---

app/assets/javascripts/pageflow/editor/views/page_preview_view.js

Trigger a global event when a page is updated inside the editor. This
enables features like the slideshow atmo to react to configuration
changes.

Dispatch page:update via pageflow.events

---

README.md
lib/generators/pageflow/initializer/templates/pageflow.rb

Env for api keys

---

app/assets/javascripts/pageflow/editor/collections/subset_collection.js

* Remove models when they are removed from the parent
* Correctly call add when models are added to the parent

Improve SubsetCollection

---

app/assets/javascripts/pageflow/ui/views/mixins/subview_container.js

Registers view as subview and appends to element of view.

Add appendSubview Method

---

app/assets/javascripts/pageflow/editor/base.js
app/assets/javascripts/pageflow/editor/models/chapter.js
app/assets/javascripts/pageflow/editor/models/chapter_configuration.js
app/assets/javascripts/pageflow/editor/models/entry.js
app/assets/javascripts/pageflow/editor/models/page.js
app/controllers/pageflow/chapters_controller.rb
app/models/pageflow/chapter.rb
db/migrate/20141211110226_add_configuration_to_chapters.rb
spec/models/pageflow/chapter_spec.rb

Store a configuration hash on each chapter.

Chapter Configuration

---

admins/pageflow/accounts.rb
app/helpers/pageflow/widgets_helper.rb
app/views/admin/accounts/_form.html.erb
app/views/pageflow/editor/entries/seed.json.erb
lib/pageflow/configuration.rb
spec/helpers/pageflow/widgets_helper_spec.rb

* Allow registering widget types from features
* Only display widget types enabled for account in theming form
* Only display widget types enabled for entry in editor

Let Widget Types be Part of a Feature

---

app/assets/javascripts/pageflow/slideshow/page_widget.js
app/assets/javascripts/pageflow/slideshow/scroller_widget.js

More ways for page types to interact with their scroller.

Scroller API

---

app/assets/javascripts/pageflow/browser/pushstate_support.js
app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/javascripts/pageflow/history.js
app/assets/javascripts/pageflow/history/hash_adapter.js
app/assets/javascripts/pageflow/history/push_state_adapter.js
app/assets/javascripts/pageflow/history/simulated_adapter.js
app/assets/javascripts/pageflow/slideshow.js

* back method to navigate to previously visitited page
* push state integration for playing correct page transitions when
going back

History API with Adapters for Hash, Push State and Simulation

---

app/assets/javascripts/pageflow/editor/api.js
app/assets/javascripts/pageflow/editor/api/page_type.js
app/assets/javascripts/pageflow/editor/api/page_types.js
app/assets/javascripts/pageflow/editor/initializers/setup_page_types.js
app/assets/javascripts/pageflow/editor/models/page.js
app/assets/javascripts/pageflow/editor/templates/inputs/page_link_input.jst.ejs
app/assets/javascripts/pageflow/editor/templates/page_link_item.jst.ejs
app/assets/javascripts/pageflow/editor/templates/page_links.jst.ejs
app/assets/javascripts/pageflow/editor/templates/page_selection.jst.ejs
app/assets/javascripts/pageflow/editor/views/chapter_item_view.js
app/assets/javascripts/pageflow/editor/views/edit_entry_view.js
app/assets/javascripts/pageflow/editor/views/edit_page_view.js
app/assets/javascripts/pageflow/editor/views/inputs/page_link_input_view.js
app/assets/javascripts/pageflow/editor/views/navigatable_page_item_view.js
app/assets/javascripts/pageflow/editor/views/page_item_view.js
app/assets/javascripts/pageflow/editor/views/page_link_item_view.js
app/assets/javascripts/pageflow/editor/views/page_links_view.js
app/assets/javascripts/pageflow/editor/views/page_preview_view.js
app/assets/javascripts/pageflow/editor/views/page_selection_view.js
app/assets/javascripts/pageflow/editor/views/page_thumbnail_view.js
app/assets/javascripts/pageflow/ui/views/configuration_editor_view.js
app/assets/stylesheets/pageflow/editor/base.css.scss
app/assets/stylesheets/pageflow/editor/inputs.css.scss
app/assets/stylesheets/pageflow/editor/inputs/page_link_input.css.scss
app/assets/stylesheets/pageflow/editor/outline.css.scss
app/assets/stylesheets/pageflow/editor/page_links.css.scss
app/assets/stylesheets/pageflow/editor/page_selection.css.scss
config/locales/new/page_link_input_view.yml
config/locales/new/page_links.yml
config/locales/new/page_selection.yml

Page type API and generic editor views.

Page Links

---

app/assets/javascripts/pageflow/editor/views/page_preview_view.js
app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
app/assets/javascripts/pageflow/slideshow/page_widget.js
app/views/pageflow/pages/_page.html.erb

Extract strategy for to make slideshow logic more customizable.

Scroll Navigator

---

app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/slideshow.js
app/views/pageflow/entries/show.html.erb

Feature toggles for slideshow.

Allow Registering Features for Slideshow

---

app/assets/javascripts/pageflow/editor/models/page.js
app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js
app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/javascripts/pageflow/page_types/mixins/common_page_css_classes.js
app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
app/assets/javascripts/pageflow/slideshow/scroll_indicator_widget.js
app/helpers/pageflow/pages_helper.rb
app/views/pageflow/editor/entries/_indicators_seed.html.erb
app/views/pageflow/entries/_entry.html.erb
app/views/pageflow/entries/_indicators.html.erb
app/views/pageflow/entries/edit.html.erb
config/initializers/features.rb
config/locales/new/scroll_indicator_modes.yml
lib/pageflow/theme.rb

Configurable Orientation and Visibility

Scroll Indicator Modes

---

app/assets/javascripts/pageflow/editor/views/page_preview_view.js
app/assets/javascripts/pageflow/history.js
app/assets/javascripts/pageflow/page_type.js
app/assets/javascripts/pageflow/page_types/video.js
app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/adjacent_pages.js
app/assets/javascripts/pageflow/slideshow/adjacent_preparer.js
app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
app/assets/javascripts/pageflow/slideshow/lazy_page_widget.js
app/assets/javascripts/pageflow/slideshow/page_widget.js
app/assets/javascripts/pageflow/slideshow/progressive_preload.js
spec/javascripts/pageflow/slideshow/adjacent_preparer_spec.js

Lazy initialization of entries.

Optimize Slideshow

---

app/assets/javascripts/pageflow/editor/models/configuration.js
app/assets/javascripts/pageflow/editor/views/embedded/lazy_video_embedded_view.js
app/assets/javascripts/pageflow/page_types/background_video.js
app/assets/javascripts/pageflow/page_types/video.js
app/assets/javascripts/pageflow/video_player/lazy.js
app/views/pageflow/editor/video_files/_video_file.json.jbuilder

Extract Backbone view to handle video player in editor.

Lazy Video Embedded View

---

app/assets/javascripts/pageflow/editor/models/page.js
app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js
app/assets/javascripts/pageflow/page_types/mixins/common_page_css_classes.js
app/assets/stylesheets/pageflow/base.css.scss
app/assets/stylesheets/pageflow/delayed_text_fade_in.css.scss
app/helpers/pageflow/pages_helper.rb
config/initializers/features.rb
config/locales/new/text_fade.yml

Option to fade in titles after a delay.

Delayed Title Fade In

---

app/assets/javascripts/pageflow/ui/views/mixins/input_view.js

Allow to compute visibility state based on model.

Add visible Option for Input Backbone Views

---

app/assets/javascripts/pageflow/editor/base.js
app/assets/javascripts/pageflow/editor/models/uploaded_file.js
app/assets/javascripts/pageflow/editor/templates/inputs/page_link_input.jst.ejs
app/assets/javascripts/pageflow/editor/templates/inputs/reference.jst.ejs
app/assets/javascripts/pageflow/editor/views/inputs/page_link_input_view.js
app/assets/javascripts/pageflow/editor/views/inputs/reference_input_view.js
app/assets/javascripts/pageflow/editor/views/model_thumbnail_view.js
app/assets/javascripts/pageflow/editor/views/page_thumbnail_view.js
app/assets/stylesheets/pageflow/editor/inputs.css.scss
app/assets/stylesheets/pageflow/editor/inputs/reference.css.scss
config/locales/new/reference_input_view.yml

Generic views for common editor ui use cases.

Reference Input View

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/chapter_filter.js
app/assets/javascripts/pageflow/editor/initializers/setup_collections.js
app/assets/javascripts/pageflow/editor/models/preview_entry_data.js
app/assets/javascripts/pageflow/editor/views/edit_chapter_view.js
app/assets/javascripts/pageflow/entry_data.js
app/assets/javascripts/pageflow/highlighted_page.js
app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/seed_entry_data.js
app/assets/javascripts/pageflow/widgets/page_navigation_list.js
app/assets/stylesheets/pageflow/navigation_bar.css.scss
app/helpers/pageflow/entries_helper.rb
app/helpers/pageflow/entry_json_seed_helper.rb
app/views/pageflow/entries/show.html.erb
config/initializers/features.rb
config/locales/new/chapter_hierachy.yml
spec/helpers/pageflow/entries_helper_spec.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb
spec/javascripts/models/preview_entry_data_spec.js
spec/javascripts/pageflow/chapter_filter_spec.js
spec/javascripts/pageflow/highlighted_page_spec.js
spec/javascripts/pageflow/seed_entry_data_spec.js

* Allow to define a parent page for a chapter in order to build a tree
of chapters.
* Filtering and highlighting chapters based on hierarchy.

Chapter Hierarchy

---

app/assets/javascripts/pageflow/page_types/audio.js
app/assets/javascripts/pageflow/page_types/video.js
app/assets/javascripts/pageflow/widgets/mute_button.js
app/assets/javascripts/pageflow/widgets/navigation.js
app/assets/javascripts/pageflow/widgets/skip_page_button.js
app/assets/javascripts/pageflow/widgets/volume_slider.js
app/views/pageflow/pages/templates/_audio.html.erb

* Skip button
* Volume slider
* Mute button

Additional Player Controls Buttons

---

app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js
app/assets/javascripts/pageflow/widgets/page_navigation_list.js
app/helpers/pageflow/pages_helper.rb
config/initializers/features.rb
config/locales/new/emphasize_pages_in_navigation.yml

* Emphasizing pages in the navigation
* Styling for pages inside sub chapter

Extra Navigation CSS Classes

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/fullscreen.js
app/assets/javascripts/pageflow/page_types/video.js
app/assets/javascripts/pageflow/widgets/fullscreen_button.js
app/assets/javascripts/pageflow/widgets/navigation.js

Add fullscreen button to video player controls.

Fullscreen Button

---

app/assets/javascripts/pageflow/page_types/video.js

Remove css class when deactivating page.

Always Remove faded Class from Scroll Indicators in Video Page

---

app/assets/javascripts/pageflow/editor/views/configuration_editors/video.js

Allow Pausing Atmo for Video Playback

---

app/assets/stylesheets/pageflow/page_transitions/cut.css.scss
app/assets/stylesheets/pageflow/page_transitions/fade_to_black.css.scss

Improve Fade to Black and Cut Page Transitions

---

app/assets/javascripts/pageflow/ui/views/collection_view.js
spec/javascripts/pageflow/ui/views/collection_view_spec.js

togglePlaceHolder function didn't work properly such that no loading spinner view could be displayed.

Fix a bug in collection_view.js

---

.hound.yml
.rubocop.yml
.rubocop_hound.yml

The codebase surely does not conform to these rules at the moment, but
like this we can converge towards a consistent style one pull request
at a time.

Add config files to perform Rubocop checks with Hound

---

app/views/layouts/pageflow/_meta_tags.html.erb

use the current Locale

---

app/views/layouts/pageflow/application.html.erb
app/views/pageflow/entries/edit.html.erb

Detect anywhere inside javascript whether we are currently inside the editor.

Set PAGEFLOW_EDITOR global

---

app/assets/javascripts/pageflow/slideshow/page_widget.js

For React based page types we want to create the scroller inside a component.

Let page type opt out of default scroller creation

---

CHANGELOG.md

New panorama styles need to be generated for existing image files.

Mention Paperclip refresh in changelog

---

app/assets/javascripts/pageflow/editor/views/file_item_view.js
app/models/concerns/pageflow/hosted_file.rb
app/models/pageflow/image_file.rb
app/views/pageflow/editor/files/_file.json.jbuilder

Offer original image for download in editor

---

admins/pageflow/entry.rb
config/initializers/admin_resource_tabs.rb
lib/pageflow/ability_mixin.rb
spec/controllers/admin/entries_controller_spec.rb

Add feature tab to entry admin

---

.jshintrc
app/assets/javascripts/pageflow/editor/api/page_type.js
app/assets/javascripts/pageflow/editor/collections/ordered_page_links_collection.js
app/assets/javascripts/pageflow/editor/collections/page_links_collection.js
app/assets/javascripts/pageflow/editor/collections/pages_collection.js
app/assets/javascripts/pageflow/editor/controllers/sidebar_controller.js
app/assets/javascripts/pageflow/editor/models/page_link.js
app/assets/javascripts/pageflow/editor/models/page_link_file_selection_handler.js
app/assets/javascripts/pageflow/editor/routers/sidebar_router.js
app/assets/javascripts/pageflow/editor/templates/edit_page_link.jst.ejs
app/assets/javascripts/pageflow/editor/templates/page_link_item.jst.ejs
app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/page_link.js
app/assets/javascripts/pageflow/editor/views/edit_page_link_view.js
app/assets/javascripts/pageflow/editor/views/page_link_configuration_editor_view.js
app/assets/javascripts/pageflow/editor/views/page_link_item_view.js
app/assets/stylesheets/pageflow/editor/page_links.css.scss
config/locales/new/page_link_defaults.de.yml
config/locales/new/page_link_defaults.en.yml

Provide defaults for:
* Page link backbone collection
* Routes and views to edit page links

Default Implementation for Editor Page Links Collection and Views

---

app/views/pageflow/entries/_entry.html.erb
app/views/pageflow/entries/_ie8_hint.html.erb
app/views/pageflow/entries/_indicators.html.erb
app/views/pageflow/entries/_mobile_navigation.html.erb
app/views/pageflow/entries/_multimedia_alert.html.erb
app/views/pageflow/entries/_non_js_hint.html.erb
app/views/pageflow/entries/_skip_links.html.erb
app/views/pageflow/entries/navigation/_bar_bottom.html.erb
app/views/pageflow/entries/navigation/_bar_top.html.erb
app/views/pageflow/entries/navigation/_home_button.html.erb
app/views/pageflow/entries/overview/_chapter.html.erb
app/views/pageflow/entries/overview/_entry.html.erb
app/views/pageflow/entries/share_menu/_facebook_link.html.erb
app/views/pageflow/entries/share_menu/_google_link.html.erb
app/views/pageflow/entries/share_menu/_twitter_link.html.erb
app/views/pageflow/pages/_page.html.erb
app/views/pageflow/pages/_video_tag.html.erb
app/views/pageflow/pages/templates/_audio.html.erb
app/views/pageflow/pages/templates/_background_video.html.erb
app/views/pageflow/pages/templates/_video.html.erb
config/locales/new/public.de.yml
config/locales/new/public.en.yml
config/locales/new/public.removed.yml

Solves issue #406 “Extract translations of public sites”

Extract publicly visible i18n strings from locale

---

app/assets/javascripts/pageflow/widgets/page_navigation_list.js

Highlight current chapter even if current page is not displayed in navigation bar.

Improve page navigation list widget

---

app/assets/javascripts/pageflow/editor/base.js
app/assets/javascripts/pageflow/editor/collections/chapter_pages_collection.js
app/assets/javascripts/pageflow/editor/collections/mixins/add_and_return_model.js
app/assets/javascripts/pageflow/editor/collections/storyline_chapters_collection.js
app/assets/javascripts/pageflow/editor/models/chapter.js
app/assets/javascripts/pageflow/editor/models/chapter_scaffold.js
app/assets/javascripts/pageflow/editor/models/entry.js
app/assets/javascripts/pageflow/editor/models/mixins/persited_promise.js
app/assets/javascripts/pageflow/editor/models/scaffold.js
app/assets/javascripts/pageflow/editor/models/storyline.js
app/assets/javascripts/pageflow/editor/models/storyline_scaffold.js
app/assets/javascripts/pageflow/editor/views/mixins/loadable.js
app/assets/javascripts/pageflow/editor/views/page_preview_view.js
app/assets/javascripts/pageflow/editor/views/storyline_outline_view.js
app/assets/javascripts/pageflow/editor/views/storyline_picker_view.js
app/controllers/pageflow/chapters_controller.rb
app/controllers/pageflow/storylines_controller.rb
app/models/pageflow/chapter_scaffold.rb
app/models/pageflow/storyline_scaffold.rb
config/routes.rb
spec/controllers/pageflow/chapters_controller_spec.rb
spec/controllers/pageflow/storylines_controller_spec.rb

Allow creating a storylines, a chapter and a page at once. Useful to improve editor experience instead of having to create objects in a cascade.

Scaffolding

---

app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js
app/helpers/pageflow/entry_json_seed_helper.rb
app/views/pageflow/editor/themings/_theming.json.jbuilder
lib/pageflow/theme.rb

Allow to disable default behavior of going to parent page.

Add theme option to control page change at storyline boundaries

---

app/assets/javascripts/pageflow/widgets/page_navigation_list.js

Also set filter css class on navigation bar item

---

app/assets/javascripts/pageflow/widgets/navigation.js
app/assets/javascripts/pageflow/widgets/navigation_mobile.js
app/assets/javascripts/pageflow/widgets/page_navigation_list.js
app/assets/javascripts/pageflow/widgets/page_navigation_list_animation.js
app/assets/javascripts/pageflow/widgets/parent_page_button.js
app/assets/stylesheets/pageflow/animations.css.scss
app/assets/stylesheets/pageflow/animations/navigation_bar.scss
app/assets/stylesheets/pageflow/navigation_bar.css.scss
app/assets/stylesheets/pageflow/navigation_mobile.css.scss
app/views/pageflow/entries/_mobile_navigation.html.erb

* Smooth transitions
* A parent page button for the mobile navigation

Storyline features for navigation bars

---

app/assets/javascripts/pageflow/widgets/navigation.js
app/assets/stylesheets/pageflow/navigation_bar.css.scss

Use transition to show or hide scroll indicators.

Fade scroll indicators on classic navigation bar

---

app/assets/javascripts/pageflow/editor/base.js
app/assets/javascripts/pageflow/editor/initializers/setup_common_seed.js
app/helpers/pageflow/common_entry_seed_helper.rb
app/helpers/pageflow/entry_json_seed_helper.rb
app/views/pageflow/editor/entries/seed.json.erb
spec/helpers/pageflow/common_entry_seed_helper_spec.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb

* Add common seed that is used in editor and published entries
* Provide helper that returns seed data as data structure
* Include list of present file ids in seed data

Reorganize seed data

---

app/helpers/pageflow/pages_helper.rb
config/initializers/paperclip.rb

Make new style and navigation thumbnail style available via css.

Add new thumbnail_large style

---

app/assets/stylesheets/pageflow/extendables.scss
app/assets/stylesheets/pageflow/mixins/pageflow.css.scss

Add css classes to extend from in order to:
* Apply default widget styles
* Render page type pictograms

Introduce scss extendables

---

app/assets/javascripts/pageflow/page_type.js
app/assets/javascripts/pageflow/slideshow/page_widget.js

Allow page types to clean up when a different page type is selected
inside the editor.

Add cleanup page type hook

---

admins/pageflow/accounts.rb
app/models/pageflow/cname_theming_request_scope.rb
app/views/admin/accounts/_form.html.erb
config/locales/new/additional_cnames.de.yml
config/locales/new/additional_cnames.en.yml
db/migrate/20160201130118_add_additional_cnames_to_themings.rb
spec/models/pageflow/cname_theming_request_scope_spec.rb

Make redirect URL work even if different CNAMES are used to link to entries.

Allow associating multiple CNAMES with a theming

---

app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/dom_order_scroll_navigator.js

Use horizontal animation when transitioning to a storyline whose parent page is the previous page.

Change default transition when comming from parent page

---

.travis.yml
admins/pageflow/revisions.rb
app/assets/javascripts/pageflow/editor/initializers/edit_lock.js
app/assets/javascripts/pageflow/editor/models/edit_lock_container.js
app/assets/javascripts/pageflow/editor/views/locked_view.js
app/controllers/pageflow/edit_locks_controller.rb
app/models/pageflow/edit_lock.rb
config/locales/de.yml
config/locales/en.yml
config/locales/new/edit_locks.de.yml
config/locales/new/edit_locks.en.yml
spec/controllers/admin/revisions_controller_spec.rb
spec/controllers/pageflow/chapters_controller_spec.rb
spec/controllers/pageflow/edit_locks_controller_spec.rb
spec/controllers/pageflow/editor/encoded_files_controller_examples.rb
spec/controllers/pageflow/editor/encoding_confirmations_controller_spec.rb
spec/controllers/pageflow/editor/entry_publications_controller_spec.rb
spec/controllers/pageflow/editor/file_usages_controller_spec.rb
spec/controllers/pageflow/editor/files_controller_spec.rb
spec/controllers/pageflow/entries_controller_spec.rb
spec/controllers/pageflow/pages_controller_spec.rb
spec/controllers/pageflow/storylines_controller_spec.rb
spec/models/pageflow/edit_lock_spec.rb
spec/support/helpers/edit_lock_test_helpers.rb

* `mime-types-data` gem requires Ruby 2
* Fix spelling error
* Improve linting of specs

Update Travis to use Ruby 2.1 and fix minor errors

---

config/locales/new/dynamic_meta_en.yml

"de" is wrong; that one is (correctly) in the German file.

"en" is the correct I18n key to use here

---

app/models/pageflow/draft_entry.rb
app/views/pageflow/editor/entries/_other_entry.json.jbuilder
app/views/pageflow/editor/entries/index.json.jbuilder

* Include draft when getting multiple draft entries
* Render less unneeded data in response

Make fetching other entries faster for file reuse

---

app/assets/stylesheets/pageflow/admin.css.scss
app/assets/stylesheets/pageflow/admin/features.scss
app/helpers/pageflow/admin/features_helper.rb
app/models/concerns/pageflow/feature_target.rb
app/models/pageflow/entry.rb
config/locales/new/inherited_feature_states.de.yml
config/locales/new/inherited_feature_states.en.yml
lib/pageflow/configuration.rb
lib/pageflow/features.rb
lib/pageflow/global_config_api.rb
spec/helpers/pageflow/admin/features_helper_spec.rb
spec/models/concerns/pageflow/feature_target_spec.rb
spec/pageflow/features_spec.rb
spec/pageflow/global_config_api_spec.rb

* Allow to define default feature state in initializer
* Allow disabling features which are enabled in parent
* Display inherited feature states in admin

Improve feature state inheritance

---

app/assets/stylesheets/pageflow/admin.css.scss
app/assets/stylesheets/pageflow/admin/forms.scss
app/views/admin/accounts/_form.html.erb
app/views/admin/accounts/_widgets_inline_help.html.erb
config/locales/new/admin_widget_inline_help.de.yml
config/locales/new/admin_widget_inline_help.en.yml

Note that changes only affect new entries.
fixes #475

Account widgets inline help

---

app/controllers/concerns/pageflow/entry_password_protection.rb
app/controllers/pageflow/entries_controller.rb
app/controllers/pageflow/files_controller.rb
spec/controllers/pageflow/files_controller_spec.rb

If the given entry is password protected, the files should also not be viewable.

Files password protection

---

app/helpers/pageflow/entry_json_seed_helper.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb

Required for rendering widgets.

Include title in chapter seed data

---

Rakefile
lib/pageflow/version.rb
pageflow.gemspec

Semmy provides changelog updating, doc tags rewriting, stable branch
creation and version file handling.

Install semmy release rake tasks

---

app/assets/stylesheets/pageflow/hide_text.css.scss
app/assets/stylesheets/pageflow/page.css.scss

* Use opacity/visibility transition defined by shadow itself
* Fade scroll indicator

Improve hide text css

---

app/assets/javascripts/pageflow/slideshow/hide_text.js

Allow to unsubscribe from events.

Add off event emitter method to pageflow.hideText.

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/focus_outline.js
app/assets/javascripts/pageflow/links.js
app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/slideshow/hide_text.js
app/assets/stylesheets/pageflow/base.css.scss
app/assets/stylesheets/pageflow/focus_outline.scss
app/assets/stylesheets/pageflow/navigation_bar.css.scss
app/assets/stylesheets/pageflow/skip_links.css.scss

* Hide focus outline after mouse interaction via css class on body
* Reactivate after keyboard intercation

Improve focus outline handling

---

app/assets/javascripts/pageflow/base.js
app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/javascripts/pageflow/widgets.js
app/helpers/pageflow/widgets_helper.rb
spec/helpers/pageflow/widgets_helper_spec.rb

Allow querying widgets in JavaScript.

Introduce widgets API

---

app/assets/javascripts/pageflow/widgets/multimedia_alert.js
app/assets/stylesheets/pageflow/multimedia_alert.css.scss

* Add overflow hidden to preven overflow of large background vignette
elements
* Prevent bouncy scroll on element itself on iOS

Prevent native scrolling on multimedia alert

---

app/assets/javascripts/pageflow/widgets/overview.js
app/assets/javascripts/pageflow/widgets/page_navigation_list.js

Ensure the current page is visible when opening the overview.

Scroll to active item in overview item

---

Gemfile
spec/spec_helper.rb

Install Coveralls test coverage reporter

---

admins/pageflow/user.rb
app/assets/stylesheets/pageflow/admin.css.scss
app/assets/stylesheets/pageflow/admin/embedded_index_table.scss
app/assets/stylesheets/pageflow/admin/tabs_view.css.scss
app/views/components/pageflow/admin/embedded_index_table.rb
app/views/components/pageflow/admin/entries_tab.rb
app/views/components/pageflow/admin/members_tab.rb
app/views/components/pageflow/admin/revisions_tab.rb
app/views/components/pageflow/admin/users_tab.rb
config/locales/new/admin_embedded_index_tables.de.yml
config/locales/new/admin_embedded_index_tables.en.yml
spec/features/account_manager/adding_user_membership_to_entry_spec.rb
spec/features/admin/adding_user_membership_to_entry_spec.rb
spec/support/helpers/view_component_example_group.rb
spec/views/components/pageflow/admin/embedded_index_table_spec.rb

Add sorting and pagination for entrie, member and user tables.

Improve admin tab lists

---

doc/creating_widget_types.md

this function is called widgetTypes and not widget_types.

correct the documentation for JS widget types

---

.sassdocrc
app/assets/stylesheets/pageflow/themes/default/player_controls/classic.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/container.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/info_box.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/container.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/control_bar.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/info_box.scss

Allow to configure
* info box typography
* border radius of info box and classic progress bar
Add SassDoc groups for player control variants.

Add further theme options for player controls

---

lib/generators/pageflow/active_admin_initializer/active_admin_initializer_generator.rb
lib/generators/pageflow/assets/assets_generator.rb
lib/generators/pageflow/cancan/cancan_generator.rb
lib/generators/pageflow/initializer/initializer_generator.rb
lib/generators/pageflow/resque/resque_generator.rb
lib/generators/pageflow/routes/routes_generator.rb
lib/generators/pageflow/seeds/seeds_generator.rb
lib/generators/pageflow/theme/theme_generator.rb
lib/generators/pageflow/user/user_generator.rb
pageflow.gemspec
spec/generators/pageflow/active_admin_initializer/active_admin_initializer_spec.rb
spec/generators/pageflow/assets/assets_generator_spec.rb
spec/generators/pageflow/cancan/cancan_generator_spec.rb
spec/generators/pageflow/initializer/initializer_generator_spec.rb
spec/generators/pageflow/resque/resque_generator_spec.rb
spec/generators/pageflow/routes/routes_generator_spec.rb
spec/generators/pageflow/seeds/seeds_generator_spec.rb
spec/generators/pageflow/user/user_generator_spec.rb
spec/spec_helper.rb
spec/support/shared_contexts/generator.rb

In order to implement #539 I wanted to add unit tests for the generator. Even though the `bin/rspec` helper generates a dummy app and initializes Pageflow for it, I think testing the generators directly is valuable too.
Do you agree @tf? If so I will create more unit tests for the remaining generators first.

Generator unit tests

---

app/assets/stylesheets/pageflow/themes/default/logo.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss

* Add variant displaying logo on all pages
* Add variables for logo dimensions
* Allow to fade in watermark logo on all pages

Improve logo theme configurability

---

app/assets/stylesheets/pageflow/themes/default/navigation.css.scss
app/assets/stylesheets/pageflow/themes/default/navigation/menu_boxes.scss

* Make default navigation current page marker themable
* Theme option to use navigation menu boxes with border

Navigation theme configurability

---

app/assets/stylesheets/pageflow/themes/default/navigation/dimensions.scss

Use available height for thumbnails

Change top height of top navigation

---

app/assets/stylesheets/pageflow/themes/default/page.css.scss

Use Sass maps rather then variables for individual properties.

Add page typography theme options

---

app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar/timestamp_position/right.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar/timestamp_position/split.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/info_box.scss

* Timestamp positions
* Font size
* Borders

Improve classic player controls configurability

---

app/assets/javascripts/pageflow/ui/views/inputs/slider_input_view.js

Allow speficying:
* min and max values
* default value
* unit string

Make SliderInputView more configurable

---

spec/support/config/factory_girl.rb
spec/support/config/timecop.rb
spec/support/config/web_mock.rb

* Ensure factory files show up correctly in coverage report 
* 	Remove test config for integration specs

Improve test coverage

---

.travis.yml

Ensure Pageflow works with the latest ruby version

Add Ruby 2.3.1 to Travis file

---

app/assets/stylesheets/pageflow/themes/default/navigation.scss
app/assets/stylesheets/pageflow/themes/default/navigation/dimensions.scss

Allow to hide the "hide text" button inside the navigation bar.

Add theme option to conrols display of hide text button

---

app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss

* Options `$loading-spinner-logo` where switched.
* Allow specifying the logo size

Improve loading spinner theme options

---

app/models/pageflow/published_entry.rb
spec/models/pageflow/published_entry_spec.rb

Include theming in published entry cache key.

Ensure entry cache is invalidated when theming changes

---

lib/pageflow/seeds.rb

This provides a less confusing presentation in a freshly seeded Pageflow
instance.

Set position for seeded chapters

---

app/assets/javascripts/pageflow/ui/utils/i18n_utils.js
spec/javascripts/pageflow/ui/utils/i18n_utils_spec.js

Pass additional options to `i18n.t` as interpolations.

Add interpolation support for i18nUtils.findTranslation

---

app/jobs/pageflow/poll_zencoder_job.rb
app/models/concerns/pageflow/output_source.rb
app/models/pageflow/video_file.rb
config/initializers/features.rb
config/initializers/zencoder.rb
config/locales/new/highdef_video_encoding.de.yml
config/locales/new/highdef_video_encoding.en.yml
db/migrate/20160707125400_add_output_presences_to_video_files.rb
lib/pageflow/zencoder_api.rb
lib/pageflow/zencoder_video_output_definition.rb
spec/jobs/poll_zencoder_job_spec.rb
spec/models/concerns/pageflow/output_source_spec.rb
spec/models/pageflow/video_file_spec.rb
spec/pageflow/zencoder_video_output_definition_spec.rb
spec/support/helpers/zencoder_api_double.rb

* Add highdef video definitions for Zencoder ￼
* Deprecate get_input_details, introduce get_details
* Add output presences to videos

FullHD/4k Video Variants

---

admins/pageflow/entry.rb
app/assets/stylesheets/pageflow/admin.scss
app/assets/stylesheets/pageflow/admin/embed_code.scss
app/controllers/pageflow/entries_controller.rb
app/helpers/pageflow/embed_code_helper.rb
app/views/admin/entries/_attributes_table.html.arb
app/views/components/pageflow/admin/embed_code_field.rb
config/locales/new/entry_embed_code.de.yml
config/locales/new/entry_embed_code.en.yml
config/routes.rb
lib/pageflow/configuration.rb
spec/controllers/pageflow/entries_controller_spec.rb
spec/features/visitor/viewing_entry_embed_spec.rb
spec/helpers/pageflow/embed_code_helper_spec.rb
spec/views/components/pageflow/admin/embed_code_field_spec.rb

* Add embed route to display entry inside iframe
* Add embed code field to entry admin attributes table
fixes #622

Embed entries as iframes

---

app/views/pageflow/entries/show.css.erb

It seems this can be optimised this way, or am I not understanding something?

remove unneeded loop

---

app/assets/javascripts/pageflow/editor/models/uploaded_file.js

Otherwise editing rights via the file settings dialog does not work.

Auto save files when rights change

---

README.md

Link to plugins wiki page from README

---

.jshintrc
app/assets/javascripts/pageflow/seed_entry_data.js
app/helpers/pageflow/entry_json_seed_helper.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb
spec/javascripts/pageflow/chapter_filter_spec.js
spec/javascripts/pageflow/entry_data_spec.js
spec/javascripts/pageflow/highlighted_page_spec.js
spec/javascripts/pageflow/seed_entry_data_spec.js

Unify interface to allow generic handling of storylines just like any
other collection.

Render storylines as array in seed data

---

app/assets/javascripts/pageflow/editor/templates/drop_down_button.jst.ejs
app/assets/javascripts/pageflow/editor/templates/drop_down_button_item.jst.ejs
app/assets/javascripts/pageflow/editor/templates/inputs/file_input.jst.ejs
app/assets/javascripts/pageflow/editor/views/drop_down_button_item_list_view.js
app/assets/javascripts/pageflow/editor/views/drop_down_button_item_view.js
app/assets/javascripts/pageflow/editor/views/drop_down_button_view.js
app/assets/stylesheets/pageflow/editor/drop_down_button.scss
app/assets/stylesheets/pageflow/editor/inputs/file_input.scss
spec/javascripts/views/drop_down_button_view_spec.js

* Allow displaying nested items
* Allow displaying a check mark in front of a menu item
* Improve display of buttons with only an icon
* Ensure only one drop down button shows its menu at the same time

Improve DropDownButton

---

app/assets/javascripts/pageflow/editor/models/text_track_file.js
app/assets/javascripts/pageflow/editor/views/inputs/file_input_view.js
config/locales/new/default_text_track_file.de.yml
config/locales/new/default_text_track_file.en.yml
spec/javascripts/models/file_uploader_spec.js
spec/javascripts/support/dominos/editor/drop_down_button.js
spec/javascripts/support/factories.js
spec/javascripts/views/inputs/file_input_view_spec.js

If a file as nested text track files, allow specifying a property to
store the id of a default text track file.

Default text track file

---

app/assets/javascripts/pageflow/editor/initializers/setup_file_types.js
app/assets/javascripts/pageflow/editor/views/text_file_meta_data_item_value_view.js
config/locales/new/alt.de.yml
config/locales/new/alt.en.yml

* Editable via settings dialog
* Display as meta data item

Add alt text attribute to files

---

app/assets/javascripts/pageflow/editor/utils/form_data_utils.js
spec/javascripts/utils/form_data_utils_spec.js

Correctly parse plus signs, spaces etc.

Improve special character handling in formDataUtils

---

app/assets/javascripts/pageflow/editor/api/file_type.js
app/assets/javascripts/pageflow/editor/collections/nested_files_collection.js
app/assets/javascripts/pageflow/editor/initializers/setup_file_types.js
app/assets/javascripts/pageflow/editor/models/text_track_file.js
app/assets/javascripts/pageflow/editor/models/uploaded_file.js
app/assets/javascripts/pageflow/editor/views/inputs/file_input_view.js
app/assets/javascripts/pageflow/editor/views/text_tracks_file_meta_data_item_value_view.js
app/assets/javascripts/pageflow/ui/templates/table_blank_slate.jst.ejs
app/assets/javascripts/pageflow/ui/views/inputs/text_input_view.js
app/assets/javascripts/pageflow/ui/views/inputs/url_display_view.js
app/assets/javascripts/pageflow/ui/views/table_cells/table_cell_view.js
app/assets/javascripts/pageflow/ui/views/table_view.js
app/assets/stylesheets/pageflow/editor/text_tracks.scss
app/assets/stylesheets/pageflow/ui/table_view.scss
config/locales/new/default_text_track_file.de.yml
config/locales/new/default_text_track_file.en.yml
config/locales/new/file_meta_data_items.en.yml
config/locales/new/video_subtitles.de.yml
config/locales/new/video_subtitles.en.yml
spec/javascripts/collections/nested_files_collection_spec.js
spec/javascripts/models/file_uploader_spec.js
spec/javascripts/models/mixins/encoded_file_spec.js
spec/javascripts/models/text_track_file_spec.js
spec/javascripts/models/uploaded_file_spec.js
spec/javascripts/pageflow/ui/views/inputs/text_input_view_spec.js
spec/javascripts/pageflow/ui/views/table_cells/table_cell_view_spec.js
spec/javascripts/spec_helper.js
spec/javascripts/support/factories.js
spec/javascripts/support/setup_globals.js

* Display default labels also in file input view and file meta data items
* Display inferred label name as input placeholder
* Sort text track files by display label
* Add button to open file settings dialog from input view

Text track improvements

---

app/assets/stylesheets/pageflow/themes/default/video_wrapper.scss

Pageflow now brings its own controls.

Prevent VideoJS controls from being displayed

---

app/assets/javascripts/pageflow/focus_outline.js
app/assets/stylesheets/pageflow/themes/default/player_controls/classic.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/icons/custom.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/icons/icon_font.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/icons/sprite.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/container.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/control_bar.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/vjs_mapping.scss

* Allow using custom icon for player controls play button
* Improve focus rect display for player progress bar 
* Prevent hiding player controls while focus is inside

Player controls improvements

---

app/assets/javascripts/pageflow/editor/collections/pages_collection.js
app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/javascripts/pageflow/editor/views/page_preview_view.js

* Only render persisted pages in editor preview 
* Add delay before reinitializing page on type change

Make Editor play nicely with Redux

---

app/models/pageflow/image_file.rb
app/models/pageflow/video_file.rb
app/models/pageflow/video_file_url_templates.rb
app/views/pageflow/video_files/_video_file.json.jbuilder
spec/models/pageflow/video_file_url_templates_spec.rb

Supply higher quality posters along with 4k/fullhd videos.

Add ultra variant to image file and video file posters

---

app/assets/javascripts/pageflow/video_player/filter_sources.js

We now also use VideoJS to play audio files.

Do not filter sources for audio tags

---

app/assets/javascripts/pageflow/editor/views/page_preview_view.js
app/assets/javascripts/pageflow/slideshow/adjacent_preparer.js
app/assets/javascripts/pageflow/slideshow/lazy_page_widget.js

* Do not call unprepare for destroyed pages
* Cleanup pages before destroy

Improve editor page lifecycle during delete

---

app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/background.js
config/locales/new/background_types.de.yml

A reusable set of form inputs to manage page background image/videos.

Add background inputs group

---

app/assets/stylesheets/pageflow/themes/default/base.scss
app/assets/stylesheets/pageflow/themes/default/text_track_cues.scss
app/assets/stylesheets/pageflow/themes/default/video_player/vjs_base.scss

* Hide text tracks when video is paused
* Prevent visual conflict with page content.
* Ensure  display on Firefox

Style text track cues

---

app/models/pageflow/video_file_url_templates.rb
app/views/pageflow/video_files/_video_file.json.jbuilder

* Print variant
* Medium poster

Add video file url to templates and json

---

app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/control_bar.scss

Allow using an SVG icon as loading spinner

Use svg icon for slim loading spinner

---

app/assets/stylesheets/pageflow/themes/default/variables/widgets.scss

!default was missing in declaration.

Allow overriding widget theme options

---

app/assets/javascripts/pageflow/ui/views/inputs/select_input_view.js

Always select the first item if no blank item is present.

Ensure select input view displays default

---

config/initializers/help_entries.rb
config/locales/new/text_tracks_help.de.yml
config/locales/new/text_tracks_help.en.yml

Describe how text tracks can be added and how the automatic selection
of subtitles works.

Add help entry for text tracks

---

config/locales/new/background_inline_help.de.yml
config/locales/new/background_inline_help.en.yml

Add helps texts explaining background types and poster images.

Add inline help for background inputs

---

app/assets/stylesheets/pageflow/entries.scss

Some locales provide a bit more text here.

Prevent line wrap in scroll indicator

---

app/assets/stylesheets/pageflow/themes/default/logo.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/page.scss

* Add theme options for height and top position of background logo on mobile and phone layout
* Add theme options for first page top padding

Logo theme options

---

app/assets/javascripts/pageflow/editor/templates/inputs/reference.jst.ejs
app/assets/javascripts/pageflow/editor/views/inputs/reference_input_view.js
app/assets/stylesheets/pageflow/editor/inputs/reference.scss
spec/javascripts/views/inputs/reference_input_view_spec.js

Prevent change by disabling buttons.

Add disabled option to ReferenceInputView

---

app/assets/javascripts/pageflow/video_player.js
app/assets/javascripts/pageflow/video_player/cue_settings_methods.js

Update cue settings when showing text track changed

Add cueSettings method to video player

---

node_package/src/components/PlayerControls/InfoBox.jsx
node_package/src/components/PlayerControls/__spec__/InfoBox-spec.jsx
node_package/src/components/PlayerControls/index.jsx

* Allow HTML content in description
* Move component inside `PlayerControls` Model

Fix HTML descriptions in InfoBox component

---

pageflow.gemspec

Adds translations for new media features.

Depend on pageflow-public-i18n 1.9

---

app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss

Allow retina images as animated second layer for the loading spinner
logo.

Allow setting size of custom loading spinner background

---

app/assets/javascripts/pageflow/ui/views/inputs/text_area_input_view.js
app/assets/javascripts/pageflow/ui/views/inputs/text_input_view.js
app/assets/javascripts/pageflow/ui/views/mixins/input_with_placeholder_text.js
spec/javascripts/pageflow/ui/views/inputs/text_area_input_view_spec.js

Extract functionality from `TextInputView` into reused mixin.

Add placeholder options to TextAreaInputView

---

app/models/concerns/pageflow/configuration.rb
app/models/concerns/pageflow/serialized_configuration.rb
app/models/pageflow/chapter.rb
app/models/pageflow/file_usage.rb
app/models/pageflow/page.rb
app/models/pageflow/storyline.rb
app/models/pageflow/widget.rb

This makes it obvious where to document this module.
And it DRYs things up.

move configuration into a concern

---

doc/using_the_nginx_upload_module.md

Details of the instructions depend on the exact gem verion.

Import nginx-upload-module guide from wiki

---

pageflow.gemspec

Allow using state_machine_job gem 1.x

---

app/assets/javascripts/pageflow/editor/models/file_stage.js
app/models/concerns/pageflow/hosted_file.rb

* Prevent caching outdated JSON when state changes multiple times in one
second.
* Ensure error message is updated in file stage when it changes during reprocessing.q

Improve polling for HostedFile state

---

README.md
doc/setting_up_external_services.md
doc/setting_up_s3_bucket_policies.md

Allow versioning the contents together with gem releases.

Import external services doc from wiki

---

app/assets/javascripts/pageflow/admin.js
app/assets/javascripts/pageflow/admin/users.js
app/assets/stylesheets/pageflow/admin/quotas.scss
app/helpers/pageflow/admin/users_helper.rb
app/helpers/pageflow/quota_helper.rb
app/models/pageflow/invitation_form.rb
app/policies/pageflow/account_policy.rb
app/views/admin/users/_quota_exhausted.html.erb
app/views/admin/users/invitation.html.erb
app/views/pageflow/admin/users/_quota_exhausted.html.erb
app/views/pageflow/admin/users/_quota_state.html.erb
lib/pageflow/configuration.rb
spec/controllers/admin/users_controller_spec.rb
spec/features/account_manager/inviting_a_user_spec.rb
spec/helpers/pageflow/admin/users_helper_spec.rb
spec/policies/pageflow/account_policy_spec.rb
spec/support/helpers/quota_double.rb

Allow staying compatible with old user management.

Add config option to prevent multi account users

---

.travis.yml
db/migrate/20170913105048_fix_hls_output_presences_for_legacy_video_files.rb

Include hls in output presences of legacy files

---

pageflow.gemspec

- add MIT license
- add lib as the standard require path
- don't put lib on the load path if it's already there
- make the bundler and rake dependencies explicit

update contents of gemspec

---

app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss

The size of the glowing area can now be set in a specified theme.

new variable to determine size of glowing area

---

README.md
pageflow.gemspec
spec/support/pageflow-support.gemspec

* storytelling is one word
* pageflow's website is at https://pageflow.io

fypos fixed

---

README.md
bin/console
doc/contributing/rails_engine_development.md
pageflow.gemspec
spec/support/pageflow-support.gemspec

Last one for the day. Just added a developer console to quickly try out code in the library.

Developer console

---

Gemfile

Includes two fixes:
* Client options for Chrome driver support
https://github.com/codevise/teaspoon/pull/2
* Backtrace printing
https://github.com/codevise/teaspoon/pull/1

Use Teaspoon fork from pageflow branch

---

CODE_OF_CONDUCT.md
README.md
doc/index.md

* Add and link to code of conduct
* Add Contributing section with links to existing resources
* Add license section

Improve Readme/Add Code of Conduct

---

app/assets/javascripts/pageflow/ui/templates/inputs/text_area_input.jst.ejs
app/assets/javascripts/pageflow/ui/templates/inputs/text_input.jst.ejs
app/assets/javascripts/pageflow/widgets/overview.js
app/assets/stylesheets/pageflow/entries.scss
app/assets/stylesheets/pageflow/mixins.scss
app/assets/stylesheets/pageflow/mixins/layout_direction.scss
app/assets/stylesheets/pageflow/mixins/shadow.scss
app/assets/stylesheets/pageflow/navigation_bar.scss
app/assets/stylesheets/pageflow/navigation_mobile.scss
app/assets/stylesheets/pageflow/overview.scss
app/assets/stylesheets/pageflow/page.scss
app/assets/stylesheets/pageflow/slideshow.scss
app/assets/stylesheets/pageflow/themes/default/anchors.scss
app/assets/stylesheets/pageflow/themes/default/logo/alignment.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/overview.scss
app/assets/stylesheets/pageflow/themes/default/overview/icons/icon_font.scss
app/assets/stylesheets/pageflow/themes/default/page.scss
app/assets/stylesheets/pageflow/themes/default/page/line_lengths.scss
app/assets/stylesheets/pageflow/themes/default/page/paddings.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/classic/control_bar.scss
app/helpers/pageflow/text_direction_helper.rb
app/views/layouts/pageflow/application.html.erb
app/views/pageflow/entries/edit.html.erb
app/views/pageflow/entries/show.html.erb
pageflow.gemspec
vendor/assets/javascripts/iscroll.js

* Make browser auto detect text direction in editor inputs
* Use logical direction mixins to make theme text direction
independent
* Apply text direction according to locale
* Make IScroll right to left compatible
* Use widget margins to replace hard coded paddings and margins which
are supposed to make room for navigation bars

Add support for locales with right to left script

---

app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss

- Its now possible to have a full width SVG background for the logo area 
- Added SVG Image support for Logo

Logo Banner & Logo SVG Option

---

app/assets/javascripts/pageflow/ui/views/inputs/color_input_view.js
app/assets/stylesheets/pageflow/ui/input/color_input.scss
spec/javascripts/pageflow/ui/views/inputs/color_input_view_spec.js

Allow passing a function to dynamically determine default value based
on a binding attribute.

Add defaultValueBinding option to ColorInputView

---

app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
app/assets/stylesheets/pageflow/themes/default/logo.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss

Adding the option to choose between SVG and PNG for the Logo and Loading Spinner Images.

Image variants for Logo & Loading Spinner

---

app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/visited.js
app/views/pageflow/entries/show.html.erb
spec/javascripts/pageflow/visited_spec.js

* Prevent storing duplicated page ids
* Use entry specific cookie to limit cookie size

Improve tracking of visited pages

---

app/assets/stylesheets/pageflow/page.scss
app/assets/stylesheets/pageflow/themes/default/page.scss
app/assets/stylesheets/pageflow/themes/default/page/scroller.scss
app/assets/stylesheets/pageflow/themes/default/page/shadow.scss

Extract shadow and scroller styles from page theme

---

admins/pageflow/user.rb
lib/generators/pageflow/resque/resque_generator.rb
lib/generators/pageflow/resque/templates/devise_async.rb
lib/pageflow/user_mixin.rb
pageflow.gemspec
spec/controllers/admin/accounts_controller_spec.rb
spec/controllers/admin/any_controller_spec.rb
spec/controllers/admin/entries_controller_spec.rb
spec/controllers/admin/folders_controller_spec.rb
spec/controllers/admin/memberships_controller_spec.rb
spec/controllers/admin/revisions_controller_spec.rb
spec/controllers/admin/users_controller_spec.rb
spec/controllers/pageflow/chapters_controller_spec.rb
spec/controllers/pageflow/edit_locks_controller_spec.rb
spec/controllers/pageflow/editor/encoding_confirmations_controller_spec.rb
spec/controllers/pageflow/editor/entries_controller_spec.rb
spec/controllers/pageflow/editor/entry_publications_controller_spec.rb
spec/controllers/pageflow/editor/files_controller_spec.rb
spec/controllers/pageflow/editor/widgets_controller_spec.rb
spec/controllers/pageflow/entries_controller_spec.rb
spec/controllers/pageflow/pages_controller_spec.rb
spec/controllers/pageflow/revisions_controller_spec.rb
spec/controllers/pageflow/storylines_controller_spec.rb
spec/generators/pageflow/resque/resque_generator_spec.rb
spec/support/config/devise.rb
spec/views/components/pageflow/admin/user_accounts_tab_spec.rb
spec/views/components/pageflow/admin/user_entries_tab_spec.rb

* Upgraded devise to 4.4.0 (we need this for Ruby 2.5.0 compat)
* Drop devise-async, use ActiveJob for background mails now
* Use current syntax for sign_in method

Devise 4.4.0

---

app/models/pageflow/chapter.rb
app/models/pageflow/chapter_scaffold.rb
app/models/pageflow/page.rb
app/models/pageflow/storyline.rb

Set `inverse_of` on association.

Fix building of nested associations

---

Gemfile
README.md
app/controllers/pageflow/application_controller.rb
lib/pageflow/engine.rb
pageflow.gemspec

The `state_machine` gem has been unmaintained for a long time.

Migrate to state_machines gem

---

Gemfile
pageflow.gemspec

Improve scss compilation times.

Allow using sassc-rails

---

lib/pageflow/engine.rb

Rails 5 no longer eager loads autoload paths. Prevent `lib/generators`
from being eager loaded.

Ensure lib/pagefow is eager loaded in production

---

app/assets/javascripts/pageflow/editor/views/configuration_editors/video.js

Mobile video poster is displayed cover. So it needs to be positionable.
REDMINE-15022

Allow positioning of mobile video poster

---

spec/factories/accounts.rb
spec/factories/audio_files.rb
spec/factories/chapters.rb
spec/factories/entries.rb
spec/factories/file_usages.rb
spec/factories/folders.rb
spec/factories/hosted_files.rb
spec/factories/image_files.rb
spec/factories/invited_user.rb
spec/factories/memberships.rb
spec/factories/pages.rb
spec/factories/revisions.rb
spec/factories/text_track_files.rb
spec/factories/themings.rb
spec/factories/users.rb
spec/factories/video_files.rb
spec/factories/widgets.rb

Fix a ton of deprecation warnings.

Rewrite factories to use dynamic attributes

---

pageflow.gemspec

Let's hope Active Admin will follow SemVer.

Relax Active Admin dependency

---

app/assets/javascripts/pageflow/media_player/volume_fading/web_audio.js

Chrome 71 will prevent using Web Audio contexts before the user
interacted with the page. In particular using a video tag as a media
source prevents muted playback.
Delay setting up the context until after background media has been
unmuted.
REDMINE-15771

Lazy Web Audio setup for Chrome 71

---

vendor/assets/javascripts/iscroll.js

* Make event listener target configurable for iScroll
* Prevent scrolling after movement in other direction
REDMINE-15957

Improve iScroll

---

app/models/pageflow/image_file.rb

Pan zoom feature of linkmap page requires better quality.
REDMINE-15957

Improve quality of panorama image file styles

---

app/assets/stylesheets/pageflow/themes/default/indicators/icons/icon_font.scss

Center text relative to arrow.
REDMINE-15957

Fix position of scroll indicator arrow icon

---

spec/controllers/pageflow/editor/files_controller_spec.rb
spec/factories/hosted_files.rb
spec/models/concerns/pageflow/hosted_file_spec.rb

Ensure hosted files are valid by default.
REDMINE-15957

Improve hosted file factory

---

app/assets/javascripts/pageflow/editor/views/info_box_view.js
app/assets/stylesheets/pageflow/editor/base.scss
app/assets/stylesheets/pageflow/editor/info_box.scss

Can be used to display multiple paragraphs.
REDMINE-15846

Allow using HTML in InfoBox view

---

app/assets/javascripts/pageflow/ui/views/mixins/input_view.js
spec/javascripts/pageflow/ui/views/mixins/input_view_spec.js

Allow appending further text to the translation based inline
help.
REDMINE-15846

Add additionalInlineHelpText option to input views

---

app/assets/stylesheets/pageflow/entries.scss
app/views/pageflow/entries/_indicators.html.erb
pageflow.gemspec

Use "Swipe to continue" for scroll indicator on mobile

---

app/assets/javascripts/pageflow/editor/views/entry_preview_view.js
app/assets/stylesheets/pageflow/mixins/breakpoints.scss

In landscape check height instead. Phones are a lot wider these
days.
REDMINE-15846

Prevent using desktop layout for landscape phones

---

app/assets/javascripts/pageflow/editor/views/widget_types/phone_horizontal_slideshow_mode.js
app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/navigation_direction.js
app/assets/javascripts/pageflow/slideshow/page_widget.js
app/assets/javascripts/pageflow/slideshow/scroller_widget.js
app/assets/stylesheets/pageflow/navigation_mobile.scss
config/locales/new/horizontal_slideshow_navigation_on_phone.de.yml
config/locales/new/horizontal_slideshow_navigation_on_phone.en.yml
lib/pageflow/built_in_widget_type.rb
lib/pageflow/built_in_widget_types_plugin.rb
spec/controllers/pageflow/editor/widgets_controller_spec.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb
spec/helpers/pageflow/widgets_helper_spec.rb

Option to allow horizontal swiping to change pages on phone

---

app/assets/javascripts/pageflow/page_type.js
app/assets/javascripts/pageflow/slideshow.js
app/assets/javascripts/pageflow/slideshow/lazy_page_widget.js
app/assets/javascripts/pageflow/slideshow/page_widget.js

Let page types prevent page changes via scrolling/gestures.
REDMINE-15848

Add isPageChangeAllowed page type hook

---

app/assets/javascripts/pageflow/slideshow/scroll_indicator_widget.js
app/assets/stylesheets/pageflow/animations/bounce.scss
app/assets/stylesheets/pageflow/entries.scss
app/assets/stylesheets/pageflow/mixins/icons/fontawesome.scss
app/assets/stylesheets/pageflow/themes/default/indicators/icons/icon_font.scss
app/views/pageflow/entries/_indicators.html.erb

Adapt icon and animation when pages can be changed via horizontal swipe. 
REDMINE-15847

Adapt scroll indicator for horizontal page change on phone

---

spec/javascripts/pageflow/page_transitions_spec.js

File is missing in #1043.
REDMINE-15846

Add spec for PageTransitions

---

spec/features/visitor/reading_entry_spec.rb
spec/support/dominos/entry.rb
spec/support/dominos/page.rb

Smoke test to detect js errors.

Add js feature spec for published entry

---

node_package/package.json
node_package/webpack.karma.config.js

https://github.com/airbnb/enzyme/issues/892

Fix warnings caused by Enzyme 2.8.2

---

app/assets/stylesheets/pageflow/themes/default/background_media_unmute_button.scss

Allow using theme specific svg image for background media unmute
button.
REDMINE-15986

Add theme option to use image for unmute button

---

app/assets/stylesheets/pageflow/themes/default/anchors.scss
app/assets/stylesheets/pageflow/themes/default/page/anchors.scss

* Allow adjusting typography settings for links in page content text.
*  Make anchor icon color configurable
REDMINE-15986

Add theme variables for anchors

---

app/assets/javascripts/pageflow/ui/views/inputs/text_input_view.js
app/assets/javascripts/pageflow/ui/views/mixins/input_view.js
config/locales/new/maxlength_for_text_inputs.de.yml
config/locales/new/maxlength_for_text_inputs.en.yml
spec/javascripts/pageflow/ui/views/inputs/text_input_view_spec.js

This will prevent errors where the input exeeds the
maximum character count for mysql varchar types.
fixes #782 
REDMINE-16097

Add maxlength attribute to text input fields

---

admins/pageflow/entry.rb
app/views/components/pageflow/admin/revisions_tab.rb

Fixes issue https://github.com/codevise/pageflow/issues/621
REDMINE-16102

Redirect to active tab when modifying revisions

---

app/assets/stylesheets/pageflow/navigation_mobile.scss
app/assets/stylesheets/pageflow/page_types/background-image.scss
app/assets/stylesheets/pageflow/themes/default/background_media_unmute_button.scss

by swapping deprecated mixins for regular CSS3 notations
REDMINE-16105

Fix bourbon deprecation warnings

---

app/assets/javascripts/pageflow/ui/views/inputs/text_input_view.js

Also validate text input on close

---

app/assets/javascripts/pageflow/media_player/volume_fading/web_audio.js

Ensure audio context is resumed even if background media was never
muted (e.g. the user interacted with the page before the first
autoplay failed).
REDMINE-16164

Try to resume suspended audio context on volume change

---

app/assets/javascripts/pageflow/media_player/volume_fading/web_audio.js

Backport of #1079
Ensure audio context is resumed even if background media was never
muted (e.g. the user interacted with the page before the first
autoplay failed).
REDMINE-16164

Try to resume suspended audio context on volume change (12.x Backport)

---

node_package/spec/support/sagas/runSagaInPageScope.js
node_package/src/__spec__/collections-spec.js
node_package/src/collections/__spec__/createFirstItemSelector-spec.js
node_package/src/collections/__spec__/createItemSelector-spec.js
node_package/src/collections/__spec__/createItemsSelector-spec.js
node_package/src/collections/__spec__/createReducer-spec.js
node_package/src/collections/__spec__/watchBackboneCollection-spec.js
node_package/src/collections/actions.js
node_package/src/collections/createFirstItemSelector.js
node_package/src/collections/createItemSelector.js
node_package/src/collections/createItemsSelector.js
node_package/src/collections/createReducer.js
node_package/src/collections/index.js
node_package/src/collections/watch.js
node_package/src/collections/watchBackboneCollection.js

Add selector to determine first collection item
REDMINE-15907

Store order of collections in Redux store

---

app/helpers/pageflow/common_entry_seed_helper.rb
app/helpers/pageflow/entry_json_seed_helper.rb
app/views/pageflow/entry_json_seed/_entry.json.jbuilder
node_package/src/__spec__/entry-spec.js
node_package/src/boot.js
node_package/src/entry/__spec__/reducer-spec.js
node_package/src/entry/actions.js
node_package/src/entry/index.js
node_package/src/entry/reducer.js
spec/helpers/pageflow/common_entry_seed_helper_spec.rb
spec/helpers/pageflow/entry_json_seed_helper_spec.rb

Read either from seed or entry model.
REDMINE-15907

Add selector to get entry title

---

app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss

Allow applying variant specific logo styles to other elements.
REDMINE-15907

Extract %background_logo SCSS placeholder

---

node_package/src/components/PageThumbnail.jsx
node_package/src/pages/selectors/__spec__/pageBackgroundImageUrl-spec.js
node_package/src/pages/selectors/index.js
node_package/src/pages/selectors/pageBackgroundImageUrl.js
node_package/src/pages/thumbnailCandidates.js

Determine background image based on thumbnail candidates.
REDMINE-15907

Add pageBackgroundImageUrl selector

---

app/assets/javascripts/pageflow/editor/models/widget.js
app/assets/javascripts/pageflow/editor/models/widget_configuration_file_selection_handler.js
app/assets/javascripts/pageflow/editor/views/widget_types/classic_loading_spinner.js
app/assets/javascripts/pageflow/editor/views/widget_types/title_loading_spinner.js
app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner/title.scss
app/views/pageflow/react/_widget.html.erb
config/locales/new/title_loading_spinner.de.yml
config/locales/new/title_loading_spinner.en.yml
lib/pageflow/built_in_widget_type.rb
lib/pageflow/built_in_widget_types_plugin.rb
node_package/src/loadingSpinner/components/ClassicLoadingSpinner.jsx
node_package/src/loadingSpinner/components/TitleLoadingSpinner.jsx
node_package/src/loadingSpinner/index.js
node_package/src/widgets/selectors.js

Loading spinner widget with title and blurred image

---

app/assets/javascripts/pageflow/jquery_utils.js
app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/widgets/navigation.js
app/assets/javascripts/pageflow/widgets/navigation_mobile.js
app/assets/javascripts/pageflow/widgets/overview.js
app/assets/stylesheets/pageflow/navigation_bar.scss
app/views/pageflow/entries/_mobile_navigation.html.erb
app/views/pageflow/entries/mobile_navigation/_page.html.erb
app/views/pageflow/entries/navigation/_page.html.erb
app/views/pageflow/entries/overview/_page.html.erb
node_package/src/__spec__/entry-spec.js
node_package/src/entry/__spec__/reducer-spec.js
node_package/src/entry/actions.js
node_package/src/entry/index.js
node_package/src/entry/reducer.js
node_package/src/entry/selectors.js
node_package/src/media/components/PagePrintImage.jsx

Since loading spinner is hidden on `load` this decreases loading
spinner display time.
REDMINE-16290

Prevent loading of invisible images before load event

---

app/assets/javascripts/pageflow/jquery_utils.js
app/assets/javascripts/pageflow/ready.js
app/assets/javascripts/pageflow/widgets/navigation.js
app/assets/javascripts/pageflow/widgets/navigation_mobile.js
app/assets/javascripts/pageflow/widgets/overview.js
app/assets/stylesheets/pageflow/navigation_bar.scss
app/views/pageflow/entries/_mobile_navigation.html.erb
app/views/pageflow/entries/mobile_navigation/_page.html.erb
app/views/pageflow/entries/navigation/_page.html.erb
app/views/pageflow/entries/overview/_page.html.erb
node_package/src/__spec__/entry-spec.js
node_package/src/entry/actions.js
node_package/src/entry/index.js
node_package/src/entry/reducer.js
node_package/src/entry/selectors.js
node_package/src/media/components/PagePrintImage.jsx

Backport of #1094 
REDMINE-16290

Prevent loading of invisible images before load event (12.x Backport)

---

config/locales/new/title_loading_spinner.de.yml
config/locales/new/title_loading_spinner.en.yml
lib/pageflow/built_in_widget_types_plugin.rb

REDMINE-15907
Allow decoupling deploy and user facing release.

Scope title loading spinner with feature flag

---

.gitignore
node_package/package-lock.json

Ensure builds of `app/assets/javascript/pageflow/dist` files are
reproducable across machines.
REDMINE-16381

Add package-lock.json to version control

---

.gitignore
node_package/package-lock.json

Backport of #1106
Ensure builds of `app/assets/javascript/pageflow/dist` files are
reproducable across machines.
REDMINE-16381

Add package-lock.json to version control (12.x Backport)

---

app/assets/stylesheets/pageflow/themes/default/page.scss

Add typography theme vars for first page of chapter

---

app/assets/stylesheets/pageflow/navigation_bar.scss
app/assets/stylesheets/pageflow/navigation_mobile.scss
app/views/pageflow/entries/mobile_navigation/_page.html.erb
app/views/pageflow/entries/navigation/_page.html.erb

Make page links friendlier for screen readers and search engines.
REDMINE-16513

Include text in navigation bar links

---

db/migrate/20190404075934_copy_filenames_of_processing_failed_images.rb

Add migration to fix "processing_failed"-image files

---

config/initializers/paperclip.rb
lib/generators/pageflow/initializer/templates/pageflow.rb
lib/pageflow/configuration.rb
spec/support/pageflow/dummy/config/pageflow.rb

It's not needed anymore since we're not storing anything on the filesystem any longer
REDMINE-16119
REDMINE-16715

Remove papclip_filesystem_root config

---

bin/build-edge
doc/contributing/directory_layout_overview.md
doc/contributing/node_package_development.md
doc/contributing/rails_engine_development.md
doc/contributing/running_pageflow_from_a_branch.md

Add instructions on how to use Pageflow from a branch in a Gemfile.

Add build-edge script

---

app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/general.js
app/assets/javascripts/pageflow/page_types/mixins/default_page_content.js
app/assets/javascripts/pageflow/slideshow/page_split_layout.js
app/assets/javascripts/pageflow/slideshow/page_widget.js
app/assets/javascripts/pageflow/ui/templates/inputs/text_area_input.jst.ejs
app/assets/javascripts/pageflow/ui/views/inputs/text_area_input_view.js
app/assets/stylesheets/pageflow/editor/wysihtml5.scss
app/assets/stylesheets/pageflow/mixins/icons.scss
app/assets/stylesheets/pageflow/themes/default/page.scss
app/assets/stylesheets/pageflow/themes/default/page/line_lengths.scss
app/helpers/pageflow/pages_helper.rb
config/locales/new/lists_in_text_editor.de.yml
config/locales/new/lists_in_text_editor.en.yml
node_package/src/components/PageText.jsx
spec/helpers/pageflow/pages_helper_spec.rb

Add lists to WYSIHTML editor

---

app/assets/stylesheets/pageflow/themes/default/page.scss
app/assets/stylesheets/pageflow/themes/default/page/colors.scss

Extract page color rules into separate file and add rule for title
color. Inverted title color could already be styled.
REDMINE-16798

Add theme variable for title color

---

app/assets/javascripts/pageflow/ui/templates/inputs/json_input.jst.ejs
app/assets/javascripts/pageflow/ui/views/inputs/json_input_view.js
app/assets/stylesheets/pageflow/ui/forms.scss
config/locales/new/json_input.de.yml
config/locales/new/json_input.en.yml
spec/javascripts/pageflow/ui/views/inputs/json_input_view_spec.js

Parse and pretty print JSON data.
REDMINE-16823

Add JSONInputView

---

app/assets/javascripts/pageflow/admin.js
app/assets/javascripts/pageflow/ui/views/tabs_view.js

Check if `pageflow.app` exists, since it is only present inside the
editor.
REDMINE-16823

Fix TabsViews outside of editor

---

app/assets/stylesheets/pageflow/editor/files_explorer.scss
app/assets/stylesheets/pageflow/ui/tabs_view.scss

Custom styles for file explorer caused tabs to no longer be displayed.
REDMINE-16847

Fix tabs in editor file explorer view

---

app/helpers/pageflow/meta_tags_helper.rb
app/models/pageflow/revision.rb

fix missing analytics interpolator variables

---

app/models/pageflow/membership.rb
config/locales/new/membership.de.yml
config/locales/new/membership.en.yml

fix entry membership create error

---

app/helpers/pageflow/meta_tags_helper.rb
app/models/pageflow/revision.rb

Backport of #1192 
REDMINE-16980

Move meta data defaults to attribute reader (14.4 Backport)

---

app/models/pageflow/membership.rb
config/locales/new/membership.de.yml
config/locales/new/membership.en.yml

Fix entry membership create error (14.4 Backport)

---

app/assets/stylesheets/pageflow/themes/default/player_controls/classic/info_box.scss
app/assets/stylesheets/pageflow/themes/default/player_controls/slim/info_box.scss

Info box pointer-events enabled for anchor tag

---

app/assets/javascripts/pageflow/editor/api/widget_type.js
app/assets/javascripts/pageflow/editor/views/widget_types/media_loading_spinner.js
app/assets/javascripts/pageflow/editor/views/widget_types/title_loading_spinner.js
app/assets/stylesheets/pageflow/themes/default/base.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner/media.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner/title.scss
app/models/pageflow/widget.rb
config/locales/en.yml
config/locales/new/loading_spinner.de.yml
config/locales/new/loading_spinner.en.yml
config/locales/new/loading_spinner_invert.de.yml
config/locales/new/loading_spinner_invert.en.yml
lib/pageflow/built_in_widget_type.rb
lib/pageflow/built_in_widget_types_plugin.rb
lib/pageflow/widget_types.rb
node_package/src/loadingSpinner/components/MediaLoadingSpinner.jsx
node_package/src/loadingSpinner/components/TitleLoadingSpinner.jsx
node_package/src/loadingSpinner/index.js
node_package/src/pages/selectors/index.js
spec/controllers/pageflow/editor/widgets_controller_spec.rb
spec/models/pageflow/widget_spec.rb

REDMINE-16560
Backport of #1215

Configurable loading spinner (14.5 Backport)

---

app/assets/javascripts/pageflow/editor/api/widget_type.js
app/assets/javascripts/pageflow/editor/views/widget_types/media_loading_spinner.js
app/assets/javascripts/pageflow/editor/views/widget_types/title_loading_spinner.js
app/assets/stylesheets/pageflow/themes/default/base.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner/media.scss
app/assets/stylesheets/pageflow/themes/default/loading_spinner/title.scss
app/models/pageflow/widget.rb
config/locales/en.yml
config/locales/new/loading_spinner.de.yml
config/locales/new/loading_spinner.en.yml
config/locales/new/loading_spinner_invert.de.yml
config/locales/new/loading_spinner_invert.en.yml
lib/pageflow/built_in_widget_type.rb
lib/pageflow/built_in_widget_types_plugin.rb
lib/pageflow/widget_types.rb
node_package/src/loadingSpinner/components/MediaLoadingSpinner.jsx
node_package/src/loadingSpinner/components/TitleLoadingSpinner.jsx
node_package/src/loadingSpinner/index.js
node_package/src/pages/selectors/index.js
spec/controllers/pageflow/editor/widgets_controller_spec.rb
spec/models/pageflow/widget_spec.rb

REDMINE-16560
1. Added media loading spinner.
2. Added blurriness property of background image to loading spinners.
3. Added invert option to title and image loading spinner.

Configurable loading spinner

---

app/assets/stylesheets/pageflow/themes/default/loading_spinner.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss

REDMINE-17045
New Theme options
1. $logo-mobile-watermark-height
2. $loading-spinner-background-position
3. $loading-spinner-background-size
4. $loading-spinner-logo-mobile-width
5. $loading-spinner-logo-mobile-height

Theme options for logo and loading spinner

---

app/assets/stylesheets/pageflow/themes/default/mobile_navigation.scss

Add active class color styling for mobile share panel

---

config/locales/new/text_track_languages.de.yml
config/locales/new/text_track_languages.en.yml

Add text track languages

---

config/locales/de.yml
config/locales/en.yml

Add text track languages (15.0 Backport)

---

app/assets/javascripts/pageflow/seed_entry_data.js
spec/javascripts/pageflow/seed_entry_data_spec.js

Index seed entry data files by perma id (15.0 Backport)

---

app/assets/javascripts/pageflow/seed_entry_data.js
spec/javascripts/pageflow/seed_entry_data_spec.js

Index seed entry data files by perma id

---

config/initializers/help_entries.rb
config/initializers/page_types.rb
lib/pageflow/configuration.rb
lib/pageflow/file_types.rb
lib/pageflow/page_types.rb
lib/pageflow/revision_components.rb
spec/helpers/pageflow/files_helper_spec.rb
spec/models/pageflow/revision_spec.rb
spec/pageflow/configuration_spec.rb
spec/pageflow/entry_export_import/revision_serialization_spec.rb
spec/pageflow/file_types_spec.rb
spec/pageflow/page_types_spec.rb
spec/support/helpers/test_revision_component.rb

Decouple revision components and file types from page types

---

app/controllers/pageflow/editor/file_import_controller.rb
app/helpers/pageflow/config_helper.rb
app/views/pageflow/config/_editor_seeds.json.jbuilder
app/views/pageflow/editor/entries/seed.json.erb
lib/pageflow/file_importers.rb
packages/pageflow/src/editor/api/FileImporters.js
packages/pageflow/src/editor/views/FilesView.js
spec/controllers/pageflow/editor/file_import_controller_spec.rb
spec/helpers/pageflow/config_helper_spec.rb
spec/support/helpers/test_file_importer.rb

File import feature flag

---

app/helpers/pageflow/editor/entries_helper.rb
app/views/pageflow/entries/edit.html.erb
doc/creating_entry_types.md
entry_types/paged/app/assets/javascripts/pageflow_paged/editor.js
entry_types/paged/app/assets/stylesheets/pageflow_paged/editor.scss
entry_types/paged/app/controllers/pageflow_paged/editor/entries_controller.rb
entry_types/paged/app/views/pageflow_paged/editor/entries/_head.html.erb
entry_types/paged/lib/pageflow_paged.rb
entry_types/paged/lib/pageflow_paged/engine.rb
entry_types/paged/lib/pageflow_paged/plugin.rb
entry_types/paged/spec/integration/entry_type_spec.rb
lib/pageflow/engine.rb
lib/pageflow/entry_type.rb
lib/pageflow/partial_editor_fragment_renderer.rb
spec/controllers/pageflow/entries_controller_spec.rb
spec/helpers/pageflow/editor/entries_helper_spec.rb
spec/pageflow/entry_types_spec.rb
spec/pageflow/partial_editor_fragment_renderer_spec.rb
spec/support/helpers/test_entry_type.rb
spec/support/pageflow/lint.rb
spec/support/pageflow/lint/entry_type.rb

Allow loading type entry type specific assets in editor head.
REDMINE-17213

Entry type specific editor assets

---

doc/creating_file_importers.md

mentioned that file importer should be registered in a feature flag

---

entry_types/scrolled/app/controllers/pageflow_scrolled/editor/entries_controller.rb
entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_body.html.erb
entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/dummy-spec.js
entry_types/scrolled/package/spec/editor/views/EntryPreviewView-spec.js
entry_types/scrolled/package/src/editor/index.js
entry_types/scrolled/package/src/editor/views/EntryPreviewView.js
entry_types/scrolled/package/src/editor/views/EntryPreviewView.module.css
entry_types/scrolled/spec/helpers/pageflow_scrolled/editor/seed_html_helper_spec.rb
packages/pageflow/config/jest/index.js
packages/pageflow/config/jest/transformers/cssModules.js
packages/pageflow/spec/ui/utils/cssModulesUtils-spec.js
packages/pageflow/src/editor/views/EditorView.js
packages/pageflow/src/ui/index.js
packages/pageflow/src/ui/utils/cssModulesUtils.js
yarn.lock

Render demo in editor

---

entry_types/scrolled/lib/pageflow_scrolled/seeds.rb
entry_types/scrolled/spec/pageflow_scrolled/seeds_spec.rb

Add seeds for scrolled models

---

app/views/pageflow/config/_editor_seeds.json.jbuilder
spec/helpers/pageflow/config_helper_spec.rb

Use entry specific config in config seed.
REDMINE-17274, REDMINE-17257

Consider feature flags for file types available in editor

---

app/models/pageflow/draft_entry.rb
app/models/pageflow/published_entry.rb
doc/creating_entry_types.md
entry_types/paged/lib/pageflow_paged.rb
entry_types/paged/lib/pageflow_paged/plugin.rb
entry_types/scrolled/lib/pageflow_scrolled.rb
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
lib/pageflow/configuration.rb
lib/pageflow/entry_type.rb
lib/pageflow/global_config_api.rb
spec/pageflow/global_config_api_spec.rb
spec/requests/pageflow/entries_show_request_spec.rb
spec/support/helpers/test_entry_type.rb

Extend config DSL for entry types

---

lib/pageflow/configuration.rb
lib/pageflow/global_config_api.rb
lib/pageflow/widget_type.rb
lib/pageflow/widget_types.rb
spec/pageflow/global_config_api_spec.rb

Allow scoping file types and widget types by entry types

---

app/models/concerns/pageflow/feature_target.rb
app/views/admin/features/_form.html.erb
doc/creating_entry_types.md
entry_types/paged/lib/pageflow_paged.rb
entry_types/paged/lib/pageflow_paged/configuration.rb
entry_types/paged/lib/pageflow_paged/plugin.rb
entry_types/scrolled/lib/pageflow_scrolled.rb
entry_types/scrolled/lib/pageflow_scrolled/configuration.rb
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
lib/pageflow/configuration.rb
lib/pageflow/entry_type_configuration.rb
lib/pageflow/feature.rb
lib/pageflow/global_config_api.rb
spec/models/concerns/pageflow/feature_target_spec.rb
spec/pageflow/feature_spec.rb
spec/pageflow/global_config_api_spec.rb
spec/support/helpers/test_entry_type.rb
spec/views/components/pageflow/admin/features_tab_spec.rb

Integrate entry type specific config with feature flags

---

config/initializers/features.rb
config/initializers/page_types.rb
entry_types/paged/config/initializers/features.rb
entry_types/paged/config/initializers/page_types.rb
entry_types/paged/lib/pageflow_paged/configuration.rb
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
lib/pageflow/built_in_page_types_plugin.rb
lib/pageflow/built_in_widget_types_plugin.rb
lib/pageflow/configuration.rb
lib/pageflow/entry_type_configuration.rb
spec/pageflow/configuration_spec.rb
spec/pageflow/global_config_api_spec.rb

* Extract page type configuration to entry type engine
* Scope built in features, file types, widget types and help entries to paged entry type
REDMINE-17189

Scope existing built ins to paged entry type 

---

entry_types/scrolled/lib/pageflow_scrolled/seeds.rb
entry_types/scrolled/package/spec/useEntryState-spec.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/Heading.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/navigation/AppHeader.js
entry_types/scrolled/package/src/frontend/navigation/AppHeaderTooltip.js
entry_types/scrolled/package/src/frontend/navigation/AppHeaderTooltip.module.css
entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js
entry_types/scrolled/package/src/useEntryState.js
entry_types/scrolled/spec/pageflow_scrolled/seeds_spec.rb

Use chapter data in navigation

---

app/models/pageflow/revision.rb
entry_types/scrolled/app/models/pageflow_scrolled/chapter.rb
entry_types/scrolled/app/models/pageflow_scrolled/content_element.rb
entry_types/scrolled/app/models/pageflow_scrolled/section.rb
entry_types/scrolled/app/models/pageflow_scrolled/storyline.rb
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/spec/models/pageflow_scrolled/storyline_spec.rb
spec/support/pageflow/lint.rb

Deep copy all chapters, sections and content elements of the storyline
to new revisions.
REDMINE-17315

Register scrolled storyline as revision component

---

doc/creating_entry_types.md
entry_types/paged/packages/pageflow-paged/src/editor/helpers/appearanceInputs.js
entry_types/paged/packages/pageflow-paged/src/editor/index.js
packages/pageflow/spec/editor/views/EditMetaDataView-spec.js
packages/pageflow/src/editor/views/EditMetaDataView.js

Extract part of appearance options into paged entry type

---

entry_types/scrolled/package/src/frontend/navigation/AppHeaderTooltip.module.css
entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js

Small fixes for scrolled navigation bar

---

spec/controllers/pageflow/editor/file_import_controller_spec.rb
spec/pageflow/test_file_importer_spec.rb
spec/support/helpers/test_file_importer.rb
spec/support/pageflow/lint/file_import.rb

minor file import lint change

---

app/models/pageflow/home_button.rb
spec/models/pageflow/home_button_spec.rb

Fix link_to home_button raises URLGenerationError

---

entry_types/paged/app/views/pageflow_paged/pages/_page.html.erb

Include entry locale in cache key of page partial

---

entry_types/scrolled/package/spec/entryState/files-spec.js
entry_types/scrolled/package/spec/entryState/structure-spec.js
packages/pageflow/.gitignore
packages/pageflow/documentation.yml
packages/pageflow/spec/support/index.js
packages/pageflow/src/editor/api/index.js
packages/pageflow/src/editor/state.js
packages/pageflow/src/testHelpers/factories.js
packages/pageflow/src/testHelpers/index.js
rollup.config.js

Make Backbone model factory test helpers reusable
REDMINE-17298

Pass scrolled entry to watchCollections in tests

---

entry_types/paged/app/views/layouts/pageflow_paged/application.html.erb

added meta charset tag in application layout of paged entries

---

app/assets/stylesheets/pageflow/editor/file_import.scss

changed file importer box size and margins of footer

---

config/locales/new/entry_metadata_configuration.de.yml
config/locales/new/entry_metadata_configuration.en.yml
doc/creating_entry_types.md
entry_types/paged/packages/pageflow-paged/src/editor/helpers/appearanceInputs.js
packages/pageflow/spec/editor/views/EditMetaDataView-spec.js
packages/pageflow/spec/support/dominos/ui/ConfigurationEditor.js
packages/pageflow/spec/support/dominos/ui/ConfigurationEditorTab.js
packages/pageflow/src/editor/views/EditMetaDataView.js
packages/pageflow/src/ui/views/mixins/inputView.js

Re-add help entries for appearance options

---

packages/pageflow/src/editor/models/Entry.js

Backport of #1331.
REDMINE-17418

Re-add entry.configuration in editor for backwards compatibility (15.1 Backport)

---

packages/pageflow/src/editor/models/Entry.js

Re-add entry.configuration in editor for backwards compatibility

---

.travis.yml

Use ruby 2.6.5 in travis

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.module.css
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor/DataWrapperAdView.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/frontend.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/stories.js
entry_types/scrolled/package/src/contentElements/editor.js
entry_types/scrolled/package/src/contentElements/frontend.js

dataWrapperChart content element

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js

Deduplicate position input translations

---

entry_types/scrolled/package/src/entryState/legalInfo.js

Fixes a timing issue when reusing images from other entries.

Fix useFileRights hook

---

entry_types/scrolled/package/src/editor/api/ContentElementTypeRegistry.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry.js
entry_types/scrolled/package/src/editor/views/InsertContentElementView.js

Enable registering content elements with default config

---

entry_types/scrolled/doc/creating_content_elements.md

Add documentation about default values for content element config

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
entry_types/scrolled/package/src/editor/index.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/common_content_element_attributes.js

Introduce configuration editor groups in scrolled editor

---

doc/contributing/node_package_development.md
doc/understanding_plugins_and_features.md

Remind developers to configure their editor with ESLint before starting to contribute

---

app/assets/stylesheets/pageflow/themes/default/logo/variant/background_image.scss
app/assets/stylesheets/pageflow/themes/default/logo/variant/watermark.scss
app/helpers/pageflow/pages_helper.rb
app/views/pageflow/themes/_theme.json.jbuilder
config/locales/new/hide_logo_on_page_level.de.yml
config/locales/new/hide_logo_on_page_level.en.yml
lib/pageflow/theme.rb
lib/pageflow/themes.rb
packages/pageflow/src/editor/models/Theme.js
packages/pageflow/src/editor/views/configurationEditors/groups/options.js
packages/pageflow/src/frontend/jquery_ui_widgets/header.js
packages/pageflow/src/frontend/page_types/mixins/common_page_css_classes.js

Hide logo on page level

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/editor/views/EditSectionView.js

Add section editing options in editor sidebar

---

.travis.yml

Abort and retry scrolled Capybara specs when Chromedriver hangs

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/spec/frontend/Audio-spec.js
entry_types/scrolled/package/spec/support/__spec__/normalizeSeed-spec.js
entry_types/scrolled/package/spec/support/normalizeSeed.js
entry_types/scrolled/package/src/contentElements/editor.js
entry_types/scrolled/package/src/contentElements/frontend.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.module.css
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineAudio/frontend.js
entry_types/scrolled/package/src/contentElements/inlineAudio/stories.js
entry_types/scrolled/package/src/contentElements/inlineVideo/stories.js
entry_types/scrolled/package/src/entryState/watchCollections.js
entry_types/scrolled/package/src/frontend/Audio.js
entry_types/scrolled/package/src/frontend/Audio.module.css
entry_types/scrolled/package/src/frontend/index.js

Seed data integration for audio files

---

packages/pageflow-react/src/loadingSpinner/components/MediaLoadingSpinner.jsx

Loading spinner image fov fix

---

entry_types/scrolled/package/src/frontend/transitions/revealConceal.module.css
entry_types/scrolled/package/src/frontend/transitions/revealFadeOut.module.css
entry_types/scrolled/package/src/frontend/transitions/revealFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/revealScrollOut.module.css
entry_types/scrolled/package/src/frontend/utils.module.css
package.json
rollup.config.js
yarn.lock

Improve Safari/IE 11 compatibility of reveal transitions

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/polyfills.js
yarn.lock

Install polyfills to make scrolled frontend work in IE 11

---

.github/workflows/docs.yml

Build storybook to Github pages

---

doc/contributing/rails_engine_development.md

Add troubleshooting section to Rails Engine Development docs

---

bin/build-edge

Current version throws error, because there is no frontend.js.
REDMINE-17606

Update edge script

---

admins/pageflow/user.rb
app/assets/javascripts/pageflow/admin/users.js
app/policies/pageflow/account_policy.rb
app/views/admin/users/_not_allowed_to_see_user_quota.html.erb
app/views/pageflow/admin/users/_quota_exhausted.html.erb
config/locales/new/user_quota.de.yml
config/locales/new/user_quota.en.yml
lib/pageflow/ability_mixin.rb
spec/controllers/admin/users_controller_spec.rb
spec/features/admin/inviting_a_user_spec.rb
spec/policies/pageflow/account_policy_spec.rb
spec/support/dominos/admin/invitation_form.rb
spec/support/helpers/quota_double.rb

Repair user invite form for admin users

---

admins/pageflow/entry.rb
app/assets/javascripts/pageflow/admin/entries.js
app/helpers/pageflow/admin/entries_helper.rb
app/models/pageflow/entry.rb
app/models/pageflow/entry_duplicate.rb
app/policies/pageflow/account_policy.rb
app/views/admin/entries/_attributes_table.html.arb
app/views/admin/entries/_not_allowed_to_see_entry_types.json.jbuilder
app/views/admin/entries/entry_types.json.jbuilder
config/locales/de.yml
config/locales/en.yml
config/locales/new/create_scrolled_entry.de.yml
config/locales/new/create_scrolled_entry.en.yml
config/locales/new/user_quota.de.yml
entry_types/paged/lib/pageflow_paged/plugin.rb
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/spec/support/config/pageflow.rb
lib/pageflow/ability_mixin.rb
lib/pageflow/configuration.rb
lib/pageflow/global_config_api.rb
spec/controllers/admin/entries_controller_spec.rb
spec/controllers/admin/users_controller_spec.rb
spec/features/account_publisher/adding_an_entry_spec.rb
spec/models/pageflow/entry_duplicate_spec.rb
spec/models/pageflow/entry_spec.rb
spec/pageflow/global_config_api_spec.rb
spec/policies/pageflow/account_policy_spec.rb
spec/support/dominos/admin/entry_form.rb

Create scrolled entries

---

bin/build-edge
bin/build-packages
pageflow.gemspec

Rewrite build scripts to use gemspec files

---

entry_types/scrolled/lib/tasks/pageflow_scrolled_tasks.rake

Enable scrolled entry type for storybook seed

---

entry_types/scrolled/package/src/editor/views/EditContentElementView.js
package/spec/editor/views/EditConfigurationView-spec.js
package/src/editor/views/EditConfigurationView.js

This enables merging adjacent text block elements when a common
neighbor is deleted.
REDMINE-17336, REDMINE-17429

Use batch action to destroy content elements

---

entry_types/scrolled/package/spec/collections-spec.js
entry_types/scrolled/package/src/collections.js

Ignore new records in watchCollection

---

admins/pageflow/membership.rb

Initially posted as a commit message by Tim.
REDMINE-17306

Add inline documentation to membership admin

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/editor/views/EditSectionTransitionView-spec.js
entry_types/scrolled/package/spec/frontend/transitions-spec.js
entry_types/scrolled/package/src/editor/models/Chapter.js
entry_types/scrolled/package/src/editor/views/EditSectionTransitionView.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/transitions/index.js
package/spec/ui/views/inputs/SelectInputView-spec.js
package/src/testHelpers/dominos/ui/inputs/Base.js
package/src/testHelpers/dominos/ui/inputs/SelectInput.js
package/src/ui/views/inputs/SelectInputView.js

* Ignore fade transitions between non full height sections.
* Disable fade transitions in edit form if adjacent sections are not
full height.
REDMINE-17338

Handle available section transitions

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/editor/api/ContentElementTypeRegistry-spec.js
entry_types/scrolled/package/spec/editor/controllers/PreviewMessageController-spec.js
entry_types/scrolled/package/spec/editor/models/ContentElement-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/spec/editor/views/InsertContentElementDialogView-spec.js
entry_types/scrolled/package/spec/frontend/Entry-spec.js
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/soundDisclaimer/editor.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/editor/api/ContentElementTypeRegistry.js
entry_types/scrolled/package/src/editor/config.js
entry_types/scrolled/package/src/editor/controllers/PreviewMessageController.js
entry_types/scrolled/package/src/editor/index.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/deleteContentElement.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/insertContentElement.js
entry_types/scrolled/package/src/editor/views/InsertContentElementDialogView.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.js
entry_types/scrolled/package/src/frontend/inlineEditing/__stories__/SelectionRect-stories.js
entry_types/scrolled/package/src/frontend/inlineEditing/postMessage.js

* Prevent inserting text blocks next to text blocks
* Prevent inserting text blocks with sticky position
* Use position of sibling when inserting content elements
REDMINE-17624

Add supportedPositions option for content element types

---

app/assets/stylesheets/pageflow/editor/composables.scss
entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/editor/views/EditMotifAreaDialogView-spec.js
entry_types/scrolled/package/src/editor/vendor/jquery.imgareaselect.js
entry_types/scrolled/package/src/editor/vendor/jquery.imgareaselect.module.css
entry_types/scrolled/package/src/editor/views/EditMotifAreaDialogView.js
entry_types/scrolled/package/src/editor/views/EditMotifAreaDialogView.module.css
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/editor/views/buttons.module.css
entry_types/scrolled/package/src/editor/views/icons.module.css
entry_types/scrolled/package/src/editor/views/mixins/dialogView.module.css
package/spec/editor/views/inputs/FileInputView-spec.js
package/src/editor/views/inputs/FileInputView.js

Allow editing motif areas in scrolled editor

---

entry_types/paged/packages/pageflow-paged/src/editor/models/PagedEntry.js
entry_types/paged/packages/pageflow-paged/src/editor/views/EntryPreviewView.js
entry_types/scrolled/package/spec/editor/views/EntryPreviewView-spec.js
entry_types/scrolled/package/src/editor/views/EntryPreviewView.js
entry_types/scrolled/package/src/editor/views/EntryPreviewView.module.css
package/src/editor/models/Entry.js
package/src/editor/views/EmulationModeButtonView.js
package/src/editor/views/SidebarFooterView.js

Add phone emulation mode to scrolled editor

---

entry_types/scrolled/package/spec/frontend/AudioPlayer-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
entry_types/scrolled/package/spec/frontend/usePlayerState-spec.js
entry_types/scrolled/package/spec/support/fakePlayerState.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/frontend/MediaPlayer/applyPlayerState.js
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
entry_types/scrolled/package/src/frontend/MediaPlayer/playerActions.js
entry_types/scrolled/package/src/frontend/MediaPlayer/updatePlayerState.js
entry_types/scrolled/package/src/frontend/MediaPlayer/usePlayerState.js
entry_types/scrolled/package/src/frontend/MediaPlayer/watchPlayer.js
package/src/frontend/media/createMediaPlayer.js

Media player state hook

---

entry_types/scrolled/package/spec/editor/controllers/PreviewMessageController-spec.js
entry_types/scrolled/package/spec/editor/views/EditContentElementView-spec.js
entry_types/scrolled/package/spec/frontend/useContentElementCommandSubscription/inEditorPreview-spec.js
entry_types/scrolled/package/spec/frontend/useContentElementCommandSubscription/inFrontend-spec.js
entry_types/scrolled/package/spec/frontend/useContentElementEditorState/inEditorPreview-spec.js
entry_types/scrolled/package/spec/frontend/useContentElementEditorState/inFrontend-spec.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/editor/controllers/PreviewMessageController.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/views/EditContentElementView.js
entry_types/scrolled/package/src/frontend/ContentElement.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementEditorCommandSubscriptionProvider.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementEditorStateProvider.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/EntryDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/postMessage.js
entry_types/scrolled/package/src/frontend/useContentElementAttributes.js
entry_types/scrolled/package/src/frontend/useContentElementEditorCommandSubscription.js
entry_types/scrolled/package/src/frontend/useContentElementEditorState.js
package/spec/editor/views/EditConfigurationView-spec.js
package/src/editor/views/EditConfigurationView.js

**Still contains all commits from #1439**
REDMINE-17627

Make delete button remove text block elements

---

entry_types/scrolled/package/src/frontend/Backdrop.js

`VideoPlayer` now requires `playerState` and `playerActions`.
REDMINE-17588

Fix backdrop video

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/frontend/transitions-spec.js
entry_types/scrolled/package/src/editor/views/SectionItemView.module.css
entry_types/scrolled/package/src/frontend/FillColor.js
entry_types/scrolled/package/src/frontend/FillColor.module.css
entry_types/scrolled/package/src/frontend/Fullscreen.js
entry_types/scrolled/package/src/frontend/SectionThumbnail.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css
entry_types/scrolled/package/src/frontend/transitions/index.js
entry_types/scrolled/package/src/frontend/transitions/previewScrollOut.module.css
yarn.lock

Allow overriding 100vh height of Fullscreen component

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/InlineBeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.module.css
entry_types/scrolled/package/src/frontend/Fullscreen.js
entry_types/scrolled/package/src/frontend/VideoPlayer.js
entry_types/scrolled/package/src/frontend/VideoPlayer.module.css
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.js
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.module.css
entry_types/scrolled/package/src/frontend/index.js
yarn.lock

Viewport dependent pillar boxes

---

entry_types/scrolled/doc/creating_content_elements.md
entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/spec/frontend/useContentElementLifecycle-spec.js
entry_types/scrolled/package/spec/support/ErrorCatching.js
entry_types/scrolled/package/spec/support/fakeIntersectionObserver.js
entry_types/scrolled/package/spec/support/index.js
entry_types/scrolled/package/src/frontend/ContentElement.js
entry_types/scrolled/package/src/frontend/SectionThumbnail.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useContentElementLifecycle.js

Add useContentElementLifecycle hook

---

entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/InlineBeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/frontend.js

Replace useOnScreen with useContentElementLifecycle in before/after

---

entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.module.css
entry_types/scrolled/package/src/contentElements/dataWrapperChart/frontend.js

Chart content element fixes

---

entry_types/scrolled/package/.storybook/preview-head.html
entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/videojsBase.module.css
entry_types/scrolled/package/src/frontend/VideoPlayer.js
entry_types/scrolled/package/src/frontend/VideoPlayer.module.css
entry_types/scrolled/package/src/frontend/__stories__/MediaPlayer-stories.js

Make backdrop videos cover

---

entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/spec/frontend/ViewportDependentPillarBoxes-spec.js
entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js
entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.module.css
entry_types/scrolled/package/src/frontend/VideoPlayer.js
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.js
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.module.css

Display black pillar boxes for full width embed videos

---

entry_types/scrolled/package/spec/frontend/AudioPlayer-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineAudio/frontend.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/frontend.js
entry_types/scrolled/package/src/frontend/AudioPlayer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
entry_types/scrolled/package/src/frontend/VideoPlayer.js

Use lifecycle hook in media content elements

---

entry_types/scrolled/package/spec/frontend/AudioPlayer-spec.js
entry_types/scrolled/package/spec/frontend/Backdrop-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
entry_types/scrolled/package/spec/frontend/PlayerContainer-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
entry_types/scrolled/package/spec/support/fakeMedia.js
entry_types/scrolled/package/spec/support/normalizeSeed.js
entry_types/scrolled/package/src/frontend/AudioPlayer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
entry_types/scrolled/package/src/frontend/VideoPlayer.js

Introduce fakeMedia test helpers

---

entry_types/paged/packages/pageflow-paged/jest.config.js
entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/jest.config.js
entry_types/scrolled/package/spec/editor/models/SectionConfiguration-spec.js
entry_types/scrolled/package/spec/frontend/Backdrop-spec.js
entry_types/scrolled/package/spec/support/matchMediaStub.js
entry_types/scrolled/package/src/editor/models/SectionConfiguration.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/Image.js
entry_types/scrolled/package/src/frontend/Image.module.css
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/useMediaQuery.js
entry_types/scrolled/package/src/frontend/usePortraitOrientation.js
package/jest.config.js

Add imageMobile configuration for section

---

entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/MotifArea.js
entry_types/scrolled/package/src/frontend/Section.js

Rerender when motif area changes

---

entry_types/scrolled/package/src/frontend/PlayerControls/ControlBar.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.js
entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/Toolbar.module.css
entry_types/scrolled/package/src/frontend/navigation/AppHeader.js

Prevent display of horizontal scroll bar

---

entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/index.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/InlineBeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
entry_types/scrolled/package/src/contentElements/inlineImage/frontend.js

Lazy load inline images

---

entry_types/scrolled/package/spec/frontend/Image-spec.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
entry_types/scrolled/package/src/frontend/Image.js

Use smaller variants for inline images

---

entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js

Fix external link file selection handler referer

---

entry_types/scrolled/package/src/editor/models/SectionConfiguration.js
entry_types/scrolled/package/src/frontend/Section.module.css

Improve section defaults

---

entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/__stories__/transitions-stories.js

Add stories for appearance/layout/positions

---

entry_types/scrolled/package/src/frontend/MediaPlayer/playerActions.js
entry_types/scrolled/package/src/frontend/MediaPlayerControls.js

Bless Pool Players through play button

---

entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css

Inverted shadows

---

entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css

Inverted cards

---

app/assets/stylesheets/pageflow/ui/tooltip.scss

Remove x positioning CSS for editor tooltip 

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/editor/api/ContentElementTypeRegistry-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/frontend/features/insertContentElementMessage-spec.js
entry_types/scrolled/package/spec/frontend/features/sectionPadding-spec.js
entry_types/scrolled/package/spec/support/pageObjects.js
entry_types/scrolled/package/src/editor/api/ContentElementTypeRegistry.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/frontend/Foreground.js
entry_types/scrolled/package/src/frontend/Foreground.module.css
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementInsertButton.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementInsertButton.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/LayoutWithPlaceholder.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/components.js
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/index.js

Display insert button when section is selected

---

entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css

Add invert-option support for GradientBox

---

entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/stories.js
entry_types/scrolled/package/src/frontend/Section.js

Support headings of different levels

---

config/locales/new/loading_spinner_animation_time.de.yml
config/locales/new/loading_spinner_animation_time.en.yml
entry_types/paged/packages/pageflow-paged-react/src/loadingSpinner/components/MediaLoadingSpinner.jsx
entry_types/paged/packages/pageflow-paged-react/src/loadingSpinner/components/TitleLoadingSpinner.jsx
package/src/editor/views/widgetTypes/mediaLoadingSpinner.js
package/src/editor/views/widgetTypes/titleLoadingSpinner.js

Loading spinner configurable animation time

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/entryState/useAvailableQualities-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/useSetting-spec.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/entryState/index.js
entry_types/scrolled/package/src/entryState/useAvailableQualities.js
entry_types/scrolled/package/src/entryState/watchCollections.js
entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
entry_types/scrolled/package/src/frontend/VideoPlayerControls.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useSetting.js
entry_types/scrolled/package/src/frontend/useVideoQualitySetting.js

Add quality menu to inline video player controls

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/entryState/useFile-spec.js
entry_types/scrolled/package/spec/entryState/useNestedFiles-spec.js
entry_types/scrolled/package/spec/frontend/AudioPlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/useTextTracks-spec.js
entry_types/scrolled/package/spec/support/normalizeSeed.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/entryState/extendFile.js
entry_types/scrolled/package/src/entryState/index.js
entry_types/scrolled/package/src/entryState/useFile.js
entry_types/scrolled/package/src/entryState/useNestedFiles.js
entry_types/scrolled/package/src/entryState/watchCollections.js
entry_types/scrolled/package/src/frontend/AudioPlayerControls.js
entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
entry_types/scrolled/package/src/frontend/PlayerControls/MenuBarButton.js
entry_types/scrolled/package/src/frontend/PlayerControls/index.js
entry_types/scrolled/package/src/frontend/VideoPlayerControls.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useTextTracks.js
yarn.lock

Add text tracks menu to player controls

---

entry_types/scrolled/package/spec/collections-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer/textTracks-spec.js
entry_types/scrolled/package/spec/frontend/useMediaMuted-spec.js
entry_types/scrolled/package/spec/support/fakeMedia.js
entry_types/scrolled/package/src/collections.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/frontend/AudioPlayer.js
entry_types/scrolled/package/src/frontend/AudioPlayer.module.css
entry_types/scrolled/package/src/frontend/Entry.js
entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
entry_types/scrolled/package/src/frontend/MediaPlayer/textTracks.js
entry_types/scrolled/package/src/frontend/MediaPlayer/textTracks.module.css
entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
entry_types/scrolled/package/src/frontend/MutedContext.js
entry_types/scrolled/package/src/frontend/VideoPlayer.js
entry_types/scrolled/package/src/frontend/useMediaMuted.js
package/spec/frontend/media/MediaPool_spec.js
package/spec/frontend/media/media_spec.js
package/src/frontend/media/MediaPool.js
package/src/frontend/media/media.js

Display text tracks in inline videos and audios

---

entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer/sources-spec.js
entry_types/scrolled/package/src/frontend/VideoPlayer/index.js
entry_types/scrolled/package/src/frontend/VideoPlayer/sources.js
entry_types/scrolled/package/src/frontend/useVideoQualitySetting.js

Read video quality setting and assemble sources accordingly.
REDMINE-17678

Use active quality in VideoPlayer

---

entry_types/scrolled/package/spec/frontend/ViewportDependentPillarBoxes-spec.js
entry_types/scrolled/package/src/frontend/VideoPlayer/index.js
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.js
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.module.css

Prevent newly inserted video content element from collapsing.
REDMINE-17742

Display black poster in empty inline video

---

entry_types/scrolled/package/src/frontend/MediaPlayerControls.js
entry_types/scrolled/package/src/frontend/PlayerControls/ControlBar.module.css
entry_types/scrolled/package/src/frontend/PlayerControls/ProgressIndicators.js
entry_types/scrolled/package/src/frontend/PlayerControls/ProgressIndicators.module.css
entry_types/scrolled/package/src/frontend/PlayerControls/index.js
entry_types/scrolled/package/src/frontend/__stories__/playerControls-stories.js

Make player controls visible on boxes

---

entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/frontend/ContentElement.js
entry_types/scrolled/package/src/frontend/ContentElement.module.css
entry_types/scrolled/package/src/frontend/ContentElementMargin.module.css
entry_types/scrolled/package/src/frontend/ContentElements.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/InvisibleBoxWrapper.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/InvisibleBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/NoOpBoxWrapper.js
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css
entry_types/scrolled/package/src/frontend/layouts/index.js
entry_types/scrolled/package/src/frontend/useNarrowViewport.js

Improve cards appearance variant

---

entry_types/scrolled/package/spec/frontend/Image-spec.js
entry_types/scrolled/package/spec/support/normalizeSeed.js
entry_types/scrolled/package/src/frontend/Image.js
package/spec/editor/models/mixins/transientReferences-spec.js
package/src/editor/models/mixins/transientReferences.js

Allow selecting processing images

---

entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css

Use black links in black text.
REDMINE-17758

Make link color match inverted text color

---

entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/lib/pageflow_scrolled/engine.rb
entry_types/scrolled/package/spec/frontend/features/changeSectionEvent-spec.js
entry_types/scrolled/package/src/frontend/Entry.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/registerTemplateWidgetType.js
entry_types/scrolled/package/src/frontend/sectionChangeMessagePoster.js
entry_types/scrolled/package/src/frontend/useSectionChangeEvents.js
entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
package/src/frontend/polyfills.js
spec/support/pageflow/lint/entry_type.rb

Widgets for scrolled entries

---

entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/soundDisclaimer/SoundDisclaimer.module.css
entry_types/scrolled/package/src/frontend/MediaPlayer.module.css
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js

Improve inline media

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/frontend/EditableInlineText-spec.js
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableInlineText-spec.js
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableText-spec.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/soundDisclaimer/editor.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/editor/config.js
entry_types/scrolled/package/src/editor/index.js
entry_types/scrolled/package/src/editor/views/NoOptionsHintView.js
entry_types/scrolled/package/src/editor/views/NoOptionsHintView.module.css
entry_types/scrolled/package/src/frontend/EditableInlineText.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/TextPlaceholder.js
entry_types/scrolled/package/src/frontend/inlineEditing/TextPlaceholder.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/components.js
entry_types/scrolled/package/src/frontend/useContentElementAttributes.js
entry_types/scrolled/spec/features/entry_editor/editing_a_content_element_spec.rb
entry_types/scrolled/spec/support/dominos/scrolled_entry.rb

* Make headings inline editable
* Display placeholder when headings or text blocks are blank
REDMINE-17519

Improve inline editing

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml

Do not talk about pages in scrolled atmo inline help

---

entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/editor/seed_html_helper_spec.rb

Improve widget scope handling for scrolled entries

---

.rubocop.yml
admins/pageflow/accounts.rb
admins/pageflow/entry_templates.rb
app/models/pageflow/account.rb
app/models/pageflow/entry_template.rb
app/policies/pageflow/entry_template_policy.rb
app/views/admin/accounts/_entry_template_details.html.arb
app/views/admin/accounts/_form.html.erb
app/views/admin/entry_templates/_form.html.erb
app/views/components/pageflow/admin/entry_templates_tab.rb
config/initializers/admin_resource_tabs.rb
config/locales/new/edit_entry_templates.de.yml
config/locales/new/edit_entry_templates.en.yml
db/migrate/20200515112500_add_constraints_to_entry_templates.rb
lib/pageflow/ability_mixin.rb
spec/controllers/admin/accounts_controller_spec.rb
spec/controllers/admin/entry_templates_controller_spec.rb
spec/factories/entry_templates.rb
spec/features/account_manager/editing_an_account_spec.rb
spec/features/account_manager/editing_an_entry_template_spec.rb
spec/policies/pageflow/entry_template_policy_spec.rb
spec/support/dominos/admin/entry_template_form.rb
spec/support/dominos/admin/entry_templates_tab.rb
spec/views/components/pageflow/admin/entry_templates_tab_spec.rb

Make entry templates editable

---

entry_types/scrolled/package/spec/frontend/Atmo-spec.js
entry_types/scrolled/package/src/frontend/Atmo.js
entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useAtmo.js
package/spec/frontend/documentHiddenState_spec.js
package/src/frontend/documentHiddenState.js
package/src/frontend/index.js
package/src/frontend/media/MultiPlayer.js

Media in background

---

entry_types/scrolled/package/spec/frontend/MediaPlayer-spec.js
entry_types/scrolled/package/spec/frontend/useEventContextData-spec.js
entry_types/scrolled/package/spec/support/rendering.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/MediaPlayer/PlayerContainer.js
entry_types/scrolled/package/src/frontend/MediaPlayer/index.js
entry_types/scrolled/package/src/frontend/useAtmo.js
entry_types/scrolled/package/src/frontend/useEventContextData.js
entry_types/scrolled/package/src/frontend/useSectionChangeEvents.js
package/spec/frontend/media/media_spec.js
package/src/frontend/VideoPlayer/mediaEvents.js
package/src/frontend/media/MediaPool.js
package/src/frontend/media/createMediaPlayer.js

Media player context data

---

entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js

Images are not cropped. So there is nothing to position.
REDMINE-17840

Hide background position option for inline image

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/editor/views/EntryPreviewView-spec.js
entry_types/scrolled/package/src/editor/views/BlankEntryView.js
entry_types/scrolled/package/src/editor/views/BlankEntryView.module.css
entry_types/scrolled/package/src/editor/views/EntryPreviewView.js

Add blank slate for scrolled entries

---

admins/pageflow/entry_templates.rb
app/models/pageflow/account.rb
app/models/pageflow/entry.rb
app/models/pageflow/entry_template.rb
app/views/admin/accounts/_entry_template_details.html.arb
app/views/admin/entry_templates/_form.html.erb
app/views/components/pageflow/admin/entry_templates_tab.rb
config/locales/new/edit_entry_templates.de.yml
config/locales/new/edit_entry_templates.en.yml
db/migrate/20200807135200_rename_pageflow_entry_template_entry_type_to_entry_type_name.rb
spec/controllers/admin/entry_templates_controller_spec.rb
spec/factories/accounts.rb
spec/factories/entry_templates.rb
spec/features/account_manager/editing_an_entry_template_spec.rb
spec/models/pageflow/entry_spec.rb
spec/views/components/pageflow/admin/entry_templates_tab_spec.rb

Config for entry template

---

app/helpers/pageflow/structured_data_helper.rb
entry_types/paged/app/views/pageflow_paged/entries/_entry.html.erb
entry_types/paged/spec/controllers/pageflow_paged/entries_controller_spec.rb
entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry.json.jbuilder
entry_types/scrolled/package/spec/frontend/AudioPlayer/structuredData-spec.js
entry_types/scrolled/package/spec/frontend/Image-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer/structuredData-spec.js
entry_types/scrolled/package/spec/frontend/utils/iso8601-spec.js
entry_types/scrolled/package/spec/frontend/utils/urls-spec.js
entry_types/scrolled/package/spec/support/jsonLdQueries.js
entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
entry_types/scrolled/package/src/entryState/watchCollections.js
entry_types/scrolled/package/src/frontend/AudioPlayer/AudioStructuredData.js
entry_types/scrolled/package/src/frontend/AudioPlayer/index.js
entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/Image.js
entry_types/scrolled/package/src/frontend/ImageStructuredData.js
entry_types/scrolled/package/src/frontend/StructuredData.js
entry_types/scrolled/package/src/frontend/VideoPlayer/VideoStructuredData.js
entry_types/scrolled/package/src/frontend/VideoPlayer/index.js
entry_types/scrolled/package/src/frontend/utils/iso8601.js
entry_types/scrolled/package/src/frontend/utils/urls.js
entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
spec/helpers/pageflow/structured_data_helper_spec.rb

Structured data for scrolled entries

---

app/assets/stylesheets/pageflow/editor/emulation_mode_button.scss
app/assets/stylesheets/pageflow/editor/help.scss
app/assets/stylesheets/pageflow/ui/tooltip.scss
config/locales/new/phone_preview_toggle.de.yml
config/locales/new/phone_preview_toggle.en.yml
package/src/editor/templates/emulationModeButton.jst
package/src/editor/views/EmulationModeButtonView.js
package/src/ui/views/TooltipView.js
package/src/ui/views/mixins/tooltipContainer.js

Increase discoverability by always showing the desktop phone icons. Before
the other first had to expand the menu to see the options.
REDMINE-17857

Turn emulation menu into toggle

---

config/locales/new/locale_inline_help.de.yml
config/locales/new/locale_inline_help.en.yml
entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml

* Inline help for entry locale
* Better labels text for invert section option
* Better inline help for full viewport height section option
REDMINE-17841

Improve editor inline help and labels

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/editor/views/ChapterItemView.js
entry_types/scrolled/package/src/editor/views/ChapterItemView.module.css
entry_types/scrolled/package/src/editor/views/SectionItemView.js
entry_types/scrolled/package/src/editor/views/SectionItemView.module.css
entry_types/scrolled/package/src/editor/views/icons.module.css
entry_types/scrolled/package/src/editor/views/outline.module.css

Possibility to reorder chapters and items is otherwise hard to
discover.
REDMINE-17873

Drag handles for chapter and section outline items

---

entry_types/scrolled/config/initializers/help_entries.rb
entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/editor/views/EditMotifAreaDialogView.js
entry_types/scrolled/package/src/editor/views/EditMotifAreaDialogView.module.css
entry_types/scrolled/package/src/editor/views/colors.module.css
entry_types/scrolled/package/src/editor/views/icons.module.css

Link to help entry from motif area dialog

---

entry_types/scrolled/doc/creating_content_elements.md
entry_types/scrolled/lib/tasks/pageflow_scrolled_tasks.rake

Fix storybook documentation

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/frontend/Backdrop-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/MotifArea-spec.js
entry_types/scrolled/package/spec/support/normalizeSeed.js
entry_types/scrolled/package/spec/support/rendering.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/Backdrop.js
entry_types/scrolled/package/src/frontend/MotifArea.js

Add motif area support for background videos

---

entry_types/scrolled/package/spec/contentElements/dataWrapperChart/useIframeHeight-spec.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/useIframeHeight.js

Add caption and position options to chart element

---

entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/contentElements/textBlock/frontend.js
entry_types/scrolled/package/src/frontend/api/ContentElementTypeRegistry.js
entry_types/scrolled/package/src/frontend/inlineEditing/TextPlaceholder.js
entry_types/scrolled/package/src/frontend/inlineEditing/TextPlaceholder.module.css
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css

Prevent overlapping floated elements in centered layout

---

entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb

Those were left over from imported prototype HTML.
REDMINE-18021

Replace hard coded title and meta tags

---

entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js

Align with video element behavior.
REDMINE-18018

Fade out audio element when deactivating

---

entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css

Fix external links layout narrow screen sizes

---

entry_types/scrolled/package/src/entryState/sharing.js

change Email to Mail

---

entry_types/scrolled/config/locales/new/en.yml

Add missing translation

---

.travis.yml
README.md
spec/support/pageflow/dummy/app.rb
spec/support/pageflow/dummy/exit_on_failure_patch.rb

Fix CI and abort when dummy app generation fails

---

entry_types/scrolled/doc/creating_themes.md
entry_types/scrolled/package/src/frontend/navigation/Logo.js
lib/pageflow/themes.rb

Logo link through theme option

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css

Heading word-wrap and hyphen css

---

entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css

Fixed before after height issue

---

entry_types/scrolled/package/src/frontend/navigation/Logo.js

Open logo link in new tab

---

entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/spec/frontend/features/useAudioFocus-spec.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/PlayerControls/WaveformPlayerControls/Wavesurfer.js
entry_types/scrolled/package/src/frontend/RootProviders.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useAudioFocus.js

Prevent parallel playback of media elements

---

entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.module.css
entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
entry_types/scrolled/package/src/frontend/navigation/Logo.js
entry_types/scrolled/package/src/frontend/navigation/SkipLinks.js

Show logo focus outline

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/frontend/utils/blank-spec.js
entry_types/scrolled/package/src/frontend/navigation/AppHeader.js
entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js
entry_types/scrolled/package/src/frontend/utils/blank.js
yarn.lock

Improve handling of untitled chapters

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/collections-spec.js
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/entryState/updateContentElementConfiguration-spec.js
entry_types/scrolled/package/src/collections.js
entry_types/scrolled/package/src/entryState/EntryStateProvider.js
entry_types/scrolled/package/src/entryState/extendFile.js
entry_types/scrolled/package/src/entryState/index.js
entry_types/scrolled/package/src/entryState/legalInfo.js
entry_types/scrolled/package/src/entryState/metadata.js
entry_types/scrolled/package/src/entryState/sharing.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/entryState/theme.js
entry_types/scrolled/package/src/entryState/useFile.js
entry_types/scrolled/package/src/entryState/useNestedFiles.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/ContentElements.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/SectionThumbnail.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/layouts/index.js
entry_types/scrolled/package/src/frontend/navigation/AppHeader.js
entry_types/scrolled/package/src/frontend/useBoundingClientRect.js
entry_types/scrolled/package/src/frontend/useMotifAreaState.js
yarn.lock

Optimize frontend rendering

---

entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css

BeforeAfter safari animation fix

---

app/assets/stylesheets/pageflow/ui/forms.scss
entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/frontend/useMotifAreaState-spec.js
entry_types/scrolled/package/spec/support/createElementWithDimension.js
entry_types/scrolled/package/src/editor/models/SectionConfiguration.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css
entry_types/scrolled/package/src/frontend/useBoundingClientRect.js
entry_types/scrolled/package/src/frontend/useMotifAreaState.js
package/spec/ui/views/inputs/CheckBoxInputView-spec.js
package/spec/ui/views/inputs/TextInputView-spec.js
package/spec/ui/views/mixins/inputView-spec.js
package/src/ui/views/inputs/CheckBoxInputView.js
package/src/ui/views/inputs/SliderInputView.js
package/src/ui/views/mixins/inputView.js
package/src/ui/views/mixins/inputWithPlaceholderText.js

Add options for gradient opacity/motif area exposure

---

entry_types/scrolled/config/locales/new/de.yml

Extend german help texts

---

entry_types/scrolled/config/locales/new/de.yml
entry_types/scrolled/config/locales/new/en.yml
entry_types/scrolled/package/spec/frontend/features/selectedMessage-spec.js
entry_types/scrolled/package/spec/support/pageObjects.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.module.css

Remove edit button to make editing sections easier.

Show section settings directly when section is selected

---

entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js

Apply default configuration when adding to end of section

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/frontend/features/changeSectionEvent-spec.js
entry_types/scrolled/package/spec/frontend/features/changeURLFragment-spec.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/Entry.js
entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js
yarn.lock

Chapter deep linking for scrolled entries

---

entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css

Fix for unstable navigation bar on Safari

---

entry_types/scrolled/package/src/frontend/VideoPlayer/sources.js

Used for debugging.
REDMINE-18067

Allow disabling video or dash via browser feature flag

---

entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/package/src/frontend/Backdrop.module.css
entry_types/scrolled/package/src/frontend/Entry.module.css
entry_types/scrolled/package/src/frontend/FillColor.module.css
entry_types/scrolled/package/src/frontend/Foreground.module.css
entry_types/scrolled/package/src/frontend/Fullscreen.module.css
entry_types/scrolled/package/src/frontend/Section.module.css
entry_types/scrolled/package/src/frontend/ViewportDependentPillarBoxes.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBox.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBox.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
entry_types/scrolled/package/src/frontend/navigation/HamburgerIcon.module.css
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css

* Hide navigation elements
* Make text black on white
* Inline backdrops and remove gradients
* Avoid page breaks inside content elements
REDMINE-17394

Basic styles for print layout of scrolled entries

---

doc/troubleshooting.md
entry_types/paged/packages/pageflow-paged/spec/frontend/cookie_notice-spec.js
entry_types/paged/packages/pageflow-paged/src/frontend/cookieNotice.js
spec/features/visitor/reading_entry_spec.rb
spec/support/dominos/cookie_notice_bar.rb

When moving some files, inadvertently, this was deleted and went
unnoticed.
REDMINE-18247

Wait until listener is ready before requesting cookie notice

---

entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.module.css

Improve before/after wiggle animation

---

entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css

Prevent horizontal overflow.
REDMINE-18427

Hyphenate long text block headers

---

app/assets/stylesheets/pageflow/themes/default/page.scss

Add theme option for content text phone typography

---

entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
package/spec/ui/views/inputs/UrlInputView-spec.js
package/src/ui/views/inputs/UrlInputView.js

Prevent concurrent save requests for embed urls

---

entry_types/scrolled/lib/tasks/pageflow_scrolled_tasks.rake

Add equirectangular panorama images to storybook seed

---

entry_types/scrolled/config/locales/new/wide_headers.de.yml
entry_types/scrolled/config/locales/new/wide_headers.en.yml
entry_types/scrolled/package/spec/collections-spec.js
entry_types/scrolled/package/spec/editor/models/ContentElement-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/spec/entryState/updateContentElementConfiguration-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/frontend/features/useContentElementConfigurationUpdate-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/collections.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Add position wide for heading content elements

---

entry_types/scrolled/package/src/frontend/navigation/ChapterLink.js
entry_types/scrolled/package/src/frontend/navigation/ChapterLink.module.css

Remove chapter number from chapter box

---

lib/pageflow/entry_type_configuration.rb
spec/pageflow/global_config_api_spec.rb

Not all file importers might be applicable for all entry types.
REDMINE-18696

Allow registering entry type specific file importers

---

entry_types/scrolled/lib/pageflow_scrolled/engine.rb
entry_types/scrolled/lib/tasks/pageflow_scrolled/create_bundle_symlinks_for_yarn.rake
entry_types/scrolled/spec/support/helpers/rake_test_helper.rb
entry_types/scrolled/spec/support/helpers/suppress_output_test_helper.rb
entry_types/scrolled/spec/tasks/pageflow_scrolled/create_bundle_symlinks_for_yarn_task_spec.rb
entry_types/scrolled/spec/tasks/pageflow_scrolled/storybook_tasks_spec.rb

Support non-root packages in create_bundle_symlinks_for_yarn tasks

---

entry_types/scrolled/package/package.json
yarn.lock

see https://github.com/videojs/video.js/pull/7247
REDMINE-18771

Update Video.js for SSR fix

---

app/assets/stylesheets/pageflow/ui.scss
app/assets/stylesheets/pageflow/ui/forms.scss
app/assets/stylesheets/pageflow/ui/validation_error_messages.scss
package/package.json
package/spec/ui/models/mixins/serverSideValidation-spec.js
package/spec/ui/views/mixins/viewWithValidationErrorMessages-spec.js
package/src/ui/index.js
package/src/ui/models/mixins/serverSideValidation.js
package/src/ui/views/inputs/TextInputView.js
package/src/ui/views/mixins/viewWithValidationErrorMessages.js
yarn.lock

Read validation errors from `errors` field in server response.
REDMINE-18761

Allow displaying server side validation on text field

---

package/spec/ui/views/mixins/inputView-spec.js
package/src/ui/views/mixins/inputView.js

Set CSS class on input view element when disabled

---

app/assets/stylesheets/pageflow/themes/default/page/shadow.scss

Add theme option to display image on page shadow

---

app/assets/stylesheets/pageflow/themes/default/page/shadow.scss

Still hide image when text is hidden or video is playing.
REDMINE-18778

Do not couple page shadow image to shadow opacity

---

app/assets/stylesheets/pageflow/themes/default/logo/alignment.scss

Add theme option to change left position of logo

---

app/assets/stylesheets/pageflow/themes/default/base.scss
app/assets/stylesheets/pageflow/themes/default/consent_bar.scss
config/locales/new/consent.de.yml
config/locales/new/consent.en.yml
entry_types/paged/packages/pageflow-paged-react/spec/support/flushPromises.js
entry_types/paged/packages/pageflow-paged-react/src/__spec__/consent-spec.js
entry_types/paged/packages/pageflow-paged-react/src/boot.js
entry_types/paged/packages/pageflow-paged-react/src/consent/actions.js
entry_types/paged/packages/pageflow-paged-react/src/consent/components/ConsentBar.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/createReducer.js
entry_types/paged/packages/pageflow-paged-react/src/consent/index.js
entry_types/paged/packages/pageflow-paged-react/src/consent/selectors.js
entry_types/paged/packages/pageflow-paged-react/src/index.js
entry_types/paged/packages/pageflow-paged/src/frontend/boot.js
lib/pageflow/built_in_widget_type.rb
lib/pageflow/built_in_widget_types_plugin.rb
package/spec/frontend/consent_spec.js
package/spec/support/flushPromises.js
package/src/editor/index.js
package/src/editor/views/widgetTypes/consentBar.js
package/src/frontend/Consent.js
package/src/frontend/index.js

Introduce consent concept

---

app/assets/stylesheets/pageflow/themes/default/consent_bar.scss
entry_types/paged/packages/pageflow-paged-react/src/__spec__/consent-spec.js
entry_types/paged/packages/pageflow-paged-react/src/consent/actions.js
entry_types/paged/packages/pageflow-paged-react/src/consent/components/ConsentBar.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/__spec__/ConsentBar-spec.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/createReducer.js
entry_types/paged/packages/pageflow-paged-react/src/consent/index.js
entry_types/paged/packages/pageflow-paged-react/src/consent/selectors.js
package/spec/frontend/consent_spec.js
package/src/frontend/Consent.js

Consent toggles

---

entry_types/scrolled/config/locales/de.yml
entry_types/scrolled/config/locales/en.yml

Add missing translation for VR content element

---

.rubocop.yml
app/models/pageflow/customized_theme.rb
app/models/pageflow/draft_entry.rb
app/models/pageflow/entry_at_revision.rb
app/models/pageflow/published_entry.rb
app/models/pageflow/theme_customization.rb
app/models/pageflow/theme_customization_file.rb
db/migrate/20210528073122_create_pageflow_theme_customizations.rb
db/migrate/20210531090654_create_pageflow_theme_customization_files.rb
db/migrate/20210531102228_add_selected_file_ids_to_theme_customizations.rb
doc/customizing_themes.md
entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_theme.json.jbuilder
entry_types/scrolled/lib/pageflow_scrolled.rb
entry_types/scrolled/package/src/frontend/navigation/AppHeader.module.css
entry_types/scrolled/spec/fixtures/image.svg
entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb
entry_types/scrolled/spec/spec_helper.rb
lib/pageflow.rb
lib/pageflow/entry_type.rb
lib/pageflow/theme_customizations.rb
spec/factories/published_entries.rb
spec/pageflow/theme_customizations_spec.rb
spec/spec_helper.rb
spec/support/helpers/test_paperclip_processor.rb

Allow customizing themes at runtime.
REDMINE-18710

Theme customization

---

entry_types/paged/packages/pageflow-paged-react/src/consent/components/Settings.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/__spec__/Settings-spec.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/index.js
entry_types/paged/packages/pageflow-paged-react/src/index.js
package/spec/frontend/Consent/Persistence_spec.js
package/spec/frontend/Consent_spec.js
package/src/frontend/Consent/Persistence.js
package/src/frontend/Consent/index.js
package/src/frontend/index.js

Consent settings

---

app/assets/stylesheets/pageflow/themes/default/base.scss
app/assets/stylesheets/pageflow/themes/default/consent.scss
app/assets/stylesheets/pageflow/themes/default/consent/bar.scss
app/assets/stylesheets/pageflow/themes/default/consent/vendor_list.scss
entry_types/paged/packages/pageflow-paged-react/src/__spec__/consent-spec.js
entry_types/paged/packages/pageflow-paged-react/src/components/icons/ToggleOff.jsx
entry_types/paged/packages/pageflow-paged-react/src/components/icons/ToggleOn.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/ConsentBar.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/Settings.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/Toggle.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/VendorList.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/__spec__/ConsentBar-spec.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/components/__spec__/Settings-spec.jsx
entry_types/paged/packages/pageflow-paged-react/src/consent/index.js
package/spec/frontend/Consent_spec.js
package/src/frontend/Consent/Persistence.js
package/src/frontend/Consent/index.js

Improve consent UI

---

config/locales/new/transliterate.de.yml

Friendly ID only applies changes to existing entries when titles
change.
REDMINE-19010

Transliterate German Umlauts in entry slugs

---

entry_types/scrolled/config/locales/de.yml
entry_types/scrolled/config/locales/en.yml
entry_types/scrolled/config/locales/new/before_after_slider.de.yml
entry_types/scrolled/config/locales/new/before_after_slider.en.yml
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/BeforeAfter.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/stories.js

Providing the handle ensures better accessibility.
REDMINE-19006

Remove option hide before/after handles

---

entry_types/scrolled/package/src/frontend/FitViewport.module.css

Ensure text in placeholder is white even if section is inverted.
REDMINE-18993

Ensure contrast of text in embed opt-in

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/src/contentElements/vrImage/VrImage.js
entry_types/scrolled/package/src/contentElements/vrImage/stories.js
entry_types/scrolled/package/src/contentElements/vrImage/useAutoCruising.js
entry_types/scrolled/package/src/frontend/Panorama/FullscreenIndicator.js
entry_types/scrolled/package/src/frontend/Panorama/FullscreenIndicator.module.css
entry_types/scrolled/package/src/frontend/Panorama/PanoramaIndicator.js
entry_types/scrolled/package/src/frontend/Panorama/PanoramaIndicator.module.css
entry_types/scrolled/package/src/frontend/Panorama/Viewer.js
entry_types/scrolled/package/src/frontend/Panorama/Viewer.module.css
entry_types/scrolled/package/src/frontend/icons/arrowLeft.svg
entry_types/scrolled/package/src/frontend/icons/arrowRight.svg
yarn.lock

* Slowly pan panorama until it is interacted with
* Display a panorama indicator until first interaction on desktop and
tablets.
* Display a centered fullscreen button on phone to make it easy to
enter gyroscope mode.
REDMINE-19009

Make it easier to recognize 360° images

---

entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry.json.jbuilder
entry_types/scrolled/config/locales/new/consent.de.yml
entry_types/scrolled/config/locales/new/consent.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/src/contentElements/dataWrapperChart/DataWrapperChart.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/frontend.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb

Render enabled feature names in scrolled seed and set up `features`
object from core package.
REDMINE-19039

Add feature flag to disable scrolled chart opt-in

---

entry_types/scrolled/package/spec/frontend/features/thirdPartyConsent-spec.js
package/spec/frontend/Consent/Persistence_spec.js
package/spec/frontend/cookies-spec.js
package/src/frontend/Consent/Persistence.js
package/src/frontend/cookies.js

* Set expires option to prevent only setting a session cookie.
* Set SameSite and Secure options to ensure cookie can be read from
iframe embed
REDMINE-19062

Fix consent cookie options

---

entry_types/scrolled/package/spec/editor/controllers/PreviewMessageController-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/editor/controllers/PreviewMessageController.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/Batch.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/moveContentElement.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementEditorStateProvider.js
entry_types/scrolled/package/src/frontend/inlineEditing/DropTargets.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/DropTargets.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditorState.js
entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/postMessage.js

Allow moving text block ranges

---

spec/support/pageflow/used_file_test_helper.rb

Match FactoryBot API.
REDMINE-19000

Allow passing traits to create_used_file

---

entry_types/scrolled/config/locales/new/portrait_inline_image.de.yml
entry_types/scrolled/config/locales/new/portrait_inline_image.en.yml
entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/thirdPartyConsent/OptIn.js
entry_types/scrolled/package/src/frontend/usePortraitOrientation.js

Make `usePortraitOrientation` public API. Allow rendering different
image based on orientation.
REDMINE-19186

Add portrait image option to inline image

---

app/models/pageflow/customized_theme.rb
app/models/pageflow/entry_at_revision.rb
lib/pageflow/configuration.rb
lib/pageflow/entry_type_configuration.rb
spec/pageflow/theme_customizations_spec.rb

Allow transforming theme customizations

---

entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js

Allow more position options for content elements

---

entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/frontend/EditableText.js
entry_types/scrolled/package/src/frontend/Text.module.css
entry_types/scrolled/spec/helpers/pageflow_scrolled/themes_helper_spec.rb

Render typography CSS rules based on scrolled theme options

---

entry_types/scrolled/app/helpers/pageflow_scrolled/webpack_public_path_helper.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/webpack_public_path_helper_spec.rb

Support proc as asset host

---

entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css

[WIP] Prevent shadow flickering while scrolling on iOS 14

---

admins/pageflow/entry.rb
app/policies/pageflow/entry_policy.rb
lib/pageflow/ability_mixin.rb
spec/controllers/admin/entries_controller_spec.rb
spec/helpers/pageflow/admin/entries_helper_spec.rb
spec/policies/pageflow/entry_policy_spec.rb

For now we do not want to surface the entry type concept for all
users.
REDMINE-19371

Let admin filters entry admin by entry type

---

entry_types/scrolled/config/locales/new/iframe_embed.de.yml
entry_types/scrolled/config/locales/new/iframe_embed.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/spec/editor/api/ContentElementTypeRegistry-spec.js
entry_types/scrolled/package/src/contentElements/editor.js
entry_types/scrolled/package/src/contentElements/frontend.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/IframeEmbed.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/IframeEmbed.module.css
entry_types/scrolled/package/src/contentElements/iframeEmbed/editor.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/frontend.js
entry_types/scrolled/package/src/editor/api/ContentElementTypeRegistry.js
entry_types/scrolled/package/src/editor/api/index.js

Add iframe embed content element

---

entry_types/scrolled/app/helpers/pageflow_scrolled/themes_helper.rb
entry_types/scrolled/package/src/frontend/Foreground.module.css
entry_types/scrolled/package/src/frontend/Tooltip.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/ChapterLink.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcons.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/ScrollButton.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/Scroller.module.css
entry_types/scrolled/spec/helpers/pageflow_scrolled/themes_helper_spec.rb

More theme options for scrolled default navigation

---

entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
entry_types/scrolled/app/models/pageflow_scrolled/content_element.rb
entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_head.html.erb
entry_types/scrolled/lib/pageflow_scrolled/additional_packs.rb
entry_types/scrolled/lib/pageflow_scrolled/configuration.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/packs_helper_spec.rb

Load chunks conditionally based on feature flags and present content
elements.
REDMINE-19525

Allow registering additional frontend/editor packs

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/frontend/Figure.module.css
entry_types/scrolled/package/src/frontend/Section.module.css
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/colors.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css

Allow changing content text color via theme options

---

entry_types/scrolled/config/locales/en.yml
entry_types/scrolled/config/locales/new/center_ragged.de.yml
entry_types/scrolled/config/locales/new/center_ragged.en.yml
entry_types/scrolled/package/spec/editor/models/ContentElement-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/layouts/index.js
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css

Not only center content, but also use centered text alignment for text
blocks.
REDMINE-19573

Add centerRagged layout variant

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/spec/support/__spec__/stories-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/Section.module.css
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css
entry_types/scrolled/package/src/frontend/useNarrowViewport.js

Allow configuring section widths in theme

---

entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/frontend/Text.module.css

Allow targeting different heading sizes via theme typography rules

---

entry_types/scrolled/config/locales/new/center_ragged.de.yml
entry_types/scrolled/config/locales/new/center_ragged.en.yml
entry_types/scrolled/config/locales/new/section_width.de.yml
entry_types/scrolled/config/locales/new/section_width.en.yml
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js

Improve section width setting

---

entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
entry_types/scrolled/package/src/contentElements/heading/stories.js

Restore spacing but make it theme configurable

---

entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/editor/seed_html_helper_spec.rb

Always render additional seed data in editor preview

---

entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarListView.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/models/ExternalLinkCollection.js

Allow sorting items in external links content element

---

entry_types/scrolled/package/spec/contentElements/externalLinkList/editor/models/ExternalLinkCollection-spec.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/models/ExternalLinkCollection.js

Handle gaps in ids after links have been deleted.
REDMINE-19618

Make external link id generation more robust

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.module.css
entry_types/scrolled/package/src/frontend/Figure.module.css
entry_types/scrolled/package/src/frontend/Section.module.css
entry_types/scrolled/package/src/frontend/colors.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/values/colors.module.css

Add content surface color properties

---

entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css

Apply theme box border radius to external links

---

app/assets/stylesheets/pageflow/ui/forms.scss
app/assets/stylesheets/pageflow/ui/properties.scss
entry_types/scrolled/config/locales/new/inline_loops.de.yml
entry_types/scrolled/config/locales/new/inline_loops.en.yml
entry_types/scrolled/package/spec/contentElements/inlineVideo/handlers-spec.js
entry_types/scrolled/package/spec/frontend/PlayerControls-spec.js
entry_types/scrolled/package/spec/support/fakePlayerState.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/contentElements/inlineVideo/MutedIndicator.js
entry_types/scrolled/package/src/contentElements/inlineVideo/MutedIndicator.module.css
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/handlers.js
entry_types/scrolled/package/src/frontend/MediaPlayer/usePlayerState.js
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/BigPlayPauseButton.js
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/BigPlayPauseButton.module.css
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/index.js
package/documentation.yml
package/spec/ui/views/inputs/CheckBoxInputView-spec.js
package/src/ui/index.js
package/src/ui/views/inputs/CheckBoxInputView.js
package/src/ui/views/inputs/LabelOnlyView.js
package/src/ui/views/inputs/SeparatorView.js

Inline video loops and improved unmute options

---

entry_types/paged/config/locales/new/video_contain.de.yml
entry_types/paged/config/locales/new/video_contain.en.yml
entry_types/paged/packages/pageflow-paged-react/src/builtInPageTypes/video.jsx
entry_types/paged/packages/pageflow-paged/src/editor/views/configurationEditors/video.js

Allow deactivating smart contain for video pages

---

entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js

Let multiple loops play side by side.
REDMINE-19811

Do not pause loops when audio focus is lost

---

entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/LegalInfoLink.js
entry_types/scrolled/package/src/widgets/defaultNavigation/LegalInfoMenu.js
entry_types/scrolled/package/src/widgets/defaultNavigation/LegalInfoMenu.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/ToggleMuteButton.module.css

Allow placing widget in default navigation bar credit box

---

app/helpers/pageflow/entries_helper.rb
db/migrate/20220705084830_add_trailing_slash_in_canonical_urls_to_themings.rb
spec/helpers/pageflow/entries_helper_spec.rb

Support adding trailing slash to canonical entry urls

---

entry_types/scrolled/package/documentation.yml
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/frontend/MediaPlayer/textTracks-spec.js
entry_types/scrolled/package/spec/frontend/features/changeSectionEvent-spec.js
entry_types/scrolled/package/spec/frontend/features/changeURLFragment-spec.js
entry_types/scrolled/package/spec/frontend/useCurrentChapter-spec.js
entry_types/scrolled/package/spec/frontend/useEventContextData-spec.js
entry_types/scrolled/package/spec/frontend/useOnScreen-spec.js
entry_types/scrolled/package/spec/frontend/usePlayerState-spec.js
entry_types/scrolled/package/spec/frontend/useTextTracks-spec.js
entry_types/scrolled/package/src/contentElements/inlineVideo/handlers.js
entry_types/scrolled/package/src/entryState/index.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/Content.js
entry_types/scrolled/package/src/frontend/RootProviders.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/SectionThumbnail.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/useCurrentChapter.js
entry_types/scrolled/package/src/frontend/useEventContextData.js
entry_types/scrolled/package/src/frontend/useOnScreen.js
entry_types/scrolled/package/src/frontend/useSectionChangeEvents.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
entry_types/scrolled/package/src/widgets/defaultNavigation/stories.js

Update highlighted chapter in navigation when scrolling

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css

Make border radius of cards appearance configurable

---

app/assets/stylesheets/pageflow/editor/drop_down_button.scss
app/assets/stylesheets/pageflow/mixins/buttons.scss
entry_types/scrolled/config/locales/new/backdrop_effects.de.yml
entry_types/scrolled/config/locales/new/backdrop_effects.en.yml
entry_types/scrolled/package/spec/editor/collections/EffectsCollection-spec.js
entry_types/scrolled/package/spec/editor/models/Effect-spec.js
entry_types/scrolled/package/spec/editor/views/inputs/EffectListInputView-spec.js
entry_types/scrolled/package/spec/frontend/Backdrop-spec.js
entry_types/scrolled/package/spec/frontend/Backdrop/Effects-spec.js
entry_types/scrolled/package/spec/frontend/useBackgroundFile-spec.js
entry_types/scrolled/package/src/editor/collections/EffectsCollection.js
entry_types/scrolled/package/src/editor/models/Effect.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/editor/views/inputs/EffectListInputView.js
entry_types/scrolled/package/src/editor/views/inputs/EffectListInputView.module.css
entry_types/scrolled/package/src/frontend/Backdrop.module.css
entry_types/scrolled/package/src/frontend/Backdrop/BackgroundAsset.js
entry_types/scrolled/package/src/frontend/Backdrop/BackgroundImage.js
entry_types/scrolled/package/src/frontend/Backdrop/BackgroundVideo.js
entry_types/scrolled/package/src/frontend/Backdrop/Effects.js
entry_types/scrolled/package/src/frontend/Backdrop/index.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/__stories__/backdropEffects-stories.js
entry_types/scrolled/package/src/frontend/useBackgroundFile.js
package/src/editor/views/DropDownButtonItemView.js
package/src/editor/views/DropDownButtonView.js
package/src/editor/views/inputs/FileInputView.js
package/src/vendor/jquery-ui/index.js
package/src/vendor/jquery-ui/mouse.js
package/src/vendor/jquery-ui/slider.js

Backdrop effects

---

entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js

Do not display variant field if non are available

---

entry_types/scrolled/package/spec/editor/views/EditSectionView-spec.js
entry_types/scrolled/package/spec/support/index.js
entry_types/scrolled/package/spec/support/useEditorGlobals.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/editor/views/inputs/EffectListInputView.js
package/src/editor/templates/inputs/fileInput.jst
package/src/editor/views/inputs/FileInputView.js
package/src/testHelpers/dominos/ui/ConfigurationEditor.js
package/src/testHelpers/dominos/ui/ConfigurationEditorTab.js
package/src/testHelpers/factories.js
package/src/testHelpers/setupGlobals.js

Fix display of video backdrop effects input

---

app/controllers/pageflow/editor/file_import_controller.rb
app/views/pageflow/editor/file_import/start_import_job.json.jbuilder
package/spec/editor/models/FileImport-spec.js
package/src/editor/models/FileImport.js
spec/controllers/pageflow/editor/file_import_controller_spec.rb
spec/support/helpers/test_file_importer.rb

Improve file import controller

---

entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.module.css

Ensure link tooltip is readable in inverted sections

---

entry_types/scrolled/package/src/contentElements/videoEmbed/VideoEmbed.js

Rerender video embed on atmo settings change

---

entry_types/scrolled/app/helpers/pageflow_scrolled/generated_media_queries_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/package/spec/frontend/v2/useMotifAreaState-spec.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
entry_types/scrolled/package/src/frontend/shadows/GradientShadow.module.css
entry_types/scrolled/package/src/frontend/v2/Backdrop/Positioner.module.css
entry_types/scrolled/package/src/frontend/v2/Section.module.css
entry_types/scrolled/package/src/frontend/v2/useMotifAreaState.js
entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/editor/seed_html_helper_spec.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/generated_media_queries_helper_spec.rb

Further improve v2 backdrop

---

admins/pageflow/user.rb
spec/controllers/admin/users_controller_spec.rb

Invoke hook when users attributes change either on
creation/invitation or via admin or profile edits
REDMINE-19935

Add user_changed hook

---

admins/pageflow/membership.rb
app/models/pageflow/entry.rb
lib/pageflow/user_mixin.rb
spec/controllers/admin/memberships_controller_spec.rb

Improve membership update

---

entry_types/paged/config/initializers/features.rb
entry_types/paged/config/locales/new/force_best_video_quality.de.yml
entry_types/paged/config/locales/new/force_best_video_quality.en.yml
entry_types/paged/packages/pageflow-paged-react/src/media/components/VideoFilePlayer/__spec__/sources-spec.js
entry_types/paged/packages/pageflow-paged-react/src/media/components/VideoFilePlayer/sources.js
entry_types/paged/packages/pageflow-paged-react/src/media/components/__spec__/createFilePlayer-spec.jsx
entry_types/paged/packages/pageflow-paged-react/src/media/components/createFilePlayer/index.jsx

Allow enforcing best video quality in Paged entries

---

entry_types/scrolled/package/src/contentElements/twitterEmbed/Placeholder.js
entry_types/scrolled/package/src/contentElements/twitterEmbed/Placeholder.module.css
entry_types/scrolled/package/src/contentElements/twitterEmbed/TwitterEmbed.js

Apply min-height to prevent scroll jump when off-screen Tweet gets unloaded.
REDMINE-19964

Preserve Tweet hide when unloading

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css

Add theme properties for cards colors

---

entry_types/scrolled/config/locales/new/default_nav_options.de.yml
entry_types/scrolled/config/locales/new/default_nav_options.en.yml
entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/editor/config.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/LegalInfoMenu.js

Options for scrolled default navigation

---

entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css

Reduce horizontal spacing and quotes symbol size.
REDMINE-19967

Improve mobile block quote size

---

app/assets/stylesheets/pageflow/editor/info_box.scss
entry_types/scrolled/config/locales/de.yml
entry_types/scrolled/config/locales/en.yml
entry_types/scrolled/config/locales/new/text_block_breaks.de.yml
entry_types/scrolled/config/locales/new/text_block_breaks.en.yml
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableText/lineBreaks-spec.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableInlineText/lineBreaks.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/characters.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/lineBreaks.js

Text block line breaks

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/package.json
entry_types/scrolled/package/spec/support/__spec__/stories-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/contentElements/textBlock/stories.js

Text block theme properties

---

entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js
entry_types/scrolled/package/src/widgets/defaultNavigation/SharingMenu.js

Account for the fact that the share button will not be displayed in this case.
REDMINE-19999

Fix info box position when all share providers are disabled

---

entry_types/scrolled/package/src/contentElements/inlineVideo/MutedIndicator.module.css
entry_types/scrolled/package/src/frontend/Backdrop.module.css
entry_types/scrolled/package/src/frontend/foregroundBoxes/GradientBox.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInBgConceal.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInBgFadeOut.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInBgFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInBgScrollOut.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInConceal.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInFadeOut.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInScrollOut.module.css
entry_types/scrolled/package/src/frontend/transitions/revealFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/scrollInFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/v1/Backdrop/index.js

Improve performance on iOS

---

entry_types/scrolled/package/spec/frontend/v1/Backdrop-spec.js
entry_types/scrolled/package/src/frontend/transitions/fadeInBgFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/fadeInFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/revealFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/transitions/scrollInFadeOutBg.module.css
entry_types/scrolled/package/src/frontend/v1/Backdrop/index.js

Improve backdrop hiding

---

entry_types/paged/packages/pageflow-paged-react/src/builtInPageTypes/audio.jsx
entry_types/paged/packages/pageflow-paged-react/src/builtInPageTypes/video.jsx
entry_types/paged/packages/pageflow-paged-react/src/media/components/PageBackgroundVideo.jsx
entry_types/paged/packages/pageflow-paged-react/src/media/components/PlayerMediaContextProvider.jsx
entry_types/paged/packages/pageflow-paged-react/src/media/index.js
entry_types/paged/packages/pageflow-paged/spec/editor/models/PreviewEntryData-spec.js
entry_types/paged/packages/pageflow-paged/spec/frontend/entry_data-spec.js
entry_types/paged/packages/pageflow-paged/spec/frontend/seed_entry_data-spec.js
entry_types/paged/packages/pageflow-paged/src/editor/models/PreviewEntryData.js
entry_types/paged/packages/pageflow-paged/src/frontend/EntryData.js
entry_types/paged/packages/pageflow-paged/src/frontend/SeedEntryData.js
entry_types/paged/packages/pageflow-paged/src/frontend/Slideshow/lazyPageWidget.js
entry_types/paged/packages/pageflow-paged/src/frontend/Slideshow/pageWidget.js
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/frontend/features/changeSectionEvent-spec.js
entry_types/scrolled/package/spec/frontend/useEventContextData-spec.js
entry_types/scrolled/package/src/contentElements/inlineAudio/InlineAudio.js
entry_types/scrolled/package/src/contentElements/inlineVideo/InlineVideo.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/Chapter.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/useEventContextData.js
entry_types/scrolled/package/src/frontend/useSectionChangeEvents.js
entry_types/scrolled/package/src/frontend/v1/Backdrop/BackgroundVideo.js
entry_types/scrolled/package/src/frontend/v2/Backdrop/BackgroundVideo.js

Provide more tracking data

---

entry_types/scrolled/config/locales/new/default_nav_options.de.yml
entry_types/scrolled/config/locales/new/default_nav_options.en.yml
entry_types/scrolled/package/src/editor/config.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js

Add option to prevent collapsing default navigation on desktop

---

package/src/frontend/VideoPlayer/mediaEvents.js

Pass alt text in media events

---

entry_types/scrolled/doc/creating_themes/custom_icons.md
entry_types/scrolled/package/spec/entryState/sharing-spec.js
entry_types/scrolled/package/src/entryState/sharing.js
entry_types/scrolled/package/src/frontend/ThemeIcon.js
entry_types/scrolled/package/src/widgets/defaultNavigation/SharingMenu.js
entry_types/scrolled/package/src/widgets/defaultNavigation/SharingMenu.module.css

Allow using custom icons for share options

---

entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.js
entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcon.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/HamburgerIcons.module.css

Add theme option to use smaller menu icon variant

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css

Add theme property for chapter link separator color

---

app/assets/stylesheets/pageflow/editor/drop_down_button.scss
entry_types/scrolled/config/locales/new/file_links.de.yml
entry_types/scrolled/config/locales/new/file_links.en.yml
entry_types/scrolled/package/spec/editor/views/SelectLinkDestinationDialogView-spec.js
entry_types/scrolled/package/src/editor/views/SelectLinkDestinationDialogView.js
entry_types/scrolled/package/src/editor/views/SelectLinkDestinationDialogView.module.css
entry_types/scrolled/package/src/editor/views/buttons.module.css
package/spec/editor/api-spec.js
package/src/editor/api/index.js
package/src/editor/controllers/SidebarController.js
package/src/editor/views/DropDownButtonView.js
package/src/editor/views/FilesView.js

Add file type drop down to link dialog

---

entry_types/scrolled/config/initializers/features.rb
entry_types/scrolled/config/locales/new/hls.de.yml
entry_types/scrolled/config/locales/new/hls.en.yml
entry_types/scrolled/package/spec/frontend/VideoPlayer/sources-spec.js
entry_types/scrolled/package/src/frontend/VideoPlayer/sources.js

Add feature flag to use HLS in all Desktop browsers

---

entry_types/scrolled/package/package.json
package/src/frontend/media/createMediaPlayer.js
yarn.lock

Upgrade to video.js 7.21 and http-streaming 2.16

---

entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css

Ensure text fits smaller cards.

Decrease external link font size on mobile

---

config/initializers/features.rb
entry_types/paged/config/initializers/features.rb
entry_types/scrolled/package/spec/frontend/VideoPlayer/sources-spec.js
entry_types/scrolled/package/src/frontend/VideoPlayer/sources.js

Make feature flag to enforce FullHD videos available for scrolled

---

entry_types/scrolled/config/locales/new/portrait_backdrop_video.de.yml
entry_types/scrolled/config/locales/new/portrait_backdrop_video.en.yml
entry_types/scrolled/package/spec/editor/models/SectionConfiguration-spec.js
entry_types/scrolled/package/spec/editor/views/EditSectionView-spec.js
entry_types/scrolled/package/spec/frontend/v1/Backdrop-spec.js
entry_types/scrolled/package/src/editor/models/SectionConfiguration.js
entry_types/scrolled/package/src/editor/views/EditSectionView.js
entry_types/scrolled/package/src/frontend/v1/Backdrop/BackgroundAsset.js
entry_types/scrolled/package/src/frontend/v1/Backdrop/OrientationAwareBackgroundVideo.js

Support portrait backdrop videos

---

entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/contentElements/quote/Quote.js
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/contentElements/quote/stories.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/contentElements/textBlock/stories.js

Quote designs

---

entry_types/scrolled/package/src/frontend/utils.module.css

Prevent line artifact between sections on Chrome

---

entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css

Especially with short texts the default paragraph spacing is too much.
REDMINE-20162

Reduce spacing between list items

---

package/src/frontend/AudioPlayer/mediaEvents.js
package/src/frontend/VideoPlayer/mediaEvents.js
package/src/frontend/utils/throttle.js

Add throttled media events

---

entry_types/scrolled/config/locales/new/counter.de.yml
entry_types/scrolled/config/locales/new/counter.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/src/contentElements/counter/Counter.js
entry_types/scrolled/package/src/contentElements/counter/Counter.module.css
entry_types/scrolled/package/src/contentElements/counter/editor.js
entry_types/scrolled/package/src/contentElements/quote/Quote.js
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/SelectionRect.module.css

Counter improvements

---

app/controllers/pageflow/feeds_controller.rb
app/helpers/pageflow/feeds_helper.rb
app/models/pageflow/entries_feed.rb
app/views/pageflow/feeds/index.atom.builder
config/routes.rb
db/migrate/20230323115745_add_feeds_enabled_to_sites.rb
entry_types/paged/app/controllers/pageflow_paged/entries_controller.rb
entry_types/paged/app/views/pageflow_paged/entries/show.html.erb
entry_types/paged/spec/controllers/pageflow_paged/entries_controller_spec.rb
entry_types/scrolled/app/controllers/pageflow_scrolled/entries_controller.rb
entry_types/scrolled/app/helpers/pageflow_scrolled/editor/seed_html_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
entry_types/scrolled/spec/controllers/pageflow_scrolled/entries_controller_spec.rb
spec/controllers/pageflow/feeds_controller_spec.rb
spec/factories/entries.rb
spec/factories/sites.rb
spec/helpers/pageflow/feeds_helper_spec.rb
spec/models/pageflow/entries_feed_spec.rb

Atom feeds

---

admins/pageflow/sites.rb
app/controllers/pageflow/sitemaps_controller.rb
app/models/pageflow/entries_feed.rb
app/models/pageflow/published_entry.rb
app/models/pageflow/sitemaps.rb
app/views/admin/sites/_attributes_table.html.arb
app/views/admin/sites/_fields.html.erb
app/views/pageflow/sitemaps/index.xml.builder
config/locales/new/sitemaps.de.yml
config/locales/new/sitemaps.en.yml
config/routes.rb
db/migrate/20230323154323_add_sitemap_enabled_to_sites.rb
spec/controllers/admin/sites_controller_spec.rb
spec/controllers/pageflow/sitemaps_controller_spec.rb
spec/factories/sites.rb
spec/models/pageflow/published_entry_spec.rb
spec/models/pageflow/sitemaps_spec.rb

Add XML sitemaps for sites

---

admins/pageflow/sites.rb
app/helpers/pageflow/entries_helper.rb
app/helpers/pageflow/feeds_helper.rb
app/models/pageflow/entries_feed.rb
app/views/admin/sites/_attributes_table.html.arb
app/views/admin/sites/_fields.html.erb
app/views/components/pageflow/admin/sites_tab.rb
app/views/pageflow/feeds/index.atom.builder
config/locales/new/sitemaps.de.yml
config/locales/new/sitemaps.en.yml
db/migrate/20230331103823_add_title_to_sites.rb
pageflow.gemspec
spec/controllers/admin/sites_controller_spec.rb
spec/controllers/pageflow/feeds_controller_spec.rb
spec/helpers/pageflow/entries_helper_spec.rb
spec/models/pageflow/entries_feed_spec.rb

Improve atom feeds

---

app/helpers/pageflow/feeds_helper.rb
db/migrate/20230405103612_add_custom_feed_url_to_sites.rb
spec/helpers/pageflow/feeds_helper_spec.rb

Allow using custom feeds urls for sites

---

app/views/pageflow/editor/config/_seeds.json.jbuilder
lib/pageflow/configuration.rb
package/spec/editor/views/PublishEntryView-spec.js
package/src/editor/controllers/SidebarController.js
package/src/editor/views/PublishEntryView.js
package/src/vendor/jquery-ui/datepicker.js
package/src/vendor/jquery-ui/index.js
spec/helpers/pageflow/editor/config_helper_spec.rb

Make default published until duration configurable

---

pageflow.gemspec

Allow any 2.6 version of react-rails

---

config/locales/new/other_files.de.yml
config/locales/new/other_files.en.yml
package/spec/editor/collections/fileTypesCollection-spec.js
package/src/editor/api/FileTypes.js
package/src/editor/api/errors.js
package/src/editor/initializers/setupFileTypes.js

Introduce file type priorities to fix text track upload in scrolled

---

app/assets/stylesheets/pageflow/editor/help.scss
config/locales/de.yml
config/locales/en.yml
config/locales/new/short_help_button.de.yml
config/locales/new/short_help_button.en.yml

Add space for additional buttons the host application might want to add there.
REDMINE-20343

Use short label for editor help button

---

entry_types/scrolled/package/spec/contentElements/imageGallery/editor/models/ItemsCollection-spec.js
entry_types/scrolled/package/spec/frontend/FitViewport-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.js
entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.module.css
entry_types/scrolled/package/src/contentElements/imageGallery/editor/models/ItemsCollection.js
entry_types/scrolled/package/src/contentElements/imageGallery/frontend.js
entry_types/scrolled/package/src/contentElements/imageGallery/useIntersectionObserver.js
entry_types/scrolled/package/src/frontend/ContentElement.js
entry_types/scrolled/package/src/frontend/ContentElements.js
entry_types/scrolled/package/src/frontend/FitViewport.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementDecorator.js
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Custom margin for image galleries

---

entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Align current image of sticky gallery with sticky inline images.
REDMINE-20325

Support custom margins for sticky elements

---

entry_types/scrolled/package/src/contentElements/quote/Quote.module.css

Add theme properties for quote mark font family and color

---

entry_types/scrolled/package/src/contentElements/imageGallery/useIntersectionObserver.js
entry_types/scrolled/package/src/frontend/Text.js

Fix gallery crash when going to fullscreen after removing item 

---

entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/frontend/__stories__/floatingAndSelfClearing-stories.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.js
entry_types/scrolled/package/src/frontend/foregroundBoxes/CardBoxWrapper.module.css
entry_types/scrolled/package/src/frontend/layouts/Center.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css

Allow placing floated elements side by side

---

entry_types/scrolled/config/locales/new/image_gallery.de.yml
entry_types/scrolled/config/locales/new/image_gallery.en.yml
entry_types/scrolled/package/src/contentElements/imageGallery/editor/index.js

Make content element generally available.
REDMINE-20325

Remove feature flag for image gallery

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/contentElements/textBlock/stories.js

Allow controlling item margins and indentation.
REDMINE-20338

Add list related theme properties

---

entry_types/scrolled/config/locales/new/quote.de.yml
entry_types/scrolled/config/locales/new/quote.en.yml
entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/contentElements/quote/Quote.js
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/contentElements/quote/editor.js
entry_types/scrolled/package/src/contentElements/quote/stories.js
entry_types/scrolled/package/src/frontend/Text.js
entry_types/scrolled/package/src/frontend/Text.module.css

Quote additions

---

entry_types/scrolled/package/src/contentElements/counter/Counter.js
entry_types/scrolled/package/src/contentElements/counter/Counter.module.css
entry_types/scrolled/package/src/contentElements/counter/editor.js

Allow full position to center counters in viewport

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/contentElements/textBlock/stories.js

Add theme property for marker color of unordered list items

---

entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/index.js
entry_types/scrolled/package/src/frontend/layouts/index.js

Use different widths in appearance stories

---

entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js

Do not display single item position drop down

---

entry_types/scrolled/app/helpers/pageflow_scrolled/editor/entry_json_seed_helper.rb
entry_types/scrolled/app/views/pageflow_scrolled/editor/entries/_seed.json.jbuilder
entry_types/scrolled/config/locales/new/palettes.de.yml
entry_types/scrolled/config/locales/new/palettes.en.yml
entry_types/scrolled/lib/pageflow_scrolled/configuration.rb
entry_types/scrolled/package/spec/editor/models/ScrolledEntry-spec.js
entry_types/scrolled/package/spec/frontend/EditableText-spec.js
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableText/blocks-spec.js
entry_types/scrolled/package/spec/frontend/paletteColor-spec.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/heading/stories.js
entry_types/scrolled/package/src/contentElements/textBlock/editor.js
entry_types/scrolled/package/src/contentElements/textBlock/stories.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
entry_types/scrolled/package/src/frontend/EditableText.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/Selection.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/blocks.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/paletteColor.js
entry_types/scrolled/spec/helpers/pageflow_scrolled/editor/entry_json_seed_helper_spec.rb

Palette color support for text blocks and headings

---

entry_types/scrolled/package/src/contentElements/quote/Quote.js
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/contentElements/quote/stories.js
entry_types/scrolled/package/src/editor/views/inputs/ListboxInputView.module.css

Allow coloring SVG quote mark symbol with palette colors

---

.gitignore
Gemfile
bin/rspec
config/spring.rb
lib/pageflow/rails_version.rb
pageflow.gemspec
spec/support/pageflow-support.gemspec

Now also used by production code.
REDMINE-19438

Move RailsVersion helper from support to core gem

---

entry_types/scrolled/package/src/contentElements/counter/Counter.module.css

Counter description already was centered. Center number as well.
REDMINE-20380

Center wide counter numbers

---

Gemfile
README.md
spec/spec_helper.rb

Has been failing silently for a long time without anyone really missing it.
REDMINE-18079

Remove Coveralls integration

---

pageflow.gemspec

Relax kramdown dependency requirement

---

entry_types/scrolled/config/locales/new/heading_subtitles.de.yml
entry_types/scrolled/config/locales/new/heading_subtitles.en.yml
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/heading/Heading.module.css
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/heading/frontend.js
entry_types/scrolled/package/src/contentElements/heading/stories.js
entry_types/scrolled/package/src/frontend/Text.js
entry_types/scrolled/package/src/frontend/Text.module.css

Add tagline and subtitle to heading content element

---

pageflow.gemspec
spec/support/pageflow/support/config/capybara.rb

Replace webdrivers with selenium-webdriver 4.15

---

app/helpers/pageflow/entries_helper.rb
spec/helpers/pageflow/entries_helper_spec.rb

Allow removing cname domain suffix from entry title

---

package/src/editor/initializers/setupFileTypes.js

Hide license and source url meta data if not supported by entry type

---

spec/support/pageflow/support/config/capybara.rb

see https://github.com/SeleniumHQ/selenium/issues/13112

Fix accessing logs in headless Chrome 120

---

package/src/vendor/jquery-ui/index.js
package/src/vendor/jquery-ui/sortable.js

Allow testing Backbone views that use sortable collections.
REDMINE-20511

Vendor jQuery UI sortable for tests

---

app/assets/stylesheets/pageflow/editor/base.scss
app/assets/stylesheets/pageflow/ui.scss
app/assets/stylesheets/pageflow/ui/input/text_area_input.scss
package/src/ui/views/inputs/TextAreaInputView.js

Improve `TextAreaInputView` for usage outside editor

---

entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js

Add theme option to hide legal info button

---

entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
entry_types/scrolled/lib/pageflow_scrolled/additional_packs.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/packs_helper_spec.rb

Always render those packs - independent of present content elements.
REDMINE-20507

Allow additional frontend packs without content element types 

---

.github/workflows/reusable-workflow-rspec.yml

Run specs in reusable workflow against Rails 7.1

---

.github/workflows/storybook.yml
.github/workflows/tests.yml
bin/build-packages

Required by postcss-import@16.

Use Node 18 in CI

---

app/assets/stylesheets/pageflow/admin/active_admin_patches.scss

Now rendered as a button instead of an type submit input.
REDMINE-20487

Fix style of action item submit buttons

---

app/controllers/pageflow/entries_controller.rb
spec/requests/pageflow/entries_show_request_spec.rb

Allow other host in entry redirect

---

.github/workflows/reusable-workflow-rspec.yml
.github/workflows/tests.yml
README.md
app/models/concerns/pageflow/feature_target.rb
app/models/concerns/pageflow/output_source.rb
app/models/concerns/pageflow/serialized_configuration.rb
app/models/pageflow/entry_template.rb
app/models/pageflow/revision.rb
app/models/pageflow/theme_customization.rb
entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb
lib/pageflow/rails_version.rb
pageflow.gemspec
spec/pageflow/configuration_spec.rb
spec/support/helpers/stub_template_in_helper_specs.rb
spec/support/pageflow/dummy/rails_template.rb

Require Rails 7

---

pageflow.gemspec
spec/support/pageflow/support/config/capybara.rb

Upgrade puma

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css

Add theme property to customize logo height in default navigation

---

entry_types/paged/packages/pageflow-paged-react/package.json
entry_types/scrolled/package/package.json
yarn.lock

Fix https://github.com/codevise/pageflow/security/dependabot/79 and https://github.com/codevise/pageflow/security/dependabot/270.

Upgrade striptags package

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/spec/frontend/EditableText-spec.js
entry_types/scrolled/package/src/contentElements/counter/Counter.module.css
entry_types/scrolled/package/src/contentElements/imageGallery/ImageGallery.module.css
entry_types/scrolled/package/src/contentElements/question/Question.module.css
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css
entry_types/scrolled/package/src/frontend/EditableText.js
entry_types/scrolled/package/src/frontend/EditableText.module.css
entry_types/scrolled/package/src/frontend/Figure.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/ChapterLink.js
entry_types/scrolled/package/src/widgets/defaultNavigation/ChapterLink.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/Logo.js
entry_types/scrolled/package/src/widgets/defaultNavigation/ToggleMuteButton.module.css
entry_types/scrolled/package/src/widgets/defaultNavigation/stories.js
entry_types/scrolled/spec/helpers/pageflow_scrolled/themes_helper_spec.rb

Additional theme options and properties

---

package/src/editor/initializers/additionalInitializers.js

Pass entry model to additional editor initializers

---

entry_types/scrolled/package/src/editor/models/Chapter.js
entry_types/scrolled/package/src/editor/views/ChapterItemView.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.module.css
entry_types/scrolled/spec/features/entry_editor/editing_the_entry_outline_spec.rb

Instead only highlight the current section in the preview to make it easy to click.
REDMINE-20374

Do not switch to section settings when adding section

---

entry_types/scrolled/app/helpers/pageflow_scrolled/packs_helper.rb
entry_types/scrolled/lib/pageflow_scrolled/additional_packs.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/packs_helper_spec.rb

Add if and unless options to additional packs

---

app/controllers/pageflow/application_controller.rb

Remove unused Devise helpers

---

admins/pageflow/entry.rb
lib/pageflow/configuration.rb
spec/controllers/admin/entries_controller_spec.rb

Add config option to redirect to editor after entry create

---

admins/pageflow/user.rb
app/views/admin/users/_attributes_table.html.arb
spec/controllers/admin/users_controller_spec.rb

Make user admin attributes table extensible

---

entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/contentElements/quote/Quote.js
entry_types/scrolled/package/src/frontend/Text.module.css

Add typography classes for different sizes of quote element

---

entry_types/scrolled/package/spec/support/stories.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarEditLinkView.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
entry_types/scrolled/package/src/frontend/InlineFileRights.module.css
entry_types/scrolled/package/src/widgets/iconInlineFileRights/IconInlineFileRights.module.css

* Render inline file rights for thumbnails
* Add theme properties to customize paddings, colors and hover scaling of cards
REDMINE-20744

External links improvements

---

app/controllers/pageflow/entries_controller.rb
entry_types/scrolled/lib/pageflow_scrolled/configuration.rb
lib/pageflow/additional_headers.rb
lib/pageflow/configuration.rb
spec/pageflow/additional_headers_spec.rb
spec/requests/pageflow/entries_show_request_spec.rb

Allow registering additional headers for published entries

---

entry_types/scrolled/package/src/widgets/defaultNavigation/index.js

First step towards enabling custom navigation widgets based on default navigation.
REDMINE-20674

Export default navigation widget component

---

entry_types/scrolled/package/src/contentElements/textBlock/TextBlock.module.css

Also apply quote mark font family to text block quotes

---

entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css

Add typography classes for external links

---

entry_types/scrolled/package/spec/widgets/defaultNavigation/Defaultnavigation-spec.js
entry_types/scrolled/package/src/widgets/defaultNavigation/DefaultNavigation.js

Allow existing default navigation with custom components

---

entry_types/scrolled/package/src/frontend/ThemeIcon.js
entry_types/scrolled/package/src/frontend/icons/close.svg
entry_types/scrolled/package/src/widgets/defaultNavigation/ScrollButton.js
entry_types/scrolled/package/src/widgets/defaultNavigation/ScrollButton.module.css

Use theme icons for default navigation scroll buttons 

---

entry_types/scrolled/package/src/frontend/inlineEditing/ActionButton.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/EditableLink.js
entry_types/scrolled/package/src/frontend/inlineEditing/LinkTooltip.js

* Only show action button when content element is selected
* Make link preview and action button position configurable
REDMINE-20782

Improve editable link component

---

entry_types/scrolled/config/locales/new/hotspots.de.yml
entry_types/scrolled/config/locales/new/hotspots.en.yml
entry_types/scrolled/package/spec/contentElements/hotspots/Hotspots-spec.js
entry_types/scrolled/package/spec/frontend/Image-spec.js
entry_types/scrolled/package/src/contentElements/hotspots/Area.js
entry_types/scrolled/package/src/contentElements/hotspots/Hotspots.js
entry_types/scrolled/package/src/contentElements/hotspots/Indicator.js
entry_types/scrolled/package/src/contentElements/hotspots/Indicator.module.css
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
entry_types/scrolled/package/src/contentElements/hotspots/editor/SidebarEditAreaView.js
entry_types/scrolled/package/src/contentElements/hotspots/getBoundingRect.js
entry_types/scrolled/package/src/contentElements/hotspots/getTooltipReferencePosition.js
entry_types/scrolled/package/src/contentElements/hotspots/panZoom.js
entry_types/scrolled/package/src/frontend/Image.js
entry_types/scrolled/package/src/frontend/inlineEditing/ContentElementEditorStateProvider.js

Hotspots element improvements

---

entry_types/scrolled/config/locales/new/hotspots.de.yml
entry_types/scrolled/config/locales/new/hotspots.en.yml
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
entry_types/scrolled/package/src/contentElements/hotspots/editor/EditAreaDialogView/DraggableEditorView.js
entry_types/scrolled/package/src/contentElements/hotspots/editor/EditAreaDialogView/DraggableEditorView.module.css
entry_types/scrolled/package/src/contentElements/hotspots/editor/index.js

Further improvements for hotspots element

---

entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/EditableLink.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/HoveringToolbar.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.module.css

Improve hotspot tooltip keyboard editing

---

entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css

Use outline style for hotspots tooltip buttons

---

entry_types/scrolled/package/spec/contentElements/hotspots/Hotspots-spec.js
entry_types/scrolled/package/src/contentElements/hotspots/Area.js
entry_types/scrolled/package/src/contentElements/hotspots/Area.module.css
entry_types/scrolled/package/src/contentElements/hotspots/Hotspots.js
entry_types/scrolled/package/src/contentElements/hotspots/Hotspots.module.css
entry_types/scrolled/package/src/contentElements/hotspots/ImageArea.js
entry_types/scrolled/package/src/contentElements/hotspots/ImageArea.module.css
entry_types/scrolled/package/src/contentElements/hotspots/ScrollButton.js
entry_types/scrolled/package/src/contentElements/hotspots/ScrollButton.module.css
entry_types/scrolled/package/src/contentElements/hotspots/Scroller.js
entry_types/scrolled/package/src/contentElements/hotspots/Scroller.module.css
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.js
entry_types/scrolled/package/src/contentElements/hotspots/Tooltip.module.css
entry_types/scrolled/package/src/contentElements/hotspots/frontend.js
entry_types/scrolled/package/src/contentElements/hotspots/useIntersectionObserver.js
entry_types/scrolled/package/src/contentElements/hotspots/useScrollPanZoom.js
entry_types/scrolled/package/src/frontend/global.module.css

Allow both scrolling via swipe and clicking hotspots 

---

entry_types/scrolled/app/views/pageflow_scrolled/entries/show.html.erb

see
https://www.searchenginejournal.com/increase-google-traffic-with-max-image-preview-tag/416123/
REDMINE-20826

Optimize display in Google Discover

---

app/controllers/pageflow/entries_controller.rb
app/helpers/pageflow/entries_helper.rb
app/models/concerns/pageflow/permalinkable.rb
app/models/pageflow/permalink.rb
app/models/pageflow/permalink_directory.rb
app/models/pageflow/permalink_redirect.rb
app/models/pageflow/published_entry.rb
app/views/admin/entries/_permalink_inputs.html.erb
config/locales/new/permalink_redirects.de.yml
config/locales/new/permalink_redirects.en.yml
db/migrate/20240918084059_create_pageflow_permalink_redirects.rb
spec/controllers/admin/entries_controller_spec.rb
spec/helpers/pageflow/entries_helper_spec.rb
spec/models/concerns/pageflow/permalinkable_spec.rb
spec/models/pageflow/published_entry_spec.rb
spec/requests/pageflow/entries_show_request_spec.rb

Redirect after permalink change

---

app/views/components/pageflow/admin/entry_translations_tab.rb
config/locales/new/entry_translations.de.yml
config/locales/new/entry_translations.en.yml
lib/pageflow/configuration.rb
spec/views/components/pageflow/admin/entry_translations_tab_spec.rb

Create configuration option for specifying a translator url

---

app/assets/stylesheets/pageflow/editor/list.scss

Prevent text from overlapping list item edit button

---

entry_types/scrolled/package/src/contentElements/hotspots/ScrollButton.js
entry_types/scrolled/package/src/contentElements/hotspots/ScrollButton.module.css

Fix horizontal overflow on mobile caused by hotspots scroll buttons

---

app/assets/stylesheets/pageflow/editor/background_positioning.scss
entry_types/scrolled/config/locales/new/ext-link-options.de.yml
entry_types/scrolled/config/locales/new/ext-link-options.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/spec/contentElements/externalLinkList/frontend/ExternalLink-spec.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/SidebarEditLinkView.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/models/ExternalLinkModel.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLink.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/ExternalLinkList.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/Thumbnail.js
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/Thumbnail.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/below.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/frontend/textPositons/right.module.css
entry_types/scrolled/package/src/contentElements/externalLinkList/linkWidths.js
entry_types/scrolled/package/src/contentElements/externalLinkList/stories.js
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
package/spec/editor/views/inputs/FileInputView-spec.js
package/src/editor/views/BackgroundPositioningView.js
package/src/editor/views/inputs/FileInputView.js
package/src/ui/views/inputs/SliderInputView.js

Alternative text positions and sizing options for external links

---

entry_types/scrolled/config/locales/new/hotspots.de.yml
entry_types/scrolled/config/locales/new/hotspots.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/src/contentElements/hotspots/editor/index.js

Also remove unsed image gallery feature flag.
REDMINE-20673

Make hotspots element generally available

---

entry_types/scrolled/config/locales/new/info_table.de.yml
entry_types/scrolled/config/locales/new/info_table.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/src/contentElements/infoTable/editor.js

No longer place info table behind feature flag

---

entry_types/scrolled/config/locales/de.yml
entry_types/scrolled/config/locales/en.yml
entry_types/scrolled/config/locales/new/side.de.yml
entry_types/scrolled/config/locales/new/side.en.yml
entry_types/scrolled/package/spec/editor/models/ContentElement-spec.js
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/src/contentElements/counter/editor.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/hotspots/editor/index.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/editor.js
entry_types/scrolled/package/src/contentElements/imageGallery/editor/index.js
entry_types/scrolled/package/src/contentElements/infoTable/editor.js
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/quote/editor.js
entry_types/scrolled/package/src/contentElements/tikTokEmbed/editor.js
entry_types/scrolled/package/src/contentElements/twitterEmbed/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
entry_types/scrolled/package/src/contentElements/vrImage/editor.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/views/inputs/PositionSelectInputView.module.css
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.js
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Content element position "side"

---

entry_types/scrolled/config/locales/new/info_table.de.yml
entry_types/scrolled/config/locales/new/info_table.en.yml
entry_types/scrolled/package/spec/frontend/EditableTable-spec.js
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableTable/withFixedColumns-spec.js
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.js
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.module.css
entry_types/scrolled/package/src/contentElements/infoTable/editor.js
entry_types/scrolled/package/src/contentElements/infoTable/stories.js
entry_types/scrolled/package/src/frontend/EditableTable.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableTable/withFixedColumns/handleTableNavigation.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableTable/withFixedColumns/helpers.js

Info table improvements

---

entry_types/scrolled/doc/creating_themes/custom_typography.md
entry_types/scrolled/package/spec/frontend/EditableText-spec.js
entry_types/scrolled/package/spec/frontend/Text-spec.js
entry_types/scrolled/package/spec/frontend/inlineEditing/EditableText-spec.js
entry_types/scrolled/package/src/contentElements/heading/Heading.js
entry_types/scrolled/package/src/contentElements/question/Question.js
entry_types/scrolled/package/src/contentElements/question/editor.js
entry_types/scrolled/package/src/contentElements/quote/Quote.module.css
entry_types/scrolled/package/src/contentElements/quote/stories.js
entry_types/scrolled/package/src/contentElements/textBlock/stories.js
entry_types/scrolled/package/src/frontend/EditableText.js
entry_types/scrolled/package/src/frontend/EditableText.module.css
entry_types/scrolled/package/src/frontend/Text.js
entry_types/scrolled/package/src/frontend/Text.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js

Further typography options

---

entry_types/scrolled/package/src/frontend/inlineEditing/EditableTable/withFixedColumns/plugin.js

Fix pasting text in info table cells

---

entry_types/scrolled/config/locales/new/info_table.de.yml
entry_types/scrolled/config/locales/new/info_table.en.yml
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.js
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.module.css
entry_types/scrolled/package/src/contentElements/infoTable/editor.js
entry_types/scrolled/package/src/contentElements/infoTable/stories.js

Allow applying palette colors to info table columns

---

entry_types/scrolled/package/src/contentElements/soundDisclaimer/SoundDisclaimer.js
entry_types/scrolled/package/src/contentElements/soundDisclaimer/editor.js
entry_types/scrolled/package/src/contentElements/soundDisclaimer/stories.js

Make sound disclaimer texts configurable

---

entry_types/scrolled/config/locales/new/full_width_in_phone_layout.de.yml
entry_types/scrolled/config/locales/new/full_width_in_phone_layout.en.yml
entry_types/scrolled/package/spec/editor/models/ContentElement-spec.js
entry_types/scrolled/package/spec/entryState/structure-spec.js
entry_types/scrolled/package/spec/frontend/Layout-spec.js
entry_types/scrolled/package/spec/frontend/features/contentElementWidth-spec.js
entry_types/scrolled/package/spec/support/matchMediaStub.js
entry_types/scrolled/package/src/editor/models/ContentElement.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
entry_types/scrolled/package/src/entryState/structure.js
entry_types/scrolled/package/src/frontend/RootProviders.js
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/usePhoneLayout.js

All elements that support full width can now be configured to take full width on narrow viewports.
REDMINE-20894

Add full width in phone layout option

---

entry_types/scrolled/package/spec/editor/views/inputs/ColorSelectInputView-spec.js
entry_types/scrolled/package/src/editor/index.js
entry_types/scrolled/package/src/editor/views/inputs/ColorSelectInputView.js
entry_types/scrolled/package/src/editor/views/inputs/ColorSelectInputView.module.css

Allow displaying multiple color swatches based on configured property prefixes.
REDMINE-20892

Export and extend ColorSelectInputView

---

entry_types/scrolled/package/spec/widgets/defaultNavigation/Defaultnavigation-spec.js
entry_types/scrolled/package/src/widgets/defaultNavigation/Logo.js

Support opening logo url in same tab

---

app/assets/stylesheets/pageflow/editor/info_box.scss
entry_types/scrolled/config/locales/new/iframe_resize.de.yml
entry_types/scrolled/config/locales/new/iframe_resize.en.yml
entry_types/scrolled/package/spec/contentElements/iframeEmbed/useIframeHeight-spec.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/IframeEmbed.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/editor.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/useIframeHeight.js

Add option to resize iframe embed based on message sent from embed

---

entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.module.css
entry_types/scrolled/package/src/frontend/inlineEditing/EditableTable/placeholders.module.css

Wrap text in first column of info table on narrow viewports

---

package/src/editor/initializers/setupFileTypes.js

Increase max length of alt texts to 5000

---

.github/workflows/reusable-workflow-rspec.yml
.github/workflows/storybook.yml
.github/workflows/tests.yml

Upgrade cache action to v4

---

entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_entry.json.jbuilder
entry_types/scrolled/app/views/pageflow_scrolled/entry_json_seed/_theme.json.jbuilder
entry_types/scrolled/lib/pageflow_scrolled/additional_theme_assets.rb
entry_types/scrolled/lib/pageflow_scrolled/configuration.rb
entry_types/scrolled/spec/helpers/pageflow_scrolled/entry_json_seed_helper_spec.rb

Can be used to provide configurable assets for widgets defined in plugins.
REDMINE-20913

Allow including additional theme customization files in seed data

---

entry_types/scrolled/config/locales/new/counter_grouping.de.yml
entry_types/scrolled/config/locales/new/counter_grouping.en.yml
entry_types/scrolled/package/src/contentElements/counter/Counter.js
entry_types/scrolled/package/src/contentElements/counter/editor.js
entry_types/scrolled/package/src/contentElements/counter/stories.js

Allow disabling thousands separators in counter

---

entry_types/scrolled/package/src/frontend/EditableInlineText.module.css

Fix typo in hyphens none rule

---

entry_types/scrolled/package/src/frontend/inlineEditing/EditableLink.js

Make link preview align of editable link configurable

---

entry_types/scrolled/package/src/frontend/Figure.js
entry_types/scrolled/package/src/frontend/inlineEditing/EditableText/index.js
entry_types/scrolled/package/src/frontend/inlineEditing/LinkTooltip.js

Stop propagation in link preview to prevent teaser list from preventing default.

Ensure teaser item link preview can be clicked 

---

entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/src/frontend/ContentElementBox.js
entry_types/scrolled/package/src/frontend/ContentElementBox.module.css
entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js

Allow setting different border radius for full width elements

---

entry_types/scrolled/package/src/frontend/__stories__/appearance-stories.js
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Allow either providing as a fraction or as a fixed value.
REDMINE-20991

Let themes change content margin

---

entry_types/scrolled/config/locales/new/decoration_effects.de.yml
entry_types/scrolled/config/locales/new/decoration_effects.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/spec/editor/collections/EffectsCollection-spec.js
entry_types/scrolled/package/spec/editor/models/Effect-spec.js
entry_types/scrolled/package/spec/frontend/features/backdropDecorationEffects-spec.js
entry_types/scrolled/package/src/editor/collections/EffectsCollection.js
entry_types/scrolled/package/src/editor/models/Effect.js
entry_types/scrolled/package/src/editor/views/inputs/EffectListInputView.js
entry_types/scrolled/package/src/editor/views/inputs/EffectListInputView.module.css
entry_types/scrolled/package/src/frontend/BackdropFrameEffect.js
entry_types/scrolled/package/src/frontend/BackdropFrameEffect.module.css
entry_types/scrolled/package/src/frontend/Section.js
entry_types/scrolled/package/src/frontend/getEffectValue.js
entry_types/scrolled/package/src/frontend/inlineEditing/SectionDecorator.module.css
entry_types/scrolled/package/src/frontend/v1/Backdrop/Effects.js

Backdrop decoration effects

---

entry_types/scrolled/package/src/frontend/Section.module.css
entry_types/scrolled/package/src/frontend/layouts/Center.module.css
entry_types/scrolled/package/src/frontend/layouts/TwoColumn.module.css

Make content margin configurable for narrow sections

---

entry_types/scrolled/config/locales/new/element_margins.de.yml
entry_types/scrolled/config/locales/new/element_margins.en.yml
entry_types/scrolled/lib/pageflow_scrolled/plugin.rb
entry_types/scrolled/package/spec/editor/models/ScrolledEntry/getScale-spec.js
entry_types/scrolled/package/src/contentElements/counter/editor.js
entry_types/scrolled/package/src/contentElements/dataWrapperChart/editor.js
entry_types/scrolled/package/src/contentElements/externalLinkList/editor/index.js
entry_types/scrolled/package/src/contentElements/heading/editor.js
entry_types/scrolled/package/src/contentElements/hotspots/editor/index.js
entry_types/scrolled/package/src/contentElements/iframeEmbed/editor.js
entry_types/scrolled/package/src/contentElements/imageGallery/editor/index.js
entry_types/scrolled/package/src/contentElements/infoTable/editor.js
entry_types/scrolled/package/src/contentElements/inlineAudio/editor.js
entry_types/scrolled/package/src/contentElements/inlineBeforeAfter/editor.js
entry_types/scrolled/package/src/contentElements/inlineImage/editor.js
entry_types/scrolled/package/src/contentElements/inlineVideo/editor.js
entry_types/scrolled/package/src/contentElements/quote/editor.js
entry_types/scrolled/package/src/contentElements/tikTokEmbed/editor.js
entry_types/scrolled/package/src/contentElements/twitterEmbed/editor.js
entry_types/scrolled/package/src/contentElements/videoEmbed/editor.js
entry_types/scrolled/package/src/contentElements/vrImage/editor.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/views/configurationEditors/groups/CommonContentElementAttributes.js
entry_types/scrolled/package/src/frontend/ContentElement.js
entry_types/scrolled/package/src/frontend/ContentElementMargin.js
entry_types/scrolled/package/src/frontend/__stories__/contentElementMargins-stories.js
package/spec/ui/views/inputs/SelectInputView-spec.js
package/src/ui/views/inputs/SelectInputView.js

Content element margins

---

entry_types/scrolled/config/locales/new/border_radius_scale.de.yml
entry_types/scrolled/config/locales/new/border_radius_scale.en.yml
entry_types/scrolled/config/locales/new/default_suffix.de.yml
entry_types/scrolled/config/locales/new/default_suffix.en.yml
entry_types/scrolled/config/locales/new/ext-link-options.de.yml
entry_types/scrolled/config/locales/new/ext-link-options.en.yml
entry_types/scrolled/config/locales/new/image_crop_types.de.yml
entry_types/scrolled/config/locales/new/image_crop_types.en.yml
entry_types/scrolled/doc/creating_themes/custom_colors_and_dimensions.md
entry_types/scrolled/package/spec/contentElements/inlineImage/InlineImage-spec.js
entry_types/scrolled/package/spec/editor/collections/StylesCollection-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry/getScale-spec.js
entry_types/scrolled/package/spec/editor/models/ScrolledEntry/getThemeProperties-spec.js
entry_types/scrolled/package/spec/editor/models/Style-spec.js
entry_types/scrolled/package/spec/frontend/features/contentElementBox-spec.js
entry_types/scrolled/package/spec/support/pageObjects.js
entry_types/scrolled/package/src/contentElements/inlineImage/InlineImage.js
entry_types/scrolled/package/src/contentElements/inlineImage/stories.js
entry_types/scrolled/package/src/editor/collections/StylesCollection.js
entry_types/scrolled/package/src/editor/models/ScrolledEntry/index.js
entry_types/scrolled/package/src/editor/models/Style.js
entry_types/scrolled/package/src/frontend/ContentElementBox.js
entry_types/scrolled/package/src/frontend/ContentElementBox.module.css
entry_types/scrolled/package/src/frontend/global.module.css

Rounded circle image modifier styles

---

app/models/pageflow/video_file.rb
app/models/pageflow/video_file_url_templates.rb
app/models/pageflow/zencoder_attachment.rb
entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
entry_types/scrolled/package/spec/frontend/VideoPlayer/sources-spec.js
entry_types/scrolled/package/src/frontend/VideoPlayer/index.js
entry_types/scrolled/package/src/frontend/VideoPlayer/sources.js
entry_types/scrolled/package/src/frontend/v1/Backdrop/BackgroundVideo.js
lib/pageflow/zencoder_video_output_definition.rb
spec/models/pageflow/video_file_url_templates_spec.rb
spec/models/pageflow/zencoder_attachment_spec.rb
spec/pageflow/zencoder_video_output_definition_spec.rb
spec/support/matchers/have_output.rb

Prevent blurry background videos

---

entry_types/scrolled/package/package.json
entry_types/scrolled/package/src/contentElements/inlineImage/stories.js
entry_types/scrolled/package/src/frontend/Figure.js
yarn.lock

Add theme option to display caption above

---

app/helpers/pageflow/entries_helper.rb
app/models/pageflow/site.rb
app/views/pageflow/social_share/_entry_meta_tags.html.erb
app/views/pageflow/social_share/_page_meta_tags.html.erb
spec/helpers/pageflow/social_share_helper_spec.rb
spec/models/pageflow/site_spec.rb

Align with pretty_entry title. Use CNAME domain only as fallback.

Use custom site title in og:site_name

---

app/controllers/pageflow/entries_controller.rb
spec/requests/pageflow/entries_index_request_spec.rb

Port redirect and password protection to site root entry

---

app/models/concerns/pageflow/permalinkable.rb
spec/models/concerns/pageflow/permalinkable_spec.rb

Free up permalinks when deleting an entry.

Clean up permalinks when deleting entries

---

app/assets/stylesheets/pageflow/editor/file_meta_data.scss
app/assets/stylesheets/pageflow/editor/files.scss
config/locales/de.yml
config/locales/en.yml
package/spec/editor/views/ConfirmableFileItemView-spec.js
package/spec/editor/views/ExplorerFileItemView-spec.js
package/spec/editor/views/FileItemView-spec.js
package/spec/editor/views/inputs/FileInputView-spec.js
package/src/editor/templates/fileItem.jst
package/src/editor/templates/fileMetaDataItemValueView.jst
package/src/editor/views/ConfirmableFileItemView.js
package/src/editor/views/ExplorerFileItemView.js
package/src/editor/views/FileItemView.js
package/src/editor/views/inputs/FileInputView.js

Improve file item views

---

spec/models/pageflow/draft_entry_spec.rb

Attachments are uploaded via direct upload to S3. We do not receive an attachment here.
REDMINE-21089

Align DraftEntry#create_file! spec with real usage

---

entry_types/scrolled/config/locales/de.yml
entry_types/scrolled/config/locales/en.yml
entry_types/scrolled/package/spec/contentElements/infoTable/InfoTable-spec.js
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.js
entry_types/scrolled/package/src/contentElements/infoTable/InfoTable.module.css
entry_types/scrolled/package/src/contentElements/infoTable/editor.js
entry_types/scrolled/package/src/contentElements/infoTable/stories.js

Center content by default in center ragged layout.

Add option for info table single column alignment

---

entry_types/scrolled/package/spec/entryState/sharing-spec.js
entry_types/scrolled/package/src/entryState/sharing.js
entry_types/scrolled/package/src/testHelpers/normalizeSeed.js
entry_types/scrolled/package/src/widgets/defaultNavigation/SharingMenu.js

Ruby code was changed due a Rubocop autofix.

Use correct url placeholde use JS share link logic

---

entry_types/scrolled/package/spec/frontend/PlayerControls-spec.js
entry_types/scrolled/package/spec/frontend/PlayerControls/ClassicPlayerControls-spec.js
entry_types/scrolled/package/spec/support/roleQueriesExcludingInert.js
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/BigPlayPauseButton.js
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/index.js
entry_types/scrolled/package/src/frontend/PlayerControls/ClassicPlayerControls/useFocusHandoff.js
entry_types/scrolled/package/src/frontend/PlayerControls/ControlBar.module.css
entry_types/scrolled/package/src/widgets/iconInlineFileRights/IconInlineFileRights.module.css

Improve keyboard control for player controls

---

app/assets/stylesheets/pageflow/ui/tabs_view.scss
entry_types/scrolled/package/src/contentElements/hotspots/editor/EditAreaDialogView/index.js
entry_types/scrolled/package/src/contentElements/hotspots/editor/SidebarEditAreaView.module.css
entry_types/scrolled/package/src/editor/views/EditSectionPaddingsView.module.css
package/spec/ui/views/TabsView-spec.js
package/src/ui/templates/tabsView.jst
package/src/ui/views/TabsView.js

Improve keyboard control and aria labels. Also makes it easier to interacts with tabs in specs.
REDMINE-20481

Make TabsView implement tabslist role
